### ISSUE TITLE
广播任务，派发任务后关闭一个Worker,有一个Worker会执行两次任务。

### ISSUE THREAD

**Issue by wangwenhu666** [PowerJob/PowerJob#1003]
**Describe the bug**
广播任务，派发任务后关闭一个Worker,有一个Worker会执行两次任务。
看作者写逻辑是把失败的子任务更新到数据库的时候  地址重新设置了 N/A ,导致重新分配到了一个已经执行了一次广播任务的Worker 上了。
**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
 - PowerJob Version: [e.g. 4.3.6]
 - Java Version: [e.g. OpenJDK 8]
 - OS: [e.g. Windows]

**Comment by wangwenhu666** [comment]
![WPS图片(1)](https://github.com/user-attachments/assets/ecfefc13-2e2f-43dd-b036-f9a9f3d13d13)

**Comment by KFCFans** [comment]
感谢反馈，确实有这个问题。将在下个版本修复。

**Comment by KFCFans** [comment]
5.1.1 已修复
