### ISSUE TITLE
命名空间创建失败会导致服务不可用

### ISSUE THREAD

**Issue by AMysteryMan** [PowerJob/PowerJob#1009]
创建命名空间时一旦填写了已经存在的code，错误提示：
ERROR: DatalntegrityViolationException: could not execute statement; SQL in/al; constraint [uidx01 namespacel; nested exception is
org.hibernate.exception.ConstraintViolationException: could not execute statement

之后服务的其他模块也无法使用，错误提示：
ERROR：JpaSystemException: could not extract ResultSet; nested exception is org.hibernate.exception.GenericJDBCException: could not extract ResultSet

**Comment by KFCFans** [comment]
测试无法复现，请提供详细的复现路径

**Comment by AMysteryMan** [comment]
> 测试无法复现，请提供详细的复现路径

你创建应用的时候，在同一个命名空间下，appName输入一个已经存在的，然后创建，这个时候出错后，整个集群服务不可用。
比如获取命名空间或者应用列表就会报错：could not extract ResultSet; nested exception is org.hibernate.exception.GenericJDBCException: could

**Comment by KFCFans** [comment]
我估计和 db 有关，我自己验证是无法复现的，会被 mysql 的唯一索引卡住，数据插不进去。
不过保险起见代码层做个校验吧。
