### ISSUE TITLE
机器地址为127.0.0.1

### ISSUE THREAD

**Issue by 1343228975** [PowerJob/PowerJob#1014]
## 你好，请教一下我的机器地址为什么会是127.0.0.1，但是server和work是部署在两个容器的，然后执行的时候会报错
![image](https://github.com/user-attachments/assets/87e2e9a1-f9d8-477c-931b-fa677a5870c4)

我执行器地址输入127.0.0.1会一直等待work接收，过一段时间失败，使用内网地址会报no worker available
![image](https://github.com/user-attachments/assets/0496c323-8c70-410d-bcdd-3bb230c29edc)

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by Coolnibo** [comment]
两个容器之间无法通讯，应该在woker配置文件里面写server容器开放的宿主机端口

**Comment by KFCFans** [comment]
需要保证server和worker 相互可访问
https://www.yuque.com/powerjob/guidence/problem#sJvDR
