### ISSUE TITLE
powerjob可以用来实现延迟任务吗？可靠性高吗？

### ISSUE THREAD

**Issue by twojin** [PowerJob/PowerJob#1015]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by KFCFans** [comment]
可以的，基于 OpenAPI 可以创建延迟任务。server 集群不挂的情况下，能保证至少执行一次。
至于 server 集群本身的稳定性，可以自己做好监控。

**Comment by zhihaoHappyeveryday** [comment]
> 可以的，基于 OpenAPI 可以创建延迟任务。server 集群不挂的情况下，能保证至少执行一次。 至于 server 集群本身的稳定性，可以自己做好监控。

如果有大量的延迟任务,  性能怎么样的呀, 有没有性能验证报告呀,  从网上没找到有!
