### ISSUE TITLE
server端使用5.1.0 worker端使用4.3.6 任务下发后worker端报错

### ISSUE THREAD

**Issue by prettygogogo** [PowerJob/PowerJob#1016]
最开始server端和worker端版本一致 都是使用的4.3.6
现在需要将server端升级到5.1.0,使用账号统一管理,但是worker端并未做升级
启动后发现server端将任务下发后,worker端接收参数会报错,提示:
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "advancedRuntimeConfig" (class tech.powerjob.common.request.ServerScheduleJobReq);
因为5.1.0的server端新增了一个advancedRuntimeConfig参数,下发给worker端,结果worker端未定义这个属性字段导致解析json异常

**Comment by KFCFans** [comment]
嗯，这是低版本的bug。详细内容可见：PowerJob-V4.3.8 的 release 日志
<img width="901" alt="image" src="https://github.com/user-attachments/assets/8a9f9cbe-8b89-4ccd-9fd9-3a294de07c2a">
