### ISSUE TITLE
定时任务启动后用API再去触发报too many instances(1>1)

### ISSUE THREAD

**Issue by juforg** [PowerJob/PowerJob#1025]
## Question
该种用法 似乎也没有明确禁止，是禁止吗？如果是禁止，提示是不是该的更友好，甚至不应该产生实例记录，直接api接口报错即可？

场景是 优先使用 API按需触发，定时任务作为 兜底 差缺补漏，、
定时时间较长，全依赖定时的话，用户体验不好，定时时间较短，有触发太频繁

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details. 
任务配置
![image](https://github.com/user-attachments/assets/d150cbd7-21ea-482a-9e34-9babf5660c37)
实例记录
![image](https://github.com/user-attachments/assets/3c98dc71-dac3-4355-b10d-023c163c78e1)
定时任务实例
![image](https://github.com/user-attachments/assets/476f9d83-c4a8-40df-aa8b-a5d8a6c3fc6b)
API触发时报的错误
![image](https://github.com/user-attachments/assets/408534a5-efff-4ee1-9c2a-8de70a3f06e8)

**Comment by KFCFans** [comment]
5.1.1 版本 openAPI 新增了任务实例查询 API：`tech.powerjob.client.IPowerJobClient#queryInstanceInfo`

你这种场景，就可以自己做逻辑了。判断不存在，才用 openAPI 调用触发，理论上可以解决问题。

**Comment by KFCFans** [comment]
另外，固定频率其实是不需要考虑在不在运行的。固定频率任务，server 是一定会保证时刻调度的。
