### ISSUE TITLE
当我的健康检查时间health-report-interval设置成300时，我的机器会处于下线状态，导致调度失败

### ISSUE THREAD

**Issue by koralcc** [PowerJob/PowerJob#1026]
我把我的健康报告时间设置成了300s时，调度的页面我的机器会变灰色下线状态，导致调度失败
![image](https://github.com/user-attachments/assets/5a5ce51e-fab5-45e8-bcd8-efbcd2e3910b)

这种情况是正常的吗，我现在把这个配置去掉，或者设置很小是正常的，这种情况是什么原因呢？健康检查间隔是否有个阈值？

**Comment by KFCFans** [comment]
健康检查间隔太久肯定不行的，会让 server 以为机器 offline 了。
什么场景需要那么长的间隔 =。=？建议不超过 30S
