### ISSUE TITLE
Add PowerjobClient api  /queryInstance

### ISSUE THREAD

**Issue by ljp190** [PowerJob/PowerJob#1034]
OpenAPI中存在 queryInstance 这个接口
![image](https://github.com/user-attachments/assets/892eae4e-891d-48e2-8084-2ac962364701)
但是在目前的client包中，缺少定义   无法调用
![image](https://github.com/user-attachments/assets/1e757116-aba0-4346-98e6-0cc6ed531273)

需要给client中 添加一下 queryInstance  这个接口

**Comment by KFCFans** [comment]
5.1.1 已支持
