### ISSUE TITLE
JVM配置和容器的CPU&内存配置

### ISSUE THREAD

**Issue by q710245300** [PowerJob/PowerJob#1036]
请问生产环境k8s部署server和worker，是否有参考的JVM配置和容器的CPU&内存配置呢？

**Comment by KFCFans** [comment]
这个还是取决于你们自己的任务调度规模，量级不大的话，常规 2C4G 的机器足够了。如果调度规模比较大，就同步往上增加资源即可。可以先自己简单压测一下。
