### ISSUE TITLE
PowerJobClient.saveJob 重复执行两次

### ISSUE THREAD

**Issue by zengbo1997** [PowerJob/PowerJob#1037]
5.X server 为兼容4.0的client 默认配置oms.auth.openapi.enable=false 会导致 PowerJobClient执行两次
原因: 
OpenApiInterceptor 不生效导致server 端的response未添加X-POWERJOB-AUTH-PASSED头信息
client AppAuthClusterRequestService认为鉴权失败又会刷新权限信息后再发送次请求
![image](https://github.com/user-attachments/assets/5cdd3087-10c9-4477-b069-14d45be1b87c)

**Comment by KFCFans** [comment]
5.1.1 已修复
