### ISSUE TITLE
多个server下查看日志的问题

### ISSUE THREAD

**Issue by sunjiadong** [PowerJob/PowerJob#1042]
## Question

部署了2台server，
1、运行工作流之后任务的日志在两台机器都有吗？
2、目前问题: 运行工作流，A机器下有工作流下每个任务的日志，B机器没有任务日志
3、查看日志时，日志展示内容为空，多点几次之后又可以看到日志展示

麻烦问下，这个是什么问题，多server部署有问题吗？

**Comment by wuweihongdd** [comment]
这个是因为日志默认存在app的master server本地。假设两台server分别为SA和SB，上午九点执行的任务时，app的master server为SA，则此时生成的任务日志保存在SA中，而查看日志时web请求是会随机分配到两个server上，可是SB上没有日志，SA上有日志，就会表现为时而看到日志时而看不到日志。（这里SB不会去SA上找，因为app多server的设计下，其实不知道当时是谁调度了那个实例）

目前官方提供日志启用MongoDB存储，通过这种统一日志存储的方式，解决了这个问题

**Comment by KFCFans** [comment]
补充：目前的远程存储支持扩展，除了 MongoDB，还可以用 OSS、MySQL 等数据库

**Comment by wuweihongdd** [comment]
感谢作者大大补充

**Comment by sunjiadong** [comment]
使用mysql存储解决这个问题了，但是有个隐患问题提醒下：任务执行完之后日志写入数据库存在延迟，这段时间内用户如果点击查看日志，那么空日志就会存储到server本地了，后面就算日志写入了数据库，这个存储在本地的空日志也不会被替换
