### ISSUE TITLE
延迟任务很多会导致性能问题吗？

### ISSUE THREAD

**Issue by xnq727** [PowerJob/PowerJob#1043]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by KFCFans** [comment]
不会，延迟任务是高度去中心化的，对 server 几乎没有负担。
