### ISSUE TITLE
【多元存储】日志存储多元化，不仅限于 MongoDB

### ISSUE THREAD

**Issue by KFCFans** [PowerJob/PowerJob#130]
## 需要完成的功能
1. 抽象 powerjob-server 当前的文件存储层，设计**独立接口**进行文件的 save / delete / search 等操作
2. 提供多种具体的实现，比如 MongoDb 和 DB 的实现
3. 提供可配置的方式供用户选择文件的存储系统（默认 MongodDb）

## 思路参考
1. 新建接口，如 DistributeFileService，定义基础操作
2. 实现 MongoDistributeFileServiceImpl, DbDistributeFileServiceImpl 等
3. 提供配置允许用户简单切换，可参考 com.github.kfcfans.powerjob.server.common.PowerJobServerConfigKey

## 注意事项
1. 接口设计注意扩展性，后端存储实现可以有 HDFS、ElasticSearch 等，**可以先不实现，但不能后续无法实现**
2. 使用 DB 作为存储时需要考虑**数据库兼容性**，必须满足 Spring Data JPA 规范，即可跨数据库平台

***
**建议设计完顶层接口后在 ISSUE 中同步，顶层接口需要先单独 review**

**Comment by KFCFans** [comment]
ES 需求：https://github.com/KFCFans/PowerJob/issues/112

ES API 可能比较奇怪，如果无法实现可以不用考虑。

**Comment by jjnnzb** [comment]
我研究一下这个吧

**Comment by Jamel-jun** [comment]
使用opentelemetry协议吧，可以考虑下接入云原生方向
