### ISSUE TITLE
脚本执行临时文件自动清理

### ISSUE THREAD

**Issue by qq583158399** [PowerJob/PowerJob#136]
目前worker每次执行shell脚本任务时会自动创建一个临时文件，是否能够提供脚本临时文件的自动清理,或者在本地只生成一个脚本文件,而不是每次都生成名字带id的文件

**Comment by KFCFans** [comment]
每次都重新生成脚本文件的原因是原始脚本文件可能产生变化（比如修改控制台参数什么的）。
其实有个比较 hack 的解决方法，就是在 PowerJob 上创建一个清理脚本文件的定时任务 hhh。

在 worker 里面单独配置清理感觉有点浪费资源。

**Comment by KFCFans** [comment]
配合官方通用处理器可快速实现该需求。
https://www.yuque.com/powerjob/guidence/xc7dzm#sYUmZ
