### ISSUE TITLE
做了一个容器，部署报错

### ISSUE THREAD

**Issue by maijieren** [PowerJob/PowerJob#148]
容器部署报错：
SYSTEM: deploy failed because of the exception
java.io.IOException: Unable to delete file: C:\Users\xujuan\powerjob-server\temporary\36812e10789a4ffba288cb4ad215929d\.git\objects\pack\pack-1b1fb045cfeddd7a77d935e3400155c651906001.pack at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2400) at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721) at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617) at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391) at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721) at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617) at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391) at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721) at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617) at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391) at org.apache.commons.io.FileUtils.

任务执行报错：
任务结果: com.github.kfcfans.powerjob.common.PowerJobException: fetch Processor failed, please check your processorType and processorInfo config

**Comment by KFCFans** [comment]
IO 异常啊...
我估计是 windows 环境的文件操作不是很兼容......

**Comment by KFCFans** [comment]
尝试下本地构建后直接上传完整Jar的模式吧，服务端编译构建目前看来仅支持 Linux。因为我手上没有 windows 的机器，也没办法 debug 问题...
（要是你能自己查一下问题顺便修复就更好了！

![image](https://user-images.githubusercontent.com/9402086/103477335-cfe43600-4df8-11eb-900f-bb13e2a39a24.png)

**Comment by maijieren** [comment]
通过本地构建后直接上传完整Jar的模式，这种没有问题，谢谢解答 @KFCFans
