### ISSUE TITLE
固定频率子任务显示不是很友好

### ISSUE THREAD

**Issue by ocean23** [PowerJob/PowerJob#149]
**步骤**
1、创建一个任务**定时信息**选择固定频率（毫秒）然后每秒执行一次，执行配置选择**单机执行**和**JAVA**
2、在worker端新建对应的`BasicProcessor`, 然后`sleep`10秒模拟每次需要执行10秒
3、这时查看这个任务实例的详情如下图
![image](https://user-images.githubusercontent.com/8874638/103481680-86efaa00-4e17-11eb-9f2d-643b870832e1.png)

查看最近10条记录一定是等待**worker接收**

**原因**
由于worker端的秒级任务是每秒派发一次, 但是处理的`BasicProcessor`每次需要10秒才能处理完很快就会导致队列的长度达到了最大值，所以后面派发的命令都会被拒绝导致不会返回成功信息给前端代码如下:
![image](https://user-images.githubusercontent.com/8874638/103481898-94f1fa80-4e18-11eb-9634-d9c04c2ecef6.png)

**结论**
虽然子任务显示的状态是等待worker接收但是实际上内部的执行是没有问题的只是担心不看源码的新手会误以为这个任务出现了什么问题，我也暂时想不到什么好的建议不过假如改为查询worker实际最新执行的任务而不是派发的任务好像合理一点就是不知道这样改合不合理。

**Comment by KFCFans** [comment]
1. 这一块 UI 和交互确实不算“体验友好”的范畴，不过目前应该算能用。
2. 你这个 case 实际情况应该比较少见，所以还好。

如果有 UI 交互上的 idea，可以贡献下哈哈

**Comment by ocean23** [comment]
这一块影响不大反正执行结果是正确的，迟点有空我再看看如何优化之前写过一段时间react已经有一段时间没写了:smile:
