### ISSUE TITLE
master和worker是去中心化的吗？一个master挂了后，job会不会失败？

### ISSUE THREAD

**Issue by wwh2156** [PowerJob/PowerJob#150]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by KFCFans** [comment]
多看文档。
![image](https://user-images.githubusercontent.com/9402086/103517811-b224d880-4ead-11eb-8d4d-a656a0656e02.png)
