### ISSUE TITLE
Getting ready for internationalization.

### ISSUE THREAD

**Issue by jjnnzb** [PowerJob/PowerJob#152]
To promote PowerJob and create better experience for our foreign friends, we do need to complete the following tasks:

- [x] Translate all the comments and explanations into English in properties files.
- [x] Translate the description in powerjob-worker-spring-boot-starter into English.
- [x] ~~Translate the thoughts and comments in source code into English.~~
- [x] Translate the release messages into English.
- [x] Optimize English version of user manual in Yuque.
- [x] Add gitter support.
- [x] Add official Reddit introduction.
- [x] Add Medium introduction.
- [x] Add stackoverflow answer.
- [x] Add Quora answers in related questions.
What are your opinions?

**Comment by jjnnzb** [comment]
Add gitter support.
![C9DB1678-3BF6-4DE1-9753-7FC4ECC4F886](https://user-images.githubusercontent.com/58833386/103659469-635b6980-4fa7-11eb-9fb0-7d1d01511b51.png)

**Comment by jjnnzb** [comment]
#155 completed.

**Comment by KFCFans** [comment]
PowerJob in gitter has registered...😭

**Comment by jjnnzb** [comment]
Reddit post in java topic of Reddit: https://www.reddit.com/r/java/comments/kugcu4/powerjob_distributed_jobscheduling_framework_of/

**Comment by jjnnzb** [comment]
Yuque update: Finish quick start with IDE chapter. Link is https://www.yuque.com/powerjob/en/baz8y6

**Comment by jjnnzb** [comment]
[Another Reddit post](https://www.reddit.com/r/javahelp/comments/kv6bfh/my_experience_of_hunting_for_jobscheduling/)

**Comment by KFCFans** [comment]
> Yuque update: Finish quick start with IDE chapter. Link is https://www.yuque.com/powerjob/en/baz8y6

语雀's English name: Lark

**Comment by jjnnzb** [comment]
> > Yuque update: Finish quick start with IDE chapter. Link is https://www.yuque.com/powerjob/en/baz8y6
> 
> 语雀's English name: Lark

The domain has the name Yuque in it, so I didn't even google for the English name.

**Comment by KFCFans** [comment]
> > > Yuque update: Finish quick start with IDE chapter. Link is https://www.yuque.com/powerjob/en/baz8y6
> > 
> > 
> > 语雀's English name: Lark
> 
> The domain has the name Yuque in it, so I didn't even google for the English name.

U are right!

**Comment by jjnnzb** [comment]
Medium article has been published. Link is [PowerJob — Distributed computing and job scheduling framework](https://jjnnzb.medium.com/powerjob-distributed-computing-and-job-scheduling-framework-39809c58b4e2)

**Comment by jjnnzb** [comment]
Quora answer can be seen on [What is best Job scheduling framework for java?](https://www.quora.com/What-is-best-Job-scheduling-framework-for-java/answer/Jining-Jiang?ch=10&share=353810a5&srid=z8fS)

**Comment by jjnnzb** [comment]
Reddit post of Release v3.4.4 [Release of V3.4.4](https://www.reddit.com/r/java/comments/kz5o8s/powerjob_v343_has_been_released_check_to_see_the/)

**Comment by jjnnzb** [comment]
StackOverFlow answer: [https://stackoverflow.com/a/65763389/9149315](https://stackoverflow.com/a/65763389/9149315)

**Comment by jjnnzb** [comment]
DONE! @KFCFans
