### ISSUE TITLE
有没有办法在访问的时候带上项目名称

### ISSUE THREAD

**Issue by erisonlan** [PowerJob/PowerJob#156]
我想在访问的时候带上路径powerjob，比如http://localhost:7700/powerjob/；
在springboot的application.properties里面加了配置server.servlet.context-path=/powerjob，但是这样加了之后静态文件都是404了，并没有自动带上/powerjob/的路径，有没有啥办法解决。我尝试过修改index.html的link href标签，但是修改之后仅仅是样式正常了，点击登录按钮，调用后台接口任然是404
![123](https://user-images.githubusercontent.com/38589139/103856828-467e7d80-50f0-11eb-9926-d90b53c9f1d4.png)

**Comment by KFCFans** [comment]
1. 使用源码（PowerJob-Console）独立部署前端
2. 使用 nginx 代理请求

二选一

**Comment by yixiaco** [comment]
> 1. 使用源码（PowerJob-Console）独立部署前端
> 2. 使用 nginx 代理请求
> 
> 二选一

nginx有没有示例配置，我也遇到这个问题。
通过访问https://域名/powerjob的方式，nginx代理到真实的后端地址上，但是脚本加载的还是https://域名，并不会被nginx代理到。
请问nginx应该怎么配置项目前缀而不是一个全新的域名或端口号的方式代理
