### ISSUE TITLE
K8S 部署如何连接集群的ip,集群ip还是pod ip？怎么设置能让process连接到docker中的镜像ip？

### ISSUE THREAD

**Issue by pzlgit** [PowerJob/PowerJob#157]
问题描述：
      Server端的操作无异常，但是Processor执行有问题，可能是因为我们是部署在docker镜像内的，读取的地址是镜像的pod地址，导致后面没法执行吧？ 报错信息如下：
 Outbound message stream to [akka://oms-server@ip:10086] failed. Restarting it. akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [akka://oms-server@ip:10086] did not complete within 20000 ms
      我是在本地打包成jar，然后直接放到云平台执行的，但是底层也是部署在docker镜像内的，我应该使用集群ip，还是pod节点IP，默认app_info表中的current_server是pod节点ip，出现上述的问题应该如何解决呢？

       需要每个pod能相互访问的ip,需要保证worker和server在的pod能获取到能互相访问的ip，这个操作应该如何配置，或者说如何处理？

**Comment by KFCFans** [comment]
@ocean23 能否请你们公司的运维大哥出个教程😂～
k8s 部署这一块，挺多人踩坑的。
感谢～

**Comment by ocean23** [comment]
好的，我把他拉入这个项目让他看一下这个问题

**Comment by ocean23** [comment]
@techsnail 业余时间有空时帮忙看一下上面的错误，假如有兴趣可以参与到这个项目中来出个教程什么的。@KFCFans techsnail是我们的运维大佬 :smile:

**Comment by KFCFans** [comment]
> @techsnail 业余时间有空时帮忙看一下上面的错误，假如有兴趣可以参与到这个项目中来出个教程什么的。@KFCFans techsnail是我们的运维大佬 :smile:

哈哈，好～感谢各位！

**Comment by techsnail** [comment]
> 问题描述：
> Server端的操作无异常，但是Processor执行有问题，可能是因为我们是部署在docker镜像内的，读取的地址是镜像的pod地址，导致后面没法执行吧？ 报错信息如下：
> Outbound message stream to [akka://oms-server@ip:10086] failed. Restarting it. akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [akka://oms-server@ip:10086] did not complete within 20000 ms
> 我是在本地打包成jar，然后直接放到云平台执行的，但是底层也是部署在docker镜像内的，我应该使用集群ip，还是pod节点IP，默认app_info表中的current_server是pod节点ip，出现上述的问题应该如何解决呢？
> 
> ```
>    需要每个pod能相互访问的ip,需要保证worker和server在的pod能获取到能互相访问的ip，这个操作应该如何配置，或者说如何处理？
> ```

如果单纯就你这个问题来说，是客户端访问不了服务端的10086端口导致的。
就我个人的使用经验而言，powerjob对网络的要求是，客户端和服务端的IP需要能够双向互通。更具体地说，在未更改默认端口设置的情况下，客户端需要能够访问服务端IP的7700和10086端口，服务端能够访问客户端IP的27777端口(如果未更改默认端口设置的话)。

若你将服务端部署到k8s中，客户端要如何才能与服务端正常通信？
这其实是一个k8s的网络问题，跟powerjob本身关系不大，当然我们需要清楚上述所说的powerjob对网络的要求。在k8s中部署powerjob有几种方式吧，依据具体情况可能问题会变复杂，在这里无法把所有情况都说清楚。我说一种最简单、基本上可以保证100%成功的方式吧，做法是：
使用statefulset来将powerjob-server端部署到k8s，假设为2个副本。再创建一个headless service与该statefulset相关联，该服务需暴露7700和10086端口，假设该服务的名称为jobserver。客户端应用同样部署到k8s的同一namespace中，此时客户端上面只需配置服务端地址为“jobserver-0.jobserver:7700,jobserver-1.jobserver:7700”即可正常通信。更多副本的情况也是类似的。在这种情况下，客户端与服务端是相互使用pod ip通信的。

关于你遇到的问题，说实话，跟你具体的部署方式有关，有很多可能的问题点。如果你熟悉k8s的话，参照上述说明，相信应该不是问题。如果不是很熟悉k8s，建议可与你们管理k8s的运维沟通下，相信他应该能明白，如有问题，可再让他提供下更具体的部署信息。
在k8s中部署powerjob的文档，需改天有空再写。

**Comment by pzlgit** [comment]
谢谢讲解，我对于k8s部署其实不是很清晰，感谢你的讲解，我这边问问运维处理。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Guowei"<notifications@github.com&gt;; 
发送时间: 2021年1月8日(星期五) 下午2:21
收件人: "PowerJob/PowerJob"<PowerJob@noreply.github.com&gt;; 
抄送: "1414001474"<1414001474@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PowerJob/PowerJob] K8S 部署如何连接集群的ip,集群ip还是pod ip？怎么设置能让process连接到docker中的镜像ip？ (#157)





  
问题描述：
 Server端的操作无异常，但是Processor执行有问题，可能是因为我们是部署在docker镜像内的，读取的地址是镜像的pod地址，导致后面没法执行吧？ 报错信息如下：
 Outbound message stream to [akka://oms-server@ip:10086] failed. Restarting it. akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [akka://oms-server@ip:10086] did not complete within 20000 ms
 我是在本地打包成jar，然后直接放到云平台执行的，但是底层也是部署在docker镜像内的，我应该使用集群ip，还是pod节点IP，默认app_info表中的current_server是pod节点ip，出现上述的问题应该如何解决呢？
    需要每个pod能相互访问的ip,需要保证worker和server在的pod能获取到能互相访问的ip，这个操作应该如何配置，或者说如何处理？   
如果单纯就你这个问题来说，是客户端访问不了服务端的10086端口导致的。
 就我个人的使用经验而言，powerjob对网络的要求是，客户端和服务端的IP需要能够双向互通。更具体地说，在未更改默认端口设置的情况下，客户端需要能够访问服务端IP的7700和10086端口，服务端能够访问客户端IP的27777端口(如果未更改默认端口设置的话)。
 
若你将服务端部署到k8s中，客户端要如何才能与服务端正常通信？
 这其实是一个k8s的网络问题，跟powerjob本身关系不大，当然我们需要清楚上述所说的powerjob对网络的要求。在k8s中部署powerjob有几种方式吧，依据具体情况可能问题会变复杂，在这里无法把所有情况都说清楚。我说一种最简单、基本上可以保证100%成功的方式吧，做法是：
 使用statefulset来将powerjob-server端部署到k8s，假设为2个副本。再创建一个headless service与该statefulset相关联，该服务需暴露7700和10086端口，假设该服务的名称为jobserver。客户端应用同样部署到k8s的同一namespace中，此时客户端上面只需配置服务端地址为“jobserver-0.jobserver:7700,jobserver-1.jobserver:7700”即可正常通信。更多副本的情况也是类似的。在这种情况下，客户端与服务端是相互使用pod ip通信的。
 
关于你遇到的问题，说实话，跟你具体的部署方式有关，有很多可能的问题点。如果你熟悉k8s的话，参照上述说明，相信应该不是问题。如果不是很熟悉k8s，建议可与你们管理k8s的运维沟通下，相信他应该能明白，如有问题，可再让他提供下更具体的部署信息。
 在k8s中部署powerjob的文档，需改天有空再写。

**Comment by KFCFans** [comment]
> > 问题描述：
> > Server端的操作无异常，但是Processor执行有问题，可能是因为我们是部署在docker镜像内的，读取的地址是镜像的pod地址，导致后面没法执行吧？ 报错信息如下：
> > Outbound message stream to [akka://oms-server@ip:10086] failed. Restarting it. akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [akka://oms-server@ip:10086] did not complete within 20000 ms
> > 我是在本地打包成jar，然后直接放到云平台执行的，但是底层也是部署在docker镜像内的，我应该使用集群ip，还是pod节点IP，默认app_info表中的current_server是pod节点ip，出现上述的问题应该如何解决呢？
> > ```
> >    需要每个pod能相互访问的ip,需要保证worker和server在的pod能获取到能互相访问的ip，这个操作应该如何配置，或者说如何处理？
> > ```
> 
> 如果单纯就你这个问题来说，是客户端访问不了服务端的10086端口导致的。
> 就我个人的使用经验而言，powerjob对网络的要求是，客户端和服务端的IP需要能够双向互通。更具体地说，在未更改默认端口设置的情况下，客户端需要能够访问服务端IP的7700和10086端口，服务端能够访问客户端IP的27777端口(如果未更改默认端口设置的话)。
> 
> 若你将服务端部署到k8s中，客户端要如何才能与服务端正常通信？
> 这其实是一个k8s的网络问题，跟powerjob本身关系不大，当然我们需要清楚上述所说的powerjob对网络的要求。在k8s中部署powerjob有几种方式吧，依据具体情况可能问题会变复杂，在这里无法把所有情况都说清楚。我说一种最简单、基本上可以保证100%成功的方式吧，做法是：
> 使用statefulset来将powerjob-server端部署到k8s，假设为2个副本。再创建一个headless service与该statefulset相关联，该服务需暴露7700和10086端口，假设该服务的名称为jobserver。客户端应用同样部署到k8s的同一namespace中，此时客户端上面只需配置服务端地址为“jobserver-0.jobserver:7700,jobserver-1.jobserver:7700”即可正常通信。更多副本的情况也是类似的。在这种情况下，客户端与服务端是相互使用pod ip通信的。
> 
> 关于你遇到的问题，说实话，跟你具体的部署方式有关，有很多可能的问题点。如果你熟悉k8s的话，参照上述说明，相信应该不是问题。如果不是很熟悉k8s，建议可与你们管理k8s的运维沟通下，相信他应该能明白，如有问题，可再让他提供下更具体的部署信息。
> 在k8s中部署powerjob的文档，需改天有空再写。

感谢那么详细的讲解，费心了！
