### ISSUE TITLE
任务job管理

### ISSUE THREAD

**Issue by f123ma** [PowerJob/PowerJob#158]
目前任务只是按照JOB_ID做唯一性判断，api的方式看起来有点弱，
能否采用quartz的api管理方式，远程api调用？

**Comment by KFCFans** [comment]
OpenAPI 目前确实只实现了最基础的功能。
我一直在等待用户需求来进行完善。
你可以列举一下需要的接口，我们逐渐完善。

**Comment by f123ma** [comment]
1、由于是改造项目切自定义了自己的类加载器，需要在启动时把定时任务全部注册进调度器，目前操作JOB的api基本够用，但是操作JOB都是根据JOB_ID来判断，但是ID又不能写死，能否提供一套根据名字的判断标准？能否提供查询全部JOB的api？触发时间比如下一次，上一次触发时间？
2、目前的console操作界面不适合开放给用户使用，部分定时任务需要开发简化的用户界面，由用户来操作关闭，启动，修改时间等操作，我的理解是如果开放JOB_NAME查询，如果做唯一性校验更好，这样用户可以自定义查询

**Comment by KFCFans** [comment]
1. 下个版本会提供 OpenAPI 的 Query 方法，支持根据 name 等条件查出任务
2. JobName 唯一性很好解决，你自己对数据库建个唯一索引就搞定了。然后配合查询 API 查出 ID 进行操作就行。

理论上下周一发布，还有需求的话可以再提。趁这个机会好好完善下 OpenAPI 也是极好的。

**Comment by KFCFans** [comment]
“触发时间比如下一次，上一次触发时间？” 
这一句话没看懂，还请详细描述一下。

**Comment by f123ma** [comment]
这个任务上一次的触发时间是什么时候，下一次任务将要在什么时间触发，类似console界面的任务实列详情的最近10条执行记录，这个需求可以看看别人是否也有这个需要？

**Comment by KFCFans** [comment]
目前看来增加这三个 API 可以满足你的需求：

- [ ] 任务全量查询，返回某个分组下所有任务数据
- [ ] 任务复杂查询，根据条件查询数据
- [ ] 任务实例查询（任务历史记录查询）（最近10条 and more）
