### ISSUE TITLE
Windows 环境体验优化（Java I/O in windows）

### ISSUE THREAD

**Issue by KFCFans** [PowerJob/PowerJob#161]
# 背景
当前 PowerJob 的文件操作都是针对 Linux 进行开发，在 Linux 和 macOS 系统上一切正常，但在 Windows 系统上存在着一些错误。
比如 https://github.com/PowerJob/PowerJob/issues/148 中的文件操作报错。

又比如：ScriptProcessor 中直接使用了 Linux 命令导致 Windows 环境下无法执行报错：
![image](https://user-images.githubusercontent.com/9402086/104410131-af5b6f00-55a2-11eb-8804-33c038643994.png)

综上所诉，有必要对 PowerJob 进行一轮文件操作的优化，使其对 Windows 的支持更加友好。

# 一些实现思路
* 寻求跨平台通过的 I/O API。
* 添加操作系统判断的工具类，按系统类型执行不同的文件操作。

**Comment by KFCFans** [comment]
@ocean23 有兴趣的话，可以看看这个 feature 😄

**Comment by ocean23** [comment]
我的电脑也是Mac，手上没有window的电脑:joy:   有没有其他的feature我可以参与

**Comment by KFCFans** [comment]
> 我的电脑也是Mac，手上没有window的电脑:joy:   有没有其他的feature我可以参与

哈哈哈，好的。

**Comment by jjnnzb** [comment]
我倒是用Windows居多，可以assign给我
