### ISSUE TITLE
秒级任务并发度控制不准确

### ISSUE THREAD

**Issue by ocean23** [PowerJob/PowerJob#164]
## 任务执行的并发问题

不管是设置为**CRON**还是**固定频率**, 由于真正执行的Processor都是通过akka异步通知的，所以就算设置了实例数量为1也只是能够保证**powerjob**通知是串行的，但是假如Processor执行的时间太长同样会出现同一时间多个Processor同时执行的情况，假如要在分布式环境下对串行执行有要求的话，需要在业务代码里面加锁来实现，不知道我理解的对不对？感谢指正哈

**Comment by KFCFans** [comment]
Dispatch 前会对数量做校验。
在纯由 powerjob-server 调度的情况下，一般并发度是可靠的。

**Comment by ocean23** [comment]
对于**固定频率**昨晚看代码时没发现原来任务派发时，它是发到当前这个worker，就是这句代码`dispatchTask(newRootTask, myAddress);`所以虽然通过akka把任务派发出去了但是由于是发到当前这个worker所以还是在同一个线程池里面执行。
不过就算是派发到当前这个worker的情况下对于**固定频率**这个场景还是会有机会发生同时运行两个`Processor`的情况，以下是具体重现的步骤:
1、
```
定时信息:  固定频率(毫秒)  时间区间: 2000(2秒)
```
2、
worker实现Processor的代码块, **Processor**线程`sleep` 5秒
```
private int increaseNumber = 1;

    @Override
    public ProcessResult process(TaskContext context) throws Exception {
        System.out.println("subId=" +context.getSubInstanceId());
        System.out.println("increaseNumber=" + increaseNumber);
        increaseNumber++;
        Thread.sleep(5000);
        System.out.println(new Date(System.currentTimeMillis()));
        System.out.println("end and subId=" +context.getSubInstanceId() + ";increaseNumber=" + increaseNumber);
        return new ProcessResult(true,"success");
    }
```

结果:
最后worker运行的console结果
<img width="544" alt="consoleprocess" src="https://user-images.githubusercontent.com/8874638/104567914-4fd88e80-568a-11eb-8b5b-6af7ab1b1112.png">

从上面的结果可以看到同时是有二个processor在运行的


原因如下图是因为初始化**固定频率**的线程池时poolSize设置为2，这时由于`processor`需要执行5秒但是**固定频率**的间隔是2秒，所以当前一个`processor`还没执行完时第二个任务又提交到了`threadPool`里面了，但是由于`poolSize`设置为2所以这时就会有两个processor在运行
<img width="1004" alt="initThread" src="https://user-images.githubusercontent.com/8874638/104568204-c1184180-568a-11eb-833f-846ce277f278.png">

建议方案：
<img width="581" alt="change" src="https://user-images.githubusercontent.com/8874638/104568841-895dc980-568b-11eb-8bfe-019035150c54.png">

以下是改为**1**后的console结果:
<img width="474" alt="result" src="https://user-images.githubusercontent.com/8874638/104570138-81eaf000-568c-11eb-8865-c822dd6e1e5e.png">

我们是希望**固定频率**在分布式环境下同一时间只有一个processor在运行，假如同意这样改的话我就发一个PR @KFCFans

**Comment by KFCFans** [comment]
我说了和线程池没关系，你咋就不信呢。。。
线程池只是线程池，事实上 size 设成 100 都没关系。

**Comment by KFCFans** [comment]
你没仔细看代码，秒级任务在 worker 端提交任务的时候也做了数量判断的。

![image](https://user-images.githubusercontent.com/9402086/104611810-7dd8c580-56c0-11eb-9e9b-0a3586469698.png)

不过我仔细看了下，这块判断逻辑有个小 bug，导致了你说的现象。
应该是 >= 而不是 >。
你可以提个 PR 修复这个 BUG，而不是纠结线程池的大小问题。

**Comment by ocean23** [comment]
嗯，size改为>=确实可以解决问题，另外我想请教一下这里`return 2`是出于什么考虑，为什么不是1或者3？
<img width="568" alt="pic9" src="https://user-images.githubusercontent.com/8874638/104615683-6ef41200-56c4-11eb-9939-e4f683aaf834.png">

**Comment by KFCFans** [comment]
当时是想着“万事留一线”来着。。。
你要是是在看着不爽，改成 1 也行吧......

**Comment by KFCFans** [comment]
不过不太建议改，因为单机任务也还是可能存在多次执行的情况的（假失败重试等等）。

反正凡事不要太死，有时候能避免很多问题。

**Comment by ocean23** [comment]
另外假如线程池的已经写死为**2**的话，最大实例数就算设置为超过2的实例数例如为10，但是同一时间最多也只有2个线程在跑另外8个实例也只是在`BlockingQueue`里面而已，所以对于**固定频率**假如这里的最大实例数指的是最大同时运行的实例，我建议不要写死而是直接传入最大实例数的值，这样就能够做到在配制页数设置的最大实例数就是最大的同时运行processor

**Comment by KFCFans** [comment]
不同的 instance 对应不同的 ProcessorTracker。
10个实例会有10个大小为2的线程池。

还是要继续深入研究源码啊。。。

**Comment by ocean23** [comment]
我觉得现在配置页面的实例和`subInstance`这两个概念是混合着用了，例如在配置页面文字写的是最大实例数，对于**固定频率**来说假如worker不挂就一直只会有一个而已，例如看页面上就只会有一条记录这就是我理解的实例，但是里面又用`subInstanceId2TimeHolder`和`maxInstanceNum`来比较这样很容易会让人混淆。

**Comment by ocean23** [comment]
由于对于**固定频率**这个场景假如收到任务的worker一直不挂的话，这个任务只会在这个worker一直运行下去这时这个woker会有一个大小为2的线程池，那这时配置页面这个最大实例数我们要如何设置，例如设置为3只是这里
```
subInstanceId2TimeHolder.size() >= maxInstanceNum
```
`maxInstanceNum`变为3而已，但是由于这台机的线程池的大小是2那设置为3还有什么意义呢？不知道我理解的对不对呀可能我对代码不熟，假如不正确麻烦指正哈

**Comment by KFCFans** [comment]
点赞，理论上确实存在问题。
可以在 calculate 线程池大小时加入类型判断，如果是秒级任务，也用 maxInstanceNum 作为线程池大小。

**Comment by gitnamegu** [comment]
固定频率执行修复了，CRON执行不顺道一起修复下吗？

**Comment by KFCFans** [comment]
> 固定频率执行修复了，CRON执行不顺道一起修复下吗？

CRON 不存在这个问题。

**Comment by gitnamegu** [comment]
> > 固定频率执行修复了，CRON执行不顺道一起修复下吗？
> 
> CRON 不存在这个问题。

这个是本地执行情况的截图
配置信息如下:
<img width="1680" alt="图片" src="https://user-images.githubusercontent.com/31877528/117292144-6b1e1280-aea2-11eb-8da9-4dc0f8a1db49.png">

执行情况如下:
<img width="1577" alt="图片" src="https://user-images.githubusercontent.com/31877528/117292377-b59f8f00-aea2-11eb-94ba-17ee817f8d73.png">

麻烦再确认下, 使用的powerjob-worker-spring-boot-starter是3.4.8版本, 代码中线程休眠50s, 如果是串行执行, 日志打印间隔至少相差50s

**Comment by gitnamegu** [comment]
> > 固定频率执行修复了，CRON执行不顺道一起修复下吗？
> 
> CRON 不存在这个问题。

这个是本地执行情况的截图:

配置信息如下:
<img width="996" alt="图片" src="https://user-images.githubusercontent.com/31877528/117293061-850c2500-aea3-11eb-8f7c-b2988bc79840.png">

执行情况如下:
<img width="1665" alt="图片" src="https://user-images.githubusercontent.com/31877528/117293489-05328a80-aea4-11eb-8c49-a8c90eb832e0.png">

麻烦再确认一下, 使用的powerjob-worker-spring-boot-starter版本是3.4.8, 本地测试中线程休眠50s, 如果串行执行, 每次日志打印间隔至少为50s

**Comment by gitnamegu** [comment]
> > 固定频率执行修复了，CRON执行不顺道一起修复下吗？
> 
> CRON 不存在这个问题。

这个是本地测试的截图:

配置截图:
<img width="1001" alt="图片" src="https://user-images.githubusercontent.com/31877528/117390008-f5588c00-af1f-11eb-8047-94bda89d3a35.png">

运行情况截图:
<img width="1592" alt="图片" src="https://user-images.githubusercontent.com/31877528/117390313-816ab380-af20-11eb-8ff2-1c284685edec.png">

麻烦再确认一下, 使用的powerjob-worker-spring-boot-starter是3.4.8版本. 代码中线程休眠50s, 如果是串行执行, 检测到上一个任务尚未结束, 那么这个任务不应该执行, 日志打印时间间隔应该相差50s.  目前的执行情况与预期不符

**Comment by limng06** [comment]
哈哈 好有趣啊 这层楼 都是苦命人
