### ISSUE TITLE
workflow 执行性能问题

### ISSUE THREAD

**Issue by jeickey** [PowerJob/PowerJob#166]
![image](https://user-images.githubusercontent.com/11632658/104561051-bd33f180-5681-11eb-9d86-1b4c39c9e891.png)
我的流程里2个任务，各自就是输出一个日志，执行完需要26秒？大家的测试结果是这样嘛？ 这和什么有关系 ？ 谢谢，

**Comment by jeickey** [comment]
普通的1秒的任务，也需要2 到 4秒的执行时间，并且还有时调度不到，是我用的有问题嘛？

**Comment by KFCFans** [comment]
这是 PowerJob 的内部实现决定的。
PowerJob的任务执行时间 = 任务的实际运行时间 + 最高 13 秒的 gap。
这个 gap 源自 PowerJob 的任务执行模型：异步执行 + 检测上报，这个检测的时间间隔为 13S，因此对于一个普通任务来说，最短需要的时间就是 13S。

![image](https://user-images.githubusercontent.com/9402086/104616294-15401780-56c5-11eb-86d9-489c0f23327d.png)

不过你这个 issue 提醒了我，对于这种快速执行完毕的任务，我可以通过调短 initDelay 来降低延迟。虽然个人认为任务多几秒的假耗时并不是什么问题。

不得不说你是个很仔细的人，为你的仔细点赞！

**Comment by jeickey** [comment]
是这样， 我在调研替代airflow的Java方案，如果这每个流程节点间隔13s还是有点夸张了，这个有参数调优嘛，或者是需要改源码？

**Comment by KFCFans** [comment]
下个版本会把初次检测的时间缩短到 3S，也就是对于耗时短的任务，最终耗时时间为 3S。对于执行时间较长的任务，假耗时多一点影响也不大。

这个参数对于不熟悉原理的人来说不能使用，乱改可能会带来很大的性能开销，所以不会放在配置文件里面。
可能考虑以 JVM 启动参数的形式支持。

**Comment by KFCFans** [comment]
v3.4.4 版本起，支持 `-Dpowerjob.worker.status-check.normal.period=10` 参数指定状态检测时间。单位为秒。
