### ISSUE TITLE
账号管理

### ISSUE THREAD

**Issue by linwei-scholar** [PowerJob/PowerJob#167]
执行器都要在调度中心server先注册再使用，但是感觉缺少了一个超级管理员的角色，对注册进行确认，对已注册账号进行管理，对所有调度任务的全局监控。
不知后期是否考虑实现这部分功能，如果执行器注册的越来越多，就会存在比较难运维和监控的情况。

**Comment by KFCFans** [comment]
这个最麻烦的点就是账号体系。
PowerJob 自建账号体系没什么意义，一般公司内部都有自己的账号体系。
但框架本身又没办法很好的去对接外部现有的账号体系......

绕开账号体系的话，就是提供一个全局的 portal 去展示所有已注册的 app 以及一些相关的信息，这个倒是可以。

**Comment by KFCFans** [comment]
目前倾向于去参考携程 Apollo 的设计，自建一套简单的账户与权限体系。

**Comment by linwei-scholar** [comment]
> 目前倾向于去参考携程 Apollo 的设计，自建一套简单的账户与权限体系。

后面我们会考虑进行这方面的客制化改造

**Comment by daliandazi** [comment]
可以提供简单的账户体系，顺便把接口留出来，可以自己扩展接入以有账户体系。

**Comment by KFCFans** [comment]
暂时先不考虑账户权限体系，集中精力完成基础建设。
