### ISSUE TITLE
超出最大同时运行的查询有误

### ISSUE THREAD

**Issue by ocean23** [PowerJob/PowerJob#168]
**To Reproduce**
1. 创建一个任务配置如下
```
定时信息: 固定频率（毫秒）2000
执行配置: 单机执行
运行时配置 最大实例数: 1 
```
2. 启动这个任务这时任务实例会显示有一条正在运行的实例
3. 回到任务实例管理界面点击**运行**
4. 这时在任务实例界面会看到有两个实例在正常运行

**Expected behavior**
由于我们在任务配置时是设置了最大实例数为**1**，但是现在结果是有两个实例在同时运行

**Environment**
 - PowerJob Version: [e.g. 3.4.2]
 - Java Version: [e.g. OpenJDK 8]
 - OS: [e.g. CentOS 8.1]

**原因**
```
            // 这个 runningInstanceCount 已经包含了本 instance
            // 不统计 WAITING_DISPATCH 的状态：使用 OpenAPI 触发的延迟任务不应该统计进去（比如 delay 是 1 天）
            long runningInstanceCount = instanceInfoRepository.countByJobIdAndStatusIn(jobId, Lists.newArrayList(WAITING_WORKER_RECEIVE.getV(), RUNNING.getV()));
```
手动触发时这个实例的状态为**等待派发**, 但是查询时没有把这个状态包括在内导致没能查出这条记录
**解决方案**
查询`runningInstanceCount`时要把**等待派发**这个条件加上去

**Comment by KFCFans** [comment]
你别钻这部分牛角尖了，注释写的很清楚，这部分是深思熟虑后才这样写的。
你要是想严格控制任务实例数，就自己上各种分布式锁去做判断。
PowerJob 现在的这套设计是在权衡了很多东西后得出的，并且在绝大部分情况下都能正常工作。

你要是想深钻，就给方案。不要只说问题不给方案，这只能说明你没有看到本质。当你去思考解决方案的时候，你就会知道为什么现在要这样设计。

**Comment by ocean23** [comment]
我只是想了解**powerjob**设计原则，假如已经确认**powerjob**秒级任务来说不能够严格控制任务数的话就只能在业务系统加锁来解决，因为我之前用的是ElasticJob所以思维定势也以为**powerjob**也能保证在同一时间只能有一个任务在执行。因为由于之前理解的不清楚导致生产上已经出现了重复推送数据，现在确认了就行。这个issue我除了提出问题，上面也已经给出解决方案了，只是不知道这个改正不正确而已，不是不给方案
![image](https://user-images.githubusercontent.com/8874638/104679188-1d7d6e80-5728-11eb-96be-02705491fd07.png)

```
原代码:
            long runningInstanceCount = instanceInfoRepository.countByJobIdAndStatusIn(jobId, Lists.newArrayList(WAITING_WORKER_RECEIVE.getV(), RUNNING.getV()));
```
```
改为：
            long runningInstanceCount = instanceInfoRepository.countByJobIdAndStatusIn(jobId, Lists.newArrayList(WAITING_WORKER_RECEIVE.getV(), RUNNING.getV(), WAITING_DISPATCH.getV()));
```
我在本地这样改后经过测试已经解决了这个问题。

**Comment by KFCFans** [comment]
你没看到我那行注释吗？你这样改，一旦有延迟任务就会出问题。

而且控制台触发本来就不是正常手段，通过控制台触发而导致的超出最大运行数符合预期。当然这里有可优化点，控制台触发可以前置加分布式锁去保证。

**Comment by KFCFans** [comment]
你用控制台触发去当测试 case 这个出发点就是错的。在错误的起点得出的结论当然都是错的。

DispatchService 这个方法没有任何的锁控制，理论上你在控制台狂点运行一瞬间就可以启动N个任务。

但是在 server 自助调度的情况下，这些都是不可能出现的场景。

所有我希望你能看清本质，而不是看到一点 case 就认定有问题。

**Comment by ocean23** [comment]
了解，那假如真的把powerjob用在重要的项目上时，我们自己内部的使用规范要写的非常清楚，不然只从powerjob的文档介绍来配制再加上使用其他定时任务框架的经验会造成实际结果和预期的不一致，感谢回复

**Comment by KFCFans** [comment]
嗯，这点很对。
感觉 PowerJob 可以制订一份 SLA。
有兴趣搞下吗哈哈？

还有，我想了下控制台触发任务这个也可以算个 bug 修复，通过控制台触发可以全局加个分布式锁，你有兴趣的话可以搞个 PR。

**Comment by ocean23** [comment]
> 嗯，这点很对。
> 感觉 PowerJob 可以制订一份 SLA。
> 有兴趣搞下吗哈哈？
> 
> 还有，我想了下控制台触发任务这个也可以算个 bug 修复，通过控制台触发可以全局加个分布式锁，你有兴趣的话可以搞个 PR。

好的，这一块我处理，迟点发一个PR
