### ISSUE TITLE
工作流运维能力升级

### ISSUE THREAD

**Issue by Echo009** [PowerJob/PowerJob#172]
#### 需求背景
在某些复杂的需求场景下，整个工作流非常庞大，如果在某个节点失败了，不支持原地重试的话，整体重试的时间成本过高。

#### 解决方案
执行失败的工作流支持原地重试（从失败的节点开始往后继续执行）。

#### 需求背景
工作流中的某个任务因为某些因素短时间内无法执行成功 🐶，但这个任务又不是那么重要（没有执行成功的前提下跑后面的节点影响尚且可以接受），希望能忽略掉当前节点继续跑后面的任务。

#### 解决方案
允许将工作流中失败的任务标记为成功状态并记录日志，搭配原地重试功能实现灵活运维 (๑•̀ㅂ•́)و✧

**Comment by KFCFans** [comment]
* 工作流原地重试应该不难实现～
* “支持将某个失败节点标记成功” 这个和 #117 提到的失败不打断整体工作流算是一个功能吧？如果我没理解错的话。

**Comment by Echo009** [comment]
> * 工作流原地重试应该不难实现～
> * “支持将某个失败节点标记成功” 这个和 #117 提到的失败不打断整体工作流算是一个功能吧？如果我没理解错的话。

[#117](https://github.com/PowerJob/PowerJob/issues/117) 这个是提供任务的复制功能，是不是弄错了。

任务的复制功能确实挺实用的，实现也简单。

不过工作流的复制更加实用，我们这边存在很多相似的工作流（仅有几个任务不一样，还有参数不一样）。

可以顺便做了 ~

**Comment by KFCFans** [comment]
嗯，输错了，是 #170 哈哈

**Comment by Echo009** [comment]
> 嗯，输错了，是 #170 哈哈

底层实现原理是一样的，只是他们的场景不一样，[#170](https://github.com/PowerJob/PowerJob/issues/170) 中是指在配置工作流中任务的时候指定的属性，对后面流程真正无关紧要的节点允许失败。
而这里指的是这类节点是对后面的流程有影响的，但是可能哪天出现了线上的该任务就是没法正常执行，短时间内无法解决的情况，但对后面的流程影响有限，这个时候允许在工作流实例详情界面将该节点标记为执行成功，点击重试后直接继续执行后面的流程。

**Comment by KFCFans** [comment]
懂了，确实是两个功能搭配实现下就好了。可以的。

**Comment by wang1589019** [comment]
想问下作者大大，这个fix在哪里版本能看到呢？
