### ISSUE TITLE
HTTP Processor

### ISSUE THREAD

**Issue by Echo009** [PowerJob/PowerJob#173]

**Comment by KFCFans** [comment]
诶，这个你们的想法是由 worker 来支持吗？即执行链路是
powerjob-server -> powerjob-worker -> http

如果还需要 worker 端参与的话，其实是没必要单独支持 HTTP Processor 的，因为你们完全可以开发一个单机的 Java 处理器，读取控制台的参数（url+请求参数）然后发送请求。这也是 PowerJob 为什么一开始不支持 Http Processor 的原因（用户编程可实现）。

我理想的 HTTP Processor 是不需要经过 worker 的，即 server 直接发调度请求，不依赖于 worker。这样也算是第一阶段的多语言支持。

**Comment by Echo009** [comment]
> 诶，这个你们的想法是由 worker 来支持吗？即执行链路是
> powerjob-server -> powerjob-worker -> http
> 
> 如果还需要 worker 端参与的话，其实是没必要单独支持 HTTP Processor 的，因为你们完全可以开发一个单机的 Java 处理器，读取控制台的参数（url+请求参数）然后发送请求。这也是 PowerJob 为什么一开始不支持 Http Processor 的原因（用户编程可实现）。
> 
> 我理想的 HTTP Processor 是不需要经过 worker 的，即 server 直接发调度请求，不依赖于 worker。这样也算是第一阶段的多语言支持。

我们之前也有想到过这个方式（通过开发一个Java 处理器来实现），但这样不同的 APP 就得都开发一个 Java 处理器才行。

至于放在 server 还是 worker ，从设计上讲，server 的职责是调度，worker 职责是执行，就看怎么理解发起 HTTP 请求这个动作了，算是 **执行** 还是 **调度** 。

**Comment by KFCFans** [comment]
我觉得算是调度。
整个流程中， server 只是发出 HTTP 请求，然后什么都不干，直到 HttpProcessor 回调 server 接口。整个模型和目前 server 和 worker 的模型是一致的，只是请求类型从 Akka 换成了 HTTP 而已，这是典型的调度。

如果让 server 同步等待 HTTP 返回结果的话，那就是执行了。

**Comment by Echo009** [comment]
> 我觉得算是调度。
> 整个流程中， server 只是发出 HTTP 请求，然后什么都不干，直到 HttpProcessor 回调 server 接口。整个模型和目前 server 和 worker 的模型是一致的，只是请求类型从 Akka 换成了 HTTP 而已，这是典型的调度。
> 
> 如果让 server 同步等待 HTTP 返回结果的话，那就是执行了。

表示赞同。但其实我们最开始的想法是直接同步等待 HTTP 返回结果，通过预定义好的响应体规范来判断成功或者失败。哈哈哈 😂 ，因为这样实现成本是最低的，被调方也不需要做特殊处理。

长远看的话，你的思路确实更好（算是第一阶段的多语言支持）

那关掉这个 issue ，另起一个？ (●ﾟωﾟ●)

**Comment by KFCFans** [comment]
可以的～
达成一致，哈哈
