### ISSUE TITLE
可否有办法不提示`Duplicate entry`这个错误

### ISSUE THREAD

**Issue by ocean23** [PowerJob/PowerJob#176]
## 由于是基于数据库实现的分布式锁，所以这个错误是预期内的行为想提示错误日志
由于每晚删除日志时监控都会报出这个错误:

![image](https://user-images.githubusercontent.com/8874638/104868294-ec967700-597d-11eb-8be7-5f5e1b0e4136.png)

但是这个错误又是`SqlExceptionHelper`报出来的感觉没办法不打印，打印错误的代码段:
![image](https://user-images.githubusercontent.com/8874638/104868359-16e83480-597e-11eb-9a89-07ed998c89a4.png)

大家有没有什么办法让这个错误不打印，不然每晚提醒一次有点烦。

**Comment by KFCFans** [comment]
我想到的只有通过 logback 配置文件全屏蔽 Spring Data JPA 的所有日志...不过这显然太暴力了......
估计不太行。

**Comment by ocean23** [comment]
那算了就让它报吧不理它就行了。
