### ISSUE TITLE
Windows 指定网卡

### ISSUE THREAD

**Issue by iamzzq** [PowerJob/PowerJob#179]
8:46:22.744 WARN  akka.event.slf4j.Slf4jLogger$$anonfun$receive$1 89 $anonfun$applyOrElse$2 - [outbound connection to [akka://oms-server@192.168.1.208:10086], message stream] Upstream failed, cause: StreamTcpException: Tcp command [Connect(192.168.1.208:10086,None,List(),Some(5000 milliseconds),true)] failed because of akka.io.TcpOutgoingConnection$$anon$2: Connect timeout of Some(5000 milliseconds) expired

**Comment by KFCFans** [comment]
1. 检查绑定的 IP 是否正确，如果不正确，请通过启动参数指定正确的网卡：https://www.yuque.com/powerjob/guidence/problem#ZaRnE
2. 检查端口打开情况
3. 检查防火墙

**Comment by iamzzq** [comment]
java -jar powerjob-server-3.4.3.jar -Dpowerjob.network.interface.preferred=Realtek PCIe GBE Family Controller博主您好，我这样设置jvm参数，绑定网卡，ip仍然不对，现在定位的是多网卡问题，我把其他网卡禁用了就好了，但是现在设置指定网卡启动没有生效

**Comment by iamzzq** [comment]
> 1. 检查绑定的 IP 是否正确，如果不正确，请通过启动参数指定正确的网卡：https://www.yuque.com/powerjob/guidence/problem#ZaRnE
> 2. 检查端口打开情况
> 3. 检查防火墙

java -jar powerjob-server-3.4.3.jar -Dpowerjob.network.interface.preferred=Realtek PCIe GBE Family Controller博主您好，我这样设置jvm参数，绑定网卡，ip仍然不对，现在定位的是多网卡问题，我把其他网卡禁用了就好了，但是现在设置指定网卡启动没有生效

**Comment by KFCFans** [comment]
感觉你指定的应该不是网卡名称
Linux 下一般是 eth0 这样
Windows 下一般是本地网络这种（没错...就是中文...），绑定网卡的时候应该也有启动日志，你可以看看。

PS.我确实没在 Windows 平台测试过这个启动参数的有效性，不过理论上应该是OK的

**Comment by KFCFans** [comment]
1. 下载源码，打开 `com.github.kfcfans.powerjob.common.utils.NetUtils` 类
2. 在指定位置插入一下代码
![image](https://user-images.githubusercontent.com/9402086/104974946-52ddd100-5a34-11eb-82bc-b7dc8f77d0ce.png)

3. 随便找地方写给 main 方法，运行这个方法，打印出所有网卡名称。

**Comment by KFCFans** [comment]
顺便，寻找真正网卡的代码是这一块，可以先用 IDE 启动然后单步调试 debug 看看原因。

![image](https://user-images.githubusercontent.com/9402086/104975277-3db57200-5a35-11eb-971d-ea9765343c31.png)

**Comment by KFCFans** [comment]
你的 Realtek PCIe GBE Family Controller 确实是网卡名称
![image](https://user-images.githubusercontent.com/9402086/104975410-879e5800-5a35-11eb-9ccd-f1e53a9931c3.png)

不过 PowerJob 使用的是网卡对外的展示名称
![image](https://user-images.githubusercontent.com/9402086/104975460-ae5c8e80-5a35-11eb-9f4b-c1dac0be46b1.png)

哈哈，我也是去看了下源码才发现...

**Comment by iamzzq** [comment]
> 你的 Realtek PCIe GBE Family Controller 确实是网卡名称
> ![image](https://user-images.githubusercontent.com/9402086/104975410-879e5800-5a35-11eb-9ccd-f1e53a9931c3.png)
> 
> 不过 PowerJob 使用的是网卡对外的展示名称
> ![image](https://user-images.githubusercontent.com/9402086/104975460-ae5c8e80-5a35-11eb-9f4b-c1dac0be46b1.png)
> 
> 哈哈，我也是去看了下源码才发现...

对外展示名称怎么查看，博主

**Comment by KFCFans** [comment]
下个版本同时支持 name 和 displayname 的指定～

**Comment by KFCFans** [comment]
> > 你的 Realtek PCIe GBE Family Controller 确实是网卡名称
> > ![image](https://user-images.githubusercontent.com/9402086/104975410-879e5800-5a35-11eb-9ccd-f1e53a9931c3.png)
> > 不过 PowerJob 使用的是网卡对外的展示名称
> > ![image](https://user-images.githubusercontent.com/9402086/104975460-ae5c8e80-5a35-11eb-9f4b-c1dac0be46b1.png)
> > 哈哈，我也是去看了下源码才发现...
> 
> 对外展示名称怎么查看，博主

我那个代码就是打印所有的对外展示。

**Comment by KFCFans** [comment]
记录：java -D参数 -jar xxx.jar args参数
