### ISSUE TITLE
界面任务都删了，后台还在执行任务

### ISSUE THREAD

**Issue by yushiyuxudong** [PowerJob/PowerJob#180]
**Describe the bug**
界面任务都删了，后台还在执行任务
**To Reproduce**
界面建个任务，启动他，然后停止，接下来删除任务，执行器还是在定时跑任务。
**Expected behavior**
删除任务能把任务实例表一起删了
**Environment**
 - PowerJob Version: [e.g. 3.0.0]
 - Java Version: [e.g. OpenJDK 8]
 - OS: [e.g. CentOS 8.1]

**Screenshots**
[image](https://user-images.githubusercontent.com/25975253/104982398-89701780-5a45-11eb-9e9f-47401c626be6.png)

**Additional context**

**Comment by KFCFans** [comment]
已修复
