### ISSUE TITLE
Question on PowerJob-worker currentServer assignment

### ISSUE THREAD

**Issue by jjnnzb** [PowerJob/PowerJob#181]
## Question
We deployed two PowerJob-server nodes, e.g. 192.168.10.11,192.168.10.12. All the business applications deployed, would own the following configurations, e.g. 
```properties
powerjob:
  worker:
    akka-port: 27777
    app-name: xxxxxx
    server-address: 192.168.10.11:7700,192.168.10.12:7700
    store-strategy: disk
```
We have now about 20 applications. When I query the `app_info` table, I found that most applications, about 15, were assigned the server `192.168.10.11:7700`, and only 5 were assigned to `192.168.10.12:7700`. 
My question is, what is the strategy for assigning currentServer for the application node? Should PowerJob-server node be assigned with the similar number of nodes, so that they withstand similar overall pressure?

**Comment by KFCFans** [comment]
1. worker use the first IP as the server by default, so as to reduce the conflict when the server selects the master
2. Different applications can use different IP order to achieve load balancing manually
3. It is recommended to assign domain name to powerjob-server to achieve load balancing automatically.

**Comment by jjnnzb** [comment]
> 1. worker use the first IP as the server by default, so as to reduce the conflict when the server selects the master
> 2. Different applications can use different IP order to achieve load balancing manually
> 3. It is recommended to assign domain name to powerjob-server to achieve load balancing automatically.

So to make the distribution more equivalent in my case, I should configure half of the applications in `192.168.10.11:7700,192.168.10.12:7700`, and half in `192.168.10.12:7700,192.168.10.11:7700`?

**Comment by KFCFans** [comment]
right
