### ISSUE TITLE
powerjob-server打成jar包后，在本机执行不报错，换台机器运行报错

### ISSUE THREAD

**Issue by maijieren** [PowerJob/PowerJob#182]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creati
ng bean with name 'mongo' defined in class path resource [org/springframework/bo
ot/autoconfigure/mongo/MongoAutoConfiguration.class]: Bean instantiation via fac
tory method failed; nested exception is org.springframework.beans.BeanInstantiat
ionException: Failed to instantiate [com.mongodb.client.MongoClient]: Factory me
thod 'mongo' threw exception; nested exception is com.mongodb.MongoConfiguration
Exception: Unable to look up TXT record for host cluster0.wie54.gcp.mongodb.net
        at org.springframework.beans.factory.support.ConstructorResolver.instant
iate(ConstructorResolver.java:655)
        at org.springframework.beans.factory.support.ConstructorResolver.instant
iateUsingFactoryMethod(ConstructorResolver.java:635)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:13
36)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:516)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$
doGetBean$0(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
y.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolve
Candidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
doResolveDependency(DefaultListableBeanFactory.java:1307)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
resolveDependency(DefaultListableBeanFactory.java:1227)
        at org.springframework.beans.factory.support.ConstructorResolver.resolve
AutowiredArgument(ConstructorResolver.java:884)
        at org.springframework.beans.factory.support.ConstructorResolver.createA
rgumentArray(ConstructorResolver.java:788)
        ... 55 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to insta
ntiate [com.mongodb.client.MongoClient]: Factory method 'mongo' threw exception;
 nested exception is com.mongodb.MongoConfigurationException: Unable to look up
TXT record for host cluster0.wie54.gcp.mongodb.net
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy
.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instant
iate(ConstructorResolver.java:650)
        ... 69 common frames omitted
Caused by: com.mongodb.MongoConfigurationException: Unable to look up TXT record
 for host cluster0.wie54.gcp.mongodb.net
        at com.mongodb.internal.dns.DefaultDnsResolver.resolveAdditionalQueryPar
ametersFromTxtRecords(DefaultDnsResolver.java:131)
        at com.mongodb.ConnectionString.<init>(ConnectionString.java:378)
        at org.springframework.boot.autoconfigure.mongo.MongoClientFactorySuppor
t.applyHostAndPort(MongoClientFactorySupport.java:102)
        at org.springframework.boot.autoconfigure.mongo.MongoClientFactorySuppor
t.computeClientSettings(MongoClientFactorySupport.java:70)
        at org.springframework.boot.autoconfigure.mongo.MongoClientFactorySuppor
t.createMongoClient(MongoClientFactorySupport.java:61)
        at org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration.m
ongo(MongoAutoConfiguration.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy
.instantiate(SimpleInstantiationStrategy.java:154)
        ... 70 common frames omitted
Caused by: javax.naming.CommunicationException: DNS error
        at com.sun.jndi.dns.DnsClient.query(Unknown Source)
        at com.sun.jndi.dns.Resolver.query(Unknown Source)
        at com.sun.jndi.dns.DnsContext.c_getAttributes(Unknown Source)
        at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_getAttributes(Unknown

**Comment by KFCFans** [comment]
mongoDB 连接失败，错误提示很明显，自己的配置有问题。

**Comment by maijieren** [comment]
oms.mongodb.enable=false,这个配置的都是false，在windows下执行不报错，在windows server2012上会出现这个问题，估计是和操作系统有关吧

**Comment by KFCFans** [comment]
我觉得大概是配置文件指定的有问题。
不用 mongoDB 的话可以把相关配置全部删掉。

**Comment by LeoDeYang** [comment]
我的也是这个问题。oms.mongodb.enable=false，Windows上没有问题。打包Jar到centos7服务器上去，一启动就是这个问题；还在解决中。
