### ISSUE TITLE
JobInfoQuery 无法 serialize

### ISSUE THREAD

**Issue by f123ma** [PowerJob/PowerJob#183]
**Describe the bug**
JobInfoQuery的注解@Accessors(chain = true, fluent = true)不产生getter，setter方法
导致JsonUtils在jackson-databind-2.10.3.jar无法序列化

**Environment**
 - powerjob-common: [3.4.4]
 - jackson-databind-2.10.3.jar: [2.10.3]

**Screenshots**
以下为powerjob-common的依赖关系
[INFO] +- com.typesafe.akka:akka-serialization-jackson_2.13:jar:2.6.4:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.10.3:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.3:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.3:compile
[INFO] |  +- com.fasterxml.jackson.module:jackson-module-scala_2.13:jar:2.10.3:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-paranamer:jar:2.10.3:compile
[INFO] |  |     \- com.thoughtworks.paranamer:paranamer:jar:2.8:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.10.3:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.10.3:compile
[INFO] |  +- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.10.3:compile
[INFO] |  \- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.10.3:compile

**Additional context**

**Comment by KFCFans** [comment]
具体表现出来的问题是什么呢？🤔

queryJob 方法无效吗？

**Comment by f123ma** [comment]
powerjob-client项目OhMyClient的
` public ResultDTO<List<JobInfoDTO>> queryJob(JobInfoQuery powerQuery) {
        powerQuery.setAppIdEq(appId);
        MediaType jsonType = MediaType.parse(OmsConstant.JSON_MEDIA_TYPE);
        String json = JsonUtils.toJSONStringUnsafe(powerQuery);
        String post = postHA(OpenAPIConstant.QUERY_JOB, RequestBody.create(jsonType, json));
        return JSONObject.parseObject(post, LIST_JOB_RESULT_TYPE);
    }
`
  String json = JsonUtils.toJSONStringUnsafe(powerQuery);
这个方法没法序列化没有getter，setter方法的pojo吧

**Comment by KFCFans** [comment]
谁和你说需要 get 和 set 方法的？
没试过就不要下结论。

**Comment by f123ma** [comment]
测试TestCase如下：
`public class JobInfoQueryTest {

	@Test
	public void testSerialize() {
		JobInfoQuery jobInfoQuery = new JobInfoQuery();
		jobInfoQuery.setAppIdEq(1L);
		jobInfoQuery.jobNameEq("testJobName");
		String json = JsonUtils.toJSONStringUnsafe(jobInfoQuery);
		System.out.println(json);
		assertEquals(json, "{\"appIdEq\":1}");
		assertEquals(json, "{\"appIdEq\":1,\"jobNameEq\":\"testJobName\"}");
	}

}`

为了避免开发工具包依赖的污染，采用maven命令mvn clean install 执行前删除maven仓库jackson的全部包，结果如下

`-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running JobInfoQueryTest
{"appIdEq":1}
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.479 sec <<< FAILURE!
JobInfoQueryTest.testSerialize()  Time elapsed: 0.447 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <{"appIdEq":1}> but was: <{"appIdEq":1,"jobNameEq":"testJobName"}>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
        at JobInfoQueryTest.testSerialize(JobInfoQueryTest.java:18)

Running NetUtilsTest`

序列化源码位于jackson-databind-2.10.3.jar
AnnotationIntrospectorPair.class的collectAll方法
如果必须这么用需要加
objectMapper.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY);

**Comment by KFCFans** [comment]
好，感谢反馈，稍后我测试一下。

**Comment by KFCFans** [comment]
已修复
