### ISSUE TITLE
集群机器数显示感觉不对

### ISSUE THREAD

**Issue by maijieren** [PowerJob/PowerJob#184]
部署了两个worker,两个应用名称，用两个应用名称分别登录看到的集群数都是1个，而不是两个，如图
![image](https://user-images.githubusercontent.com/50438521/105157317-d2a89000-5b47-11eb-98cd-4876784e6ca0.png)

**Comment by maijieren** [comment]
![1](https://user-images.githubusercontent.com/50438521/105157954-6e3a0080-5b48-11eb-82ed-4a17b50cc69c.png)
![2](https://user-images.githubusercontent.com/50438521/105157961-6f6b2d80-5b48-11eb-82a3-ce02edddc68a.png)

**Comment by KFCFans** [comment]
理解不够深入。

**Comment by KFCFans** [comment]
PowerJob 是以 appName 维度隔离的，不同 appName 的控制台只能看到自己这个分组下的集群。
