### ISSUE TITLE
固定频率任务启动后一直页面上查看一直提示timeout

### ISSUE THREAD

**Issue by wangzgBoom** [PowerJob/PowerJob#185]
最近在做分布式调度调研，搭了个demo，跑起来后发现固定频率任务启动后一直页面上查看一直提示time out

使用的时demo自带的StandaloneProcessorDemo，固定30s频率，超时时间5s,重试次数1
本地搭建的一个调度节点和一个worker节点
除了第一次提示成功，后续执行全部提示time out
换成cron表达式执行没有问题

想请问一下固定频率任务是有什么特殊机制导致了这个问题

**Comment by KFCFans** [comment]
秒级任务出于优化角度，底层的检测时间会根据执行频率调整，最高 15S（比如你 30S 才执行一次，PowerJob 没必要每秒都做轮询去检测，因此会计算出一个合适的轮询延迟）。
因此也许任务执行只需要 1ms，但状态检测带来了虚假的执行时常，从而导致 timeout。
一般建议秒级任务的超时时间 = 间隔时间，即 30S。
