### ISSUE TITLE
是否支持打成war包并在WebSphere中部署运行？

### ISSUE THREAD

**Issue by xuanyuan898701** [PowerJob/PowerJob#189]
官方推荐的是jar包，出于后续运维的需求，可能需要导成war包，在WebSphere上运行，目前部署不成功，初步看是因为有包冲突的原因，还在尝试解决。请问powerjob的工程，尤其是powerjob-server，有必须打成jar包这一说吗？

**Comment by KFCFans** [comment]
自己修改源码打包，网上一大把教程。
