### ISSUE TITLE
关于server集群调度的疑问

### ISSUE THREAD

**Issue by binsook** [PowerJob/PowerJob#191]
任务调度平台需要实现可以分片功能，可以支持到成千上万的定时任务调度。
根据官方文档 “引入分组依据 AppName，以应用集群作为 server 调度的单位”。
那么问题是
1.如何让不同的AppName分组可以基本均衡到不同的server呢？需要避免appName1,appName2,appName3.....都调度到某一个server上。
2.如果已经存在成千上万的定时任务，当重启server集群时，某一个server先启动好，所有的分组都会集中到该server上。其它server重启好之后，是否会成为永远空闲的server呢？是否有自动化机制可以在server之前做任务的均衡呢，以达到更高的性能。

谢谢

**Comment by KFCFans** [comment]
1. 内网域名自行完成负载均衡 OR 不同 worker 使用不同顺序的server IP 列表
2. 这种量级也不会只有 2 台 server 去支撑，不考虑这种比较极端的情况。

server 一般来讲不可能成为性能瓶颈，如果你真有成千上万的任务实例需要在短时间内调度执行，首先需要考虑的是 DB 和 worker 集群能否承受着压力。

**Comment by airect** [comment]
看过powerjob的文档，powerjob的设计很不错，但我有些疑问，和上面楼主有点类似，希望能解答下：
1. work集群应该是支持扩缩容的，server看起来应该是不支持扩缩容的，或者需要新增appname来支持吗？
2. server的HA看到上面的commit是用zk来保证吗？比如某个appname绑定的server挂掉了，只能依靠zk来选举一个新的server吗？

**Comment by KFCFans** [comment]
建议重新仔细看一遍文档
1. powerjob 任意组件支持水平扩展，app_name 只是个 worker 的租户概念
2. 不依赖 ZK

**Comment by KFCFans** [comment]
> 看过powerjob的文档，powerjob的设计很不错，但我有些疑问，和上面楼主有点类似，希望能解答下：
> 
> 1. work集群应该是支持扩缩容的，server看起来应该是不支持扩缩容的，或者需要新增appname来支持吗？
> 2. server的HA看到上面的commit是用zk来保证吗？比如某个appname绑定的server挂掉了，只能依靠zk来选举一个新的server吗？

建议重新仔细看一遍文档

powerjob 任意组件支持水平扩展，app_name 只是个 worker 的租户概念
不依赖 ZK

**Comment by airect** [comment]
刚翻到了高可用方案的微信公众号文章，server挂掉会依赖一个选举过程，挂到另外一个server上 https://mp.weixin.qq.com/s?__biz=MzA5MzYyNzQ0MQ==&mid=2247488202&idx=1&sn=129f0e65ee1d5104e2db391e4ef67e50&chksm=905ba794a72c2e824b9ebc642eb55af1ec6215144f0f660c2a6163c3aafe10d606835edacbe3&scene=178&cur_album_id=1424305043590791168#rd
