### ISSUE TITLE
邮件报警配置后没有收到邮件

### ISSUE THREAD

**Issue by maijieren** [PowerJob/PowerJob#192]
邮件报警配置后，故意让一个任务执行失败，但是没有收到邮件。如图，不清楚还需要配置什么
![11](https://user-images.githubusercontent.com/50438521/105939934-2447a200-6095-11eb-88b5-1f0136da5223.png)
![22](https://user-images.githubusercontent.com/50438521/105939945-27db2900-6095-11eb-8d69-57e3581da147.png)
![33](https://user-images.githubusercontent.com/50438521/105939947-27db2900-6095-11eb-82f4-4c94d2efd2f5.png)

**Comment by KFCFans** [comment]
看看 server 端日志，有没有邮件相关的报错信息。根据报错信息自己解决问题。
