### ISSUE TITLE
单个服务是否可以支持多个worker

### ISSUE THREAD

**Issue by lilongyang52** [PowerJob/PowerJob#194]
## Question
![image](https://user-images.githubusercontent.com/30489241/106239356-70354b00-623d-11eb-8405-9c5a335ba251.png)

如图所示，单个服务应该可以通过不同config来实例化多个worker ？

**Comment by KFCFans** [comment]
你可以试试，理论上是可以的，不过必要性是什么🤔

**Comment by lilongyang52** [comment]
> 你可以试试，理论上是可以的，不过必要性是什么🤔

我试过了，不可以！
![image](https://user-images.githubusercontent.com/30489241/106260931-f1033f80-625b-11eb-8e3f-c74ee8d96848.png)
这个方法就限制死了。
我的需求就是单个服务要支持多个app_name的定时任务调用

**Comment by KFCFans** [comment]
oh...
单 worker 多 name 会作为一个 feature 在后续版本中支持。

**Comment by KFCFans** [comment]
那为什么需要区分 appname 呢？我不是很理解实际需求。

**Comment by KFCFans** [comment]
短期内应该不会支持这个功能，抱歉。

**Comment by lilongyang52** [comment]
我已经修改并支持该业务
