### ISSUE TITLE
有时worker会出现这种情况，秒级任务，固定延时,但任务却成功执行了

### ISSUE THREAD

**Issue by StevenKin** [PowerJob/PowerJob#195]
**Describe the bug**
在秒级任务历史记录中会出现执行结果为LAUNCH_FAILED的记录，但查看日志却没有抛出异常

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
这种异常应该没有

**Environment**
 - PowerJob Version: 3.3.0
 - Java Version: java version "1.8.0_251"
                        Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
                        Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
 - OS: Linux version 3.10.0-1160.11.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Fri Dec 18 16:34:56 UTC 2020

**Screenshots**
![QQ图片20210129163520](https://user-images.githubusercontent.com/12849461/106251528-096d5d00-6250-11eb-935e-34ad520daa7d.png)

**Additional context**
日志文件
[worker.log](https://github.com/PowerJob/PowerJob/files/5892651/worker.log)

**Comment by KFCFans** [comment]
奇怪了🤔居然没有任何 error 日志🤔

**Comment by KFCFans** [comment]
任务的定时参数能发一下吗？
有点奇怪，这一块开始时间和结束时间怎么会完全一致呢🤔
![image](https://user-images.githubusercontent.com/9402086/106376044-5e35e280-63cc-11eb-88e6-bbf73c4261ca.png)

从代码的角度来看，如果开始和结束时间完全一致，那就是 save task 的时候出错了，那应该是会有 ERROR 日志的。

**Comment by KFCFans** [comment]
oh...
原来你用的是 v3.3.0，这个问题在后续版本中已经修复了。v3.3.x 版本存在着内存泄漏的 BUG，建议升级到最新版本。
