### ISSUE TITLE
对于使用shell 启动任务，监控任务状态优化

### ISSUE THREAD

**Issue by xjxjin** [PowerJob/PowerJob#196]
能否添加一个监控指标，目前的使用shell启动 是看控制台是否存活来判定任务是否是在运行中，如果是使用nohup启动的任务，能否兼容监控任务是否运行中，比如可以监控 进程来判断任务是否正常运行

**Comment by KFCFans** [comment]
这种需求建议自己写一个特殊的 Processor 来实现。

**Comment by KFCFans** [comment]
一个自己开发的 JavaProcessor，里面去完成你想要的 shell 启动逻辑和监控逻辑。

**Comment by xjxjin** [comment]
> 这种需求建议自己写一个特殊的 Processor 来实现。

好吧~~
