### ISSUE TITLE
关于Cron类型任务最小间隔为15s的问题

### ISSUE THREAD

**Issue by wangzgBoom** [PowerJob/PowerJob#201]
目前在做性能测试，发现配置的每秒一次的cron类型任务最低触发间隔为15s
这个相关机制是什么，核心源码在哪个位置，想去了解一下
还请作者能解答一下，谢谢

**Comment by KFCFans** [comment]
com.github.kfcfans.powerjob.server.service.timing.schedule.OmsScheduleService

更短间隔的任务可以通过秒级任务（固定频率 or 固定延迟）实现。

**Comment by linwei-scholar** [comment]
这个我在测试的时候也发现了，这个时间间隔设置15秒是处于什么考虑，能否调整呢？

**Comment by KFCFans** [comment]
PowerJob 会对执行非常频繁的任务（以下简称秒级任务）进行特殊处理以提升 server 的调度性能。
对于几秒钟执行一次的任务，完全可以使用固定频率 / 固定延迟 来代替 CRON 。
