### ISSUE TITLE
SwaggerUI 选择性开启

### ISSUE THREAD

**Issue by linwei-scholar** [PowerJob/PowerJob#203]
在测试的时候，单独部署了PowerJob的前端项目，发现后台api的调用可以直接使用postman测试，不用任何认证信息（账号密码或者token），这个太不安全，我们公司会定期都内部所有系统进行安全扫描，即便是部署在公司内网但有些公司对安全性要求很高，这个问题就比较严重了，建议给后端API加上校验，不知道后面会不会加上这个内容呢？

**Comment by KFCFans** [comment]
powerjob-server 是很容易定制开发的，你们可以直接关闭 swagger（删除 SwaggerConfig 这个类就行）。

后续考虑在配置文件中加一个配置直接关闭。

**Comment by KFCFans** [comment]
先支持通过配置文件 `oms.swagger.enable=false` 来关闭 Swagger-UI（默认就是关闭状态）。
权限这块将在后续版本支持。

**Comment by KFCFans** [comment]
已发布
