### ISSUE TITLE
Worker启动时找不到可用Server后启动失败

### ISSUE THREAD

**Issue by linwei-scholar** [PowerJob/PowerJob#204]
经测试和查看源码，发现worker在启动时，如果找不到可用的server就会启动失败，这就限制了server和worker的启动顺序，调度中心server必须先于worker启动，否则所有worker都不能正常启动；对于机房维护或者停电的生产场景，必须人工干预先启动调度中心，再启动worker。
我们是想把调度中心和worker都通过脚本设置成开机自启动，无需人工干预；所以能否在worker启动的时候不强制必须找到一个可用的server，启动之后在通过心跳检测可用server？不把worker的启动强制绑定server

**Comment by KFCFans** [comment]
worker 的配置中有一个参数 `enableDebugMode`。

当开启时不会强制做 server 连接校验。

**Comment by KFCFans** [comment]
com.github.kfcfans.powerjob.worker.common.OhMyConfig#enableTestMode

**Comment by linwei-scholar** [comment]
OK， 谢谢 @KFCFans

**Comment by linwei-scholar** [comment]
> com.github.kfcfans.powerjob.worker.common.OhMyConfig#enableTestMode

@KFCFans   在worker中配置了powerjob.worker.enable-test-mode=true，worker可以不校验server正常启动，但是发现好像有个Bug, 因为worker启动时没有校验server所以OhMyConfig初始化后没有给appId赋值，所以后面每次调用ServerDiscoveryService#acquire方法时，请求的地址都是http://127.0.0.1:7700/server/acquire?**appId=null**&currentServer=null，请求报错导致Worker永远都无法连接到Server，即使Server服务正常。

**Comment by KFCFans** [comment]
感谢反馈，后续解决。
