### ISSUE TITLE
工作集群运行久了发现只有一台机器在执行任务

### ISSUE THREAD

**Issue by PANIXS** [PowerJob/PowerJob#205]
3个server,12个worker,worker是逐步增加到12台的,跑了一段时间后,任务列表显示任务基本都超时了,重启任务并看服务器日志发现,只有一台机器在跑任务.
项目配置:
![image](https://user-images.githubusercontent.com/22359128/106987213-ec80de80-67a7-11eb-9672-6fcad169e167.png)

![image](https://user-images.githubusercontent.com/22359128/106986649-c575dd00-67a6-11eb-96f7-dd50a8d350a1.png)
![image](https://user-images.githubusercontent.com/22359128/106987053-a166cb80-67a7-11eb-91eb-7510903f5c43.png)

![image](https://user-images.githubusercontent.com/22359128/106986740-f3f3b800-67a6-11eb-9db8-2892cd0890d3.png)

看了下没有跑任务的服务器,akka连接都是aborted
重启worker之后等了很久也没啥效果,没有任务调度机器上
![image](https://user-images.githubusercontent.com/22359128/106987314-2356f480-67a8-11eb-9a50-25befa8967d1.png)

**Comment by KFCFans** [comment]
![image](https://user-images.githubusercontent.com/9402086/106996085-32936d80-67bb-11eb-8ed4-679eab25db76.png)

单机任务当然只会有一台机器执行。

**Comment by PANIXS** [comment]
20几个任务都同时在一个机器上执行,这些任务不应该分散在12台机器上吗,而且我配的是两个实例,至少应该有两台机子在跑啊

**Comment by KFCFans** [comment]
目前的任务派发策略只会选择状态最优的机器，不考虑均衡度。
不过秒级任务一旦下发就不再更换 worker，确实存在着过度偏斜的问题。

**Comment by KFCFans** [comment]
至于“最大实例数”这个参数，只有下一次调度开始时上一次调度的任务还没有结束才可能生效。在固定延迟的场景中是不会出现多实例的情况的。

即便出现多实例的情况，也不意味着有多台机器，这是两个不同的概念。

**Comment by KFCFans** [comment]
不过后续版本确实考虑加上“轮询”或“随机”策略

**Comment by PANIXS** [comment]
好的,谢谢大师,我悟了
