### ISSUE TITLE
日志传输，为什么不实现slf4j整合，完全可以实现一个Appender实现日志静默传输，这样子对系统整合更高，对于接入的人来说学习成本更低

### ISSUE THREAD

**Issue by OriginLU** [PowerJob/PowerJob#206]
日志传输，为什么不实现slf4j整合，完全可以实现一个Appender实现日志静默传输，这样子对系统整合更高，对于接入的人来说学习成本更低

**Comment by KFCFans** [comment]
1. Slf4J 只是门面，底层没有任何日志的具体实现。
2. 你想说的应该是写个自定义 Appender 然后后台传输数据给 server 吧？本质上和当前的方式没什么区别，并且使用 appender 就需要强依赖某种日志框架。
3. 不太理解你说的学习成本。PowerJob 提供的日志 API 是完全遵循 SLF4J 规范的，几乎没有任何额外的理解成本。

**Comment by OriginLU** [comment]
不够恰当描述，这边先说个抱歉，以下只是个人观点:
1.个人觉得使用的日志输出整合不够优雅，如果整合实现了logback，log4j的appender，在实现上会更加优雅点。
2.但在排查错误的时候，本地日志不需要在调用两次日志输出。

**Comment by KFCFans** [comment]
你是说系统的本地日志吗？
这一块后续会考虑换成 PowerJob 自己的 LogFactory，属于非重要非紧急事项。

“本地日志不需要在调用两次日志输出”这个还是没懂，两次日志输出是什么？

**Comment by QcoderWho** [comment]
我想他的意思是，在定时任务中要将日志写两遍，一遍是输出给powerjob server的，一遍是输出到本地日志框架的。。。如果直接自定义powerjob专用的appender，可以在这个自定义appender中将日志（需要定义flag来判断）输出到powerjob server

**Comment by KFCFans** [comment]
> 我想他的意思是，在定时任务中要将日志写两遍，一遍是输出给powerjob server的，一遍是输出到本地日志框架的。。。如果直接自定义powerjob专用的appender，可以在这个自定义appender中将日志（需要定义flag来判断）输出到powerjob server

这样有利有弊吧，坏处就是将在线日志和本地日志绑死了。事实上我觉得很大部分情况都是不绑死的，比如大规模任务如果所有日志都上报给 server 会对 server 有冲击，本地可以多大点，但是用 OmsLogger 需要精简。

如果需要完全一样的双写，可以自己用个方法封装一下。所以这点我觉得还好。
