### ISSUE TITLE
“too many instances”后任务频繁执行

### ISSUE THREAD

**Issue by likeonechild** [PowerJob/PowerJob#207]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）
版本：3.4.5
现象：在powerJob中配置了一个CRON定时任务0 0/1 * * * ? ，最大实例数及线程数都为1，没有配置“运行时间限制”，任务配置及内容不变，运行2到3个小时之后总会出现“too many instances”异常。
而且出现异常后这些任务每秒钟都会执行一次，跟了一下代码发现runningInstanceCount确实为1，可是我配置的间隔时间为1分钟，为什么会有1秒钟执行的一次任务，作者有时间麻烦看一下，多谢
![1612512465(1)](https://user-images.githubusercontent.com/19264156/107006655-704cc200-67cc-11eb-8574-1e613329d589.png)
![1612512574(1)](https://user-images.githubusercontent.com/19264156/107006751-94100800-67cc-11eb-906b-845f9e63a9cb.png)

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by KFCFans** [comment]
麻烦提供下 powerjob-server 端的日志，可以以 jobId 或 instanceId 作为关键字搜索。

**Comment by KFCFans** [comment]
![image](https://user-images.githubusercontent.com/9402086/107026233-62f00180-67e5-11eb-8788-b202ae4d82f6.png)

**Comment by KFCFans** [comment]
目前框架没有做很多合法性校验，你的问题应该是参数不合法导致的。
后续版本中会修复这个问题。

**Comment by likeonechild** [comment]
额，我是idea起的，当时的日志没保存，会不会是OmsScheduleService.refreshJob里面NextTriggerTime修改后没有立即flush造成的，额，我现在没时间，我明天仔细看一下，，，，谢谢作者帮忙，哈哈

**Comment by likeonechild** [comment]
判空加上之后，不是特别好使，还会出现too many instances。我把OmsScheduleService.refreshJob改成saveAndFlush之后，暂时没出现too many instances这个问题

**Comment by KFCFans** [comment]
save 后会统一 refresh，理论上和这一块没有关系。
