### ISSUE TITLE
任务周期管理，指定时间自动关闭任务

### ISSUE THREAD

**Issue by yangshp** [PowerJob/PowerJob#208]
任务周期管理，指定时间自动关闭任务

**Comment by KFCFans** [comment]
任务生命周期
Job（Workflow） 会增加两个参数，startTime 和 endTime 来管理生命周期，只有时间介于这两者之间的任务才会被调度执行。

需要考虑的事项：
* 向下兼容性：数据库中老任务的字段为 NULL，需要兼容这种情况
* 任务过期处理：状态处理 & 过期通知（MAIL + 扩展接口实现）

计划上线时间：2021年3月低

**Comment by KFCFans** [comment]
可能需要支持多个时间段

**Comment by dream0708** [comment]
需要支持多个时间段

**Comment by Echo009** [comment]
暂不支持多个时间段，如需配置多个时间段，请复制任务再配置不同时段
