### ISSUE TITLE
针对容器的处理任务可以加入到工作流吗？

### ISSUE THREAD

**Issue by caozhenhuamail** [PowerJob/PowerJob#211]
我这里有个需求是说比如有标准的处理流程，处理流程当中有很多任务可以组成工作流，因为我们是ToB业务，如果某一个客户的某一个任务是个性化的需求的话，这个个性化需要有可能自己开发也有可能第三方开发，所以希望这个三方开发的包能支持热部署那种，而且可以和原有流程串联起来。

**Comment by KFCFans** [comment]
当然可以。
容器只是一种热加载的能力而已，和工作流本身没有任何关系。

**Comment by caozhenhuamail** [comment]
嗯，我又重新看了下，是支持的。任务里可以选择容器；非常棒，本来我要用多个工具产品搞定的，在这里一个就可以了。

**Comment by KFCFans** [comment]
哈哈，可以去填个接入登记哦～

**Comment by caozhenhuamail** [comment]
嗯，还没开始接入那，在产品调研过程中，但是一定回填的。我看jd的已经有了是吧；

**Comment by KFCFans** [comment]
是的，再填一次也不错呀，哈哈。

顺便剧透下下个版本（4.x）工作流会有一次大规模的升级，敬请期待～

**Comment by caozhenhuamail** [comment]
4.x啥时候可以用，现在UI是有点不太友好。期待中

**Comment by KFCFans** [comment]
预计3月底 ～ 4月初。

UI的话确实不是很友好，期待你们也可以做做贡献，哈哈。
