### ISSUE TITLE
powerjob server 未启动时集成worker的应用启动会阻塞

### ISSUE THREAD

**Issue by QcoderWho** [PowerJob/PowerJob#214]
可以考虑启动个子线程，轮训server进行worker注册，就像eureka client 一样，默认30秒注册一次；
客户端目前的注册流程（需要先在server端注册）感觉有点怪怪的，可以考虑客户端自动注册的方式，当然自动注册的前提是服务端已经集成了使用者的用户体系，客户端在注册时携带凭证进行鉴权然后自动注册。。。不过这个做下去内容就太多了，目前我准备接入我们自己的用户体系打算这么做的，还准备做个处理器的注解（继承@Component）实现任务自动注册并同步到服务端，这样服务端就可以直接选任务了

**Comment by KFCFans** [comment]
目前通过设置 `com.github.kfcfans.powerjob.worker.common.OhMyConfig#enableTestMode`  = true 可以实现你说的自动注册功能。

不过在我的设计中，powerjob-server 是中间件 server 的存在，不存在没有 server 的情况。

appName 的自动注册这个应该没什么必要，因为后面 PowerJob 会引入用户与权限系统，自动注册没办法做到权限的分类。

至于任务自动注册并同步到服务端可供直接下拉选择，这个我其实有考虑过，当时觉得不是主要功能就没做哈哈。要是有兴趣你可以提个 PR 过来。非常欢迎～
