### ISSUE TITLE
自定义 Worker 选择逻辑

### ISSUE THREAD

**Issue by KFCFans** [PowerJob/PowerJob#215]
**Is your feature request related to a problem? Please describe.**
目前 PowerJob 只支持按 CPU、Memory、Disk 等指标进行 worker 的筛选，但部分用户存在按 GPU、IO 等指标筛选的需求。比如 AI 计算任务需要 GPU 资源等，所以需要开放自定义选择逻辑。

**Describe the solution you'd like**
新增 WorkerFilter 接口，允许用户扩展并在 dispatch 前调用

https://www.bilibili.com/video/BV1Fr4y1N7Ni

from 37:00

**Comment by KFCFans** [comment]
- [ ] JobInfo 新增 extra 字段，允许用户填写各种自定义 server 端的判断参数，比如 worker filter 需要的参数
- [ ] 重构 DispatchService 的 filter 逻辑，目前自带的 Filter 作为默认实现，DispatchService 调用 WorkerFilterService（注入所有 filter，所有 filter 都未过滤视为可用） 完成过滤
- [ ] 重构 Worker 端 SystemMetrics 收集逻辑，目前实现作为默认参数

**Comment by lehuqizhong** [comment]
SystemMetrics 收集逻辑目前没法自定义,PowerJobWorkerConfig中SystemMetricsCollector无法外部配置，一直使用内置的
