### ISSUE TITLE
单个app下较多任务的支持度

### ISSUE THREAD

**Issue by BEAR-S** [PowerJob/PowerJob#216]
新年好~
    看了powerJob的解读，感觉很有趣，看了又看，哈哈。这2天有个疑惑：无锁的一个关键是通过本机调度，根据应用分组，当不考虑服务器异常的情况，一个应用下面所有任务都会在同一台服务器上执行。那么遇到性能瓶颈，只能通过拆分应用的方式来解决吗？

**Comment by KFCFans** [comment]
新年好～
1. 单 app 几乎不可能到达 server 的性能瓶颈，除非你的场景下单 app 瞬时调度量在千或万级别（这种情况下主要的性能瓶颈也是在 DB 而不是在 server），在 DB 性能足够的情况下，server 几乎不可能成为瓶颈。
2. 假如真的存在这种情况，目前确实得通过分拆应用来实现。PowerJob 会在 4.x（下一个大版本）支持“单 Java 应用可启动多个 worker ”的功能，到时候就可以完成任务的拆分了。

**Comment by BEAR-S** [comment]
感谢回答啦。定时任务数据的获取不光是数据库，还有微服务嘛~期待4.x版本
（场景：由于数据时效性、数据保密性、系统定位等因素，一些系统定时任务逐步采用微服务来获取数据，而一些提供方只提供原子级别的服务，就出现轮询的局面。）

**Comment by KFCFans** [comment]
我提到的“数据库瓶颈”中的数据库是 powerjob- server 所使用的数据库。

如果是轮询类任务，PowerJob 的秒级任务几乎是 worker自治的，server负担非常小（仅负责一开始的派发和状态检测）。

综上，一般情况 server 不会出现性能瓶颈。

或者你可以列一下大致的实际任务情况，我可以帮你评估下。

BEAR-S <notifications@github.com>于2021年2月17日 周三下午7:30写道：

**Comment by BEAR-S** [comment]
看了您最新的回复终于想明白了，派发是给所有可用的worker
