### ISSUE TITLE
单应用支持启动多个 worker

### ISSUE THREAD

**Issue by KFCFans** [PowerJob/PowerJob#217]
**Is your feature request related to a problem? Please describe.**
单应用支持启动多个 worker

**Describe the solution you'd like**
1. 移除静态变量的方式
2. TaskTracker 的地址由 server 请求中携带或通过 Akka Actor 传递
3. ProcessorTracker 的地址由 TaskTracker 的 start 请求传递

**Comment by KFCFans** [comment]
https://github.com/PowerJob/PowerJob/issues/194

**Comment by KFCFans** [comment]
https://github.com/PowerJob/PowerJob/issues/216

**Comment by KFCFans** [comment]
WorkerRuntimeMeta

**Comment by Hey518** [comment]
![image](https://user-images.githubusercontent.com/72976175/108787135-11e75800-75b0-11eb-9e2b-0bdaca52b08c.png)
请问这种形式的单server配置多个worker是通过上述方法实现的吗？

**Comment by KFCFans** [comment]
> ![image](https://user-images.githubusercontent.com/72976175/108787135-11e75800-75b0-11eb-9e2b-0bdaca52b08c.png)
> 请问这种形式的单server配置多个worker是通过上述方法实现的吗？

不是一回事，是指单个 Java 应用上启动多个 powerjob-worker，这是比较小众的需求。
