### ISSUE TITLE
worker一直在发心跳，但是在server上只存活两三秒就消失了，原因未知

### ISSUE THREAD

**Issue by QcoderWho** [PowerJob/PowerJob#218]
在本地开发环境可以持续在线，但是在两台测试服务器上（centos7，各自用的不同数据库），一台可以持续在线，一台在线两三秒就没了，netstat -anlp|grep 10086显示worker的长连接是存在的，经过断点worker心跳上报发现心跳是持续在上报的，但是上报后其中一台服务器在线两三秒。。。请问这个问题的排查方向是什么，我明天多打点日志或者远程调试看看？

**Comment by jjnnzb** [comment]
看看两台机器有没有时间差的问题，我踩过这个坑

**Comment by KFCFans** [comment]
- [ ] 在控制台展示所有 worker，使用特殊标识标记不可用的机器

**Comment by QcoderWho** [comment]
> * [ ]  在控制台展示所有 worker，使用特殊标识标记不可用的机器

控制台显示不了那台机器，上报心跳后两三秒就消失了，一直这样重复。上面那哥们说对了，就是时间问题，我的有一台机器快了一分多钟，我把时间校准后就没有问题了

**Comment by KFCFans** [comment]
这个是我给自己记的后续 action
降低排查成本
