### ISSUE TITLE
本地启动时考虑用h2替换mysql？

### ISSUE THREAD

**Issue by xiaoed** [PowerJob/PowerJob#219]
本地启动时考虑用h2替换mysql？这样代码clone下来后无需配置就可以直接启动了。

**Comment by KFCFans** [comment]
1. 没必要
2. 可以自己改

**Comment by KFCFans** [comment]
主要是考虑到大部分用户使用的是 MySQL，所以项目配置文件中的 MySQL 应该是不会改的。
不过可以我可以在文档的教程中给出 H2 本地启动的配置，方便直接启动。

总而言之感谢建议！

**Comment by KFCFans** [comment]
已更新官方文档
![image](https://user-images.githubusercontent.com/9402086/108751312-0169ba00-757d-11eb-9ede-b49043c05720.png)

**Comment by KFCFans** [comment]
h2配置
```
spring.datasource.core.driver-class-name=org.h2.Driver
spring.datasource.core.jdbc-url=jdbc:h2:file:~/h2/powerjob-daily-test;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.core.username=sa
spring.datasource.core.password=
```
