### ISSUE TITLE
是否有按instanceId回写在线日志的接口？

### ISSUE THREAD

**Issue by xuanyuan898701** [PowerJob/PowerJob#221]
背景：目前在用官方提供的HttpProcessor，很实用，目前远程http接口所在应用不适合作为worker接入。

以官方提供的HttpProcessor为例，假如设置了超时时间60s，远程http接口可能在60秒内没有完成业务逻辑，没有返回执行结果（什么时候执行完毕不确定），worker与远程接口的连接就断开了，远程业务是否成功或者报错不知道，就失去了对此任务的在线日志监控。

解决方案：是否可提供一个回写在线日志的http接口，例如writeBackOnlineLog(instanceId, msg)，远程接口业务逻辑执行完毕后可以调用这个http接口，将msg回写到正确的instance日志文件中？

**Comment by KFCFans** [comment]
没正式测试过单个接口的使用情况，你可以先试试

https://www.yuque.com/powerjob/guidence/igmhuu#mBPn2

**Comment by KFCFans** [comment]
比较麻烦的是请求地址，目前的 Http Processor 是一种临时中转方案，调用路径为 server -> worker -> http。因此对 worker 来说拿到的 server address 地址是错误的（只能拿到akka端口地址，但实际需要 http 端口地址）。

现阶段你可以通过硬编码把端口号换掉（10086换成10010）的方式使用。

后续 PowerJob 会支持 server 级的 HttpProcessor（调用路径 server -> worker），这才是真正的完全体方案。

**Comment by xuanyuan898701** [comment]
找到submitLogs(String workerAddress, List<InstanceLogContent> logs)方法，请问这里的workerAddress是不是取instance_info表里面的Task_tracker_address就可以了？代表是执行此次instance的worker地址。用ip:port当参数？

**Comment by KFCFans** [comment]
NO，还是建议你直接看我给你的文档。

**Comment by KFCFans** [comment]
可以这样：
1. 使用服务发现接口获取 server address：https://www.yuque.com/powerjob/guidence/igmhuu#4PDWi
2. 使用在线日志接口写入数据：https://www.yuque.com/powerjob/guidence/igmhuu#mBPn2

**Comment by xuanyuan898701** [comment]
您说的这种方式其实还是通过worker去上报日志，假如我worker调用完远程http接口，由远程http接口直接调用server中的com.github.kfcfans.powerjob.server.service.InstanceLogService.submitLogs(String workerAddress, List<InstanceLogContent> logs)，instanceId可以拿到，workerAddress由instanceId也可以拿到，这种方式是否有问题？我写了个demo试了下，貌似是可以的，在线日志也能查到，但不确定有没有潜在问题。
ps：远程http调用的是随机一台server的接口

**Comment by KFCFans** [comment]
我说的方法完全不经过 worker，你可以重新理解下。
