### ISSUE TITLE
Official HttpProcessor support alarm configuration

### ISSUE THREAD

**Issue by jjnnzb** [PowerJob/PowerJob#223]
**Is your feature request related to a problem? Please describe.**
Official HttpProcessor always returns true, in other words, the alarm logic is always disabled. Simply printing logs won't satisfy the needs in most scenes.

**Describe the solution you'd like**
Add more configurationable fields in `HttpParams`, e.g.
```java
public class HttpParams {
    // ... (Other fields that already exist.)
    /**
     * Default value is false, if set true, then execute the alarm logic.
     */
    private Boolean alarmEnabled;
    /**
     * Eq/Ne, Eq means equals, Ne means not equals.
     */
    private String alarmCondition;
    /**
     * Alarm condition field, e.g. code. This field specifies the field for alarm condition.
     */
    private String conditionField;
    /**
     * Alarm condition value, e.g. 200. This field specifies the value for alarm condition.
     */
    private String conditionValue;
    /**
     * Alarm message field.
     */
    private String messageField;
}
```
Or put the alarm fields into another class, and include the class into the current HttpParams class.

**Describe alternatives you've considered**
When `alarmEnabled` is enabled, the `conditionField` and `conditionValue` field will be taken to form the alarm condition. For example, if `alarmEnabled=true`, `conditionField=code`, `conditionValue=200`, `messageField=msg`, if the `code` in response json is not `200`, the `msg` field will used as alarm message.

**Comment by KFCFans** [comment]
just check http return code and return false when code is not equals to 200.

**Comment by jjnnzb** [comment]
My solution seems too complicated. Just leave 
```java
 private Boolean alarmEnabled;
```
and if `alarmEnabled=true`, api that does not return `code=200` in request body will trigger alarm.

**Comment by KFCFans** [comment]
There is no need to use alarmEnabled.
"api that does not return code=200 in request body will trigger alarm" is OK

**Comment by KFCFans** [comment]
@jjnnzb 这个改动你有在跟进吗？你不做的话我有空做掉了，你这做的话可以拉个单独的 feature 分支

**Comment by jjnnzb** [comment]
@KFCFans 应该OK了，你帮我Review一下，白天我有测这个

**Comment by KFCFans** [comment]
下次创建分支时注意下规范，这种功能性改动应该直接新建一个 feature 分支。

https://github.com/orgs/PowerJob/teams/developers

![image](https://user-images.githubusercontent.com/9402086/110568918-c081c000-818e-11eb-9ddb-601ddc6c7e1b.png)

**Comment by jjnnzb** [comment]
> 下次创建分支时注意下规范，这种功能性改动应该直接新建一个 feature 分支。
> 
> https://github.com/orgs/PowerJob/teams/developers
> 
> ![image](https://user-images.githubusercontent.com/9402086/110568918-c081c000-818e-11eb-9ddb-601ddc6c7e1b.png)

OK
