### ISSUE TITLE
集成到springboot，worker启动失败NoSuchMethodError

### ISSUE THREAD

**Issue by TakeAwayAntun** [PowerJob/PowerJob#224]
java.lang.NoSuchMethodError: com.typesafe.config.Config.getDuration(Ljava/lang/String;)Ljava/time/Duration
![image](https://user-images.githubusercontent.com/37616560/109101658-19e6f980-7762-11eb-8cf3-9a86392335bb.png)

**Comment by KFCFans** [comment]
依赖冲突问题请查看文档解决
https://www.yuque.com/powerjob/guidence/problem#wtaIX

如果自己无法解决，需要提供完整的异常堆栈和 maven 依赖树。
