### ISSUE TITLE
同一AppName下的执行器动态分组

### ISSUE THREAD

**Issue by liuchengqiao** [PowerJob/PowerJob#226]
在工作流调度场景中，调度和执行的最小单位都是任务，任务最终会被分发到某个worker上，执行时任务和执行器绑定，在当前power job的worker和master的通信机制中，worker在启动时向master注册，在注册时告诉master归属于哪个AppName，通过AppName约束worker和master的关系，这里的worker是广义上的worker，特指包含了多个业务executor的jvm进程，这就引发了一个问题，在微服务场景下，不同的业务服务归属于不同的服务集群，甚至在物理上部署在不同的地域，如果一个工作流恰好横跨了多个业务服务(集群)，每一个子任务的执行都是在不同的集群上，而参与执行工作流的worker又必须要拥有全部的executor代码，这就导致了在微服务场景下任务无法被正确的调度到拥有代码的worker上，所以希望有某种机制可以把同一AppName下的worker在逻辑上分组成不同的worker集群，每一个逻辑上的worker集群对应着微服务场景下的一个服务集群，目前能够想到的是解决方案是，worker在启动时除了向master注册AppName之前，还要向master注册BusinessTag，根据BusinessTag划分worker集群，配置任务时指定当前任务由某个BusinessTag关联的worker集群执行，这就样保证了任务在执行时，任务可以通过BusinessTag关联出相应的worker，然后再根据负载均衡算法调度任务到某个worker上执行，这个概念和k8s里面的label相似，pod和service通过label相关联，本质上来讲，通过label解耦任务和worker，至于BusinessTag如何注入worker，我个人认为，可以写死在代码里，毕竟确定了就几乎不会修改，这样也更安全

**Comment by KFCFans** [comment]
1. worker 端通过 PowerJobWorkerConfig 的 tag 参数进行分组
2. Job 配置侧指定机器运行栏，除了传入执行器地址，还可以传入 tag 来进行筛选

**Comment by liuchengqiao** [comment]
感谢作者支持
