### ISSUE TITLE
Server 端是否支持指定 IP

### ISSUE THREAD

**Issue by heychek** [PowerJob/PowerJob#227]
Server 端如果是 docker 部署的，那么 Server 应该是会自动获取的容器的 IP，如果 Client 和 Server 不在一个 docker bridge 下，那么似乎二者就无法通信？我理解的，Server 端起码应该可以获取到宿主机的内网 IP 而不是容器 IP 吧。我看了语雀文档 IP 相关的问题，也看了这里好几个 issue，都与此有关。我依然认为这是个需要被解决的问题。解决方式或者可以类似于 nacos server 端那样的指定 IP 的方式

**Comment by KFCFans** [comment]
1. 请参考这个 issue （k8s + docker）:https://github.com/PowerJob/PowerJob/issues/157
2. 如果我开放出使用 JVM 指定绑定 IP 的功能，你们如何实现不同动态传递正确的 IP 进来呢？写部署脚本获取 IP 吗🤔似乎也是一种方方式。如果可行的话，这周我会出一个 mini 更新版本来支持这个特性。

**Comment by heychek** [comment]
> 1. 请参考这个 issue （k8s + docker）:#157
> 2. 如果我开放出使用 JVM 指定绑定 IP 的功能，你们如何实现不同动态传递正确的 IP 进来呢？写部署脚本获取 IP 吗🤔似乎也是一种方方式。如果可行的话，这周我会出一个 mini 更新版本来支持这个特性。

我有个疑问，这个问题大部分情况都是客户端无法访问服务端的 10086(默认) 端口。因为这个 10086 端口的 IP 是由服务端通过 7700 端口给的，服务端给的这个 IP 是他自己获取的，而这个服务端获取的 IP 无法用于和客户端的通信。但问题在于，客户端既然已经可以通过 7700 通信了，那为什么不可以直接使用这个通信 IP 而不是服务端自己获取的 IP 来访问 10086 呢

**Comment by heychek** [comment]
另外关于 157 的 issue，我个人其实认为在 k8s 中把服务端部署成 statefulset 并不合适，它应该是个 deployment

**Comment by KFCFans** [comment]
通过 JVM 启动参数 `powerjob.network.local.address` 可指定绑定 IP

这样应该能满足你的需求吧

**Comment by heychek** [comment]
我的需求肯定可以满足，就是这种做法可能不是最佳解决方案，没法用在所有客户身上。比如集群化部署，或者就是 k8s 部署的情况，逐个实例去指定 ip 感觉也不太对劲

**Comment by KFCFans** [comment]
集群化部署使用启动脚本获取需要绑定的IP，然后动态设置启动参数。需要做的只是写一个启动脚本而已。

除此以外我暂时想不到更好的方法，你要是有的话可以提出来。

**Comment by heychek** [comment]
另一款开源调度软件 xxl 里面有一项配置似乎就是为了解决容器和指定 IP 问题的(不确定，没翻看代码)，他官方文档的说明是下面这样的，你看看这是不是属于已经被踩过的坑，有没有参考意义
```
### 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
xxl.job.executor.address=
### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
xxl.job.executor.ip=
```

**Comment by heychek** [comment]
他还有一个依赖是这样使用的
```
/**
     * 针对多网卡、容器内部署等情况，可借助 "spring-cloud-commons" 提供的 "InetUtils" 组件灵活定制注册IP；
     *
     *      1、引入依赖：
     *          <dependency>
     *             <groupId>org.springframework.cloud</groupId>
     *             <artifactId>spring-cloud-commons</artifactId>
     *             <version>${version}</version>
     *         </dependency>
     *
     *      2、配置文件，或者容器启动变量
     *          spring.cloud.inetutils.preferred-networks: 'xxx.xxx.xxx.'
     *
     *      3、获取IP
     *          String ip_ = inetUtils.findFirstNonLoopbackHostInfo().getIpAddress();
     */
```

**Comment by KFCFans** [comment]
你上面列举的这些 PowerJob 都早已支持了，针对的是网卡选择问题。

**Comment by KFCFans** [comment]
已发布，参数为 `-Dpowerjob.network.local.address`
理论上用该功能可实现公网调度。

**Comment by zjf88865** [comment]
> -Dpowerjob.network.local.address
已经尝试，根本不行啊，搞什么鬼连云原生都不支持
