### ISSUE TITLE
重启 调度器和执行器

### ISSUE THREAD

**Issue by xjxjin** [PowerJob/PowerJob#228]
## Question
重启调度器 和执行器  是否会导致目前在执行的任务失败

**Comment by KFCFans** [comment]
1. 重启 server ：可以认为没有任何影响。
2. 重启 worker：当前该 worker 作为主节点（TaskTracker）的所有任务实例会失败，如果有配置失败重试，那么 server 会进行重试。

重启导致任务失败是无法避免的，除非自己去做优雅下线。
