### ISSUE TITLE
能否拓展2个接口，任务状态获取和任务停止

### ISSUE THREAD

**Issue by xjxjin** [PowerJob/PowerJob#229]
官方处理器  实际上是启动方式的自定义
那是否在任务状态获取 和任务停止也可以自定义

**Comment by xjxjin** [comment]
> 官方处理器 实际上是启动方式的自定义
> 那是否在任务状态获取 和任务停止也可以自定义
在任务状态获取和任务停止，如果没有指定处理类  就用默认的方式处理

**Comment by xjxjin** [comment]
目前的想法是能否将此处改为接口  可以自己去实现 状态判定的逻辑
![image](https://user-images.githubusercontent.com/35513148/110274559-0cefc300-800a-11eb-8b49-b95ab842e770.png)

**Comment by KFCFans** [comment]
NO，状态是框架内部的东西，不是可以对外开放和扩展的东西。

你要描述需求，而不是告诉我应该怎么怎么做。

**Comment by KFCFans** [comment]
你要做的是抛出问题，让我从框架设计者的角度来解决问题。
而不是直接来一堆解决方案，这样对我来说没有任何意义。

**Comment by xjxjin** [comment]
1、创建shell 任务
2、任务派发到目标机器
3、目标机器执行派发过来的shell 脚本命令，将任务提交到 yarn中
4、通过获取yarn集群上任务的状态 返回给server
5、任务需要提前终止，下发指令给worker 调用yarn集群api   kill任务

以上为我的需求
目前存在的问题
1、现阶段状态的判断是看线程是否运行正常，我需要调用第三方api来查询状态
2、任务的停止，现阶段的是杀死线程，但是我的需求需要调用 yarn api 来杀死任务

**Comment by KFCFans** [comment]
那我提几个问题：
1. 你的任务能不能用 Java Processor 去承接，在 Java Processor 里面调用 shell 启动任务，然后可以自己根据 API 去查询集群状态。具体的状态我觉得可以写到你自己的存储里面，没必要用 PowerJob 的状态来存。
2. 任务提前终止在 Java Processor 里面其实也能实现，不过不太优雅（catch InterruptedException 然后调用 yarn api 杀死任务）。

**Comment by KFCFans** [comment]
按我看来你这个需求其实用 JavaProcessor 去承接更好，而不是单纯把 PowerJob 当一个 shell 启动器。

**Comment by xjxjin** [comment]
主要是想实现  一旦 woker或者server 发生问题，挂掉了，运行的任务 不会受到影响

**Comment by KFCFans** [comment]
用 JavaProcessor 也不会有什么影响吧
