### ISSUE TITLE
调度器进程被杀掉

### ISSUE THREAD

**Issue by deli-tang** [PowerJob/PowerJob#231]
![image](https://user-images.githubusercontent.com/80249952/110426689-7db5de80-80e1-11eb-8cf2-bcf3cbcd67aa.png)

**Comment by deli-tang** [comment]
![image](https://user-images.githubusercontent.com/80249952/110482952-2dac3b80-8124-11eb-9f5e-f8eb3cfba369.png)

**Comment by deli-tang** [comment]
server运行一段时间 突然挂掉

**Comment by deli-tang** [comment]
![Uploading image.png…]()

**Comment by deli-tang** [comment]
![image](https://user-images.githubusercontent.com/80249952/110566098-7ac2f880-818a-11eb-9f78-15d706560e76.png)

**Comment by deli-tang** [comment]
内存在server启动后从1G多逐渐减少直到无可用内存，然后进程结束

**Comment by KFCFans** [comment]
1G 内存过小了，操作系统无法分配足够的内存就 kill 进程，很正常。

**Comment by deli-tang** [comment]
![image](https://user-images.githubusercontent.com/80249952/110567566-b363d180-818c-11eb-8747-8fc53f2b0009.png)
RSS在逐渐增大

**Comment by KFCFans** [comment]
server 占用内存启动后会有一段时间的增长（本地缓存的填充），这是正常现象。

**Comment by KFCFans** [comment]
你可以看看 Linux kill 进程的日志，看看操作系统 kill powerjob-server 的原因

**Comment by KFCFans** [comment]
dmesg 看一下

**Comment by deli-tang** [comment]
![image](https://user-images.githubusercontent.com/80249952/110602266-c7c1c180-81c0-11eb-8e78-a80d5b41c766.png)
确实是内存

**Comment by deli-tang** [comment]
调度器启动后，占用2G的内存，从top命令里DATA看实际需要 6.2G，那么机器内存最起码8G，是这样吧

**Comment by KFCFans** [comment]
不对诶，理论上不需要那么多内存的。

问几个问题来帮助排查：
1. 稍微描述下你目前的使用场景，比如控制台任务有几个，调度的量级大概有多少（任务实例数量）
2. 使用的 powerjob 版本
3. 有条件的话，最好在内存占用较大的时候 Java dump 一下，可以把 dump 文件发到这里，我会一起分析

**Comment by deli-tang** [comment]
这是刚部署到测试环境，还没有添加任务，机器是2C2G，硬盘5G，启动后3-4小时内存溢出，进程就挂了

**Comment by deli-tang** [comment]
![image](https://user-images.githubusercontent.com/80249952/110722179-d48bf700-824c-11eb-818b-a4b4dcd2ffc7.png)

**Comment by KFCFans** [comment]
ANSWER MY QUESTION

**Comment by deli-tang** [comment]
1、计算任务，目前定时任务10，动态定时任务30个，调度实例数17个
2、3.4.6

**Comment by KFCFans** [comment]
这个量不应该占用那么大内存的，可以看看 server 有没有什么异常日志（WARN ERROR），还有强烈建议内存快溢出前 dump 一下进行分析。
