### ISSUE TITLE
关于4.x版本工作流实例重试的疑问

### ISSUE THREAD

**Issue by xuanyuan898701** [PowerJob/PowerJob#235]
请问新版本即将支持的工作流实例重试，是否支持从指定节点开始重试工作流？因为上一次已经执行成功的工作流节点，可能不适合重复执行。等人工介入将失败的middle job做个处置后，希望再从失败的节点或者下游节点开始继续往下执行。

**Comment by KFCFans** [comment]
不会重复执行已经成功的节点，否则这不叫重试，叫重跑。

**Comment by xuanyuan898701** [comment]
刚看了工作流升级的视频，发现提问早了哈哈。视频比较模糊，看不清代码，echo说的两种场景，失败不允许跳过的，以及手动终止的，应该指的是重试的起点对吧？
