### ISSUE TITLE
Worker启动时检查Server出现的BUG

### ISSUE THREAD

**Issue by linwei-scholar** [PowerJob/PowerJob#236]
Worker启动检查问题：
以下两个问题的重现场景均是先启动worker，再启动server;
1. 在worker中配置了powerjob.worker.enable-test-mode=true，worker可以不校验server正常启动,但是server启动起来之后，worker始终无法连接到server上；
2. 在worker的配置powerjob.worker.server-address中配置了多个server地址，当第一个地址的server无效后，worker会启动失败，而不会继续使用后面的备用地址进行连接server;

> com.github.kfcfans.powerjob.worker.common.OhMyConfig#enableTestMode

@KFCFans   在worker中配置了powerjob.worker.enable-test-mode=true，worker可以不校验server正常启动，但是发现好像有个Bug, 因为worker启动时没有校验server所以OhMyConfig初始化后没有给appId赋值，所以后面每次调用ServerDiscoveryService#acquire方法时，请求的地址都是http://127.0.0.1:7700/server/acquire?appId=null&currentServer=null，请求报错导致Worker永远都无法连接到Server，即使Server服务正常。

_Originally posted by @linwei-scholar in https://github.com/PowerJob/PowerJob/issues/204#issuecomment-787666809_

**Comment by KFCFans** [comment]
`powerjob.worker.enable-test-mode=true` 的设计本意算是绕过 server 直接启动 worker，说是 bug 也可以，说是 feature 也可以，这个影响不是很大，暂时先忽略。

**Comment by KFCFans** [comment]
第二个点我比较在意，为什么说第一个 server 不可用 worker 就会启动失败呢？这一块我记得我是做过测试的，应该没问题才对。晚点我重新测试验证下。

或者你也可以分析下源码看看问题出在哪里。

**Comment by linwei-scholar** [comment]
抱歉，第二点我又测试了一下，会遍历最终找到一个可用的server；
第一点，我尝试看了下源码，应该可以自行修改下；

**Comment by shuowen** [comment]
请问这个问题解决完了吗 @linwei-scholar
