### ISSUE TITLE
server端无法发现work机器数

### ISSUE THREAD

**Issue by wangyubing-io** [PowerJob/PowerJob#237]
**Describe the bug**
server部署在测试环境centos, work部署在开发环境, 一切正常, 将work部署到测试环境后, server无法发现机器, 没有错误日志, 一切正常, 将数据库中的app-info表中的当前应用删除之后, 重新注册应用后, server可以正常发现机器数, 我不确定这是否是一个bug

**Comment by KFCFans** [comment]
能否提供删除前 DB 中的记录？

**Comment by wangyubing-io** [comment]
删除前app_info中我的应用current_server是ip1机器, 停止ip1的机器后, 我重新部署了work到ip2, server无法发现ip2的worker,  删除这个应用之后我重新注册了这个应用, app_info中的我的应用current_server变成了ip2, server就可以发现work; 大概是这样

**Comment by KFCFans** [comment]
暂时无法复现。
