### ISSUE TITLE
Workflow 工作流是否只支援單機執行的 processor

### ISSUE THREAD

**Issue by ccfang** [PowerJob/PowerJob#238]
您好，
使用您源碼的範例在測試工作流 A → B → C 這樣一個流程時，若是把 B 這個 processor 換成 broadcast 的話，發現並不會執行 preProcess 與 postProcess，也僅有一個 worker 會執行，因為沒有找到相關的文件或問題，所以想問問看是否不支援或是我自己本機環境的問題，謝謝

**Comment by KFCFans** [comment]
B 不只是代码层面需要更换为 BroadcastProcessor，配置侧也需要同步修改。

![image](https://user-images.githubusercontent.com/9402086/111435800-33190f80-873c-11eb-8c88-bcc4ec67f6d8.png)

请先确认下这一点，如果配置和代码都没有问题，我会进行测试，稍后给你一个回复。

**Comment by ccfang** [comment]
感謝快速回覆，的確是我配置有誤，沒改到廣播執行，謝謝
