### ISSUE TITLE
可否添加固定频率子任务的报警？

### ISSUE THREAD

**Issue by 18846837414** [PowerJob/PowerJob#239]
对于秒级任务的执行，就算执行失败了，Instance也处运行状态，无法触发报报警，更倾向于一有调用失败就触发报警的情景，这样报警可能更加的及时重要 @KFCFans

**Comment by KFCFans** [comment]
1. 该特性预计于 4.0.1 版本提供支持（下下个版本）
2. 考虑到 4.x 版本由于功能的强化，存在着某些不兼容的改动，有一定升级成本，在此处给出 3.x 版本下自主开发的方法。

**Comment by KFCFans** [comment]
概述：秒级任务的 master 节点（FrequentTaskTracker）会定时向 server 报告当前任务的执行情况，其中包括了 task 的成功、失败情况。利用该值的变化情况可以判断是否有新的任务失败。
![image](https://user-images.githubusercontent.com/9402086/111658097-01409f80-8847-11eb-9523-e769dbe649da.png)

简单说，需要改动的地方只有 server，在 InstanceManager 中对比上次 failedNum 和 当前 failedNum，如果有增加，说明有任务失败，执行报警操作。

**Comment by 18846837414** [comment]
感谢作者提供思路，但是result其实还是一个null值，对于接受报警的人来说，不能从报警信息中立马知道当前运行的状态，只能知道当前执行是有问题的，更详细的信息还是得上系统去看。 @KFCFans

**Comment by KFCFans** [comment]
可以在 worker 端记录最近的失败记录，然后 report 上来，result 信息就有了。
worker 每次 report 时把 recentFailedResult 当作 result 上报上去，然后清空本地的 cache，server 端根据这个值做判断也可以。

**Comment by KFCFans** [comment]
方案有很多，看你想怎么实现。

**Comment by Echo009** [comment]
https://github.com/PowerJob/PowerJob/issues/370
