### ISSUE TITLE
能不能创建个微信群那。QQ垃圾信息太多，都不看了。

### ISSUE THREAD

**Issue by Mihawk-lf** [PowerJob/PowerJob#241]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by KFCFans** [comment]
有群就会有垃圾信息，无可避免。
