### ISSUE TITLE
MapReduceProcessor是否有阻塞获取Reduce结果的API

### ISSUE THREAD

**Issue by 292292yang** [PowerJob/PowerJob#242]
我遇到一个需求，我有很多的商品数据需要校验(很多是5K+，商品数据校验需要校验是否启用，是否有价格，是否准销售等)，我想采用MapReduceProcessor来增加校验的速度。当我 map了需要校验的商品之后(比如分了20个片，分发到多台机器上执行），执行结果我如何获取呢（只能通过我手工去查询Instance信息么）？这个需求要求是实时的，当前端提交了校验之后我会立即执行任务，页面可阻塞的等待结果。

**Comment by KFCFans** [comment]
reduce 的入参就有全部子任务的执行结果，文档里都有写，好好看文档。
