### ISSUE TITLE
看的官方demo，http://try.powerjob.tech/#/oms/home。一个人负责多个应用，应用如何切换。

### ISSUE THREAD

**Issue by Mihawk-lf** [PowerJob/PowerJob#243]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by KFCFans** [comment]
后面引入账号和权限系统后会支持，设计上类似于 Apollo。

目前只能靠重复登陆来解决。。

**Comment by KFCFans** [comment]
目前没有“人”这个概念。

**Comment by Mihawk-lf** [comment]
> 后面引入账号和权限系统后会支持，设计上类似于 Apollo。
> 
> 目前只能靠重复登陆来解决。。

好的，谢谢哇。
MapReduce和工作流调度很赞。
我全面体验下产品，也从代码上学习下实现细节。

**Comment by KFCFans** [comment]
哈哈，好的。
如果接入使用了，可以去填个接入登记哦～

**Comment by Mihawk-lf** [comment]
> 哈哈，好的。
> 如果接入使用了，可以去填个接入登记哦～

一定一定。相信接入的话，我也能成为一个大用户，哈哈哈。

**Comment by KFCFans** [comment]
可以的，期待👍
