### ISSUE TITLE
最新版网页端后台集群机器数显示bug

### ISSUE THREAD

**Issue by mojianxiao** [PowerJob/PowerJob#245]
最新版本把清本地缓存的集群机器数放到cleanService上做了(address2WorkerInfo的remove方法)，在每天凌晨的三点才会清空这些本地缓存，导致了app下线后powerjob后台仍显示在线，状态不能及时清理
![image](https://user-images.githubusercontent.com/51684477/112602772-102edf80-8e4f-11eb-9c30-c252a71c8c6b.png)

**Comment by KFCFans** [comment]
感谢反馈，UI侧问题后续会进行修复。

**Comment by KFCFans** [comment]
已经修复该 UI 问题，下版本发布。

![image](https://user-images.githubusercontent.com/9402086/113543676-71a63980-9619-11eb-978a-034601eda852.png)
