### ISSUE TITLE
4.0.0分支工作流SQL更新

### ISSUE THREAD

**Issue by freesky100** [PowerJob/PowerJob#247]
**Describe the bug**
https://github.com/PowerJob/PowerJob/blob/v4.0.0/others/powerjob-mysql.sql
4.0分支中的的SQL未更新，在工作流导入的时候会报不能为空异常

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
 启动4.0提交导入工作流即可复现

**Environment**
 - PowerJob Version: [e.g. V4.0.0]
 - Java Version: JDK 8]
 - OS: [e.g. windows]

**Screenshots**
![image](https://user-images.githubusercontent.com/14148715/112823272-a7986a80-90bb-11eb-90cd-2be6fcb49c0f.png)

**Additional context**
更新SQL

**Comment by KFCFans** [comment]
感谢反馈，会尽快修复
