### ISSUE TITLE
删除任务能否也把该任务实例一起删掉

### ISSUE THREAD

**Issue by orangewest** [PowerJob/PowerJob#252]
任务管理中删除任务的时候能否把该任务的实例一起删掉，不然点进任务实例中很多都是已删掉任务的数据

**Comment by KFCFans** [comment]
这个是特性问题，我觉得任务删除后想看历史执行数据也是合理的需求，所以不会这么设计。

**Comment by lxx-sample** [comment]
> 这个是特性问题，我觉得任务删除后想看历史执行数据也是合理的需求，所以不会这么设计。

借楼问一下，历史记录会有定时清理功能吗
