### ISSUE TITLE
固定频率任务woker重启报警问题？

### ISSUE THREAD

**Issue by 18846837414** [PowerJob/PowerJob#254]
对于固定频率类型的任务，重启woke或者woker版本更新后，instance失败，都会引发报警，但存在大量的固定频率时，大量报警，这可能不是太友好，这对于接收人来说是不希望看到的也不应该关心，是否办法可以解决这个问题？ @KFCFans

**Comment by KFCFans** [comment]
1. 有能力的话建议自己定制报警逻辑（通过 PowerJob 的 webhook 转发到自己的报警接口上），可以添加一些自己的逻辑，比如秒级任务怎么怎么样不报警，连续 N 次失败报警等等。
2. 关于秒级任务本身的报警，后续版本有一些改动的规划，主要是对“失败”的定义会有转变，具体可以参考这个 issue：
https://github.com/PowerJob/PowerJob/issues/239

即因为机器重启导致的“失败”不计为失败，按子任务的纬度去定义失败。

**Comment by KFCFans** [comment]
since 4.1.1
