### ISSUE TITLE
Upgrade FastJson version

### ISSUE THREAD

**Issue by jjnnzb** [PowerJob/PowerJob#255]
**Is your feature request related to a problem? Please describe.**
建议项目依赖的FastJson版本升级一下，详见[Fastjson <=1.2.68 反序列化远程命令执行漏洞分析](https://www.anquanke.com/post/id/208104)，我们内部护网，PowerJob Server也涉及到了，直接升级到了1.2.75了

**Comment by jjnnzb** [comment]
刚看了一下,1.2.76已经发布了额

**Comment by KFCFans** [comment]
好的，下个版本会升级这个依赖。
顺便你可以罗列更多需要升级的依赖。

**Comment by jjnnzb** [comment]
其他Jar包似乎没啥问题，我们这边主要就是Apache Shiro和FastJson俩Jar包的版本问题。
按护网要求，还有个问题就是，MongoDB不允许不设置用户名密码直接访问，这个后面也调整一下吧。

**Comment by KFCFans** [comment]
mongodb 自己调整就行，和框架没关系。
