### ISSUE TITLE
工作流问题咨询

### ISSUE THREAD

**Issue by xuanyuan898701** [PowerJob/PowerJob#258]
几个工作流的需求，烦请指导：
第一个，在一次工作流实例执行过程中，假如想在还未执行到的某个节点上做一次人工干预，比如停止、标记跳过等操作，目前openAPI是否有相关接口可用？或者自行改造的话有何思路？
第二个，工作流中的节点实例失败后的重试目前是每隔10秒重试一次，假如不同节点重试间隔有个性化需求（比如一分钟重试一次），应该如何改造？
第三个，工作流节点processor方法调用一个远程http接口，可能过了超时时间才有返回（远程http接口运行时间不确定，延长超时时间也不是很合适），但又想根据此节点的结果决定是否往下执行，这种情况有什么好的解决方案吗？
第四个，工作流节点是否可带有延迟执行的属性，或者定点执行的属性。比如执行完前几个节点，下一个节点可能需要延迟一段时间才执行，或者到了某个时点再触发接着往下走。

**Comment by KFCFans** [comment]
1. 这些配置全部托管在工作流，和工作流实例没有关系。目前有修改工作流的 OpenAPI 接口，不过相对来说比较复杂。我理解工作流还是一个更偏向于前台配置的东西。
2. 这个属于新特性，有后续支持的计划，在 JOB 配置中新增“重试间隔时间”配置
3. 不使用官方处理器，自己写 http 处理器，然后把你认为能往下执行的情况设置为成功
4. 这个逻辑是可以写在 processor 中的，或者你可以加一个专有 processor 节点叫“等待节点”，里面执行 sleep 逻辑。

**Comment by wat1r** [comment]
需求和此需求有类似，MARK进来

**Comment by xuanyuan898701** [comment]
> 1. 这些配置全部托管在工作流，和工作流实例没有关系。目前有修改工作流的 OpenAPI 接口，不过相对来说比较复杂。我理解工作流还是一个更偏向于前台配置的东西。
> 2. 这个属于新特性，有后续支持的计划，在 JOB 配置中新增“重试间隔时间”配置
> 3. 不使用官方处理器，自己写 http 处理器，然后把你认为能往下执行的情况设置为成功
> 4. 这个逻辑是可以写在 processor 中的，或者你可以加一个专有 processor 节点叫“等待节点”，里面执行 sleep 逻辑。

你好，对于第一点，也就是目前还没有办法在一次工作流运行过程中临时在某个节点上去人工干预？而只能在编排工作流的时候就必须编排好哪个是要停止的，哪个是可以失败跳过的？

**Comment by hzhj2689083** [comment]
工作流的某个节点的参数能通过API动态传递么？

**Comment by Echo009** [comment]
> > 1. 这些配置全部托管在工作流，和工作流实例没有关系。目前有修改工作流的 OpenAPI 接口，不过相对来说比较复杂。我理解工作流还是一个更偏向于前台配置的东西。
> > 2. 这个属于新特性，有后续支持的计划，在 JOB 配置中新增“重试间隔时间”配置
> > 3. 不使用官方处理器，自己写 http 处理器，然后把你认为能往下执行的情况设置为成功
> > 4. 这个逻辑是可以写在 processor 中的，或者你可以加一个专有 processor 节点叫“等待节点”，里面执行 sleep 逻辑。
> 
> 你好，对于第一点，也就是目前还没有办法在一次工作流运行过程中临时在某个节点上去人工干预？而只能在编排工作流的时候就必须编排好哪个是要停止的，哪个是可以失败跳过的？

是的，目前是这样。你说的停止是执行到某个节点终止整个工作流还是说直接跳过（禁用节点）？

你可以提个 Feature，详细描述一下你的需求 ，我们会考虑在下个版本支持 (#^.^#) ~

**Comment by Echo009** [comment]
> 工作流的某个节点的参数能通过API动态传递么？

目前不支持，可以使用调用工作流的 OpenAPI ，指定启动参数来实现。可参考 [运行某个工作流（指定初始参数、延迟）](https://www.yuque.com/powerjob/guidence/olgyf0#jl8We)

传递的参数会注入到 [工作流上下文](https://www.yuque.com/powerjob/guidence/hczm7m#tihZO) 中。
