### ISSUE TITLE
感觉还是会存在多个server同一时间执行一个任务的情况

### ISSUE THREAD

**Issue by LiuWillow** [PowerJob/PowerJob#260]
#### 问题：多个server同时执行一个任务
复现方式：
* worker配置了server1和server2
* worker开始绑定server1，在discovery的时候worker请求server1超时，尝试server2成功，server2将数据库的currentServer更新
* 而server1在server2更新数据库之前执行了调度，拿到了worker对应的appInfo；server2在更新完之后也执行了调度，获取到同一个appInfo
* 两个server拿到了自己想要的信息，于是同时执行了两次任务

关于这个问题，看了[PowerJob源码分析-分组隔离设计](https://zhuanlan.zhihu.com/p/163487886)文章里提到，通过nextTriggerTime来保证同一时间不执行一个任务。但是调度的过程是拿到appInfoList -> 遍历appInfo写入instance -> 根据appInfo的nextTriggerTime推入时间轮 -> 最后才是修改nextTriggerTime，如果两个server已经拿到appInfoList开始走调度流程了，依然无法避免这个问题啊，毕竟全程无锁

**Comment by LiuWillow** [comment]
等等等等

**Comment by KFCFans** [comment]
一个 app 只能有一个 server，调度前会用数据库这个单点做唯一性判断。

**Comment by LiuWillow** [comment]
> 一个 app 只能有一个 server，调度前会用数据库这个单点做唯一性判断。

理想情况是这样，但是我上面说的复现方式是一种特殊情况。。。
我看代码里只是在getServer0选举过程中加了锁，但是调度的时候没加锁，所以是有一定几率发生的。

**Comment by LiuWillow** [comment]
![image](https://user-images.githubusercontent.com/25578789/114690084-f6473500-9d48-11eb-8b4d-fe4fdf0de775.png)

**Comment by KFCFans** [comment]
1. 这个概率比彩票头奖都小，纠结这个没意义
2. 重复执行本来就是分布式系统中不可避免的事情，需要强保证不重复执行的话都是在业务层自行实现。

**Comment by LiuWillow** [comment]
> 1. 这个概率比彩票头奖都小，纠结这个没意义
> 2. 重复执行本来就是分布式系统中不可避免的事情，需要强保证不重复执行的话都是在业务层自行实现。

明白了  感谢解答
