### ISSUE TITLE
一个高可用方案

### ISSUE THREAD

**Issue by xjxjin** [PowerJob/PowerJob#261]
1、部署多个server
最先启动的server往数据库中某个表写入一个标记，标记为active(活动),woker启动待woker向master注册后，向woker发送当前action的信息
其他的server启动判断如果已经有active,则为spare(备用)
如果为server状态为spare(备用)  则 定时任务不可触发,访问备用server地址，类似于访客模式，只可看不可操作
每个备用的server间隔一段时间判断action的心跳时间,如果超过一定时间则替换为action，同时向woker 发送当前action的信息
2、woker启动参数添加上多个server的地址，依次向每个地址注册信息，如有返回消息，则为注册成功，后续ip地址不用再注册，待收到active 的server信息之后，向active 的server 发送相关信息

**Comment by KFCFans** [comment]
你知道你想表达什么...
powerjob 所有组件都是自带高可用的。
