### ISSUE TITLE
同一个appName下的A,B两个worker内部的处理器必须完全一致吗

### ISSUE THREAD

**Issue by lancer2** [PowerJob/PowerJob#262]
假如同一个appName下:
workerA 执行器 包含 (processorA,processorB,processorC)三种处理器
workerB 执行器 包含 (processorC,processorD,processorE)三种处理器

A和B都可能有多个节点

**Comment by KFCFans** [comment]
核心的一点是你要保证任务的执行机器有对应的处理器。
如果你多个项目工程共用一个 appName，那么可以通过任务配置来指定任务的执行集群，比如指定IP或者指定 TAG（推荐）。可以参考：https://github.com/PowerJob/PowerJob/issues/226

![image](https://user-images.githubusercontent.com/9402086/115100690-cd08ed80-9f70-11eb-9e5d-e2b031edb299.png)

**Comment by lancer2** [comment]
tag属性我看worker文档里还没有  有时间可否完善下文档   这样后面有同样需求的同学也能明白如何使用了

**Comment by lancer2** [comment]
@KFCFans

**Comment by KFCFans** [comment]
好的
