### ISSUE TITLE
OpenAPI可以查到已删除的Job和Workflow

### ISSUE THREAD

**Issue by wsh759146139** [PowerJob/PowerJob#264]
OpenAPI可以查到已删除的Job和Workflow，并且无法从接口返回的结果判断其是否被删除

**Comment by KFCFans** [comment]
可以使用 Query 里面的 status 字段查询
tech.powerjob.common.request.query.JobInfoQuery#statusIn
![image](https://user-images.githubusercontent.com/9402086/122663290-deb67d80-d1cb-11eb-858d-72f31cd0b57f.png)

**Comment by limng06** [comment]
是否考虑添加一个 关闭逻辑删除的配置

**Comment by KFCFans** [comment]
> 是否考虑添加一个 关闭逻辑删除的配置

具体的业务场景是什么呢？请详细描述下需求。
