### ISSUE TITLE
Feature: 工作流支持workflow嵌套

### ISSUE THREAD

**Issue by BobWang-SIA** [PowerJob/PowerJob#266]
您好，请问Powerjob是否会在最近的开发计划中考虑对workflow嵌套的支持呢？
具体就是希望在创建工作流的时候，不仅能够选择导入已有的Task模板，而且能够选择导入已有的workflow模板作为工作流的一个subworkflow 节点，导入时支持用户填写该 subworkflow的参数值覆盖模板参数。
这样做的一个好处是可以提高已创建工作流模板的可复用性，并且将 subworkflow 作为一个任务节点角色，增强了工作流编排能力。
类似的特性在同类项目如Apache DolphinScheduler是可以看到的，我觉得如果Powerjob能够支持该特性的话，对于拓展使用场景是有帮助的。个人认为Powerjob在编码质量和设计方式的精妙程度上均高于DolphinScheduler，所以非常希望在功能特性上能够与其齐平。
期待回复，谢谢。

**Comment by KFCFans** [comment]
@Echo009 这个需求指给你 OK 不？

**Comment by KFCFans** [comment]
看完你的描述有一些疑惑：
在我理解中，workflow 模版和 workflow 嵌套 是两种完全不同的概念。
某一个workflow 作为另一个 workflow 的 subworkflow 这个功能（我认为的嵌套）提到的人很多，目前 PowerJob 也是有计划在 workflow 这一块上继续强化的，应该会考虑支持。

至于你说的 workflow 模版，我觉得这是一个减轻开发者工作量的工具（原来要重复导入N个任务，现在只要导入模版 + 简单配置），对于框架本身的运行时功能是没有提升的，这个短期内应该不会支持。

不知道我的这个理解全面不？如果不够全面，可以指出一下，哈哈。

**Comment by KFCFans** [comment]
@Echo009 workflow 嵌套这个功能，安排给你 OK 不？

**Comment by KFCFans** [comment]
nodeType 都留好了，我理解实现应该不复杂。顺便可以考虑下更多的 nodeType 如何优雅的支持。否则在可预见的将来会有一堆 if-else

**Comment by Echo009** [comment]
> @Echo009 workflow 嵌套这个功能，安排给你 OK 不？

ok

**Comment by Echo009** [comment]
> 看完你的描述有一些疑惑：
> 在我理解中，workflow 模版和 workflow 嵌套 是两种完全不同的概念。
> 某一个workflow 作为另一个 workflow 的 subworkflow 这个功能（我认为的嵌套）提到的人很多，目前 PowerJob 也是有计划在 workflow 这一块上继续强化的，应该会考虑支持。
> 
> 至于你说的 workflow 模版，我觉得这是一个减轻开发者工作量的工具（原来要重复导入N个任务，现在只要导入模版 + 简单配置），对于框架本身的运行时功能是没有提升的，这个短期内应该不会支持。
> 
> 不知道我的这个理解全面不？如果不够全面，可以指出一下，哈哈。

如果是单纯的配置，那挺好做的，但如果是 subworkflow ，个人感觉没那么好做，等我有空看下 DolphinScheduler 的实现 ~

**Comment by KFCFans** [comment]
可能我想的比较简单，我认为 subworkflow 对原有模型侵入也不大啊，无非是：
* 原来 run 某个节点是 job，现在变成 workflow
* 原来 move 的触发源是 job finished，现在变成 workflow finished

当然在这个基础上去额外考虑一些高级特性比如失败跳过 / 自定义参数 会比较困难，不过我觉得也问题不大。可以参考现有的 job + node_info 强化的模式，用 workflow + node_info 去强化。

总之我觉得还好，相信你能出色的完成（不是 PUA [滑稽]

**Comment by KFCFans** [comment]
顺便在这个基础上其实可以提取关键节点了，后续的工作流分支判断也类似，扩展点也就是上面提到的两个：
* 原来 run 的是某个 job 或 workflow，现在变成本地的一段代码
* 原来 move 的触发源是 job / workflow finished，现在变成分支判断 finished 

当然分支判断还有一些额外的复杂度，比如根据结果选择分支。那么这一层是不是也可以考虑抽象出去。

当然你暂时先直接写代码实现这个嵌套需求也行，不过我建议可以往这个角度去想想，看看能不能想到什么优秀的设计。

**Comment by Echo009** [comment]
> 可能我想的比较简单，我认为 subworkflow 对原有模型侵入也不大啊，无非是：
> 
> * 原来 run 某个节点是 job，现在变成 workflow
> * 原来 move 的触发源是 job finished，现在变成 workflow finished
> 
> 当然在这个基础上去额外考虑一些高级特性比如失败跳过 / 自定义参数 会比较困难，不过我觉得也问题不大。可以参考现有的 job + node_info 强化的模式，用 workflow + node_info 去强化。
> 
> 总之我觉得还好，相信你能出色的完成（不是 PUA [滑稽]
> 
> @Echo009

哈哈哈，按照你这个思路实现确实相对简单一些，（我之前想的是生成工作流实例的时候，对于嵌套工作流节点基于 节点信息 + 指定的工作流模板信息 动态生成一个 DAG ，用该 DAG 替换掉该节点，形成一个新的图）

这样的话前端交互方式要好好设计一下，我目前想到的主要包括以下几点，看看有没有要补充的 

1. 是采用“引用”的模式还是基于用户指定的工作流模板创建一个新的工作流嵌套进去？（各有利弊，引用的方式可以让用户很方便地一次性调整所有 workflow 下与之对应的 subWorkflow 信息，但是没法做到针对性的修改某个 workflow 下的 subWorkflow，另一种方案则正好相反）
2. 怎么让用户方便的定制化每个节点的参数？
3. 怎么让用户快速的查看对应 subWorkflow 实例的运行状态？（我的想法是点击节点跳转至对应 subWorkflow 实例信息展示界面）

**Comment by KFCFans** [comment]
> > 可能我想的比较简单，我认为 subworkflow 对原有模型侵入也不大啊，无非是：
> > 
> > * 原来 run 某个节点是 job，现在变成 workflow
> > * 原来 move 的触发源是 job finished，现在变成 workflow finished
> > 
> > 当然在这个基础上去额外考虑一些高级特性比如失败跳过 / 自定义参数 会比较困难，不过我觉得也问题不大。可以参考现有的 job + node_info 强化的模式，用 workflow + node_info 去强化。
> > 总之我觉得还好，相信你能出色的完成（不是 PUA [滑稽]
> > @Echo009
> 
> 哈哈哈，按照你这个思路实现确实相对简单一些，（我之前想的是生成工作流实例的时候，对于嵌套工作流节点基于 节点信息 + 指定的工作流模板信息 动态生成一个 DAG ，用该 DAG 替换掉该节点，形成一个新的图）
> 
> 这样的话前端交互方式要好好设计一下，我目前想到的主要包括以下几点，看看有没有要补充的
> 
> 1. 是采用“引用”的模式还是基于用户指定的工作流模板创建一个新的工作流嵌套进去？（各有利弊，引用的方式可以让用户很方便地一次性调整所有 workflow 下与之对应的 subWorkflow 信息，但是没法做到针对性的修改某个 workflow 下的 subWorkflow，另一种方案则正好相反）
> 2. 怎么让用户方便的定制化每个节点的参数？
> 3. 怎么让用户快速的查看对应 subWorkflow 实例的运行状态？（我的想法是点击节点跳转至对应 subWorkflow 实例信息展示界面）

我觉得没必要弄工作流模版，没有什么显著的收益。引用的方式实现简单同时很直观。
搞模版这些收益太低，只是解决开发者配置时间的事情，优先级很低。
