### ISSUE TITLE
没有轮询这种调度策略，一台服务器部署多个worker集群感觉对性能没提升

### ISSUE THREAD

**Issue by Michelean** [PowerJob/PowerJob#272]
除非你在创建任务中指定集群的机器选择哪个worker，但这就相当于你自己在做任务分配的资源平衡。还是worker的集群只为了MapReduce这种情况所服务么

**Comment by KFCFans** [comment]
1. 高可用
2. MR
3. 广播

而且你的主次有点关系。不是为了 PowerJob 部署 worker 集群。而是先有一个 app 的集群，然后引入了 PowerJob。
