### ISSUE TITLE
大佬什么时候更新啊，一两个月了

### ISSUE THREAD

**Issue by xjxjin** [PowerJob/PowerJob#274]
大佬什么时候更新啊  一两个月了，等你那个用户权限系统  都登录三四个月了

**Comment by KFCFans** [comment]
权限系统一直没有时间保证哦～
强烈需求的话可以自己考虑搞一搞，后面也可以 merge 进来。

近期应该会更新一次，把生命周期的功能发布掉。顺便清一清堆积起来的 issue。
