### ISSUE TITLE
数据库连接池hikaricp配置有误

### ISSUE THREAD

**Issue by 18846837414** [PowerJob/PowerJob#275]
配置文件原配置为：spring.datasource.core.hikari.maximum-pool-size=20，应为spring.datasource.core.maximumPoolSize=20，才能读取到配置生效。
![image](https://user-images.githubusercontent.com/50473836/117907911-32e75b80-b30a-11eb-9c18-0b408a12f0d7.png)
![image](https://user-images.githubusercontent.com/50473836/117907967-4a264900-b30a-11eb-8093-4db7a56ecaa4.png)

**Comment by KFCFans** [comment]
hikari 是你自己加上去的吧。。。。。。
