### ISSUE TITLE
能否增加任务暂停的功能！

### ISSUE THREAD

**Issue by d8txc** [PowerJob/PowerJob#278]
能否增加任务暂停的功能，有需求是这项任务故障或者业务出现变更临时需要将任务暂停一段时间，当前版本只能先删除掉，后期再添加，请大佬考虑考虑“暂停”的功能按钮

**Comment by Echo009** [comment]
是需要暂停某个定时任务，还是说暂停工作流中的某个任务节点 ？

如果是想要暂停定时任务的话，可以将对应的状态关闭

![image](https://user-images.githubusercontent.com/24402043/118064863-73101200-b3ce-11eb-82af-e0758d5a96e2.png)

如果是需要暂停工作流中的某个节点，可以将该节点禁用
