### ISSUE TITLE
工作流的流程示例没有删除按钮

### ISSUE THREAD

**Issue by dgq666** [PowerJob/PowerJob#282]
powerjob (v4.0.0) 

配置工作流时，批量导入多个任务，发现有的任务不是我想要的，想要删除。但是没有删除按钮。（delete按钮没用）

![image](https://user-images.githubusercontent.com/48819277/118218227-a1aeeb00-b4a9-11eb-8030-68f535b1477d.png)

**Comment by Echo009** [comment]
windows 用户请使用退格键 （Backspace）删除

mac os 使用 delete 键删除

**Comment by KFCFans** [comment]
> windows 用户请使用退格键 （Backspace）删除
> 
> mac os 使用 delete 键删除

同步到文档里面吧，前端也可以找机会小优化下。弄个 ？ tips 提示下之类的。

**Comment by Echo009** [comment]
> > windows 用户请使用退格键 （Backspace）删除
> > mac os 使用 delete 键删除
> 
> 同步到文档里面吧，前端也可以找机会小优化下。弄个 ？ tips 提示下之类的。

文档已更新 ，前端等下次更新再优化 ~
