### ISSUE TITLE
官方Http处理器调用远程接口超时，但又想获取远程接口的返回结果，有什么推荐的方式吗？

### ISSUE THREAD

**Issue by xuanyuan898701** [PowerJob/PowerJob#284]
现在想的是在远程接口业务逻辑执行完毕后回调server的接口去更新instance表相关的字段，比如状态和结果，不知道这样有何问题？或者可有更好的方式？

**Comment by wat1r** [comment]
目前是通过akka的方式上报状态的吧  `WorkerRequestHandler`

**Comment by KFCFans** [comment]
可以自己写一个 processor，自己构造结果就好了。

**Comment by xuanyuan898701** [comment]
> 可以自己写一个 processor，自己构造结果就好了。

额，不是很明白，可否稍加解释？目前我的逻辑是由worker调用其他应用的url，假如超时时间内的话worker可以拿到返回结果并上报server，假如超时以后worker就拿不到url返回结果了。我的思路是由worker调起远程url接口以后就上报server已调起的信息，worker就不管了。远程接口执行业务逻辑完毕后，主动调用server的接口（我自己在server里面暴露了一个类似updateInstanceById的接口）去更新实例状态和结果，不知道由远程接口代替worker上报的方式去修改实例状态这种做法，有没有什么问题？

**Comment by wat1r** [comment]
![image](https://user-images.githubusercontent.com/20732599/119309252-a4c38b80-bca0-11eb-9bc4-bfb2fc473d70.png)
---

**Comment by wat1r** [comment]
我听这个意思，大概画了了图

**Comment by wat1r** [comment]
> > 可以自己写一个 processor，自己构造结果就好了。
> 
> 额，不是很明白，可否稍加解释？目前我的逻辑是由worker调用其他应用的url，假如超时时间内的话worker可以拿到返回结果并上报server，假如超时以后worker就拿不到url返回结果了。我的思路是由worker调起远程url接口以后就上报server已调起的信息，worker就不管了。远程接口执行业务逻辑完毕后，主动调用server的接口（我自己在server里面暴露了一个类似updateInstanceById的接口）去更新实例状态和结果，不知道由远程接口代替worker上报的方式去修改实例状态这种做法，有没有什么问题？

---
