### ISSUE TITLE
MapReduce创建多个子任务运行非常慢

### ISSUE THREAD

**Issue by aokinba** [PowerJob/PowerJob#288]
**Describe the bug**
MapReduce创建多个子任务运行非常慢

**To Reproduce**
测试步骤
1. 在根任务创建9999个子任务，map参数=[0,1,2,3,4,5,6.......]
2. 子任务没有任何代码

**Expected behavior**
期待1秒内所有子任务运行完，实际预计1小时都运行不完

**Environment**
 - PowerJob Version: [e.g. 3.0.0]
 - Java Version: [e.g. OpenJDK 8]
 - OS: [e.g. CentOS 8.1]

**Screenshots**
代码截图：非常简单的代码
![image](https://user-images.githubusercontent.com/6531769/120570348-800ea700-c44a-11eb-99b0-fdc5f000c2a5.png)
日志截图：每次打印10个子任务
![image](https://user-images.githubusercontent.com/6531769/120570627-222e8f00-c44b-11eb-906a-10b8ab8283b0.png)

**Additional context**
问题原因应该是worker的线程线最多运行10个子任务

**Comment by KFCFans** [comment]
可以自行调大`单机线程并发度`

**Comment by aokinba** [comment]
> 可以自行调大`单机线程并发度`

可以我试用了阿里的SchedulerX，人家也是单机默认5个线程，几秒就运行完300个任务了。PowerJob能否也优化一下？

**Comment by KFCFans** [comment]
原理不一样，这种空任务测试没什么意义。

**Comment by junyan-zg** [comment]
(Powerjob4版本)同样遇到这个问题，如题，创建9000个MapReduce子任务（有现实场景），单机并发度为500甚至调到1000，期望在一分钟内完成。测试结果中，前面4000多个子任务执行很快完成，但后续的子任务完成速度特别慢，而且子任务有出错的情况，敬请修复。 @KFCFans
