### ISSUE TITLE
worker和server通信失败

### ISSUE THREAD

**Issue by zjinc36** [PowerJob/PowerJob#289]
**Describe the bug**
worker和server通信失败

**To Reproduce**
1. 这个bug要运行很长一段时间才会出现
2. worker正常
2. server的web ui中,没有显示机器地址,server发送定时任务失败
3. 同一台服务器启动多个worker(通信端口不一样),也会出现部分worker被踢的现象,而关闭其中一个worker,另一个"被踢"的worker又能显示且正常连接

**Environment**
 - PowerJob Version: [3.2.3]
 - Java Version: [1.8.0_221]
 - OS: [CentOS 7]

**Comment by KFCFans** [comment]
需要找些日志，仅凭描述很难判断问题

**Comment by zjinc36** [comment]
现象和这个问题比较一致"[服务端和worker端均启动成功，但在server端的机器地址中始终看不到任务worker，提示no worker available](https://github.com/PowerJob/PowerJob/issues/257)"

一台服务器内部署一个server和多个worker(这些worker属于不同的应用),而这多个worker一开始能连上,过一段时间就显示"no worker available",而worker本身没有问题

我需要找哪部分的日志有助于定位到问题?
