### ISSUE TITLE
实现任务延迟固定时间后重试，在server实现还是worker实现比较合适？要适用于工作流的某个任务，任务重试时整个工作流等待重试完成后再继续，是否能实现？

### ISSUE THREAD

**Issue by yugaoqian** [PowerJob/PowerJob#290]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KFCFans** [comment]
建议 server 端实现。
类似需求正在规划中。
