### ISSUE TITLE
支持仅执行一次吗

### ISSUE THREAD

**Issue by mouhui** [PowerJob/PowerJob#292]
有些任务场景是在某个时刻执行一次，例如：2021-06-15 10:30 执行一次后任务即为结束，不再执行
目前查看文档及demo未发现包含此功能，请问PowerJob支持该功能吗

这种仅执行一次后的场景还挺多的，例如用户下单后30分钟后未支付，取消订单...

**Comment by rxxy** [comment]
这种场景定时信息设置api就可以，不自动执行，执行是手动调用openapi，传递不同的参数延时执行

**Comment by KFCFans** [comment]
@rxxy 说的很对。我这边稍微补充一下：
1. 如果你在控制台创建任务的时候就知道运行时间，那么直接用 CRON 就能实现你的需求（CRON 支持精确时间调度）
2. 其他情况可以考虑用 OpenAPI 触发。
