### ISSUE TITLE
任务数据迁移

### ISSUE THREAD

**Issue by rxxy** [PowerJob/PowerJob#295]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details. 

如果在测试环境添加了一些任务，在发布到生产环境的时候如果想直接迁移powerjob数据库可行吗，如果可以的话需要迁移哪几张表?

ps:任务多的时候比一个个在生产环境再添加一遍方便好多了

**Comment by KFCFans** [comment]
嗯，后续会考虑任务的迁移方案。DB表数据直接拷贝的方案也是可以的。

**Comment by Macrow** [comment]
开发环境和生产环境很多配置不一致，迁移时，只拷贝app_info、job_info、workflow_info、workflow_node_info一共4张表的数据，会不会有问题？
