### ISSUE TITLE
docker部署powerjob无法访问

### ISSUE THREAD

**Issue by hzitao** [PowerJob/PowerJob#296]
## Question

在阿里云服务器上面部署好docker和mysql环境之后，按照使用手册部署容器，容器拒绝请求，阿里云端口已打开，进入容器查看log，报下面的错

- 
![image](https://user-images.githubusercontent.com/44660862/122854543-7344eb00-d346-11eb-8a56-0ffc01f9e5ca.png)

- 
![image](https://user-images.githubusercontent.com/44660862/122854629-953e6d80-d346-11eb-8967-29b906eeed84.png)

-
![image](https://user-images.githubusercontent.com/44660862/122854630-953e6d80-d346-11eb-80e1-5fe9e5087f62.png)

-
![image](https://user-images.githubusercontent.com/44660862/122854690-a9826a80-d346-11eb-909e-0b603a8d332f.png)

mysql密码是正确的，我使用Navicat可远程连接上，也可本机进入mysql容器

**Comment by hzitao** [comment]
3.4.8jar包可部署成功，但是4.x和3.4.xdocker均部署失败

**Comment by dudiao** [comment]
从日志上看，应该是MySQL没有启动

**Comment by KFCFans** [comment]
MySQL 启动问题，和 docker 网关相关
