### ISSUE TITLE
关于工作流与任务引用的疑问

### ISSUE THREAD

**Issue by BOFA1ex** [PowerJob/PowerJob#298]
> 场景: 多个工作流都选择导入了任务A, 需要更新任务A脚本内容.

> 问题: 工作流dags存储的是否仅有向无环图结构数据?

引申问题: 
1. 引用该任务A的工作流是否能感知(即工作流和任务双向的邻接关系, 任务A可以获取到相关的工作流, 工作流可以获取相关的任务)?
2. 引用该任务A的部分工作流, 若想保留任务A的旧副本, 对于UI交互, 是否需要在更新任务A时提示该任务与相关工作流之间的引用(血缘)关系?
这样的话，可以预先复制任务A作旧副本, 更新指向任务A旧副本的工作流.

**Comment by hadesy** [comment]
workflow仅存储dag数据，不会拷贝一份Job的数据
生产实践应该限制一个job只能被一个workflow引用

**Comment by BOFA1ex** [comment]
> workflow仅存储dag数据，不会拷贝一份Job的数据
> 生产实践应该限制一个job只能被一个workflow引用

我理解的是
分为三个角色task,workflow,job
定义workflow批量导入task, 这里dag存储的是task间的上下游关系数据.
workflow在生成job实例时, 根据dag对相关的task生成job实例并建立关于job间的dag关系.

回归上述问题的描述场景
> workflowA, workflowB, workflowC都选择导入了taskA
> 仅workflowA 需要更新taskA脚本内容, 在不知情workflowB, workflowC 也引用taskA的情况下, 直接修改taskA, 交互是否存在问题?

以上纯粹个人理解, 如有误解, 望指出多谢.

**Comment by hadesy** [comment]
workflow在执行instance时会去查询job具体定义，自身只保留一个jobId
https://github.com/PowerJob/PowerJob/blob/e094c22952c5b1e5d3dca11d1857629c3207478e/powerjob-server/powerjob-server-core/src/main/java/tech/powerjob/server/core/workflow/WorkflowInstanceManager.java#L137
前端部分作者实现的比较简单，很多地方没有校验，例如workflow_node还可以保存workflow_id为null的数据，但都不算大问题，你可以实现拷贝复制的机制或者加提示或者直接限制一个job只能被一个workflow引用等等...
