### ISSUE TITLE
/用户/powerjob/项目/script大量临时文件

### ISSUE THREAD

**Issue by jackylvm** [PowerJob/PowerJob#299]
## Question

在'/用户/powerjob/项目/script'文件夹下面有大量的临时文件

需要定期清理吗
powerjob有自己的清理机制吗?

**Comment by dudiao** [comment]
在'/用户/powerjob/worker/official_script_processor/'目录下会有缓存的脚本，当多次一个任务实例多次执行时，只会生成一次脚本文件。

现在powerjob还没有清理机制，是不是考虑可以设置清理N天之前的脚本？

**Comment by KFCFans** [comment]
https://www.yuque.com/powerjob/guidence/official_processor#sYUmZ
可以通过 PowerJob 自举实现
