### ISSUE TITLE
客户端启动连接到server端成功了，但服务端控制台看不到连接的客户端

### ISSUE THREAD

**Issue by bigStuart** [PowerJob/PowerJob#302]
以下情况，客户端和server端均在同一台电脑上。
1.server端启动成功：
![1](https://user-images.githubusercontent.com/14803721/125711928-6dc46a81-b2cf-44c8-8129-42eb169e5a74.png)
2.客户端也成功连接上服务器：
![2](https://user-images.githubusercontent.com/14803721/125711973-158ae785-b98d-4c99-bcf0-4afb070683cd.png)
3.但在server端控制面板首页中却看不到连接上来的客户端：
![3](https://user-images.githubusercontent.com/14803721/125712059-5455b612-fc9e-4782-859f-f085ea53ed1a.png)
4.客户端可以通过调用openApi添加任务到server端中：
![4](https://user-images.githubusercontent.com/14803721/125712103-40d899fa-1c0d-48e5-94ba-a20213a7f9c6.png)
5.但在server端控制面板中运行任务结果确提示失败：
![5](https://user-images.githubusercontent.com/14803721/125712152-c3fda0b6-4d97-460f-b5ca-efb5765f407a.png)

**Comment by bigStuart** [comment]
server:4.0.1
![6](https://user-images.githubusercontent.com/14803721/125712953-844383e4-d516-4d0d-ad63-9a8015ad757f.png)


client:4.0.1
![7](https://user-images.githubusercontent.com/14803721/125712965-5e07224a-8a0f-4a13-a15f-ef602cb5c389.png)

**Comment by bigStuart** [comment]
http://127.0.0.1:7700/server/hello?debug=true返回的结果：
![8](https://user-images.githubusercontent.com/14803721/125713817-f832e69e-d86f-4814-a84d-c710502b55d8.png)

**Comment by bigStuart** [comment]
已经解决，

**Comment by 8WangSir** [comment]
hello 咋解决的呀？

**Comment by caption-dylan** [comment]
@8WangSir 这个有点久了，忘记当时是怎样解决的了
