### ISSUE TITLE
想问下代码调用openapi添加任务的demo例子那里？

### ISSUE THREAD

**Issue by bigStuart** [PowerJob/PowerJob#303]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details. 

我已经下载了源代码了，启动了powerjob-server端，但不知道如何用调用openapi添加任务？下图中的项目列表中有那个项目是有写到openapi添加任务的例子的吗？
![8](https://user-images.githubusercontent.com/14803721/125942967-6e2094c7-957f-4708-aa8e-3958ff71a56e.png)

**Comment by dudiao** [comment]
`powerjob-client`模块是OpenAPI Java版本的SDK，相关的使用说明如下：

https://www.yuque.com/powerjob/guidence/olgyf0
