### ISSUE TITLE
FIXED_RATE+MapReduce任务不会执行

### ISSUE THREAD

**Issue by Linyuzai** [PowerJob/PowerJob#304]
发现只有MapReduce+FIXED_RATE有问题，MapReduce+CRON没有该问题（只用了MapReduce）

把worker的业务服务关闭（没有worker可用），一段时间后重新起业务服务，发现任务不会再执行，一直显示running状态

把任务stop再retry，又正常了，重复上面的操作（关闭业务服务过一段时间再起来），又不会继续执行

猜测会不会是FIXED_RATE任务持有的worker实例没有更新成新的worker实例，导致一直没有worker可调用（我看CRON和FIXED_RATE的任务展示方式不太一样，MapReduce+FIXED_RATE只有一个任务实例）

**Comment by Linyuzai** [comment]
1. 后台报错
![be083549649d286750939f9404a8b38](https://user-images.githubusercontent.com/18523183/126746584-86fc5dd0-97ba-4c1f-954d-8f86d517902b.png)
2. 查询到的后台的任务
![4aaefeed193feacf4c696335dc0a492](https://user-images.githubusercontent.com/18523183/126746596-31b3133e-7954-4f6d-bf6f-b59a140712de.png)
3. 根据jobId查到的任务
![bf0da49b7527e6bade07189012b2e0f](https://user-images.githubusercontent.com/18523183/126746600-62681738-f0af-4c8d-9b9b-d2be1b6a5431.png)
4. 后台报错的任务页面查询不到
![7810763bee15a814ab71923757f30d5](https://user-images.githubusercontent.com/18523183/126746613-62595133-163e-479d-8060-1d38f3dd7a2a.png)
![2b5c5be965f46315dc6c0169bf2f52c](https://user-images.githubusercontent.com/18523183/126746622-896ca767-5ac8-4542-a892-0ec601952144.png)

看了下数据库，很神奇数据有点对不上，所以我现在不太确定是不是我这边数据库的问题。。。

**Comment by KFCFans** [comment]
嗯，功能本身是正常的
