### ISSUE TITLE
worker节点有多个网卡时，如何制定woker注册时的ip

### ISSUE THREAD

**Issue by liu-chao-simon** [PowerJob/PowerJob#306]
## Question

1. worker节点有多个网卡时，如何制定woker注册时的ip
2. server的这两个端口如果不采用默认值，woker的配置文件里怎么调整配置
    oms.akka.port=10086
    oms.http.port=10010

**Comment by dudiao** [comment]
## worker节点有多个网卡时，如何制定woker注册时的ip
有两种方式：
1. 通过 JVM 启动参数 `-Dpowerjob.network.local.address` 来直接绑定某个IP；
2. 添加 JVM 启动参数-Dpowerjob.network.interface.preferred=xxx 来指定绑定的网卡（该参数需要填入需要绑定的网卡名称），或通过 -Dpowerjob.network.interface.ignored=xxx 来忽略错误的网卡（该参数支持正则表达式，匹配到的网卡会被忽略）。
> 参考地址：https://www.yuque.com/powerjob/guidence/problem#xMQC9

## server的这两个端口如果不采用默认值，woker的配置文件里怎么调整配置
woker的配置不需要调整，只需要指定server的http端口即可（powerjob.worker.server-address）
