### ISSUE TITLE
向工作流上下文中追加字符串时，value的值会增加双引号

### ISSUE THREAD

**Issue by dudiao** [PowerJob/PowerJob#307]
**Describe the bug**
向工作流上下文中追加数据（字符串）时，value的值会增加双引号，比如追加GitPullProcessor_LocalDirectory=D:\\aml\\aml-bank-sql2.0时，value值会变成"D:\\aml\\aml-bank-sql2.0"
```java
taskContext.getWorkflowContext().appendData2WfContext("GitPullProcessor_LocalDirectory", "D:\\aml\\aml-bank-sql2.0");
```

**Environment**
 - PowerJob Version: [4.0.1]
 - Java Version: [jdk1.8.0_291]
 - SpringBoot: [2.5.2]
 - OS: [Windows 10]

**Screenshots**
![1627403822](https://user-images.githubusercontent.com/38355949/127194334-423ec196-e50a-4b71-993a-0e9dd94b453f.jpg)

**Additional context**
这个类转成String的时候多加了个双引号：tech.powerjob.common.serialize.JsonUtils#toJSONStringUnsafe

**Comment by huarongsheng** [comment]
> **Describe the bug** 向工作流上下文中追加数据（字符串）时，value的值会增加双引号，比如追加GitPullProcessor_LocalDirectory=D:\aml\aml-bank-sql2.0时，value值会变成"D:\aml\aml-bank-sql2.0"
> 
> ```java
> taskContext.getWorkflowContext().appendData2WfContext("GitPullProcessor_LocalDirectory", "D:\\aml\\aml-bank-sql2.0");
> ```
> 
> **Environment**
> 
> * PowerJob Version: [4.0.1]
> * Java Version: [jdk1.8.0_291]
> * SpringBoot: [2.5.2]
> * OS: [Windows 10]
> 
> **Screenshots** ![1627403822](https://user-images.githubusercontent.com/38355949/127194334-423ec196-e50a-4b71-993a-0e9dd94b453f.jpg)
> 
> **Additional context** 这个类转成String的时候多加了个双引号：tech.powerjob.common.serialize.JsonUtils#toJSONStringUnsafe

**Comment by huarongsheng** [comment]
appendData2WfContext value为字符串时会多加一个双引号，已经修复close掉但是提交后代码又被覆盖掉了，bug仍然存在
![image](https://user-images.githubusercontent.com/42803819/225876041-49609d52-c6aa-46eb-ac3f-ff77e444f24b.png)
![image](https://user-images.githubusercontent.com/42803819/225876069-4df47896-457e-451b-8735-a136b56b811f.png)

**Comment by KFCFans** [comment]
> appendData2WfContext value为字符串时会多加一个双引号，已经修复close掉但是提交后代码又被覆盖掉了，bug仍然存在 ![image](https://user-images.githubusercontent.com/42803819/225876041-49609d52-c6aa-46eb-ac3f-ff77e444f24b.png) ![image](https://user-images.githubusercontent.com/42803819/225876069-4df47896-457e-451b-8735-a136b56b811f.png)

已确认，确实代码在合并过程中被回滚了。4.3.2 会修复，感谢反馈！
