### ISSUE TITLE
创建任务时，FixedRate字段值格式不对，仍能创建成功，但执行改任务会失败。

### ISSUE THREAD

**Issue by liu-chao-simon** [PowerJob/PowerJob#312]
**Describe the bug**
创建Job，选择fiexed rate(ms) ，输入时间格式为 6000a空格，并保存，保存成功，但执行会失败

**To Reproduce**
Steps to reproduce the behavior.
创建Job，选择fiexed rate(ms) ，输入时间格式为 6000a空格，并保存，保存成功
触发任务执行

job不能被执行成功
查看log提示：
java.lang.NumberFormatException: For input string: "6000a "
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_302]

**Expected behavior**
任务创建时就应该失败

**Environment**
 - PowerJob Version: 4.0.1

**Comment by KFCFans** [comment]
感谢反馈，已修复，即将发布
