### ISSUE TITLE
复制任务，更改Processor会导致任务执行不正确的processor

### ISSUE THREAD

**Issue by liu-chao-simon** [PowerJob/PowerJob#313]
**Describe the bug**
复制任务，在弹出的对话框中更改Processor会导致改任务执行不正确的processor

**To Reproduce**
Worker中有两个BasicProcessor: com.xxx.TestProcessor1, com.xxx.TestProcessor2
job1是一个fixed rate 5000ms的job，执行器为com.xxx.TestProcessor1，并处在正常running状态

Steps to reproduce the behavior.
1. 进入任务管理tab, 点击job1/更多/复制
2. 在弹出的窗口中，任务名改为job2，将执行器更改为com.xxx.TestProcessor2
3. 保存后，发现job2状态为running, 且观察worker发现：job2在执行com.xxx.TestProcessor1而不是com.xxx.TestProcessor2

**Expected behavior**
job2应执行com.xxx.TestProcessor2

**Environment**
 - PowerJob Version: 4.0.1

**Comment by KFCFans** [comment]
停止任务，然后重启就好了
