### ISSUE TITLE
docker部署worker和server无法启动 Failed to create parent directories

### ISSUE THREAD

**Issue by Garen-in-bush** [PowerJob/PowerJob#315]
以下为具体的报错信息

******************* PowerJob Tips *******************
如果应用无法启动，我们建议您仔细阅读以下文档来解决:
if server can't startup, we recommend that you read the documentation to find a solution:
https://www.yuque.com/powerjob/guidence/problem
******************* PowerJob Tips *******************
17:31:29.072 [main] INFO tech.powerjob.server.remote.transport.starter.AkkaStarter - [PowerJob] PowerJob's akka system start to bootstrap...
17:31:29.114 [main] INFO tech.powerjob.server.remote.transport.starter.AkkaStarter - [PowerJob] akka-remote server address: 172.18.0.2:10086
17:31:30.762 [oms-server-akka.actor.default-dispatcher-5] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
17:31:31.162 [oms-server-akka.actor.default-dispatcher-5] WARN akka.remote.RemoteActorRefProvider - Using the 'remote' ActorRefProvider directly, which is a low-level layer. For most use cases, the 'cluster' abstraction on top of remoting is more suitable instead.
17:31:31.163 [oms-server-akka.actor.default-dispatcher-5] WARN akka.remote.RemoteActorRefProvider - Akka Cluster not in use - Using Akka Cluster is recommended if you need remote watch and deploy.
17:31:31.959 [main] INFO tech.powerjob.server.remote.transport.starter.AkkaStarter - [PowerJob] PowerJob's akka system started successfully, using time 2.887 s.
17:31:31.965 [main] INFO tech.powerjob.server.remote.transport.starter.VertXStarter - [PowerJob] PowerJob's vert.x system start to bootstrap...
17:31:31.965 [main] INFO tech.powerjob.server.remote.transport.starter.VertXStarter - [PowerJob] vert.x server address: 172.18.0.2:10010
17:31:32.032 [main] DEBUG io.vertx.core.logging.LoggerFactory - Using io.vertx.core.logging.SLF4JLogDelegateFactory
17:31:32.101 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
17:31:32.103 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
17:31:32.103 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
17:31:32.245 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
17:31:32.246 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
17:31:32.250 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
17:31:32.253 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
17:31:32.255 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
17:31:32.257 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
17:31:32.259 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
17:31:32.260 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
17:31:32.260 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
17:31:32.260 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
17:31:32.261 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
17:31:32.261 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
17:31:32.266 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 7460618240 bytes
17:31:32.266 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
17:31:32.270 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
17:31:32.270 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
17:31:32.341 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 16
17:31:32.393 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
17:31:32.394 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
17:31:32.410 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
17:31:32.411 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
17:31:32.440 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
17:31:32.479 [main] DEBUG io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider - Default DNS servers: [/114.114.114.114:53] (sun.net.dns.ResolverConfiguration)
17:31:32.487 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
17:31:32.487 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
17:31:32.488 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%lo)
17:31:32.489 [main] DEBUG io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 128
17:31:32.527 [main] INFO tech.powerjob.server.remote.transport.starter.VertXStarter - [PowerJob] PowerJob's vert.x system started successfully, using time 561.7 ms.
Logging system failed to initialize using configuration from 'classpath:logback-product.xml'
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[ERROR_APPENDER] - Failed to create parent directories for [/root/powerjob/server/logs/powerjob-server-error.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[ERROR_APPENDER] - openFile(/root/powerjob/server/logs/powerjob-server-error.log,true) call failed. java.io.FileNotFoundException: /root/powerjob/server/logs/powerjob-server-error.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[WEB_LOG_APPENDER] - Failed to create parent directories for [/root/powerjob/server/logs/powerjob-server-web.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[WEB_LOG_APPENDER] - openFile(/root/powerjob/server/logs/powerjob-server-web.log,true) call failed. java.io.FileNotFoundException: /root/powerjob/server/logs/powerjob-server-web.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[DEFAULT_APPENDER] - Failed to create parent directories for [/root/powerjob/server/logs/powerjob-server-application.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[DEFAULT_APPENDER] - openFile(/root/powerjob/server/logs/powerjob-server-application.log,true) call failed. java.io.FileNotFoundException: /root/powerjob/server/logs/powerjob-server-application.log (No such file or directory)

**Comment by AmazingYHT** [comment]
老鸽，你解决了嘛？权限不够还是镜像包有问题？我同样的布置脚本，又在测试环境部署cos 7部署就有问题。，

**Comment by KFCFans** [comment]
应该是 Docker 镜像问题，建议自查下
