### ISSUE TITLE
工作流一次性CRON BUG

### ISSUE THREAD

**Issue by fddc** [PowerJob/PowerJob#316]
1、设置一个工作流任务，为了容易重现，任务里简单sleep1分钟就好
2、设置工作流，CRON为指定年月日时分秒，例如：0 20 9 11 8 ? 2021
3、问题重现：工作流不断被触发

**Comment by Echo009** [comment]
提供下版本号，v4.0.1 版本的 server 在这个场景下是没问题的

> 0 45 9 11 8 ? 2021-2021 这个格式也可以重现

**Comment by Echo009** [comment]
感谢反馈，下个版本修复

**Comment by fddc** [comment]
谢谢采纳
