### ISSUE TITLE
可用通过maven 的方式构建container 也可以通过spring 构建启动container。springboot 方式构建的contianer demo有吗？

### ISSUE THREAD

**Issue by numbernumberone** [PowerJob/PowerJob#318]
可用通过maven 的方式构建container 也可以通过spring 构建启动container。springboot 方式构建的contianer demo有吗？
因为有特定的container 需要依赖springboot 的插件才能满足业务需求，所以想做一个springboot 的contianer。

类似这种效果   https://www.toptal.com/spring-boot/spring-boot-application-programmatic-launch

**Comment by KFCFans** [comment]
SpringBoot 解决的问题是部署，而不是打包。
所有 SpringBoot 能用的东西 Spring 肯定也能用，PowerJob 的 container 默认就是带 Spring 环境的，这就够了。
