### ISSUE TITLE
jobParams过大，会导致akka框架报错

### ISSUE THREAD

**Issue by hjbj1** [PowerJob/PowerJob#327]
job参数过大，点击执行的时候，导致报错
akka.remote.OversizedPayloadException:Discarding oversized payload sent to Some(Actor[]): max allowed size 262144 bytes.
网上找了一些方法，更改akka配置文件，好像没作用

**Comment by KFCFans** [comment]
太大的参数也影响性能，如果参数实在大的话建议前置处理下，用 redis 或者其他存储存一下，传递key
