### ISSUE TITLE
延时任务

### ISSUE THREAD

**Issue by zengbo1997** [PowerJob/PowerJob#329]
设置一个在指定时刻运行一次的 延时任务. 这种是不是只能用cron表达式,自己计算时间,把时间转换成cron表达式?

**Comment by zqiyu** [comment]
同问

**Comment by KFCFans** [comment]
1. 控制台创建的话，只能用 CRON
2. 通过 OpenAPI，自带了延迟调度的接口
`tech.powerjob.client.PowerJobClient#runJob(java.lang.Long, java.lang.String, long)`
