### ISSUE TITLE
求问：一个业务逻辑只需要几十毫秒就能完成，从intance表里面看到的实际触发时间和结束时间间隔了3秒多，是正常的吗？

### ISSUE THREAD

**Issue by xuanyuan898701** [PowerJob/PowerJob#330]
中间的时间开销只是因为worker和server之间的通讯开销吗？

**Comment by Echo009** [comment]
一般情况下任务触发到实际执行的时间间隔在几十 ms 左右，结束时间间隔比较大的原因是在默认配置下任务执行完成后并不会立即上报到 server 端，而是每隔 3 s 检查一次状态

tech.powerjob.worker.core.tracker.task#CommonTaskTracker   line 77 

![image](https://user-images.githubusercontent.com/24402043/133781924-21e9ff8b-219d-4b48-bd81-8a1cedb03eaf.png)

可以通过 JVM 启动参数 `powerjob.worker.status-check.normal.period` 调整这个间隔
