### ISSUE TITLE
官网怎么成这鸟样了？？？？？？？？？

### ISSUE THREAD

**Issue by cnscottluo** [PowerJob/PowerJob#331]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by KFCFans** [comment]
被CDN劫持了。。。
正在修复，sorry
