### ISSUE TITLE
worker中如何查询集群中所有worker数量？

### ISSUE THREAD

**Issue by zedweein** [PowerJob/PowerJob#333]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by KFCFans** [comment]
什么场景需要让 worker 知道自己的集群规模？
详细描述业务场景后可以重现打开 issue
