### ISSUE TITLE
这个项目已经放弃维护了吗？官网都302了

### ISSUE THREAD

**Issue by clulrc** [PowerJob/PowerJob#336]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
 - PowerJob Version: [e.g. 3.0.0]
 - Java Version: [e.g. OpenJDK 8]
 - OS: [e.g. CentOS 8.1]

**Screenshots**

**Additional context**

**Comment by KFCFans** [comment]
没有，这段时间略忙，正在 fix。
