### ISSUE TITLE
触发任务到任务执行用时10s，这么耗时正常么？

### ISSUE THREAD

**Issue by amazingJing** [PowerJob/PowerJob#338]
## Question

![image](https://user-images.githubusercontent.com/28639402/136496671-dc3d72ba-1a2f-44d4-b541-93726ac6fde7.png)
![image](https://user-images.githubusercontent.com/28639402/136496704-56e9c8a3-6f27-41d3-ab15-9f44bcb070a8.png)
手动触发执行一个没有什么逻辑的任务，从触发到执行结束的时间是10s，花销这么久么？
看着主要是OmsServerDiscovery用了很久的时间，这样科学么？

**Comment by KFCFans** [comment]
根据我的设计思路，离线的大规模任务大多对延迟不敏感，因此 PowerJob 是纯异步设计，任务即使执行结束，上报结果也会有 10S 左右的延迟。
当然，开发者也可以自行通过 JVM 参数 `powerjob.worker.status-check.normal.period` 调整

**Comment by KFCFans** [comment]
单位秒，传入 1 的话就是每秒检查一次状态，响应更快，但存在额外开销。
