### ISSUE TITLE
powerjob部署问题

### ISSUE THREAD

**Issue by guduzhimu** [PowerJob/PowerJob#346]
本地部署powerjob没有问题，到内网服务器部署powerjob，会出现这个错：java.net.URISyntaxException: Expected authority at index 6: dns://
![image](https://user-images.githubusercontent.com/93956919/140843462-aedb93cc-d9d5-46a5-bd69-91052ba24810.png)
网上找不到类似的例子或说明，请协助解答，是什么原因导致的，谢谢

**Comment by wjtwjt96** [comment]
> 本地部署powerjob没有问题，到内网服务器部署powerjob，会出现这个错：java.net.URISyntaxException: Expected authority at index 6: dns:// ![image](https://user-images.githubusercontent.com/93956919/140843462-aedb93cc-d9d5-46a5-bd69-91052ba24810.png) 网上找不到类似的例子或说明，请协助解答，是什么原因导致的，谢谢

我也遇到类似问题，没有解决方案

**Comment by KFCFans** [comment]
可以自己改代码屏蔽下这部分，目前其实没用到这个功能
我后面也优化下，配置开启 vertx

**Comment by KFCFans** [comment]
只是报错不影响启动的话可以忽略
