### ISSUE TITLE
springcloud引入powerJob前端请求地址如何变更？

### ISSUE THREAD

**Issue by jzp61** [PowerJob/PowerJob#350]
因为cloud有网关地址，但是powerjob-server里前端地址请求时都不会携带网关名称，导致所有api请求都是404，如何统一更改？
![image](https://user-images.githubusercontent.com/95205603/143817732-9dfba7ab-c9c9-4f66-b2eb-6326c9415953.png)

**Comment by Echo009** [comment]
https://github.com/PowerJob/PowerJob-Console

需要修改文件 https://github.com/PowerJob/PowerJob-Console/blob/e8c1b3ee566ede88c03e7774fbf8948f5906e59b/.env.spring

`VUE_APP_BASE_URL = "/"`  改为 `VUE_APP_BASE_URL = "./" `

修改后再重新打包，用 dist 目录下的文件替换掉 [PowerJob Server 的静态资源目录]( https://github.com/PowerJob/PowerJob/tree/master/powerjob-server/powerjob-server-starter/src/main/resources/static) 下的文件
