### ISSUE TITLE
现在4.0.1秒级任务失败可以报警了吗

### ISSUE THREAD

**Issue by lm970123** [PowerJob/PowerJob#352]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by lm970123** [comment]
![image](https://user-images.githubusercontent.com/95345063/144209655-8685aa32-3db8-45e4-baa8-1c954063223c.png)
这种子任务失败的，可以报警吗

**Comment by Echo009** [comment]
暂时还不行，下个版本加上

**Comment by Echo009** [comment]
https://github.com/PowerJob/PowerJob/issues/370
