### ISSUE TITLE
powerjob如何过滤http不安全请求例如TRACE请求

### ISSUE THREAD

**Issue by iamzzq** [PowerJob/PowerJob#357]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by KFCFans** [comment]
server 吗？目前 web 端的安全性可以自己定制，PowerJob 暂时不提供这方面的支持。主要还是专注于调度本身。
