### ISSUE TITLE
大量任务，IOT业务场景使用咨询

### ISSUE THREAD

**Issue by zouxiaodong** [PowerJob/PowerJob#359]
IOT平台实现定时高度，设备可以配置一些定时执行的命令，第个定时执行命令生产一个任务，比如一个灯设备，9：00开灯，12点熄灯就是2个任务，一个开一个关,如果任务数太多（10W+）不知道这种使用方式有没有问题？或有没有更好的方案？

**Comment by zouxiaodong** [comment]
我将进行测试

**Comment by cwr31** [comment]
测试效果如何，方便share一下么？

**Comment by xywhnh** [comment]
同问，测试结果如何呢？

**Comment by liucq200518** [comment]
![Image](https://github.com/user-attachments/assets/39cbbdf2-f45c-4c4f-a7ae-0a4b3d2bebe9)

![Image](https://github.com/user-attachments/assets/ad1511f7-ffc5-4643-8998-5bb79e769003)

[powerjob-server-error.log](https://github.com/user-attachments/files/21055703/powerjob-server-error.log)
2.5w个任务并发，放开了跑的还是会oom，但是内存、cpu都没占满，挺奇怪的
