### ISSUE TITLE
powerjob-server负载问题

### ISSUE THREAD

**Issue by gaojiayi** [PowerJob/PowerJob#360]
现在是一个app对应一个powerjob-server，假设app1下面的任务在server1上调度，app2下面的任务在service2上调度，加入app1下面有很多的任务，上万个。 而app2下的任务就一两个。  会不会造成server1负载过高。任务分配不均的问题？

**Comment by csongs** [comment]
就我自己看代碼,設計上來說的確如您所說的

不能把一個app分給兩個server來分擔

**Comment by KFCFans** [comment]
目前确实有这个问题，不过这是 PowerJob 的基础设计理念，用单机分布式集群来解决问题

**Comment by wb1064330015** [comment]
这个是不是可以通过连接前做个连接排序来解决负载呢
