### ISSUE TITLE
请问powerjob如何集成Python

### ISSUE THREAD

**Issue by jzp61** [PowerJob/PowerJob#363]
现在java已经接入使用powerjob，且官方文档有提供案例，openapi方式调用，并有相关依赖包，但是暂未找到Python相关集成方式，烦请指导，谢谢~

**Comment by csongs** [comment]
你的worker要有執行python環境

如果部署是用Dockerfile 
可以參考: https://github.com/PowerJob/PowerJob/blob/master/powerjob-worker-agent/Dockerfile

使用方式可以參考:
https://www.yuque.com/powerjob/en/zpp27q

**Comment by jzp61** [comment]
使用方式我看了是直接可视化界面手动加，那我如何像java一样调用sdk动态通过接口新增数据这种方式呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PowerJob/PowerJob"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月7日(星期五) 中午1:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PowerJob/PowerJob] 请问powerjob如何集成Python (Issue #363)





 
你的worker要有執行python環境
 
如果部署是用Dockerfile
 可以參考: https://github.com/PowerJob/PowerJob/blob/master/powerjob-worker-agent/Dockerfile
 
使用方式可以參考:
 https://www.yuque.com/powerjob/en/zpp27q
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Echo009** [comment]
https://github.com/PowerJob/powerjob-python
