### ISSUE TITLE
powerjob新建任务失败

### ISSUE THREAD

**Issue by l1douhua** [PowerJob/PowerJob#364]
## Question

在新建任务时-选择处理器类型（java）-com.xxxxx.job.StudentOfferSyncProcessor报错，以下是报错内容
1.百度说是cron时间格式问题，后来尝试无果
-------------------------------------------------------------------------
ERROR：HttpMessageNotReadableException: JSON parse error: Cannot deserialize value of type `tech.powerjob.common.enums.ProcessorType` from String "EMBEDDED_JAVA": 
not one of the values accepted for Enum class: [SHELL, EXTERNAL, PYTHON, BUILT_IN]; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: 
Cannot deserialize value of type `tech.powerjob.common.enums.ProcessorType` from String "EMBEDDED_JAVA": not one of the values accepted for Enum class: [SHELL, EXTERNAL, PYTHON, BUILT_IN] 
at [Source: (PushbackInputStream); line: 1, column: 96] (through reference chain: tech.powerjob.common.request.http.SaveJobInfoRequest["processorType"])

**Comment by l1douhua** [comment]
其中用console结合nginx做域名转发

**Comment by Echo009** [comment]
前端的版本和后端版本不一致，前端传的枚举值是上个版本的。
建议拉一下前端最新的代码，重新构建部署
