### ISSUE TITLE
固定频率任务,运行中任务实例概率性出现多个,导致重复执行任务

### ISSUE THREAD

**Issue by xiaozhi88** [PowerJob/PowerJob#375]
创建定时任务且只有一台机器机器的情况下,任务执行一段时间会出现两个运行中实例,导致任务执行重复;
![image](https://user-images.githubusercontent.com/39517299/151318886-0d1f0df2-6926-49d7-9e4a-a906605af978.png)
![image](https://user-images.githubusercontent.com/39517299/151318937-3189be16-6c32-47db-9ca9-22f35e8ae846.png)
![image](https://user-images.githubusercontent.com/39517299/151318990-96e8e321-f454-475f-bbd0-eb2e6c071480.png)

**Comment by Echo009** [comment]
感谢反馈，当前确实存在这个问题 

server 端检测任务状态上报的超时时间为 60，对于固定频率的任务，用的是不可靠的上报处理逻辑，并且没有对上报失败的次数做限制，如果发生了超过 60 秒的网络分区，则有可能会导致该任务重复执行 

将于下个版本修复
