### ISSUE TITLE
OpenApi查询任务接口增加条件参数 或者 可以自定义任务ID

### ISSUE THREAD

**Issue by 13330863440** [PowerJob/PowerJob#380]
### 问题
在我的项目中我希望通过OpenApi 完成自动创建任务（任务很多，在页面上一个个配置太麻烦了）。
但是现在遇到了一个问题，我能知道powerJob中是否配置了该任务，若直接提交，将会创建2个相同的任务
现在的解决方式是本地再添加一张数据表，用来关联powerJob的任务ID 和我自己的任务ID进行一个关联。
```sql
CREATE TABLE `powerJob_id` (
  `id` varchar(32) NOT NULL COMMENT '本地ID',
  `powerJobId` bigint(20) NOT NULL COMMENT 'powerJob 对应的任务ID',
  PRIMARY KEY (`id`)
)
```

本地ID是在 开发执行器时 定义在代码中的（全局唯一的）。
这样会有一个问题，我不能完全保证本地记录的任务和实际powerJob中的任务完全相同

### 希望：
- 增加一个查询方法 通过我自己的指定条件，查询powerJob中是否有该任务
- 或者 在通过OpenApi添加任务时，可以指定一个自己的任务ID（这样更好）

**Comment by Echo009** [comment]
目前 OpenAPI 里是有提供 Job 查询接口的 

https://github.com/PowerJob/PowerJob/blob/e094c22952c5b1e5d3dca11d1857629c3207478e/powerjob-client/src/main/java/tech/powerjob/client/PowerJobClient.java#L176
