### ISSUE TITLE
为什么我用standalone示例任务创建了一个cron为*/1 * * * * ? 的定时任务，但是实际是15秒才执行一次，表达式是正确的1秒一次才正常

### ISSUE THREAD

**Issue by huangyuzhong** [PowerJob/PowerJob#388]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
 - PowerJob Version: [e.g. 3.0.0]
 - Java Version: [e.g. OpenJDK 8]
 - OS: [e.g. CentOS 8.1]

**Screenshots**

**Additional context**

**Comment by daliandazi** [comment]
时间轮是15秒扫描一次，这个文档上应该有说明 ，时间间隔不能小于15秒

**Comment by Echo009** [comment]
楼上正解，另外这种间隔很短的任务，请使用固定频率或者固定延迟类型的任务，不要用 cron
