### ISSUE TITLE
MapReduceProcessor似乎不能立即停止

### ISSUE THREAD

**Issue by sunyl-git** [PowerJob/PowerJob#389]
**Describe the bug**
MapReduceProcessor似乎不能立即停止，手动点击停止后，map子任务还在执行。
例如1000条数据，分10批次执行，每批100条。停止后最后一批还会执行。

**Expected behavior**
手动停止时立即停止，包括子任务，线程等。

**Environment**
3.4.8
JDK 8

**Screenshots**
观察两个时间。停止后还能输出日志。说明没有真正的停止。
![image](https://user-images.githubusercontent.com/16182082/159620505-2bd4b080-91e1-4b67-8208-3983b3bb6334.png)

**Additional context**

**To Reproduce**
```

public class TestMapReduceProcessor extends MapReduceProcessor {

    @Override
    public ProcessResult process(TaskContext context) throws Exception {

        OmsLogger omsLogger = context.getOmsLogger();

        omsLogger.info("TestMapReduceProcessor process,context is {}.", context);




        if (isRootTask()) {
            
            List<String> allAppNos = DB.listAllNeedUpdateAppNo();
            int size = allAppNos.size();
            omsLogger.info(size + "条数据需要更新。");
       

            int pageSize = 100;
            long totalPage = getPages(size, pageSize);

            for (long pageNum = 1; pageNum <= totalPage; pageNum++) {

                List<String> subList = allAppNos.stream()
                        .skip(pageSize * (pageNum - 1))
                        .limit(pageSize).collect(Collectors.toList());
                omsLogger.info("正在分发第{}-子任务。。", pageNum);

                try {
                    var subTasks = new ArrayList<SubTask>();
                    subTasks.add(new SubTask(pageNum, subList));
                    map(subTasks, "DATA_PROCESS_TASK" + pageNum);
                } catch (Exception e) {
                    log.error("error", e);
                    omsLogger.info("分发第{}-子任务出错：", pageNum);
                    omsLogger.error("error when map subtask-{}", e.getMessage());
                }
            }

            return new ProcessResult(true, "ROOT_PROCESS_SUCCESS");
        } else {

            SubTask subTask = (SubTask) context.getSubTask();

            omsLogger.info("第{}-size:{}子任务处理中。。noBlocking:{}", subTask.siteId, subTask.getAppNos().size(),noBlocking);
            for (String appNo : subTask.getAppNos()) {
                //todo:手动停止后 这里还能输出。
                this.blockingCall(appNo);
            }
            omsLogger.info("第{}-size:{}子任务处理完成！", subTask.siteId, subTask.getAppNos().size());
            return new ProcessResult(true, "subTask process successfully with" + subTask.getSiteId());
        }
    }

    private void blockingCall(String appNo) {
        try {
            Response response = httpClient.patentFee(appNo);
            //todo:手动停止后 这里还能输出。
            log.info("blockPatentFee-status->{},appNo:{}",response.status(), appNo);
        } catch (Exception e) {
            log.error("调用python接口失败" + appNo, e);
        }
    }

    long getPages(long total, long pageSize) {
        if (pageSize == 0) {
            return 0;
        }
        long pages = total / pageSize;
        if (total % pageSize != 0) {
            pages++;
        }
        return pages;
    }

    @Getter
    @NoArgsConstructor
    @AllArgsConstructor
    private static class SubTask {
        private Long siteId;
        private List<String> appNos;

    }

    /**
     * 所有 Task 执行结束后，reduce 将会被执行
     * taskResults 保存了所有子任务的执行结果
     */
    @Override
    public ProcessResult reduce(TaskContext taskContext, List<TaskResult> taskResults) {
//....
}
```

**Comment by sunyl-git** [comment]
或者说开发人员可以拿到一个状态来确定用户是否手动点击了停止。
然后在代码中自行break中断剩余的任务。

if(isStop()){
break;
}

**Comment by Echo009** [comment]
> 或者说开发人员可以拿到一个状态来确定用户是否手动点击了停止。 然后在代码中自行break中断剩余的任务。
> 
> if(isStop()){ break; }

停止后相应的线程都会被 interrupt ，所以只需要在对应的任务代码中处理 interrupt 信号就行

![image](https://user-images.githubusercontent.com/24402043/160608471-ac42585c-539e-45ef-ab67-ac7b935063fd.png)

这里加个判断 

> if (Thread.interrupted()){ // todo stop }

**Comment by Echo009** [comment]
> > > 或者说开发人员可以拿到一个状态来确定用户是否手动点击了停止。 然后在代码中自行break中断剩余的任务。
> > > if(isStop()){ break; }
> > 
> > 
> > 停止后相应的线程都会被 interrupt ，所以只需要在对应的任务代码中处理 interrupt 信号就行
> > ![image](https://user-images.githubusercontent.com/24402043/160608471-ac42585c-539e-45ef-ab67-ac7b935063fd.png)
> > 这里加个判断
> > > if (Thread.interrupted()){ // todo stop }
> 
> 用了Thread.interrupted() ，没有效果。手动停止后，还是会执行一段时间。
> 
> if (Thread.interrupted()) { return new ProcessResult(false, "Thread.interrupted !"); }

怎么确定没有效果的？另外能否提供下 worker 端的日志？

**Comment by Echo009** [comment]
> > 
> 
> 我是这样确定没有效果的： 和最早的观察结果一样。手动停止之后， 还有执行(有日志源源不断地print出来) 我在子任务for循环的【循环体】、【开始\结束】、和【Thread.interrupted()】的if语句都加了日志输出。
> 
> 代码： ![image](https://user-images.githubusercontent.com/16182082/161091187-f071facc-b32c-4b0d-ba9d-d1491373a66d.png)
> 
> 停止时间截图： ![image](https://user-images.githubusercontent.com/16182082/161090675-b279751b-0f7a-423e-88f8-b8ff0a66b086.png)
> 
> 23点13分停止后，子任务依然执, for循环中的print一直在打印： 2022-03-31 23:14:22.798 [PPP-0] INFO c.z.t.module.patent.job.XXXMapReduceProcessor - working... .... 2022-03-31 23:16:26.805 [PPP-0] INFO c.z.t.module.patent.job.XXXMapReduceProcessor - working...
> 
> 权限原因暂时无法提供work端的日志。
> 
> 但我上面提供了较为详细的代码，可以很容易的复现这个问题。 如果有需要的话，后面有空时我也可以提供完整复现的代码。

看了下 3.4.8 版本的代码，终止的处理和当前版本是一致的。理论上不存在你说的这个问题（至少我这边验证过是没问题的）
有对 worker 做过个性化改造么？如果没有，还是得提供 worker 端完整的日志才行。
另外，如果是新用户，建议使用 v4.x 的版本 ~

**Comment by sunyl-git** [comment]
> > > 
> > 
> > 
> > 我是这样确定没有效果的： 和最早的观察结果一样。手动停止之后， 还有执行(有日志源源不断地print出来) 我在子任务for循环的【循环体】、【开始\结束】、和【Thread.interrupted()】的if语句都加了日志输出。
> > 代码： ![image](https://user-images.githubusercontent.com/16182082/161091187-f071facc-b32c-4b0d-ba9d-d1491373a66d.png)
> > 停止时间截图： ![image](https://user-images.githubusercontent.com/16182082/161090675-b279751b-0f7a-423e-88f8-b8ff0a66b086.png)
> > 23点13分停止后，子任务依然执, for循环中的print一直在打印： 2022-03-31 23:14:22.798 [PPP-0] INFO c.z.t.module.patent.job.XXXMapReduceProcessor - working... .... 2022-03-31 23:16:26.805 [PPP-0] INFO c.z.t.module.patent.job.XXXMapReduceProcessor - working...
> > 权限原因暂时无法提供work端的日志。
> > 但我上面提供了较为详细的代码，可以很容易的复现这个问题。 如果有需要的话，后面有空时我也可以提供完整复现的代码。
> 
> 看了下 3.4.8 版本的代码，终止的处理和当前版本是一致的。理论上不存在你说的这个问题（至少我这边验证过是没问题的） 有对 worker 做过个性化改造么？如果没有，还是得提供 worker 端完整的日志才行。 另外，如果是新用户，建议使用 v4.x 的版本 ~

感谢回复。问题已经解决了。是内部使用httpclient把中断异常给生吞了。
也发现feign等spring cloud组件也有这种问题中断异常都变成HystrixRuntimeException 了。
正确处理http内部异常再设置Thread.currentThread().interrupt(); 就好了。
