### ISSUE TITLE
Admin 管理页面缺少关键的认证功能

### ISSUE THREAD

**Issue by 3d-nx** [PowerJob/PowerJob#391]
**Describe the bug**
当前管理平台缺少基本接口认证功能，对外访问不安全。

**To Reproduce**
使用 Postman 或者 VSCode RestClient 直接读取任务列表，会返回数据
POST  http://localhost:7700/job/list
Content-Type: application/json

{
  "appId": 1,
  "index": 0,
  "pageSize": 10
}

**Expected behavior**
未登录状态下，返回 401 未授权。

**Environment**
 - PowerJob Version: [e.g. 4.0.1]
 - Java Version: [e.g. OpenJDK 8]
 - OS: [e.g. CentOS 8.1]

**Screenshots**
![image](https://user-images.githubusercontent.com/77522563/159698256-08909b27-9d39-464f-b3c0-1e5fa05800c8.png)

**Comment by Echo009** [comment]
https://github.com/PowerJob/PowerJob/issues/43
