### ISSUE TITLE
关于shell脚本任务的结果判定和工作流中上下文传递

### ISSUE THREAD

**Issue by ColeXJ** [PowerJob/PowerJob#398]
有两个问题请大佬指点一下（使用的worker-agent）：
1.如果任务调用的是脚本，脚本需要如何实现 告知server执行成功还是失败（主要是基于业务的判定，非脚本致命错误）
2. 脚本任务做成的工作流如何在任务间传递上下文信息 ？

**Comment by Echo009** [comment]
1. 目前脚本处理器是通过脚本执行后的返回值是否等于 0 来判断成功与否的，所以需要自行在脚本中根据业务逻辑判定是否应该返回 0 
2. 目前没有提供这个能力，需要的话可以参考现有代码进行改造 [AbstractScriptProcessor](https://github.com/PowerJob/PowerJob/blob/master/powerjob-official-processors/src/main/java/tech/powerjob/official/processors/impl/script/AbstractScriptProcessor.java)
