### ISSUE TITLE
woker集群和server集群连接问题

### ISSUE THREAD

**Issue by tobinSen** [PowerJob/PowerJob#399]
如果部署了3台worker节点(不同的appName)和3台server节点。那么请问是如何做到3台woker近似平均的连接上3台sever?

例如：
- workerA (appName = workerA)  --> serverA  
- workerB (appName = workerB)  --> serverB  
- workerC (appName = workerC)  --> serverC

我看代码是 woker客户端 配置的是所有的server节点的ip:port信息。迭代请求每个server节点如果能获取到 currentserver 就返回了。如果按照这样的猜想 workerA、workerB、workerC 都连接 serverA了，这样是不是会存在倾斜详细? 还是存在其他的什么原因(暂时没有看出来)。

愿大佬请教，谢谢。

**Comment by Echo009** [comment]
如果每个 worker 配置的 server address 是一样的，并且用的是 ip:port 形式的地址，在网络以及 server 状态正常的情况下，确实会连上同一台 server。

建议使用域名做负载均衡，或者调整 worker 的 server 地址顺序

以你的这个场景为例，配置如下
workerA 的 server 地址配置： serverA,serverB,serverC
workerB 的 server 地址配置:   serverB,serverC,serverA
workerC 的 server 地址配置:   serverC,serverA,serverB

**Comment by Echo009** [comment]
如果每个 worker 配置的 server address 是一样的，并且用的是 ip:port 形式的地址，在网络以及 server 状态正常的情况下，确实会连上同一台 server。

建议使用域名做负载均衡，或者调整 worker 的 server 地址顺序

以你的这个场景为例，Server 地址的配置如下

workerA -》 serverA,serverB,serverC
workerB -》 serverB,serverC,serverA
workerC -》 serverC,serverA,serverB

**Comment by tobinSen** [comment]
> 如果每个 worker 配置的 server address 是一样的，并且用的是 ip:port 形式的地址，在网络以及 server 状态正常的情况下，确实会连上同一台 server。
> 
> 建议使用域名做负载均衡，或者调整 worker 的 server 地址顺序
> 
> 以你的这个场景为例，Server 地址的配置如下
> 
> workerA -》 serverA,serverB,serverC workerB -》 serverB,serverC,serverA workerC -》 serverC,serverA,serverB


好吧。起初还以为会在server服务层进行调度分配。

**Comment by tobinSen** [comment]
谢谢回复
