### ISSUE TITLE
关于工作流或者任务实例间如何同步

### ISSUE THREAD

**Issue by ColeXJ** [PowerJob/PowerJob#400]
基于某种业务场景，后启动的工作流实例必须判断前面的工作流实例是否执行完成，没有执行完成则等待，执行完成则根据未执行工作流实例的创建时间进行排序，选最早的进行执行，依次循环。请教能否给与适当的切入点和建议

**Comment by Echo009** [comment]
在当前版本下（v4.0.1）没有提供支持工作流同步的机制，按照你的描述，我的理解是这些工作流之间存在计算资源冲突，必须等到上一个工作流执行完成后才执行后面的工作流（而无需关注前边的这些工作流是否执行成功）。

如果是这样，可以考虑二开，增加“任务队列”的概念，更准确的讲应该叫“工作流互斥组“，限制在同一互斥组中的工作流同一时间仅允许存在 n 个工作流执行，如果超出了限制则等待。

如果你是需要关注前边的工作流是否执行成功，举个栗子 A -> B -> C ，工作流 B 必须在工作流 A 执行成功以后才执行。这种情况下可以考虑 在工作流 A 的末尾，增加一个创建工作流 B 的任务节点。我们下个版本会支持工作流之间的嵌套，这种情况下可以分别创建工作流 A、B、C 再根据它们的依赖关系创建复杂工作流 Compose-ABC ，这样也可以支持这个场景。

#266
