### ISSUE TITLE
我看PowerJob使用了akka，但是主要是集群管理，为何不把每个运行的任务都做成akka的actor，这样架构上看是不是更好？

### ISSUE THREAD

**Issue by bestbugwriter** [PowerJob/PowerJob#407]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by KFCFans** [comment]
目前 PowerJob 对 Akka 的用途主要还是在通讯框架上，考虑到多语言支持以及后续可能的通讯框架切换，akka 不会用的很深
