### ISSUE TITLE
关于设计方面的两个问题

### ISSUE THREAD

**Issue by 1985815103** [PowerJob/PowerJob#409]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details. 

问题1：
FIXED_RATE和FIXED_DELAY的Job调度请求，每次都会创建FrequentTaskTracker，该Tracker内部会启动一个ScheduledExecutorService，会不会出现线程池创建过多？

问题2：
服务发现ServerDiscoveryService#discover()中的acquire方法调用，为何此处又是使用HttpUtils的请求，而不是统一使用使用Akka的实现交互

**Comment by KFCFans** [comment]
1. 理论上每个 worker 的秒级任务不会太多，本身线程池的 coreSIze 也不大，影响应该不大
2. 支持域名作为接入层，这样不用维护一堆 IP。
