### ISSUE TITLE
Akka connection ERROR in k8s

### ISSUE THREAD

**Issue by RenYuH** [PowerJob/PowerJob#425]
### worker端的配置如下：

powerjob:
  worker:
    akka-port: 27777
    app-name: intg
    max-appended-wf-context-length: 4096
    max-result-length: 4096
    server-address: ${POWERJOB_SERVER_ADDRESS:127.0.0.1:7700}
    store-strategy: disk

### powerjob服务中的报错日志如下：

2022-06-21 10:20:06.220 WARN 10 --- [t-dispatcher-53] akka.stream.Materializer : [outbound connection to [akka://oms@10.248.0.137:27777], message stream] Upstream failed, cause: StreamTcpException: The connection has been aborted
2022-06-21 10:20:06.220 WARN 10 --- [t-dispatcher-53] akka.stream.Materializer : [outbound connection to [akka://oms@10.248.0.137:27777], control stream] Upstream failed, cause: StreamTcpException: The connection has been aborted

**Comment by RenYuH** [comment]
虽然没有解决问题，但目前不报错了，看代码中heartbeat检测是每15秒一次，默认4次无心跳检测也就是60s都没有响应，就认为worker宕机
集群里我们将60s无响应扩展为120s，scheduler和worker就可以通信了

**Comment by Echo009** [comment]
正常来讲，60 s 的这个时长限制肯定是足够了的 ，这样改配置没有解决根本问题。

请检查下 server 端 akka 绑定的网卡地址和 worker 端 akka 绑定网卡地址的连通性。

**Comment by AZI-D** [comment]
> ## Question
> ### 目前的情况是powerjob服务和worker服务在k8s的集群中，都可以启动成功，也可以访问到界面，worker注册也成功了，但是当页面触发一个任务调度运行时，服务器端无法通过akka和worker通讯，powerjob使用的代码只修改过数据库配置
> ### worker端的配置如下：
> powerjob: worker: akka-port: 27777 app-name: intg max-appended-wf-context-length: 4096 max-result-length: 4096 server-address: ${POWERJOB_SERVER_ADDRESS:127.0.0.1:7700} store-strategy: disk
> 
> ### powerjob服务中的报错日志如下：
> 2022-06-21 10:20:06.220 WARN 10 --- [t-dispatcher-53] akka.stream.Materializer : [outbound connection to [akka://oms@10.248.0.137:27777], message stream] Upstream failed, cause: StreamTcpException: The connection has been aborted 2022-06-21 10:20:06.220 WARN 10 --- [t-dispatcher-53] akka.stream.Materializer : [outbound connection to [akka://oms@10.248.0.137:27777], control stream] Upstream failed, cause: StreamTcpException: The connection has been aborted

你好，你们的场景是多server部署吗？

**Comment by AZI-D** [comment]
> ## Question
> ### 目前的情况是powerjob服务和worker服务在k8s的集群中，都可以启动成功，也可以访问到界面，worker注册也成功了，但是当页面触发一个任务调度运行时，服务器端无法通过akka和worker通讯，powerjob使用的代码只修改过数据库配置
> ### worker端的配置如下：
> powerjob: worker: akka-port: 27777 app-name: intg max-appended-wf-context-length: 4096 max-result-length: 4096 server-address: ${POWERJOB_SERVER_ADDRESS:127.0.0.1:7700} store-strategy: disk
> 
> ### powerjob服务中的报错日志如下：
> 2022-06-21 10:20:06.220 WARN 10 --- [t-dispatcher-53] akka.stream.Materializer : [outbound connection to [akka://oms@10.248.0.137:27777], message stream] Upstream failed, cause: StreamTcpException: The connection has been aborted 2022-06-21 10:20:06.220 WARN 10 --- [t-dispatcher-53] akka.stream.Materializer : [outbound connection to [akka://oms@10.248.0.137:27777], control stream] Upstream failed, cause: StreamTcpException: The connection has been aborted

你好，你们的场景是多server部署吗？
