### ISSUE TITLE
每天晚上有日志报错

### ISSUE THREAD

**Issue by Phoebus888** [PowerJob/PowerJob#426]
![image](https://user-images.githubusercontent.com/45359605/176125927-87112ff3-6a0b-4329-858c-b2c3270ccfa8.png)

**Comment by Echo009** [comment]
忽略就行，每晚凌晨有个自动清理的任务，在清理数据库历史记录时只需要单个 server 节点执行，所以在这之前会尝试获取数据库分布式锁，竞争锁失败了（即唯一索引冲突）就会有这个错误日志打印，这个是 JPA 的默认行为，可自行关闭
