### ISSUE TITLE
job cancel method run error

### ISSUE THREAD

**Issue by quxiangjun** [PowerJob/PowerJob#429]
**Describe the bug**
powerjob client， can not cancel any jobs，because the cancel method need two params ,but now only Long instanceId support .

analyse this method check params by annotation  @DesignateServer ，in DesignateServerAspect ，appId is REQUIRED 。

 

**To Reproduce**
Steps to reproduce the behavior.

/**
* 取消任务实例的运行
* 接口使用条件：调用接口时间与待取消任务的预计执行时间有一定时间间隔，否则不保证可靠性！
*
* @param instanceId 任务实例
*/
@DesignateServer
public void cancelInstance(Long instanceId) {
log.info("[Instance-{}] try to cancel the instance.", instanceId);

}

**Expected behavior**
this  tech.powerjob.server.core.instance.InstanceService#cancelInstance must put appId like：

updated like this :

 /**
     * 取消任务实例的运行
     * 接口使用条件：调用接口时间与待取消任务的预计执行时间有一定时间间隔，否则不保证可靠性！
     * @param appId  应用ID
     * @param instanceId 任务实例
     */
    @DesignateServer
    public void cancelInstance(Long appId,Long instanceId) {
        log.info("[Instance-{}] try to cancel the instance.", instanceId);

}

**Environment**
 - PowerJob Version: 4.0.1
 - Java Version: OpenJDK 8
 - OS: macOs 12.3.1 
 
**Screenshots**

post url : /openApi/cancelInstance

{"success":false,
"data":null,
"message":"PowerJobException: can't find appId in params for:void tech.powerjob.server.core.instance.InstanceService.cancelInstance(Long)"
}

**Additional context**

**Comment by Echo009** [comment]
感谢反馈，确实是有这个问题，将于下个版本修复

**Comment by Echo009** [comment]
#324
