### ISSUE TITLE
前端绕行问题

### ISSUE THREAD

**Issue by HerbertHuang** [PowerJob/PowerJob#433]
**Describe the bug**
通过Charles修改登录请求返回可以绕过用户名密码验证

**To Reproduce**
通过页面提示知道有哪些用户名，然后随意输入密码，通过Charles拦截响应，修改响应内容，可以登录成功。

**Expected behavior**
需要更安全的权限验证。

**Environment**
 - PowerJob Version: 3.4.3
 - Java Version: JDK1.8
 - OS: CentOS 7.6

**Screenshots**
<img width="842" alt="image" src="https://user-images.githubusercontent.com/7554491/179400231-90c09e58-cc3d-4653-b69d-ab85c383db6b.png">

**Additional context**
有看过相关issue，可以增加自定义Inteceptor实现权限验证，考虑需要保留页面功能，需要修改前端源码才能解决上述绕行问题。

**Comment by HerbertHuang** [comment]
能否将当前版本的前端源码也开源？

**Comment by dudiao** [comment]
@HerbertHuang 前端源码地址：https://github.com/PowerJob/PowerJob-Console

**Comment by nzmd** [comment]
期待早点修复

**Comment by KFCFans** [comment]
后续做权限系统的时候可能会考虑进去。但本质上 PowerJob 是一个纯内网的系统，因此对我们来说安全性相对没那么重要。我个人也不太希望有大量的代码去处理这些 WEB 问题。

**Comment by KFCFans** [comment]
https://github.com/PowerJob/PowerJob/releases/tag/v5.0.0-beta

5.0.0 版本 beta 中，任何问题欢迎及时反馈。
