### ISSUE TITLE
kryo这个序列化，一直在报错

### ISSUE THREAD

**Issue by xzq-z** [PowerJob/PowerJob#458]
Failed to deserialize message from [akka://oms@192.168.10.7:27777] with serializer id [6] and manifest []. com.esotericsoftware.kryo.kryo5.KryoException: java.lang.IndexOutOfBoundsException: Index: 110, Size: 1
Serialization trace:
appName (tech.powerjob.common.request.WorkerHeartbeat)

**Comment by xzq-z** [comment]
客户端一直连不到服务端

**Comment by langar294** [comment]
你好，可以提供一下序列化的对象吗

**Comment by KFCFans** [comment]
应该是版本兼容性导致的。
4.1.x 和之前的版本不一致。
如果是 4.1.x 版本的 worker，请使用 4.1.x 版本的 server，反之亦然。
