### ISSUE TITLE
powerjob-mysql镜像版本不一致

### ISSUE THREAD

**Issue by l1douhua** [PowerJob/PowerJob#460]
最新的docker-compose中的yaml版本是4.1.1 我看dockerhup中版本是4.1.0

https://hub.docker.com/r/powerjob/powerjob-mysql/tags

**Comment by dudiao** [comment]
docker-compose中的镜像是本地构建的，暂时不影响使用

**Comment by dudiao** [comment]
docker-compose中，已经使用latest版本
