### ISSUE TITLE
任务调度路由算法能否再优化一下？

### ISSUE THREAD

**Issue by aliciz** [PowerJob/PowerJob#461]
我开了两个节点(worker)，每个节点的最大堆内存是1G，我压测增加3000个（固定速率任务，1000ms)， 前面3000个都只会在1个节点上跑，从3000个开始（我怀疑是50%内存）占用后，才分配给另一个节点。  

为什么不一开始就轮询的给两个节点分配任务?

**Comment by KFCFans** [comment]
目前是支持随机调度策略的，不过可能控制台前端没有实现这个选项，我们后面实现下。

**Comment by KFCFans** [comment]
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/9402086/193507191-e991f824-1599-4a60-aa1d-9b7b36835cf6.png">

**Comment by KFCFans** [comment]
即将发布的 4.2.0 会支持该特性

**Comment by KFCFans** [comment]
since 4.2.0
