### ISSUE TITLE
Worker端获取的是docker内部容器的ip和端口，

### ISSUE THREAD

**Issue by Kriszttttt** [PowerJob/PowerJob#462]
![CC543A58-DBE5-46B4-BE2E-EC39583ECEB4](https://user-images.githubusercontent.com/114504439/192568009-9416b9db-2b61-415b-aa0d-e12ab4012e6e.png

**Comment by Kriszttttt** [comment]
![Uploading 685DE4BD-016D-469E-8E4D-C6CA28FCAB1E.png…]()

**Comment by Echo009** [comment]
参考这个问题 
https://github.com/PowerJob/PowerJob/issues/463
