### ISSUE TITLE
为什么worker端获取的是docker内部容器的ip和端口？aka报错了

### ISSUE THREAD

**Issue by Kriszttttt** [PowerJob/PowerJob#463]
![04E0FF92-ADEA-4B79-A6C4-C0913448F490](https://user-images.githubusercontent.com/114504439/192569271-a2711e4b-7d97-4edf-b7a9-df25a2fc75ed.png)
我的项目出现这个报错该怎么解决呢？
老是连接的是docker容器的ip和端口

**Comment by GCwithH2O** [comment]
作者在摆烂，这问题两年前已经有人提过了，不打算解决，即便有kfk和nacos这些例子他也不打算改了LoL

**Comment by Still4** [comment]
worker部署到容器，通过docker network connect手动连接

比较头疼的是遇到问题本地没法debug，除非server和worker都debug运行

**Comment by rxxy** [comment]
worker连接server是手动指定的，不用担心连接不通的问题，但后面worker发送心跳是用了server给的akka的地址，
目前server获取akka地址的逻辑是获取第一个网卡ip，这样能获取到和worker通信的概率有点小。

其实可以改为获取所有ip，和不同的worker通信可以使用不同的ip，优先使用内网ip。可以自己做一下修改代码，发布一个powrjob-patch版

**Comment by caisefeng** [comment]
垃圾框架狗都不用了

**Comment by caisefeng** [comment]
垃圾框架狗都不用了

**Comment by Echo009** [comment]
> worker连接server是手动指定的，不用担心连接不通的问题，但后面worker发送心跳是用了server给的akka的地址， 目前server获取akka地址的逻辑是获取第一个网卡ip，这样能获取到和worker通信的概率有点小。
> 
> 其实可以改为获取所有ip，和不同的worker通信可以使用不同的ip，优先使用内网ip。可以自己做一下修改代码，发布一个powrjob-patch版

👍

**Comment by Echo009** [comment]
> 作者在摆烂，这问题两年前已经有人提过了，不打算解决，即便有kfk和nacos这些例子他也不打算改了LoL

并非摆烂，文档中也提供了相应的解决方案，手动指定 ip 即可。

至于你提到的 kafka 以及 nacos 的例子，可否详细介绍一下？

**Comment by Echo009** [comment]
参考以下文档，手动指定 ip ，确保 server 和 worker 绑定的 ip 之间是可以正常通信的 

https://www.yuque.com/powerjob/guidence/problem#ZaRnE
