### ISSUE TITLE
开发了一个Processor 执行器，整合MYBATIS, 执行定时任务的时候报错！

### ISSUE THREAD

**Issue by DavidChild** [PowerJob/PowerJob#471]
**Describe the bug**
开发了一个Processor 执行器，整合MYBATIS, 执行定时任务的时候报错！
我编写了一个 MapReduceProcessor ，里面整合了MYBATIS 访问数据库。在执行的过程中，报了下截图错误，备注：我单元测试过过程中是可以查出数据：
![image](https://user-images.githubusercontent.com/18735238/195077188-b4247363-01ee-45a0-85c4-0ceeff96f8e1.png)

*
**Environment**
 - PowerJob Version: [e.g.  4.0.0]
 - powerjob.worker.version [e.g. 4.0.0]
 - Java Version: [e.g. OpenJDK 8]
 - OS: [e.g. CentOS 8.1]

**Screenshots**

**Additional context**

**Comment by KFCFans** [comment]
这个就是典型的业务逻辑问题了，和 PowerJob 应该没有任何关系，可以自己查一下
