### ISSUE TITLE
从worker解析消息异常

### ISSUE THREAD

**Issue by aseaday** [PowerJob/PowerJob#473]
**Describe the bug**
我在k8s环境下遇到了这个错误
Failed to deserialize message from [akka://oms@10.42.1.79:27777] with serializer id [6] and manifest []. com.esotericsoftware.kryo.kryo5.KryoException: Unable to read unknown data (unknown type). (tech.powerjob.common.request.WorkerHeartbeat#null)

**To Reproduce**
应该在k8s下可以复现，生产用的是powerjob:4.2.0镜像

**Comment by KFCFans** [comment]
尝试让 server 和 worker 的版本匹配

**Comment by KFCFans** [comment]
这个问题还存在吗？
如果还存在，可以提供下以下信息：
1. server 和 worker 的版本
2. JVM 和 操作系统环境
3. 完整的异常对战

**Comment by AZI-D** [comment]
> 这个问题还存在吗？ 如果还存在，可以提供下以下信息：
> 
> 1. server 和 worker 的版本
> 2. JVM 和 操作系统环境
> 3. 完整的异常对战

我这边使用了4.0.x的worker和server，想升级server端到4.1.x，这个时候出现了上述问题，我尝试进行心跳信息的兼容，但是还是存在这个问题，有什么解决办法吗？
