### ISSUE TITLE
没有真正的安全认证认证机制

### ISSUE THREAD

**Issue by aliciz** [PowerJob/PowerJob#474]
powerjob-server 的登录只是校验一下应用和密码，其他接口都没有统一拦截，没有token令牌校验，
希望能加入这个功能。

**Comment by Echo009** [comment]
#353

**Comment by nzmd** [comment]
是的，未登录的情况下，都能直接调用！期待修复
![2f7a66843c9ba9bb076def87d5d95ce](https://user-images.githubusercontent.com/21009810/222088343-afe5cac1-171c-439d-a205-40126c8a6464.png)

**Comment by ukhack** [comment]
建议直接使用XXL-JOB，我在上家公司已经经过生产实战了。
今天尝鲜使用PowerJob遇到了不少问题，其中一点就是网络安全问题，防外不防内 安全性 equals  0。

**Comment by dargoner** [comment]
内网现在的安全控制和安全扫描也很严格，希望作者要非常重视

**Comment by moonmm** [comment]
建议增加调度中心和执行器间的通信安全认证
需求：调度中心和执行器进行安全性校验，通过安全认证后才允许通讯，提升系统安全性。

需求背景：这两年对网络安全的要求越来越严格，xxx等相关部门会对系统进行流量监测，渗透测试，接口间通信没有安全控制现在是明令禁止的，直接让你下线整改。

**Comment by mklp** [comment]
+1

**Comment by KFCFans** [comment]
感谢大家的热心建议，相关意见我已收到。权限和安全相关的方案也已经在开发中，后续版本将会发布～

mklp ***@***.***>于2023年8月14日 周一13:38写道：

**Comment by KFCFans** [comment]
https://github.com/PowerJob/PowerJob/releases/tag/v5.0.0-beta

5.0.0 版本 beta 中，任何问题欢迎及时反馈。
