### ISSUE TITLE
OpenAPI保存任务，status状态改为禁用，并没有让秒级任务停下来

### ISSUE THREAD

**Issue by aliciz** [PowerJob/PowerJob#477]
`
ResultDTO<Long> result = powerJobClient.saveJob(jobInfo);
`

OpenAPI保存任务，status状态改为禁用，并没有让秒级任务停下来

看了源码发现  disable那个接口就有这样的逻辑。

**Comment by KFCFans** [comment]
最好先禁用，然后 stop。
后台接口融合了2种操作，OpenAPI 自己处理即可。
