### ISSUE TITLE
server启动时报Error accessing index information: POWERJOB_DAILY.APP_INFO

### ISSUE THREAD

**Issue by yuanlisong** [PowerJob/PowerJob#480]
第一步：创建数据库，启动server，调度中心启动正常，数据库表结构也正常，可以正常访问。
第二步：停止server。
第三步：再次启动server后，server服务报错，启动失败，报错内容如下：
org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'remoteEntityManagerFactory' defined in class path resource [tech/powerjob/server/persistence/config/RemoteJpaConfig.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: remotePersistenceUnit] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.JDBCConnectionException: Error accessing index information: POWERJOB_DAILY.APP_INFO

我用的数据库是OceanBase 数据库，在server内也加入了对应的包。
请问一下是什么原因导致的？

**Comment by Echo009** [comment]
将 `Hibernate` 的 ddlAuto 属性改成 `none` 试试

方法 ： tech.powerjob.server.persistence.config.RemoteJpaConfig#genDatasourceProperties

![image](https://user-images.githubusercontent.com/24402043/198191004-00e213b9-5e6a-435f-88f0-b2f20f0cb483.png)


 `hibernateProperties.setDdlAuto("none");`

**Comment by Echo009** [comment]
错误信息已经提示的很明显了，无法访问 APP_INFO 表的索引信息。JPA 现在肯定是没有兼容 OceanBase 的 ~

**Comment by yuanlisong** [comment]
感谢大佬的耐心指导。我目前先用OceanBase试试看。
