### ISSUE TITLE
最佳实践：MapReduce 实现静态分片 中  subTask instanceof SubTask 为false

### ISSUE THREAD

**Issue by wyhPro** [PowerJob/PowerJob#481]
**Describe the bug**
Cannot cast 'com.qlan99.ota.processor.job.MapReduceProcessorDemo$SubTask' to 'com.qlan99.ota.processor.job.MapReduceProcessorDemo$SubTask'
**To Reproduce**
The code is the same as the example:
`https://www.yuque.com/powerjob/guidence/hczm7m#bbb35cb5`

**Expected behavior**

**Environment**
 - PowerJob Version:  4.2.0
 - Java Version:  OpenJDK 8
 - OS:  WIndows 10

**Screenshots**

**Additional context**

**Comment by Echo009** [comment]
提供的有效信息太少，能否提供下 代码的截图 以及 异常栈信息？

**Comment by wyhPro** [comment]
> 提供的有效信息太少，能否提供下 代码的截图 以及 异常栈信息？
代码就是这个实例代码 https://www.yuque.com/powerjob/guidence/hczm7m#bbb35cb5，
subTask instanceof SubTask 为 false 
```
@Slf4j
@Component
public class MapReduceProcessorDemo implements MapReduceProcessor {
  @Override
  public ProcessResult process(TaskContext context) throws Exception {

    // root task 负责分发任务
    if (isRootTask()) {
      // 从控制台传递分片参数，假设格式为KV：1=a&2=b&3=c
      String jobParams ="1=a&2=b&3=c";
      Map<String, String> paramsMap = Splitter.on("&").withKeyValueSeparator("=").split(jobParams);

      List<SubTask> subTasks = Lists.newLinkedList();
      paramsMap.forEach((k, v) -> subTasks.add(new SubTask(Integer.parseInt(k), v)));
      map(subTasks, "SLICE_TASK");
      return new ProcessResult(true, "ROOT_PROCESS_SUCCESS");
    }

    Object subTask = context.getSubTask();
    if (subTask instanceof SubTask) {
      // 实际处理
      // 当然，如果觉得 subTask 还是很大，也可以继续分发哦

      return new ProcessResult(true, "subTask:" + ((SubTask) subTask).getIndex() + " process successfully");
    }
    return new ProcessResult(false, "UNKNOWN BUG");
  }

  @Override
  public ProcessResult reduce(TaskContext context, List<TaskResult> taskResults) {
    // 按需求做一些统计工作... 不需要的话，直接使用 Map 处理器即可
    return new ProcessResult(true, "xxxx");
  }

  /**
   * @author wyh
   * @date 2022-10-27 9:17
   */
  @Getter
  @NoArgsConstructor
  @AllArgsConstructor
  public static class SubTask {
    private int index;
    private String params;
  }
}
```

**Comment by Echo009** [comment]
无法复现你的这个问题，代码看着也没问题。

检查下你的项目依赖里是不是引入了 `springboot`  的  `devtools` 
 
<dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-devtools</artifactId>
</dependency> 

如果有，移除掉这个依赖，重新编译试试。

如果没有的话，建议先使用 powerjob-worker-samples 项目体验相关功能。

从你提供的信息看应该是类加载器不同导致无法转换，请自行 debug 排查下原因，这个应该不难。

**Comment by wyhPro** [comment]
是`springboot`的`devtools`导致的 谢谢大佬
