### ISSUE TITLE
当调度配置为health_first时，多机只会调用一台机器

### ISSUE THREAD

**Issue by honghao12** [PowerJob/PowerJob#487]
1.机器
![image](https://user-images.githubusercontent.com/51260721/204493079-c370bf2d-e8aa-42e0-9ab2-51aaf6d865ee.png)

2.任务配置
![屏幕截图 2022-11-29 173732](https://user-images.githubusercontent.com/51260721/204493337-30d01425-de0b-4f59-bbcd-ba3ead6c6243.png)

3.测试并发数量15
![image](https://user-images.githubusercontent.com/51260721/204493547-d97ac3e9-5e4b-4c8e-92e8-bebceb3cd7f4.png)

4.测试结果
![image](https://user-images.githubusercontent.com/51260721/204493883-d4d1e396-85d9-49d9-943c-9cc3921215cf.png)
全部都在一台机器执行；
查看15条任务都是在同一机器：
![image](https://user-images.githubusercontent.com/51260721/204494133-dc358cbe-bdc3-4c2e-8f16-dcb6970be5ba.png)

![image](https://user-images.githubusercontent.com/51260721/204494055-a2f8b49e-7090-4451-b3dc-1e54a5c368f4.png)

5.把两台机器换成相同配置
并发线程数15；同样15个任务实例只调用了同一台机器

**Comment by KFCFans** [comment]
worker 端会根据当前的配置情况上报一个健康分，健康优先模式下，永远都会是健康分最高的机器执行（就算有同分目前也不会打散）。
其设计思路是，始终选择最优机器去执行，即使不均匀也没有关系（事实上均匀分布没有太大的意义）。
如果想要均匀分布，建议选择随机策略～
当然也可以自己去改写 server 的分发逻辑
