### ISSUE TITLE
工作流是使用的flowable实现的吗

### ISSUE THREAD

**Issue by fufengyuan** [PowerJob/PowerJob#493]
## Question
- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

通过以上方式都未找到此问题的信息，希望能得到答案。

**Comment by Echo009** [comment]
没有依赖任何其他框架 ，感兴趣的话可以自行阅读相关源码，注释挺完整的，应该比较好理解。

核心代码都在 tech.powerjob.server.core.workflow 这个包下，建议先自行搜索了解 DAG 相关的基础概念
