### ISSUE TITLE
整合springboot启动报错

### ISSUE THREAD

**Issue by 2816444944** [PowerJob/PowerJob#503]
整合进springboot启动报错org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initPowerJob' defined in class path resource [tech/powerjob/worker/autoconfigure/PowerJobAutoConfiguration.class]: Invocation of init method failed; nested exception is org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table task_info (task_id varchar(255), instance_id bigint[*](https://github.com/PowerJob/PowerJob/issues/20), sub_instance_id bigint(20), task_name varchar(255), task_content blob, address varchar(255), status int(5), result text, failed_cnt int(11), created_time bigint(20), last_modified_time bigint(20), last_report_time bigint(20), unique KEY pkey (instance_id, task_id))"; expected "ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
create table task_info (task_id varchar(255), instance_id bigint(20), sub_instance_id bigint(20), task_name varchar(255), task_content blob, address varchar(255), status int(5), result text, failed_cnt int(11), created_time bigint(20), last_modified_time bigint(20), last_report_time bigint(20), unique KEY pkey (instance_id, task_id)) [42001-214]

**Comment by Echo009** [comment]
https://github.com/PowerJob/PowerJob/issues/436

可以参考这个 issue ，更换 h2 的版本，或者自行更改 初始化的 sql 语句

**Comment by 2816444944** [comment]
谢谢回复。通过更换h2版本已解决。


野指针
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PowerJob/PowerJob"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月14日(星期三) 晚上6:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PowerJob/PowerJob] 整合springboot启动报错 (Issue #503)





 
#436
 
可以参考这个 issue ，更换 h2 的版本，或者自行更改 初始化的 sql 语句
