### ISSUE TITLE
When to release a new version？

### ISSUE THREAD

**Issue by liucq200518** [PowerJob/PowerJob#504]
When to release a new version？We just very need the retry-delay custom config func.
By the way, will  second-level mission records in table "instance_info" be stored for forever? I'm afraid there will be too many records in mysql.

**Comment by Echo009** [comment]
1. 这个月会有个小版本更新
2. 实例信息不会一直存储，内置了定时清理的逻辑，默认是保留 7 天内（可通过 server 的 `oms.instanceinfo.retention` 参数配置调整）

**Comment by liucq200518** [comment]
那再请问下，内置的定时清理的逻辑会不会清理掉“等待派发”的任务？感谢

**Comment by Echo009** [comment]
> 那再请问下，内置的定时清理的逻辑会不会清理掉“等待派发”的任务实例？感谢

不会，只会清理完成状态的 （成功、失败、手动停止、取消）
