### ISSUE TITLE
Is possible integrate quarkus?

### ISSUE THREAD

**Issue by FeiHushOnSite** [PowerJob/PowerJob#508]
now quarkus as regular frame work, is possible integrate quarkus? develop quarkus starter? now i notice spring-boot-powerjob-starter

**Comment by KFCFans** [comment]
Quarkus is not very popular in China yet, and PowerJob's development team is not familiar enough with it, so we will learn more about it when we have a chance and then see how to adapt it.
Your suggestion is great and we will take it into consideration.
thank you!

**Comment by KFCFans** [comment]
4.3.0 已发布，该特性已支持

**Comment by KricYi** [comment]
@dengchaofeng 

@ApplicationScoped
public class ApplicationLifeCycle {

    @ConfigProperty(name = "powerjob.worker.port")
    Integer port;
    @ConfigProperty(name = "powerjob.worker.appName")
    String appName;
    @ConfigProperty(name = "powerjob.server.address")
    String serverAddress;
    @ConfigProperty(name = "powerjob.worker.storeStrategy")
    String storeStrategy;
    @ConfigProperty(name = "powerjob.worker.protocol")
    String protocol;
    @Inject
    PowerJobProcessorFactory powerJobProcessorFactory;


    void onStart(@Observes StartupEvent ev) throws Exception {
        Log.info("The application sat-svc is starting...");

        // 1. 创建配置文件
        PowerJobWorkerConfig config = new PowerJobWorkerConfig();
        config.setPort(port);
        config.setAppName(appName);
        config.setServerAddress(Arrays.stream(serverAddress.split(",")).toList());
        // 如果没有大型 Map/MapReduce 的需求，建议使用内存来加速计算
        config.setStoreStrategy(StoreStrategy.valueOf(storeStrategy));
        config.setProtocol(Protocol.valueOf(protocol));
        config.setProcessorFactoryList(Collections.singletonList(powerJobProcessorFactory));
        new PowerJobWorker(config).init();
    }

    void onStop(@Observes ShutdownEvent ev) {
        Log.info("The application sat-svc is stopping...");
    }
}

@Dependent
public class PowerJobClientConfig {

    @ConfigProperty(name = "powerjob.server.address")
    String serverAddress;
    @ConfigProperty(name = "powerjob.worker.appName")
    String appName;

    @ConfigProperty(name = "powerjob.client.password")
    String password;


    @Produces
    @DefaultBean
    public PowerJobClient initPowerJobClient() {
        return new PowerJobClient(Arrays.stream(serverAddress.split(",")).toList(), appName, password);
    }
}
@ApplicationScoped
public class PowerJobProcessorFactory implements ProcessorFactory {
    @Override
    public Set<String> supportTypes() {
        return Set.of(ProcessorType.BUILT_IN.name());
    }

    @Inject
    @All
    List<BasicProcessor> processors;

    @Override
    public ProcessorBean build(ProcessorDefinition processorDefinition) {
        String className = processorDefinition.getProcessorInfo() + "_ClientProxy";
        try {
            BasicProcessor basicProcessor = processors.stream().filter(processor -> processor.getClass().getName().equals(className)).findFirst().orElseThrow(() -> new RuntimeException("not found processor"));
            return new ProcessorBean()
                    .setProcessor(basicProcessor)
                    .setClassLoader(basicProcessor.getClass().getClassLoader());
        } catch (Exception e) {
            Log.warn("[ProcessorFactory] load local Processor(className = {}) failed.", className, e);
        }
        return null;
    }
}
### powerjob ###
powerjob.server.address=${POWERJOB_SERVER_ADDRESS:job-svc:7700}
powerjob.worker.appName=${POWERJOB_WORKER_APP_NAME:sat-svc}
powerjob.worker.port=${POWERJOB_WORKER_PORT:27777}
powerjob.worker.storeStrategy=${POWERJOB_WORKER_STORE_STRATEGY:DISK}
powerjob.worker.protocol=${POWERJOB_WORKER_PROTOCOL:HTTP}
