### ISSUE TITLE
使用数据库 postgresql 启动 server 报错 SQL Error ERROR

### ISSUE THREAD

**Issue by smile365** [PowerJob/PowerJob#509]
1. 按照文档 [快速开始（本地IDE版）](https://www.yuque.com/powerjob/guidence/nyio9g) 启动调度服务器 powerjob-server。
2. 使用 postgresql 数据库，版本  14。
3. 在 console 创建任务时报错 `SQL Error ERROR: column "job_params" is of type oid but expression is of type character varying`，详细错误如下：
```SystemVerilog
2022-12-23 17:38:23.739  WARN 31629 --- [  XNIO-1 task-3] o.h.e.j.s.SqlExceptionHelper             : SQL Error: 0, SQLState: 42804
2022-12-23 17:38:23.740 ERROR 31629 --- [  XNIO-1 task-3] o.h.e.j.s.SqlExceptionHelper             : ERROR: column "job_params" is of type oid but expression is of type character varying
  建议：You will need to rewrite or cast the expression.
  位置：536
2022-12-23 17:38:23.744  INFO 31629 --- [  XNIO-1 task-3] o.h.e.j.b.i.AbstractBatchImpl            : HHH000010: On release of batch it still contained JDBC statements
2022-12-23 17:38:23.902  INFO 31629 --- [  XNIO-1 task-3] MONITOR_LOGGER_DB_OPERATION              : CORE|JpaRepository|saveAndFlush|FAILED|-|649|InvalidDataAccessResourceUsageException|-
2022-12-23 17:38:23.926 ERROR 31629 --- [  XNIO-1 task-3] t.p.s.w.ControllerExceptionHandler       : [ControllerException] http request failed.

org.springframework.dao.InvalidDataAccessResourceUsageException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not execute statement
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:259)
...
```

**Comment by Echo009** [comment]
参考这个 issue https://github.com/PowerJob/PowerJob/issues/153 ，在配置文件中指定
 `spring.datasource.remote.hibernate.properties.hibernate.dialect=tech.powerjob.server.persistence.config.dialect.PowerJobPGDialect`

![image](https://user-images.githubusercontent.com/24402043/209963617-ab607392-512b-4c28-a506-e01ae6150764.png)

**Comment by smile365** [comment]
> 参考这个 issue #153 ，在配置文件中指定 `spring.datasource.remote.hibernate.properties.hibernate.dialect=tech.powerjob.server.persistence.config.dialect.PowerJobPGDialect`


忘了贴配置文件了，上面的报错信息是我按照文档 [6. 多数据库支持 PostgreSQL](https://www.yuque.com/powerjob/guidence/problem#DYCZ9) 配置了 `spring.datasource.remote.hibernate.properties.hibernate.dialect=tech.powerjob.server.persistence.config.dialect.PowerJobPGDialect`  

完整配置文件如下： 
```properties
oms.env=DAILY
logging.config=classpath:logback-dev.xml


spring.datasource.core.driver-class-name=org.postgresql.Driver
spring.datasource.core.jdbc-url=jdbc:postgresql://127.0.0.1:30132/powerjob-daily
spring.datasource.core.username=postgres
spring.datasource.core.password=xxx
spring.datasource.core.hikari.maximum-pool-size=20
spring.datasource.core.hikari.minimum-idle=5
spring.datasource.remote.hibernate.properties.hibernate.dialect=tech.powerjob.server.persistence.config.dialect.PowerJobPGDialect

oms.instanceinfo.retention=1
oms.container.retention.local=1
oms.container.retention.remote=-1

oms.instance.metadata.cache.size=1024
oms.accurate.select.server.percentage = 50

```

**Comment by Echo009** [comment]
pg 14 的版本我们目前没有测试过。

你可以先检查下自动建表时有 @Lob 注解标记的字段，在数据库中实际上用的是什么类型，如果是 Text 类型，用这种方式就没有问题。但如果建表时用的就是 Clob 类型，可以去掉数据库方言的配置再试试。

**Comment by smile365** [comment]
> pg 14 的版本我们目前没有测试过。
> 
> 你可以先检查下自动建表时有 @lob 注解标记的字段，在数据库中实际上用的是什么类型，如果是 Text 类型，用这种方式就没有问题。但如果建表时用的就是 Clob 类型，可以去掉数据库方言的配置再试试。

 @lob 注解标记的字段在数据库 pg14 里是 oid 类型，去掉数据库方言的配置正常了。

**Comment by LeoDeYang** [comment]
同意，

> > pg 14 的版本我们目前没有测试过。
> > 你可以先检查下自动建表时有 @lob 注解标记的字段，在数据库中实际上用的是什么类型，如果是 Text 类型，用这种方式就没有问题。但如果建表时用的就是 Clob 类型，可以去掉数据库方言的配置再试试。
> 
> @lob 注解标记的字段在数据库 pg14 里是 oid 类型，去掉数据库方言的配置正常了。

同意，去掉数据库方言的配置正常了，ERROR: column "job_params" is of type oid but expression is of type character；
可惜紧接着又报错：PSQLException: 大型对象无法被使用在自动确认事物交易模式
为什么不能直接修改job_params字段和processor_info字段为Text类型呢，在PG数据库里面；

**Comment by Echo009** [comment]
> 同意，
> 
> > > pg 14 的版本我们目前没有测试过。
> > > 你可以先检查下自动建表时有 @lob 注解标记的字段，在数据库中实际上用的是什么类型，如果是 Text 类型，用这种方式就没有问题。但如果建表时用的就是 Clob 类型，可以去掉数据库方言的配置再试试。
> > 
> > 
> > @lob 注解标记的字段在数据库 pg14 里是 oid 类型，去掉数据库方言的配置正常了。
> 
> 同意，去掉数据库方言的配置正常了，ERROR: column "job_params" is of type oid but expression is of type character； 可惜紧接着又报错：PSQLException: 大型对象无法被使用在自动确认事物交易模式 为什么不能直接修改job_params字段和processor_info字段为Text类型呢，在PG数据库里面；

可以这样操作，将所有的 @Lob 注解标记的字段改为 Text 类型，再指定方言。

如果用的是 PG 的话，还是建议自行建表，关掉 JPA 的自动修改表配置
