### ISSUE TITLE
关于工作流实例的“标记成功”

### ISSUE THREAD

**Issue by Gregfujie** [PowerJob/PowerJob#514]
## Question
想问一下将失败的任务标记为成功具体有什么作用？文档中提到“该功能主要用于搭配工作流实例的重试功能实现灵活运维 （想跳过某个失败的节点进行重试）”。我的理解是在实例运行中如果出现失败，但想继续测试下游的任务的话，可以将当前标记为成功，再点击重试。但实际上在任务失败时工作流已经结束，并没有起效，而且似乎在建立工作流时就可以打开失败跳过这个选项来实现。是还需要添加其他配置吗？
![image](https://user-images.githubusercontent.com/57748929/209763461-3430c194-7d65-44af-b075-8ae7df4a9e80.png)
Powerjob版本：3.0.0
工作环境：Centos 7.9
Java：1.8
Powerjob-server：4.2.0

**Comment by Echo009** [comment]
“我的理解是在实例运行中如果出现失败，但想继续测试下游的任务的话，可以将当前标记为成功，再点击重试”   —— 这个理解没错

你重试失败了是因为系统内的元数据（大概率是工作流节点表数据发生了变更）丢失，系统已经给了比较明显的提示 

![image](https://user-images.githubusercontent.com/24402043/209961572-c80904c9-694a-4ba5-99d0-fb3e97cf92ea.png)

在建立工作流的时候确实可以选择打开失败跳过来实现，这里的应用场景和上边的那种是不一样的。

第一种情况考虑到的是有些异常情况是未能预料到的，需要人工运维去解决，而解决之后，出现问题的节点有可能是不需要被重试的，这个时候标记成功的作用就来了 。
