### ISSUE TITLE
任务日志配置为Online时出现日志乱序

### ISSUE THREAD

**Issue by huzk8** [PowerJob/PowerJob#515]
**Describe the bug**
当日志配置使用Online时，任务实例的日志会出现乱序

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
 - PowerJob Version: [e.g. 3.0.0]
 - Java Version: [e.g. OpenJDK 8]
 - OS: [e.g. CentOS 8.1]

**Screenshots**
![图片](https://user-images.githubusercontent.com/18548053/209901493-e78f0571-7e9b-45a7-be20-43a6dd424645.png)
![图片](https://user-images.githubusercontent.com/18548053/209901509-b371b72a-2768-4bc9-bec1-0491c9d33eca.png)
![图片](https://user-images.githubusercontent.com/18548053/209901579-aa862bfe-0ae1-4b5f-b167-7ee81f19714c.png)

**Additional context**

**Comment by Echo009** [comment]
👍 ，当前版本 v4.2 已经没有这个日志的配置了，不过在日志频繁打印的情况下确实也会存在这个乱序的问题。

**Comment by huzk8** [comment]
4.2版本不用mongodb可以查看任务实例日志吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月29日(周四) 晚上9:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PowerJob/PowerJob] 任务日志配置为Online时出现日志乱序 (Issue #515)

**Comment by Echo009** [comment]
> 4.2版本不用mongodb可以查看任务实例日志吗
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年12月29日(周四) 晚上9:23 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [PowerJob/PowerJob] 任务日志配置为Online时出现日志乱序 (Issue #515)

可以，但是日志不会被持久化存储（重启 server 会丢失 ）

**Comment by Echo009** [comment]
> 👍 ，当前版本 v4.2 已经没有这个日志的配置了，不过在日志频繁打印的情况下确实也会存在这个乱序的问题。

纠正一下，有这个配置 = =， online 为 v4.1.0 及以前版本的默认配置

**Comment by KFCFans** [comment]
System.nanoTime() 非绝对时间，是 JVM 相对于某个启动点的偏移量。如果用 System.nanoTime() 代替当前的时间戳，只能解决单机的排序问题，但会引入集群间的排序问题，理论上问题更严重。

一般实际使用中，log 不可能那么频繁，如果是毫秒级的日志量，对 server 的压力也很大，这种情况也不建议用 online logger
