### ISSUE TITLE
部署生产后刷新界面报错ERROR：UndeclaredThrowableException

### ISSUE THREAD

**Issue by kkrgwbj** [PowerJob/PowerJob#516]
版本是:4.1.0
本地测试好好的,但是部署生产后,刷新调度中心界面报错:
ERROR：UndeclaredThrowableException
![image](https://user-images.githubusercontent.com/6836934/209905397-8eac7aad-de7f-4a64-a3a8-80041f2b8584.png)

调度中心所有日志看了均正常;

**Comment by Echo009** [comment]
你提供的有效信息太少 = =，建议先 F12 打开 console  看下是哪个请求报错，再去查下 server 端的日志

**Comment by kkrgwbj** [comment]
找到问题了,是因为现网服务器两个网卡,powerjob-server读取的网卡不对导致IP全错了.已经固定了网卡,咱们那个在线日志查看必须依赖MongoDB吗

**Comment by Echo009** [comment]
> 找到问题了,是因为现网服务器两个网卡,powerjob-server读取的网卡不对导致IP全错了.已经固定了网卡,咱们那个在线日志查看必须依赖MongoDB吗

没有照样能用，但不会被持久化，server 重启后日志可能会丢失

**Comment by kkrgwbj** [comment]
实际上我们这边在测试的时候发现,我server不重启也不能查看,直接提示
![image](https://user-images.githubusercontent.com/6836934/210047123-ae436098-a876-40f8-98ae-def12a7bf637.png)

**Comment by Echo009** [comment]
> 实际上我们这边在测试的时候发现,我server不重启也不能查看,直接提示 ![image](https://user-images.githubusercontent.com/6836934/210047123-ae436098-a876-40f8-98ae-def12a7bf637.png)

任务对应的 processor 内有用 omslogger 打印日志么？

**Comment by kkrgwbj** [comment]
好了谢谢，默认是存储在哪里的？

**Comment by Echo009** [comment]
Server 所在机器的磁盘上（会先暂存在 H2 数据库中，随后写入磁盘）
