### ISSUE TITLE
如何理解 最大实例数 和 单机线程数 配置

### ISSUE THREAD

**Issue by kkrgwbj** [PowerJob/PowerJob#519]
○ 最大实例数：该任务允许同时执行的数量，0代表不限（默认为 0）
  ○ 单机线程并发数：该实例执行过程中每个 Worker 使用的线程数量

假设，我有个任务每隔5分钟需要调度一次，但是这个任务有时候因为业务侧耗时比较长，可能执行超过了5分钟。但是我不可能说，我正在跑的任务没有跑完，就继续又触发调度了一次，这样就可能会造成数据重复；

针对这种场景，我们该如何配置 这两个参数 ，如何能够比较直观的理解 这两个参数的意义；

**Comment by Echo009** [comment]
> 我有个任务每隔5分钟需要调度一次，但是这个任务有时候因为业务侧耗时比较长，可能执行超过了5分钟。但是我不可能说，我正在跑的任务没有跑完，就继续又触发调度了一次，这样就可能会造成数据重复

这种情况下，最大实例数 配置成 1 就行 。

在每次触发任务调度的时候，都会先检查相应任务的最大实例数量，如果当前正在运行的实例数量超过了 最大实例数，那么就会调度本次调度。

至于单机线程并发数量，对于非 map / mapReduce 等不存在多个子任务的任务没有实际意义。

对于有多个子任务的，则通过该参数限制了在每个 worker 下可以同时执行的子任务个数。

**Comment by kkrgwbj** [comment]
实际测试，不是告警好像直接是报错。

**Comment by Echo009** [comment]
> 实际测试，不是告警好像直接是报错。

额，这里对告警的理解应该有分歧。

上文中的告警指的是，属于系统正常的预期行为，不影响功能的正常运行，但是需要提示用户的情况
