### ISSUE TITLE
【官方】网络层重构&协议名称征集

### ISSUE THREAD

**Issue by KFCFans** [PowerJob/PowerJob#520]
网络层重构，抽象网络框架，脱离对具体实现的依赖（开发分支：[4.3.0](https://github.com/PowerJob/PowerJob/tree/4.3.0/powerjob-remote)），预计提供以下3种实现
* AKKA：兼容层，方便老用户迁移（AKKA 后续收费，PowerJob 会剥离对其的依赖）
* HTTP：基于 vertx 的 HTTP 协议
* POWERJOB：基于 netty 的自研协议
***
PS. 自研协议的名称征集中

最简单的是像 dubbo 一样把项目名称作为协议名称，但 POWERJOB 太长，默认还有拼写问题（PowerJob并不是一个单词），一直被 idea 的语法提示骚扰本强迫症有点受不了 =.=

最近还沉浸在世界杯的喜悦中，有点想拿球星名称作为协议名称，但 MESSI 的特点和协议有点不搭，Mbappe 作为法国超跑倒是很搭，但 Mbappe 存在未来翻车的可能性，要是翻车了这个协议名称就很尴尬...而且作为梅西粉用 Mbappe 的名字当协议也说不过去......

还有很多想用的名字，比如常用的枪械 M14EBR or Gatling（感觉这个还行，寓意不错），常玩的英雄 Viktor 等等......

想了下，先尝试搞个投票征集名义吧。投票方式，在评论回复任意👍表示赞同，反之反对。
***
PS2. 有起名意向的选手仿照格式评论即可，最终采纳者奖励答疑一天！（[滑稽]）

**Comment by KFCFans** [comment]
候选名称1: MBAPPE
优点：
* 当前足坛身价第一人，梅老板队友（虽然可能关系不咋样）
* 法国超跑，速度快，寓意不错
缺点：
* 网络上抨击人品问题的比较多，未来有概率翻车，不如 MESSI 稳

**Comment by KFCFans** [comment]
候选名称2: BARRETT
优点：各大 FPS 游戏知名武器，威力大，寓意也不错
缺点：好像没有显著缺点，有点想选这个了

**Comment by KFCFans** [comment]
候选名称3: POWERJOB
优点：简单直白
缺点：
* 存在语法拼写错误，idea下划线警告
* 太单调了，boring......

**Comment by makabaka23333** [comment]
候选名称4: Quinn
优点：lol中英雄 德玛西亚之翼 奎因(开大跑的贼拉快)，和quick相近，反正速度即正义就对了；ps：后面再有组件就叫华洛，强力搭档啊
缺点：好像没有显著缺点

**Comment by KFCFans** [comment]
> 候选名称4: Quinn 优点：lol中英雄 德玛西亚之翼 奎因(开大跑的贼拉快)，和quick相近，反正速度即正义就对了；ps：后面再有组件就叫华洛，强力搭档啊 缺点：好像没有显著缺点

你是懂起名的哈哈，创意不错，但我不会玩奎因啊！[斜眼笑]

**Comment by makabaka23333** [comment]
> > 候选名称4: Quinn 优点：lol中英雄 德玛西亚之翼 奎因(开大跑的贼拉快)，和quick相近，反正速度即正义就对了；ps：后面再有组件就叫华洛，强力搭档啊 缺点：好像没有显著缺点
> 
> 你是懂起名的哈哈，创意不错，但我不会玩奎因啊！[斜眼笑]

我只玩乱斗，所以我也不会奎因，但是格局要打开嘛 [打开格局]

**Comment by KFCFans** [comment]
> > > 候选名称4: Quinn 优点：lol中英雄 德玛西亚之翼 奎因(开大跑的贼拉快)，和quick相近，反正速度即正义就对了；ps：后面再有组件就叫华洛，强力搭档啊 缺点：好像没有显著缺点
> > 
> > 
> > 你是懂起名的哈哈，创意不错，但我不会玩奎因啊！[斜眼笑]
> 
> 我只玩乱斗，所以我也不会奎因，但是格局要打开嘛 [打开格局]

只玩大乱斗能认识奎因这英雄也是蛮厉害的哈哈。RESPECT！

**Comment by 1460595002** [comment]
内部通信协议要更换了吗

**Comment by 1460595002** [comment]
请问要改成基于 netty吗

**Comment by KFCFans** [comment]
> 内部通信协议要更换了吗

可以看下 4.3.0 的 release公告
