### ISSUE TITLE
How to customize the storage path of the h2 database

### ISSUE THREAD

**Issue by tjudadc** [PowerJob/PowerJob#521]
## Question
as title said 

it seems ConnectionFactory.class  DISK_JDBC_URL cannnot customize 

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by KFCFans** [comment]
请详细描述希望自定义h2 jdbc url 的原因，如果需求足够合理，我们都会支持。

**Comment by tjudadc** [comment]
1、希望程序和h2数据库在相同目录，方便查看，了解。
2、家目录可能存储大小不够，长时间运行的话，h2数据库大小能够达到5.7G。
所以希望自由定义h2数据库目录、

**Comment by KFCFans** [comment]
收到，后续我们考虑下。短期内也可以通过自己重现修改 worker 代码，重现打包到公司私服 or 云服务厂商 maven 仓库来解决。

**Comment by KFCFans** [comment]
4.3.0 已发布，该特性已支持
