### ISSUE TITLE
是否存在异步执行转同步执行的方式

### ISSUE THREAD

**Issue by honghao12** [PowerJob/PowerJob#522]
背景：
当手动runJob时，存在需求需要利用Job执行后的结果，所以需要阻塞任务，直到任务执行完，继续进行后面的业务逻辑

**Comment by KFCFans** [comment]
不错的想法和需求。详细描述下，对你来说，你期望 PowerJob 怎么进行回调？

**Comment by honghao12** [comment]
我自己实现的方式是：循环查询任务实例状态+超时停止等待

**Comment by Echo009** [comment]
用工作流可以完美匹配你的这个场景，配置一下就行

**Comment by xljqq** [comment]
我也有同样的场景需求，不知道后续有没有做相应的优化策略，想请教一下，谢谢
