### ISSUE TITLE
可以提供一个oracle的sql脚本吗

### ISSUE THREAD

**Issue by 2816444944** [PowerJob/PowerJob#524]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KFCFans** [comment]
1. 可以自己在本地开发环境连个 oracle 库，PowerJobServer 启动的时候会自动创建表，然后再导出即可。
2. 也可以自己简单翻译和改下下当前的 mysql 建库建表脚本
自己简单操作下成本不高。
***
DB实现太多了，oracle、mysql、sqlserver 等等等等，官方开发团队对其他 DB 熟悉度没那么高，为了避免引入其他问题就暂时不提供其他 DB 实现的脚本了。敬请谅解。

**Comment by 2816444944** [comment]
> 1. 可以自己在本地开发环境连接一个oracle库，PowerJobServer启动的时候会自动创建表，然后再导出即可。
> 2. 也可以自己简单翻译和修改下下载当前的mysql建库建表脚本
>    自己简单操作下成本不高。
> 
> db实现太了，甲骨文，mysql sqlserver等等

好的 没发现他可以自己创建表。谢谢。
