### ISSUE TITLE
内网的centos7单机部署，是限制访问互联网的；请问一下，要屏蔽掉哪些配置或者代码。

### ISSUE THREAD

**Issue by LeoDeYang** [PowerJob/PowerJob#525]
## Question
**内网的centos7单机部署，单击跑一跑一些任务即可，不需要报警；也不需要集群。是限制访问互联网的。请问一下，要屏蔽掉哪些配置或者代码。**
`[main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
[main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false`

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by KFCFans** [comment]
删除以下配置即可
邮件报警：spring.mail 相关
其他报警： oms.alarm 相关
