### ISSUE TITLE
启动worker工程initPowerJob 报错，提示创建表（task_info）报错

### ISSUE THREAD

**Issue by zoo-ray** [PowerJob/PowerJob#527]
![Uploading 1673234064450.jpg…]()
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table task_info (task_id varchar(255), instance_id bigint[*](20), sub_instance_id bigint(20), task_name varchar(255), task_content blob, address varchar(255), status int(5), result text, failed_cnt int(11), created_time bigint(20), last_modified_time bigint(20), last_report_time bigint(20), unique KEY pkey (instance_id, task_id))"; expected "ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:

**Comment by KFCFans** [comment]
强制指定H2数据库版本试试（maven 依赖仲裁其他版本，只保留以下版本），如果不行的话，提供 PowerJob 版本 + JDK版本 + SpringBoot 版本
<dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>1.4.200</version>
 </dependency>

**Comment by zoo-ray** [comment]
确实是h2数据库版本问题，我maven引入1.4.200这个版本就可以了
