### ISSUE TITLE
4.2版本基于docker部署内存会一直增长，超过了最大堆分配

### ISSUE THREAD

**Issue by chenlei0427** [PowerJob/PowerJob#530]
**版本：** 4.2.0
**JVM参数：**-Xmx1344M -Xms1344M -Xmn448M -XX:MaxMetaspaceSize=256M -XX:MetaspaceSize=256M -XX:+UseConcMarkSweepGC -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+CMSClassUnloadingEnabled -XX:+ParallelRefProcEnabled -XX:+CMSScavengeBeforeRemark -XX:ErrorFile=/root/powerjob/server/jvm/hs_err_pid%p.log   -Xloggc:/root/powerjob/server/jvm/gc.log -XX:HeapDumpPath=/root/powerjob/server/jvm -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintHeapAtGC
**任务容量：** 大概每5分钟执行100个任务
**现象：** 按照以上任务量执行了4天，内存占用量已经达到1.8G，实际dump下来JVM堆只有1.1G
问题：请问有遇到过类似问题，或者是有什么参数可以优化该问题的么

**Comment by KFCFans** [comment]
请提供堆 dump 文件进行分析，或者自己分析下同步我们结果。
至少要先看看内存消耗在哪里

**Comment by KFCFans** [comment]
如果有内存上限需求，建议自己设置 JVM 启动参数。

**Comment by PainAshura** [comment]
我也遇到了这个问题，我是power-worker端，堆内一直正常，甚至我把对象监控、线程监控、pmap监控、strace监控全部打开了。线程没有增加，对象倒是有一定的起伏，限制jvm的堆内和堆外没有一点用，会把容器撑爆，然后pods直接挂掉
