### ISSUE TITLE
K8S使用镜像部署powerjob-server启动报错

### ISSUE THREAD

**Issue by intna** [PowerJob/PowerJob#533]
## Question
我尝试了更改mysql连接超时时间，也没有解决。mysql数据库也是我K8S集群内的，我可以用navicat连接
<img width="960" alt="Snipaste_2023-01-16_15-43-49" src="https://user-images.githubusercontent.com/99332409/212624659-7db3fb07-95e3-412a-a303-b1dd6e0b9c1a.png">

<img width="960" alt="Snipaste_2023-01-16_15-44-27" src="https://user-images.githubusercontent.com/99332409/212625217-83bedbd5-6355-4a45-994a-c7aa8ef57579.png">

**Comment by intna** [comment]
还有我比较好奇地是从日志里看为什么HikariPool-1 可以正常初始化，但是HikariPool-2不行

**Comment by KFCFans** [comment]
powerjob-server 就是个普通的 SpringBoot 2.x 应用，如果起不来，拿着错误去网上查，应该都有通用解决方案。
一般来说不外乎 docker 网络配置问题导致连不上 DB、或者一些兼容性问题需要自己稍微修改下代码。

**Comment by intna** [comment]
> powerjob-server 就是个普通的 SpringBoot 2.x 应用，如果起不来，拿着错误去网上查，应该都有通用解决方案。
> 
> 一般来说不外乎 docker 网络配置问题导致连不上 DB、或者一些兼容性问题需要自己稍微修改下代码。

好的谢谢
