### ISSUE TITLE
ERROR: column "job_params"

### ISSUE THREAD

**Issue by GretUp** [PowerJob/PowerJob#537]
**Describe the bug**
I am trying to create a job with **empty job params** and when I try to save it I get following error:
ERROR：InvalidDataAccessResourceUsageException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not execute statement

in the logs I can see:
```
org.postgresql.util.PSQLException: ERROR: column "job_params" is of type oid but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 536
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
```

**Environment**
I am using the latest container and PostgreSQL 11.15

This is the command to start the server:
`docker run -d --restart=always --name powerjob-server -p 7700:7700 -p 10086:10086 -e TZ="Europe/Rome" -e JVMOPTIONS="" -e PARAMS="--spring.profiles.active=product --spring.datasource.core.driver-class-name=org.postgresql.Driver --spring.datasource.core.jdbc-url=jdbc:postgresql://172.17.0.10:5432/powerjob-product?useUnicode=true&characterEncoding=UTF-8 --spring.datasource.core.username=xxx --spring.datasource.core.password=yyy --spring.datasource.remote.hibernate.properties.hibernate.dialect=tech.powerjob.server.persistence.config.dialect.PowerJobPGDialect"  -v /home/docker/powerjob-server:/root/powerjob-server -v /home/.m2:/root/.m2 tjqq/powerjob-server:latest`

**Comment by KFCFans** [comment]
https://github.com/PowerJob/PowerJob/issues/153#issuecomment-812771783

**Comment by KFCFans** [comment]
参考上诉解决方案

**Comment by KFCFans** [comment]
add this config in powerjob-server's properties and have a try

`spring.datasource.remote.hibernate.properties.hibernate.dialect=tech.powerjob.server.persistence.config.dialect.PowerJobPGDialect`

**Comment by GretUp** [comment]
as you can see above I am already applying this property when starting the docker container.
I tried with postgre version 11.15. and 15.1, but getting still same error.
is there something else I can try to fix this?

**Comment by KFCFans** [comment]
is server version is 4.2.1?

**Comment by GretUp** [comment]
I am using tjqq/powerjob-server:latest

I found a solution: I changed all database fields which have datatype "oid" to "text".
Now

**Comment by KFCFans** [comment]
You're great.

PS. We recommend that you prefer not to use the latest version and rely directly on the specific version, otherwise an error may be triggered after one of the updates
