### ISSUE TITLE
How to add a token in a http call?

### ISSUE THREAD

**Issue by GretUp** [PowerJob/PowerJob#540]
I am able to call an external API with tech.powerjob.official.processors.impl.HttpProcessor.
As job params I am passing: {"Method":"GET", "url":"http://172.17.0.15:8080/actuator/health"}

Is there a possibility also to pass a token in the header?

**Comment by KFCFans** [comment]
of course you can

**Comment by KFCFans** [comment]
<img width="558" alt="image" src="https://user-images.githubusercontent.com/9402086/215076388-fb377d17-8962-4c73-b500-871be59e3a10.png">

**Comment by KFCFans** [comment]
source code is here: tech.powerjob.official.processors.impl.HttpProcessor
It's very simple, just look at the source code and you'll understand. If there is not satisfied, you can also write your own processor.

**Comment by GretUp** [comment]
Do you have an example what you send as job parameters?

**Comment by KFCFans** [comment]
just use java code to initialize the HttpParams object, then convert it to json string.

**Comment by GretUp** [comment]
I tried this with tech.powerjob.official.processors.impl.HttpProcessor:
{"Method":"POST", "url":"http://keycloakx-localdev:30433/realms/localdev/protocol/openid-connect/token", "body":"{"grant_type":"client_credentials","client_id":"job-scheduler","client_secret":"1234"}"}

But I am getting error:
INFO using params: {"Method":"POST", "url":"http://keycloakx-localdev:30433/realms/localdev/protocol/openid-connect/token", "body":"{"grant_type":"client_credentials","client_id":"job-scheduler","client_secret":"1234"}"}
2023-02-05 20:42:58.975 [172.17.0.26:27777] ERROR execute failed!
shade.powerjob.com.alibaba.fastjson.JSONException: syntax error, unexpect token error

Any suggestion?

Thank you!

**Comment by GretUp** [comment]
I tried this, too:
{"Method":"POST", "url":"http://172.17.0.10:8080/realms/DCMP-localdev/protocol/openid-connect/token","mediaType":"application/json","header":"Content-Type:application/x-www-form-urlencoded", "body":"grant_type:client_credentials,client_id:job-scheduler,client_secret:1234"}

But getting 415 error:  Cannot consume content type

**Comment by GretUp** [comment]
I tried this too:
{"Method":"POST","url":"http://172.17.0.10:8080/realms/DCMP-localdev/protocol/openid-connect/token","mediaType":"application/x-www-form-urlencoded", "body":"{"grant_type":"client_credentials","client_id":"job-scheduler","client_secret":"1234"}"}

with error:
JSONException: syntax error, unexpect token error
