### ISSUE TITLE
Powerjob agent uses more than 100% CPU

### ISSUE THREAD

**Issue by GretUp** [PowerJob/PowerJob#548]
I installed 2 default worker agents with:
docker run -d -e PARAMS="--app test-1 --server 172.17.0.25:7700" -p 27777:27777 --name powerjob-agent-1 -v /home/docker/powerjob-agent:/root tjqq/powerjob-agent:latest

After about 2 hours on both agents the CPU load is more than 100% although I am not running any job.

I am using powerjob:latest docker on windows 10.

![image](https://user-images.githubusercontent.com/107860971/216990268-c3c612cc-f973-4fab-b9bb-aa35f98fd445.png)

**Comment by KFCFans** [comment]
1. high load may be caused by your jobs, the specific need for flame chart analysis, we recommend using tools such as [arthas](https://arthas.aliyun.com/en/) to analyze CPU consumption
2. If it is confirmed to be a powerjob problem, please provide the flame chart and thread dump file
