### ISSUE TITLE
RaiDrive影响powerjob调度通讯

### ISSUE THREAD

**Issue by iamzzq** [PowerJob/PowerJob#556]
网盘软件RaiDrive开启，powerjob调度报no worker vailable,查看powerjob日志报 process finished，final status is failed
![5447ACB4-F380-498e-96DC-1823E5D56273](https://user-images.githubusercontent.com/38712051/217985716-47a5758b-1235-4722-80a4-f22c6482eaca.png)
![lQLPJxRx_ZCjeLjNAtbNA9-ww0IhpNcOLXMD3-fzVgCqAA_991_726](https://user-images.githubusercontent.com/38712051/217986996-392ed155-c6a9-471f-a9d4-0910d2815f43.png)

第一张为powerjob日志，第二张为网盘软件

**Comment by KFCFans** [comment]
不了解这个软件，无法解答。不过可能的方向是备份时类似进行了 JVM STOP-THE-WORLD 的操作。

**Comment by iamzzq** [comment]
已经定位到问题了，网盘软件RaiDrive会挂在一个EB大小的磁盘，powerjob会检测磁盘空间是否够用，应该是声明的long类型超出范围出错，导致误认为资源不可用，不进行通讯，目前我们把判断磁盘空间的判断注释了，已经好用，希望作者以后修复这个bug

**Comment by KFCFans** [comment]
可以提个 PR ，哈哈
