### ISSUE TITLE
后续版本更换网络框架后会支持

### ISSUE THREAD

**Issue by 991567775** [PowerJob/PowerJob#560]
后续版本更换网络框架后会支持

_Originally posted by @KFCFans in https://github.com/PowerJob/PowerJob/issues/502#issuecomment-1351609438_
            什么时候支持

**Comment by KFCFans** [comment]
之前内部讨论后，有小伙伴提出真支持公网调度后，会面临非常多的安全相关的问题。如果要引入公网调度，势必需要先强化安全方面的能力。
综合考虑之下，对于用户的公网调度诉求，可能还是用 VPN 等虚拟局域网方案实现更优雅。

同时通过用户反馈来看，目前大部分跨网络调度的诉求，都是本地测试相关。这块后续也会引入本地测试方案。
