### ISSUE TITLE
Worker心跳上报未正常发送到Server

### ISSUE THREAD

**Issue by stanvl** [PowerJob/PowerJob#563]
下载4.3.0版本源码，本地编译之后，在本地启动server，然后新建springboot工程，引入worker-starter，从日志中看，server和worker启动初始化都正常，但web-console中看不到实例，后debug worker的heartbeat过程，在server对应接口打断点，执行send后，server端点没响应

[WorkerHealthReporter] report health status,appId:7,appName:powerjob-test-samples,isOverload:false,maxLightweightTaskNum:1024,currentLightweightTaskNum:0,maxHeavyweightTaskNum:64,currentHeavyweightTaskNum:0

上述日志可以正常输出，找到VertxTransporter类，看到post方法，httpClientRequest.send执行后，server没反应，response回调中加了log打印statusCode也没输出
源码：
// 获取远程服务器的HTTP连接
        Future<HttpClientRequest> httpClientRequestFuture = httpClient.request(requestOptions);
        // 转换 -> 发送请求获取响应
        Future<HttpClientResponse> responseFuture = httpClientRequestFuture.compose(httpClientRequest -> httpClientRequest.send(JsonObject.mapFrom(request).toBuffer()));
        return responseFuture.compose(httpClientResponse -> {
            // throw exception
            final int statusCode = httpClientResponse.statusCode();
            if (statusCode != HttpResponseStatus.OK.code()) {
                // CompletableFuture.get() 时会传递抛出该异常
                throw new RemotingException(String.format("request [host:%s,port:%s,url:%s] failed, status: %d, msg: %s",
                       host, port, path, statusCode, httpClientResponse.statusMessage()
                        ));
            }
            return httpClientResponse.body().compose(x -> {

                if (clz == null) {
                    return Future.succeededFuture(null);
                }

                if (clz.equals(String.class)) {
                    return Future.succeededFuture((T) x.toString());
                }

                return Future.succeededFuture(x.toJsonObject().mapTo(clz));
            });
        }).toCompletionStage();

**Comment by KFCFans** [comment]
1. 检查 server 和 worker 是否在一个局域网内
2. 检查 server 和 worker 各种是否存在防火墙，阻断了请求

**Comment by stanvl** [comment]
> 1. 检查 server 和 worker 是否在一个局域网内
> 2. 检查 server 和 worker 各种是否存在防火墙，阻断了请求

server和worker跑在同一台机器上，不存在是否在同一局域网问题，防火墙也排查了，确定没问题，将心跳上报的josn体用postman手动发送到server对应接口，是OK的，那说明上面问题描述中的post方法实际上没有执行

**Comment by KFCFans** [comment]
检查下 worker 获取的地址，大概率是获取的地址不对。

如果怀疑是 powerjob 的问题，可以尝试更换为 AKKA 协议，如果2套协议都不行，肯定是本地环境导致的一些问题。

**Comment by c475570815** [comment]
@stanvl  问题解决了吗 老哥 我遇到的情况和你描述的差不多，该加启动参数的都加了一遍了，两种通信协议都不行

**Comment by c475570815** [comment]
已解决，应该是server和worker的版本不对应造成的，我的服务端开始使用docker部署,work引用的4.3.6版本的powerjob-worker-spring-boot-starter，服务端pull下来的镜像应该不是最新版，获取最新代码自行打包发布后worker可正常挂载，但是又出现[任务编辑报错问题](https://github.com/PowerJob/PowerJob/issues/665)，怀疑前端版本也有不对应情况，估计要单独去打包了。。。。
