### ISSUE TITLE
PowerJob 产品手册语雀在线版多语言接入有错误

### ISSUE THREAD

**Issue by QcoderWho** [PowerJob/PowerJob#573]
多语言接入中，心跳上报文档地址为/server/heartbeat，经查看worker源码发现实际地址为：/server/workerHeartbeat，处理在线日志和上报任务实例状态同样也是错误的

**Comment by KFCFans** [comment]
4.3.0 重构了网络层后，统一了这部分规范，文档没有及时更新，不好意思。

**Comment by KFCFans** [comment]
https://www.yuque.com/powerjob/guidence/multi_language

**Comment by KFCFans** [comment]
文档我更新了，有问题随时反馈～
