### ISSUE TITLE
作者大大近期还会有新版本发布么

### ISSUE THREAD

**Issue by sp56** [PowerJob/PowerJob#574]
## 如题

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by KFCFans** [comment]
择日不如撞日

https://github.com/PowerJob/PowerJob/releases/tag/v4.3.1
