### ISSUE TITLE
-Dpowerjob.network.local.address` 绑定ip之后异常

### ISSUE THREAD

**Issue by wangyongkang319** [PowerJob/PowerJob#579]
server端的服务器是由一台路由器映射的外网ip，在-Dpowerjob.network.local.address` 绑定路由器ip之后报了一个 nested exception is java.util.concurrent.ExecutionException: java.net.BindException: Cannot assign requested address异常，请问这样服务器之间应该怎么配置

**Comment by paddyxi** [comment]
> 
docker network_mode:host 
-Dpowerjob.network.local.address=192.xx.xx.xx
我在本地启动也遇到了这个问题 Cannot assign requested address

**Comment by KFCFans** [comment]
4.3.4 版本已正式支持外网访问，请查看 release 日志

**Comment by Code-WangShuai** [comment]
我本地连接服务器上的server 拿的还是docker的ip地址...

**Comment by Code-WangShuai** [comment]
> > 
> 
> docker network_mode:host -Dpowerjob.network.local.address=192.xx.xx.xx 我在本地启动也遇到了这个问题 Cannot assign requested address

处理好了吗?
