### ISSUE TITLE
应用接入Worker在启用测试模式后启动失败

### ISSUE THREAD

**Issue by tzengshinfu** [PowerJob/PowerJob#580]
您好:
反应一个奇怪的状况，
在现有SpringBoot应用中接入Worker，
并在配置文件启用测试模式
(powerjob.worker.enableTestMode=true)
应用启动会失败；
但改成powerjob.worker.enableTestMode=false
却会成功。

平台：
PowerJob Server-PowerJob(docker-compose版)
PowerJob Worker-SpringBoot 2.7.9
Worker OS-Ubuntu 20.04.5 LTS
Worker JVM-Java 17.0.5 Eclipse-Temurin

项目依赖：
https://gist.github.com/tzengshinfu/502992addb8ca743c7d3ebd813db85e0

配置文件：
https://gist.github.com/tzengshinfu/5b72a54acb8aaca615a99fec71a7e6b4

PowerJobConfig.java：
https://gist.github.com/tzengshinfu/ef6747fb905a465f0395f074bfd36d20

Log：
https://gist.github.com/tzengshinfu/327ce76b268722a812ac093ea9350ed0

**Comment by tzengshinfu** [comment]
将PowerJob Worker由4.3.0版升至4.3.1版，仍有此状况。

**Comment by KFCFans** [comment]
好的，问题已收到，我看看什么原因导致的。

**Comment by tzengshinfu** [comment]
> 好的，问题已收到，我看看什么原因导致的。

谢谢 @KFCFans ，我先把processor从业务应用分拆出来，这样两边都会单纯些，您可先排查其他问题。

**Comment by KFCFans** [comment]
一个小错误，已修复。如果急用的话，也可以自己先 merge 这个改动。
