### ISSUE TITLE
ProcessResult 执行结果是否可以返回中文

### ISSUE THREAD

**Issue by sae-shishunlu** [PowerJob/PowerJob#581]
## Question
参照官方文档 处理器（Processor）开发 进行测试，当我的返回结果是ProcessResult(true,"success")，一切正常；
但如果我的返回结果中的msg是中文时，例如ProcessResult(true,"成功")，状态会停留在 等待worker接收
![image](https://user-images.githubusercontent.com/107237687/224632857-878766e5-8a5b-4377-84b2-5f06c9ba6cda.png)
![image](https://user-images.githubusercontent.com/107237687/224633121-36375dbb-6864-4c2e-9afd-c7912020eb6d.png)
采用的版本是 4.3.1-bugfix

**Comment by KFCFans** [comment]
活久见。。。收到，我看下什么原因 =。=
