### ISSUE TITLE
Server接入Nacos注册和配置中心后，自动建表的前缀异常

### ISSUE THREAD

**Issue by WhirLpooLD4C** [PowerJob/PowerJob#584]
**Describe the bug**
Server启动后自动建表的前缀会加上null_

**To Reproduce**
1，Server引入Nacos做注册和配置中心
2，Server启动后自动建表的前缀会加上null_

**Expected behavior**
表前缀正常

**Environment**
 - PowerJob Version: 4.3.1
 - Java Version: JDK 8

**Screenshots**
![image](https://user-images.githubusercontent.com/127925729/225225078-44993582-d44b-469e-b3e2-ed9f2d2b131a.png)
相关配置：
![image](https://user-images.githubusercontent.com/127925729/225225351-ff1f3826-0a90-4c0c-a34a-583bd0a2c693.png)
bootstrap.properties:
![image](https://user-images.githubusercontent.com/127925729/225226192-4484666b-fc6e-4387-9fdf-21c82db6b8d0.png)
bootstrap-fat.properties
![image](https://user-images.githubusercontent.com/127925729/225225392-ae5273f3-844a-4831-a0e3-b245e0c758e2.png)
nacos:
![image](https://user-images.githubusercontent.com/127925729/225225995-cbc30e9f-76ed-43ea-8075-a95e947f488e.png)
![image](https://user-images.githubusercontent.com/127925729/225226053-d0751ba8-1651-4e17-abe9-98d0f56238e3.png)
![image](https://user-images.githubusercontent.com/127925729/225225871-cefa105a-c3d4-440d-93e2-146a1287529f.png)

**Comment by KFCFans** [comment]
新版本已发布，可以升级解决。
