### ISSUE TITLE
powerjob 无网场景无法启动

### ISSUE THREAD

**Issue by betwowt** [PowerJob/PowerJob#589]
**Is your feature request related to a problem? Please describe.**
官方提供的镜像 可以取消 钉钉通知吗，因为是无互联网场景，访问不到钉钉的服务器，导致服务端启动不起来

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KFCFans** [comment]
新增 SpringBoot 的参数 `--oms.alarm.ding.app-key=` 即可，该参数会将默认配置文件中的 app-key 置空，触发代码的跳过初始化逻辑
