### ISSUE TITLE
启动powerjob-server报错信息- 提示  'hibernate.dialect' not set

### ISSUE THREAD

**Issue by anjian8000** [PowerJob/PowerJob#590]
![image](https://user-images.githubusercontent.com/21167020/226100780-30e121d8-f2a4-43f0-bda0-99ade2ab5994.png)

![image](https://user-images.githubusercontent.com/21167020/226100804-09ec26fa-4daa-45b7-8d71-14388d1f6743.png)

启动powerjob-server报错信息

**Comment by KFCFans** [comment]
这个错误信息很明确了，数据库不允许连接。排查自己的数据库问题，看样子应该是mysql 没打开允许远程连接的配置。

**Comment by anjian8000** [comment]
好的，谢谢，已经处理好了；  进入mysql容器，将root账号    host地址改成%，程序就可以访问mysql服务了
