### ISSUE TITLE
server端网卡多IP下，work节点如何获取正确IP

### ISSUE THREAD

**Issue by 121812** [PowerJob/PowerJob#604]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by 121812** [comment]
您好，我这边启动了server端，在启动work时指定了server-address为server端ip和端口，启动过程中提示

Outbound message stream to [akka://oms-server@192.168.235.192:18221] failed. Restarting it. akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [akka://oms-server@192.168.235.192:18221] did not complete within 20000 ms

192.168.235.192:18221 此IP为server端的一个内网IP，18221为 server akka 配置端口
![image](https://user-images.githubusercontent.com/39209748/228804900-3412666d-dc88-4ad7-9bf4-43913927fb74.png)

请问如何让work端连接正确的server端IP

**Comment by TSYMQMYST** [comment]
+1
