### ISSUE TITLE
两台服务器上，一台部署了powerjob-server，另外一台部署客户端，两台都是用docker部署的其中客户端指定了host模式，但是客户端启动的时候注册powerjob的ip确实容器的ip导致任务调度不了，这个怎么解决？ 尝试了很多种方式，指定网卡与ip都试过了 还是容器的ip，服务注册到nacos中是10.120.3.4，但是powerjob显示ip为172.....

### ISSUE THREAD

**Issue by hojGit** [PowerJob/PowerJob#608]

**Comment by xuchuntao** [comment]
不正视这个问题，之前有人提过，非要说在一个网络环境，作者有考虑过power-server部署在云上或者其他K8S集群里面，我本地开发worker如何调试，如何连接？能不能看看xxl-job如何处理的，本来想用powerjob，但是这个都实现不了，也太不云原生了。。

**Comment by QZmp236478** [comment]
搭建起来各种网络问题，用起来还是很难，不知道有没有老哥上了生产的，自己去改源码，改了一块成功了另外一块又要改，太多需要改的了，不知道作者怎么安排的吧。

**Comment by hojGit** [comment]
已切换成xxl-job

**Comment by yuxianghao-hub** [comment]
容器里面跑真的各种网络问题,要不就是注册不上,要不就是注册上了任务下发不了,总是等待Worker接收任务也不知道是为啥,准备切XxlJob了

**Comment by AZI-D** [comment]
可以试试用域名的方式

**Comment by CrossIce** [comment]
试过在服务端hosts文件加入一个指向宿主机ip的假域名，客户端（hosts文件加指向服务端ip的假域名）注册的时候 用假域名指定server地址，能规避掉这个问题。

**Comment by hojGit** [comment]
> 试过在服务端hosts文件加入一个指向宿主机ip的假域名，客户端（hosts文件加指向服务端ip的假域名）注册的时候 用假域名指定server地址，能规避掉这个问题。

换xxljob 没这么多事情
