### ISSUE TITLE
我在虚拟机docker上运行了powerjob-server，本地运行了一个客户端。运行后服务端并没有显示客户端节点注册，这是因为不在一个局域网内吗？必须是同ip才能注册吗？

### ISSUE THREAD

**Issue by hojGit** [PowerJob/PowerJob#609]
![image](https://user-images.githubusercontent.com/61861182/230111779-da325b82-e63d-47dc-8e2e-f1d5392d8374.png)
![image](https://user-images.githubusercontent.com/61861182/230111571-17179750-faec-4eeb-99de-3c1b5e9796b8.png)
![image](https://user-images.githubusercontent.com/61861182/230111949-4ecc7453-3ea8-4fb3-9e81-ba145c57b18d.png)
![image](https://user-images.githubusercontent.com/61861182/230112086-c8cce119-a63b-4504-b0a9-978057f8bcb3.png)

**Comment by hojGit** [comment]
我在虚拟机上运行客户端，服务端就能正常显示注册信息了，这到底是啥原因？ 任务与服务端只能在一台设备上吗？

![image](https://user-images.githubusercontent.com/61861182/230118980-878505f6-0a5e-4252-b402-a541c78de1bd.png)
![image](https://user-images.githubusercontent.com/61861182/230119093-de2d1e7c-a4dc-4f36-8add-77a075009991.png)

**Comment by KFCFans** [comment]
是的，目前要求必须在同一个局域网段，和 dubbo 之类的中间件是一样的要求。否则无法相互通讯
