### ISSUE TITLE
为什么还会出现这个bug

### ISSUE THREAD

**Issue by Lifedom** [PowerJob/PowerJob#615]
![image](https://user-images.githubusercontent.com/19831175/232225981-c447ce11-039d-4a98-8e76-8cd1db62073d.png)

本机起server，局域网内其他机器跑samples看不到实例
本机起server，本机起samples+内网机器samples都不管用

用的最新版本的代码4.3.2

**Comment by KFCFans** [comment]
可以检查下IP获取是否正确。
