### ISSUE TITLE
worker无法注册到server

### ISSUE THREAD

**Issue by luoluo2001108** [PowerJob/PowerJob#623]
请问大佬：

可能是什么原因呢
![image](https://user-images.githubusercontent.com/58844075/233830604-69fde701-4185-4c04-982c-fe2057a170bb.png)

没有机器显示注册上。
进入 server这个容器里看时区不是中国上海的时区，现在的时间要+8小时

![image](https://user-images.githubusercontent.com/58844075/233830642-e4871c65-d72d-4517-a6c1-81a7b7d9e78d.png)

**Comment by rongyanjuren** [comment]
大佬问题解决了吗？我也遇到这个问题了，好几天了

**Comment by luoluo2001108** [comment]
> 解决了，是网络问题，启动server的时候要加上一个JVM参数 JVMOPTIONS: "-Dpowerjob.network.local.address=
就可以了，

**Comment by rongyanjuren** [comment]
还是不行，我用的powerjob版本是4.3.2，springboot版本是2.2.4.RELEASE，页面上一直不显示work的信息，
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/49813094/234193604-78256bc4-c5d1-42d8-aab1-417a3a1b9d29.png">

springboot版本换成2.7.4，页面可以发现work信息，但是work启动不起来，报空指针
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/49813094/234193519-89c1cd0e-50a3-4e44-868d-155042685a9f.png">

**Comment by luoluo2001108** [comment]
你可以试试官方的samples，看看能不能正常注册。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PowerJob/PowerJob"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 下午2:35
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [PowerJob/PowerJob] worker无法注册到server (Issue #623)





 
还是不行，我用的powerjob版本是4.3.2，springboot版本是2.2.4.RELEASE，页面上一直不显示work的信息，
 
 
springboot版本换成2.7.4，页面可以发现work信息，但是work启动不起来，报空指针

**Comment by liweib** [comment]
-Dpowerjob.network.local.address=xxxx  这个位置是填网卡吗，还是填ip地址

**Comment by luoluo2001108** [comment]
ip



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月26日(周三) 下午2:44
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [PowerJob/PowerJob] worker无法注册到server (Issue #623)




 
-Dpowerjob.network.local.address=xxxx  这个位置是填网卡吗，还是填ip地址

**Comment by liweib** [comment]
好的，感谢，感谢




Routine
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PowerJob/PowerJob"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月26日(星期三) 下午4:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PowerJob/PowerJob] worker无法注册到server (Issue #623)





 ip 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年4月26日(周三) 下午2:44 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题: Re: [PowerJob/PowerJob] worker无法注册到server (Issue #623) 
 
 
 
 
   
 -Dpowerjob.network.local.address=xxxx  这个位置是填网卡吗，还是填ip地址

**Comment by xiaodi-hub** [comment]
兄弟，在初始化worker的时候加上默认协议http，亲测有效！
    @Bean
    public PowerJobSpringWorker initPowerJobWorker(PowerJobProperties properties) throws Exception {
        // 1. 创建配置文件
        PowerJobWorkerConfig config = new PowerJobWorkerConfig();
        // 传输协议，新用户建议直接上 HTTP
        config.setProtocol(Protocol.HTTP);
        config.setPort(Integer.parseInt(properties.getPort()));
        config.setAppName(properties.getAppName());
        config.setServerAddress(handleAddressAndPort(properties));
        // 如果没有大型 Map/MapReduce 的需求，建议使用内存来加速计算
        config.setStoreStrategy(properties.getStoreStrategy());
        // 2. 创建 Worker 对象，设置配置文件（注意 Spring 用户需要使用 PowerJobSpringWorker，而不是 PowerJobWorker）
        PowerJobSpringWorker worker = new PowerJobSpringWorker(config);
        return worker;
    }
