### ISSUE TITLE
server模块升级到springboot 3

### ISSUE THREAD

**Issue by yhan219** [PowerJob/PowerJob#643]
**Is your feature request related to a problem? Please describe.**
如题，有时候需要集成server模块到内部，比如https://gitee.com/KFCFans/PowerJob/issues/I6H8JF 这个issue，现在业务版本是spring boot 3的，集成会失败
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KFCFans** [comment]
考虑到整体的维护成本，按我们的计划，2023年还是只维护 4.x 版本，语法级别 Java8，server 框架版本 SpringBoot 2.x。
预计 2024年开始切到 Java17 和 SpringBoot3。

**Comment by KFCFans** [comment]
具体的错误信息可以贴出来看看，看看有没有兼容方案

**Comment by yhan219** [comment]
不能集成的问题已经解决了

**Comment by yhan219** [comment]
不能集成的问题已经解决了

**Comment by lin3fei** [comment]
> 不能集成的问题已经解决了

怎么解决的？求指点。

我用的server-stater ，springboot3.2.0  报错为
org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [tech.powerjob.server.config.OmsEndpointConfigure] for bean with name 'omsEndpointConfigure' defined in URL [jar:file:/C:/Users/Administrator/.m2/repository/tech/powerjob/powerjob-server-starter/4.3.6/powerjob-server-starter-4.3.6.jar!/tech/powerjob/server/config/OmsEndpointConfigure.class]: problem with class file or dependent class

**Comment by yhan219** [comment]
指定父级的版本为2版本的，这个只能分开指定了。你可以看些ruoyi vue plus

**Comment by lin3fei** [comment]
> 指定父级的版本为2版本的，这个只能分开指定了。你可以看些ruoyi vue plus

非常感谢，我先用2，等更新了再改为3
