### ISSUE TITLE
定时任务一直打印WARN日志

### ISSUE THREAD

**Issue by ylhang** [PowerJob/PowerJob#657]
我WORK里配置CRON 0/30 * * * * ?，然后客户端每隔30秒就会打印下面的WARN日志（可能影响正常问题的排查），请问这个正常吗？

[TaskTracker-549900087350788160] remove TaskTracker,task status WORKER_PROCESS_SUCCESS,start time:1686882420010,end time:1686882420016,real cost:6,total time:13

**Comment by dudiao** [comment]
可以考虑正常执行成功的任务，这条日志改为info级别

**Comment by KFCFans** [comment]
4.3.7 发布。
