### ISSUE TITLE
新建任务后，对任务进行修改，一直提示alarm config 错误

### ISSUE THREAD

**Issue by hongmin118** [PowerJob/PowerJob#665]
powerjob4.3.3，两台server的mysql和mongo配置为同一套环境。

1、新建任务后，任务可正常执行，暂停任务，对任务进行修改，一直提示alarm config 错误。
2、暂停任务后，重新启动任务，提示alarm config 错误，但后台仍然在下发任务，并非100%重现。
3、复制新的任务，点击保存，提示alarm config 错误，无法复制。但刷新页面后，新的任务其实已生成。
![image](https://github.com/PowerJob/PowerJob/assets/797422/bcc74dee-5701-41d4-8d3e-7835316c5a63)

![image](https://github.com/PowerJob/PowerJob/assets/797422/3c15a541-c98d-4fc9-be07-93896e431aa8)

**Comment by KFCFans** [comment]
请确认前端版本是否匹配

**Comment by hongmin118** [comment]
重拉镜像，清空mysql后，恢复正常。

**Comment by c475570815** [comment]
我拉取了最新的PowerJob-Console 打包后任然有这个问题，看了下/job/save接口发现传入alarmConfig属性为
`{
          alertThreshold: undefined,
          statisticWindowLen: undefined,
          silenceWindowLen: undefined
  }`
  会出现上述问题，修改了前端代码alarmConfig传入null能正常保存
