### ISSUE TITLE
任务处理器是否能增加变量参数

### ISSUE THREAD

**Issue by Zjieke** [PowerJob/PowerJob#671]
任务处理器是否能增加变量参数
如：当前时间、当前日期等

**Comment by jjnnzb** [comment]
这个PowerJob本来就支持的呀。页面上可以设置任务参数，代码里面通过taskContext里面的jobParams可以拿到值；通过runJob的API，可以设置instanceParams。可以用JSON序列化参数，然后代码里面再反序列化回来，按参数跑业务。
