### ISSUE TITLE
[Bug] Failed to clear the alert configuration of the task

### ISSUE THREAD

**Issue by archibald-nice** [PowerJob/PowerJob#676]
**Describe the bug**
如果有一个任务已定时启动且配置了告警人员，如果想取消当前任务的所有告警人员，无法更新成功。

**To Reproduce**
先运行一个含有1个告警人员以上的任务，然后尝试清空该任务的告警人员。

**Expected behavior**
如果清空某个任务的告警人员，需通过判空校验并将 notifyUserIds 设为null。

**Environment**
 - PowerJob Version: [e.g. 4.3.3]
 - Java Version: [e.g. OpenJDK 8]
 - OS: [e.g. CentOS 7.9]

**Screenshots**
...

**Additional context**
我将提交PR

**Comment by KFCFans** [comment]
点赞👍

**Comment by KFCFans** [comment]
即将发布合并，感谢贡献！
