### ISSUE TITLE
任务超时后，不中断也不报错

### ISSUE THREAD

**Issue by hongmin118** [PowerJob/PowerJob#678]
V4.4.3
任务设置超时5000毫秒，代码中设置超时20000毫秒，单机调度，结果任务仍然能正常跑完，不中断任务且不报错。

![image](https://github.com/PowerJob/PowerJob/assets/797422/8b2f2b05-076a-4114-8d9c-50aff36c539b)

以下截图可明显看出，超时20秒后，第二条打印仍然被执行。
![image](https://github.com/PowerJob/PowerJob/assets/797422/44f4d7d7-e237-4ae2-88c7-b800cad83e55)

**Comment by KFCFans** [comment]
感谢反馈，问题已定位，4.3.4 版本会修复。
