### ISSUE TITLE
在使用ShellProcessor时，成功执行目标脚本成功，打印日志时触发随机异常

### ISSUE THREAD

**Issue by studyAction** [PowerJob/PowerJob#682]
在使用ShellProcessor时，可以正常执行目标脚本，执行到copyStream() 时，对应到tech.powerjob.official.processors.impl.script.AbstractScriptProcessor第85行代码，会出现随机的异常`Java.io.IOException: Stream closed`，debug模式加断点会再次触发该异常。

**Expected behavior**
copyStream()中的readLine()方法，该处异常理论上已经被捕获，不应该被显式地抛出

**Environment**
 - PowerJob Version: [4.3.3]
 - Java Version: [OpenJDK 8]
 - OS: [win11]

**Screenshots**
![image](https://github.com/PowerJob/PowerJob/assets/32919017/9a157b4d-1d59-4cca-9416-ab8e658226f9)
![image](https://github.com/PowerJob/PowerJob/assets/32919017/8c863282-0c40-40c1-ac12-9eddeac4f570)
![image](https://github.com/PowerJob/PowerJob/assets/32919017/7ea6da75-6729-4438-acba-6576f32a6e18)

**Comment by dudiao** [comment]
好像是流重复关闭了，我复现一下

**Comment by dudiao** [comment]
debug 执行时，有可能脚本已经执行完，还尝试从 inputStream 中读取数据，才会出现。在下个版本会修复

**Comment by studyAction** [comment]
原来是这个原因。
