### ISSUE TITLE
本地运行时日志local_instance_log存在哪里

### ISSUE THREAD

**Issue by muuu100** [PowerJob/PowerJob#684]
本地运行时日志local_instance_log存在哪里，在连接的数据库中找不到。local_instance_log有什么作用，如何关闭记录本地运行时日志

**Comment by KFCFans** [comment]
1. server 本地的 H2 数据库
2. local_instance_log 为 OmsLogger 生成的在线日志数据，写库后方便按时间重排序
3. 在代码中不使用 OmsLogger 或在控制台中关闭在线日志即可
