### ISSUE TITLE
使用Cron配置秒级的任务，不按照时间执行

### ISSUE THREAD

**Issue by qingwz1994** [PowerJob/PowerJob#691]
## 使用cron配置不按照固定时间执行

请教一下：
使用cron配置(0/2 * * * * ?),单机执行，内建方式，并不是2秒执行一次，一般是在间隔15秒才会执行一次），是不支持太高的吗？使用固定频率可以按时执行。这是什么原因

**Comment by KFCFans** [comment]
处于性能考虑 cron 目前强制设置了 15S 一次的调度频率，如果低于这个值，建议直接使用秒级任务。
