### ISSUE TITLE
关于MapProcessor任务分发机制

### ISSUE THREAD

**Issue by pacoolin** [PowerJob/PowerJob#693]
您好，
现象：MapProcessor接口中提供了map方法，实现了MapProcessor后执行任务分发需要手动调用map方法。
分析和建议：这个机制看上去把业务逻辑和框架逻辑耦合了，建议是否能把map的调用放在框架调度逻辑中并提供任务拆分的接口，process接口方法只做业务逻辑处理，这样在开发人员不用关注处理任务类型和调用分发，整个分发调度逻辑就是透明的

**Comment by KFCFans** [comment]
从设计上讲你描述的方式确实更加解耦。
但实际开发过程中，从我的视角看，一般情况下子任务的拆解本身也是业务逻辑的一部分。不同的任务一般都会有自己的拆解逻辑和处理逻辑，如果分拆接口和实现，可能反而会导致开发成本的上升。

你可以举个更具体的、分拆后有明显受益的例子让我更有体感一些，哈哈～

**Comment by KFCFans** [comment]
嗯，其实我一开始也想过设计这样的接口，应该和你想象的一样，分解出 Map 、 Process 和 reduce 3 个过程：
```java
List<?> map(TaskContext ctx);

ProcessResult process(TaskContext context);

ProcessResult reduce(TaskContext context, List<TaskResult> taskResults)

```

但是这组接口带来的问题是他强制限定了 2 级 的 map，无法实现 map -> process -> map -> process 这种多级嵌套的功能。

因此最终设计成了 map 作为一个成员方法供开发者自由调用的形式，来保证灵活性。

**Comment by KFCFans** [comment]
这个其实是不是自己在业务层面也可以封装下🤔️，搞个抽象类之类的应该可以🤔️

**Comment by chuanqicc0430** [comment]
input->map->shuffle->reduce->summary
分成这几个阶段，其中shuffle和reduce节点是可跳过的，这样应该能满足绝大部分业务场景，并且能保证框架整洁，降低耦合
