### ISSUE TITLE
升级 V4.3.3 版本后邮件报警失效，回退版本正常

### ISSUE THREAD

**Issue by lulu-0827** [PowerJob/PowerJob#694]
使用 v4.2.0 版本邮件报警一直正常，最近升级版本之后发现告警无法推送。日志没有任何异常错误，回退版本后邮件通知又正常了

**Comment by KFCFans** [comment]
为啥 close 了？
是否确认存在问题？

**Comment by lulu-0827** [comment]
初步排查是测试环境存在多个 server 端， 本机work指定本机 server（v4.3.3）注册后选举为其他 server（版本一致v4.3.3 ，都使用同一个库，且有相同 work 注册在选举的 server上）。本机 severe能正常启动任务，本机work 端日志也正常，但本机sever InstanceManager#processFinishedInstance 断点无法进入，后单独切换至另一数据库启动后正常发起邮件告警，因部署生产后无此情况，后续没再排查。
