### ISSUE TITLE
点击运行报you need to use mongoDB to store the past logs.

### ISSUE THREAD

**Issue by shenle16488** [PowerJob/PowerJob#697]
## Question
issue全部看了，没有相关内容，我按照官网新建了一个单机任务，点击运行然后失败了，我看日志是：
SYSTEM: There is no local log for this task now, you need to use mongoDB to store the past logs.

相关配置是这样的：
--- # powerjob 配置
powerjob:
  worker:
    # 如何开启调度中心请查看文档教程
    enabled: false
    # 需要先在 powerjob 登录页执行应用注册后才能使用
    app-name: shenle
    enable-test-mode: false
    max-appended-wf-context-length: 4096
    max-result-length: 4096
    # 28080 端口 随着主应用端口飘逸 避免集群冲突
    port: 2${server.port}
    protocol: http
    server-address: 127.0.0.1:7700
    store-strategy: disk

这个问题看了好几天了，不知道咋回事，大哥们帮帮忙

**Comment by KFCFans** [comment]
1.  需要保证 worker 和 server 在同一个局域网内
2. 查看控制台的任务状态和任务详情中的结果（日志是 OmsLogger API 的输出，你这种情况可以先忽略）。如果状态一直是等待结果，那大概率是任务没被派发到 server 或者结果没回传会 server，应该就是网络问题。如果任务马上失败了，可以看下详情中的结果信息。里面应该会有错误提示。
3. 多看日志，日志一定会告诉你原因。
