### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by psmoros** [PowerJob/PowerJob#698]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@da22le) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by KFCFans** [comment]
Thank you for your suggestion, I will attach SECURITY.md to the next release. Until then information can be sent via email at tengjiqi@gmail.com.

In addition, I am aware of some current security issues with PowerJob and strongly discourage deployment over the Internet until a new user and permission version is released.

**Comment by KFCFans** [comment]
since 4.3.4
