### ISSUE TITLE
希望可以更新一下 samples 的最新注解相关用法

### ISSUE THREAD

**Issue by JavaLionLi** [PowerJob/PowerJob#700]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KFCFans** [comment]
<img width="1545" alt="image" src="https://github.com/PowerJob/PowerJob/assets/9402086/9c50e600-7144-4c07-bc48-aa0ea4a6bbcf">

快速开始章节已更新
