### ISSUE TITLE
执行日志无法观看 提示需要安装mongodb 这个是不是过于严格了 本身日志已经生成出来了 没必要限制吧 是否可以增加执行日志清理功能

### ISSUE THREAD

**Issue by JavaLionLi** [PowerJob/PowerJob#701]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KFCFans** [comment]
4.3.4 已支持多种日志存储机制。
清理功能本身是自带的，不过某些存储介质（如 OSS）一般都自带了生命周期管理，就不需要服务端单独处理了。
