### ISSUE TITLE
server未找到无法启动worker 希望可以启动

### ISSUE THREAD

**Issue by JavaLionLi** [PowerJob/PowerJob#702]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KFCFans** [comment]
<img width="1179" alt="image" src="https://github.com/PowerJob/PowerJob/assets/9402086/31411a2d-5087-4066-928a-29b937915daa">

现有功能，传递参数标识为测试模式后，不会强校验 server 是否可用。

**Comment by KFCFans** [comment]
Java 配置：tech.powerjob.worker.common.PowerJobWorkerConfig#enableTestMode
SpringBoot 配置：powerjob.worker.enable-test-mode
