### ISSUE TITLE
webdav导致内存溢出,worker无法调用

### ISSUE THREAD

**Issue by zhihui1999** [PowerJob/PowerJob#720]
**Describe the bug**
碰到webdav会出现内存溢出,导致磁盘总空间出现负值

**To Reproduce**
使用alist与raiDrive配置阿里云盘的盘符

**Expected behavior**
应当不出现负数

**Environment**
 - PowerJob Version: 4.3.5
 - Java Version: java 8
 - OS: windows 11

**Screenshots**
配置了webdav
![GL$P}M{@6H)2QYT 326OGN](https://github.com/PowerJob/PowerJob/assets/36041260/b22f75bc-579a-4d4a-a75b-280451b53ada)
![1@GO` HLW{(_7H}9ZHCE3J](https://github.com/PowerJob/PowerJob/assets/36041260/15aba1cf-7d10-4a0a-81ef-4ac10457496c)
![Snipaste_2023-08-24_10-40-24](https://github.com/PowerJob/PowerJob/assets/36041260/583cb235-58c6-4c8a-927c-8ff16a1b613e)

**Additional context**
解决方法: 在raiDrive中配置容量即可,不需要更改代码,但对于初次使用的开发者来讲,会出现不必要的问题,要么修改此处代码,要么添加至文档中

**Comment by KFCFans** [comment]
since 4.3.6
