### ISSUE TITLE
本地IDEA无法和阿里云服务器的server进行通信

### ISSUE THREAD

**Issue by zhoushuai1119** [PowerJob/PowerJob#723]
## Question
我部署的powerjob-server部署在阿里云的服务器，通过-Dpowerjob.network.external.port绑定的外网IP，否则自动获取的是阿里云内网IP地址。powerjob-worker是我在本地idea启动的，注册的是我本地机器的内网IP地址。
我在本地开发，阿里云服务器无法和我本地的内网IP进行通信，这种情况我应该怎么办呢？

**Comment by zhihui1999** [comment]
内网穿透了解一下

**Comment by KFCFans** [comment]
楼上正解。PowerJob 强依赖双向通讯，无法直接双向通讯的场景，请自行先建立虚拟网络。
