### ISSUE TITLE
java.lang.NoClassDefFoundError: io/netty/handler/codec/compression/StandardCompressionOptions

### ISSUE THREAD

**Issue by shijiannihao** [PowerJob/PowerJob#724]
java.lang.NoClassDefFoundError: io/netty/handler/codec/compression/StandardCompressionOptions  这个类都没看到在nettyjar包里面

**Comment by KFCFans** [comment]
可能需要排下包。如果包冲突严重的话，可以考虑切换为 akka 协议。
