### ISSUE TITLE
大佬，有相关文档介绍powerjob-server怎么集群部署，以及在集群的模式下，怎么确保同一个job同一时间只会触发一次？

### ISSUE THREAD

**Issue by zengchangjin** [PowerJob/PowerJob#756]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by zengchangjin** [comment]
我简单看了里面的源码，发现最终交给HashedWheelTimer的线程池触发，如果同一时间，需要触发的任务很多的话，线程池就会被填满，这样就导致任务延迟触发。

**Comment by zongwei007** [comment]
可参考 https://www.yuque.com/powerjob/column/nzgkyb

**Comment by KFCFans** [comment]
https://www.yuque.com/powerjob/guidence/deploy_server

**Comment by Ratsea** [comment]
依旧没找到 server的集群部署方式
