### ISSUE TITLE
状态检查的线程出现异常后，进入死循环，30s，刷出来1200M磁盘日志【磁盘空间占用飙升】

### ISSUE THREAD

**Issue by InnerPeaceD-git** [PowerJob/PowerJob#769]
**Describe the bug**
状态检查的线程出现异常后，进入死循环，30s，刷出来1200M磁盘日志

**Environment**
 - PowerJob Version: [4.3.5]
 - Java Version: [OpenJDK 8]

**Screenshots**
![powerjob-issue](https://github.com/PowerJob/PowerJob/assets/56728242/c5bd6342-2143-45f7-98be-ec3ffb40c3c6)

**Fix Approach Suggest**
在76行，打印异常之前也进行延迟处理（参考71行）

**Comment by KFCFans** [comment]
感谢反馈，将于 4.3.7 版本修复
