### ISSUE TITLE
方法使用@PowerJobHandler定义的处理器加上自己的自定义注解会出现错误，是需要增加哪些配置？

### ISSUE THREAD

**Issue by Zhanrunfeng** [PowerJob/PowerJob#770]
## Question

powerjob v4.3.6版本
在方法上使用@PowerJobHandler注解和自己的自定义注解提示错误：

init TaskTracker failed, reason: tech.powerjob.common.exception.PowerJobException: fetch Processor failed, please check your processorType and processorInfo config
如果在方法上只使用@PowerJobHandler注解，那这个处理器又可以执行成功，是缺失哪里的配置了，在官方文档好像没有找到，可能是看漏也有可能。

**Comment by zhangxiang0907** [comment]
我也遇到了同样的问题，请问你是如何解决的？
我debug跟了下，应该是CGLib代理对象拿不到该注解
![image](https://github.com/PowerJob/PowerJob/assets/50012020/6a39a25c-a072-429a-b32f-d927ccb66c3e)

**Comment by KFCFans** [comment]
感谢返回，4.3.7 版本会修复

**Comment by somnmos** [comment]
为什么4.3.9依然存在这样的问题？

**Comment by somnmos** [comment]
<img width="1334" alt="image" src="https://github.com/user-attachments/assets/9a369956-5ddd-4ea8-9005-a28c86a35fa3">
我们使用4.3.9依然存在这个问题，请问是什么原因？
