### ISSUE TITLE
普通任务实例只显示当天的执行记录，之前执行过的

### ISSUE THREAD

**Issue by chaiduolai** [PowerJob/PowerJob#776]
我在启动了PowerJob的时候，发现每天执行的普通任务实例列表只显示当天，以前执行的记录都会自动清除，不清楚是在哪配置还是BUG
![WX20231106-182418@2x](https://github.com/PowerJob/PowerJob/assets/45263891/ed75b392-4ccc-4cf3-8825-882e54b9ddc4)

**Comment by KFCFans** [comment]
<img width="1547" alt="image" src="https://github.com/PowerJob/PowerJob/assets/9402086/79e3875e-ba8d-49d9-8d7c-0abaf04dec1c">

**Comment by KFCFans** [comment]
https://www.yuque.com/powerjob/guidence/deploy_server
