### ISSUE TITLE
H2 数据库2.1.214 存在已知漏洞

### ISSUE THREAD

**Issue by zhangxiang0907** [PowerJob/PowerJob#777]
## Question

blackduck 扫描 显示 h2 当前版本 2.1.214 存在已知漏洞，建议升级到2.2.224

![image](https://github.com/PowerJob/PowerJob/assets/50012020/6ab87c9c-6ad7-4ef5-aa1a-6916bee2e288)
![image](https://github.com/PowerJob/PowerJob/assets/50012020/64235de2-b2f2-4b54-841a-d94065ebeb97)

**Comment by KFCFans** [comment]
4.3.7 版本会升级。

**Comment by KFCFans** [comment]
感谢反馈。
