### ISSUE TITLE
翻页后搜索关键字有bug

### ISSUE THREAD

**Issue by delicious111** [PowerJob/PowerJob#778]
**Describe the bug**
前端界面在翻页到第二页后，指定关键字搜索，会无法查询到指定的定时任务

问题原因，前端代码翻页index赋值有问题，当翻页后再点击搜索index会进行传值。且清空后重新点击搜索，index还是不变。导致数据展示不对

**Comment by delicious111** [comment]
而且更多操作的下拉按钮，点击字的空白位置，没反应，后来才反应过来应该点击字体上。不算bug算优化建议吧。

**Comment by KFCFans** [comment]
第一个问题属于，看上去确实是 bug，但从前端代码的角度讲也算比较合理...

这些前端的细枝末节问题，后续前端重构的时候再统一处理吧，哈哈
