### ISSUE TITLE
请问有没有微服务集成server启动的方案呢？

### ISSUE THREAD

**Issue by answerJerry** [PowerJob/PowerJob#779]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details. 

请问有没有微服务集成server启动的方案呢？
4.3.3版本，使用jar包启动的server， 在项目里集成了worker， 但是连不上server。感觉是局域网的问题，在集成server时遇到问题，请问大佬们有没有在微服务中集成server的案例参考，谢谢。

**Comment by linwei-scholar** [comment]
server就让它保持单一职责吧，毕竟它是负责整个调度的核心，多IO，存储都有自己的要求，不建议跟业务微服务绑定在一块，你甚至可以将server这个服务注册到你的注册中心去
