### ISSUE TITLE
请问是否支持多数据中心集群部署模式

### ISSUE THREAD

**Issue by yanwei7011** [PowerJob/PowerJob#781]
## Question

请问是否支持下图双机房集群部署模式？ AB两个机房局域网不互通， 但是Server都连接同一个数据库。这种模式下B机房的Worker无法连接到A机房的Server， 这样不能做到同一个分组所有Worker都连接同一个Server。 这样是否有问题？

![image](https://github.com/PowerJob/PowerJob/assets/48727081/5e9acd60-dda3-48e1-b7e0-5ea357191f81)

**Comment by Raxukl** [comment]
同问

**Comment by KFCFans** [comment]
网络不互通肯定是做不到的。

不过我更好奇具体的需求是什么，可以详细描述下需求，可能有其他的解决方案。
