### ISSUE TITLE
任务机器参数配置动态设置

### ISSUE THREAD

**Issue by lehuqizhong** [PowerJob/PowerJob#784]
任务机器参数配置能否动态设置,有这样一种情况，任务的执行配置等其他的都一样，但是需要根据不同输入参数（调用一个exe，exe路径和执行参数都是传进去的，不同执行exe所需要的资源不一样 需要根据输入去动态配置）去限制任务允许运行的机器CPU核心、内存等参数。应该不需要每次都去添加一个任务吧？，希望是能复用配置，动态修改过滤参数。还有种情况就是这个任务被配置到流程里去了，如果每次都去新建任务，流程也是需要每次新增的吧？其实可以复用，就是部分参数不一致(机器配置过滤)

**Comment by KFCFans** [comment]
<img width="977" alt="image" src="https://github.com/PowerJob/PowerJob/assets/9402086/bab53b18-0020-4452-bea0-0725a6c5410d">

**Comment by KFCFans** [comment]
设计的时候就考虑到了。你在 server 对这个接口做一个自己的实现即可。
`tech.powerjob.server.remote.worker.filter.WorkerFilter`
