### ISSUE TITLE
请教：调度器重启，错过的任务如何处理

### ISSUE THREAD

**Issue by fm2022aa** [PowerJob/PowerJob#791]
假设一个任务每分钟执行一次且下次执行时间是20:00:00, 在这之前调度器如果挂了，调度器到21:00:00才启动，那这个任务20-21之间的任务会重新处理不

**Comment by XiaoQiTong** [comment]
会重新处理吗老哥

**Comment by fm2022aa** [comment]
会的，处理一次，然后继续下一个



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月10日(周日) 上午9:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [PowerJob/PowerJob] 请教：调度器重启，错过的任务如何处理 (Issue #791)




 
会重新处理吗老哥
