### ISSUE TITLE
fetch Processor failed, please check your processorType and processorInfo config 

### ISSUE THREAD

**Issue by thyy** [PowerJob/PowerJob#792]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details. 

配置任务时候使用全限定类名方法，报找不到处理类的错误fetch Processor failed, please check your processorType and processorInfo config 

使用全限定类名方法的话，该方法必须放在work中，才能扫描的到？ 全限定类名方法可以放哪些地方？

**Comment by kkrgwbj** [comment]
高版本bug,需要你指定一个 spring处理器类型才可以
 config.setProcessorFactoryList(Arrays.asList(new BuiltInSpringProcessorFactory(applicationContext)));

**Comment by KFCFans** [comment]
哈哈，这个不是 bug，是特性。
PowerJob worker 本身和 Spring 完全解耦了，Spring 环境手动代码初始化的话，需要使用 `tech.powerjob.worker.PowerJobSpringWorker` 而不是 `tech.powerjob.worker.PowerJobWorker`
