### ISSUE TITLE
quarkus  demo  

### ISSUE THREAD

**Issue by KricYi** [PowerJob/PowerJob#793]
application.properties：
powerjob.server.address=${POWERJOB_SERVER_ADDRESS:localhost:7700}
powerjob.worker.appName=${POWERJOB_WORKER_APP_NAME}
powerjob.worker.port=${POWERJOB_WORKER_PORT:27777}
powerjob.worker.storeStrategy=${POWERJOB_WORKER_STORE_STRATEGY:DISK}
powerjob.worker.protocol=${POWERJOB_WORKER_PROTOCOL:HTTP}

@ApplicationScoped
public class ApplicationLifeCycle {

@ConfigProperty(name = "powerjob.worker.port")
Integer port;
@ConfigProperty(name = "powerjob.worker.appName")
String appName;
@ConfigProperty(name = "powerjob.server.address")
String serverAddress;
@ConfigProperty(name = "powerjob.worker.storeStrategy")
String storeStrategy;
@ConfigProperty(name = "powerjob.worker.protocol")
String protocol;
@Inject
PowerJobProcessorFactory powerJobProcessorFactory;

void onStart(@Observes StartupEvent ev) throws Exception {

    // 1. 创建配置文件
    PowerJobWorkerConfig config = new PowerJobWorkerConfig();
    config.setPort(port);
    config.setAppName(appName);
    config.setServerAddress(Arrays.stream(serverAddress.split(",")).toList());
    // 如果没有大型 Map/MapReduce 的需求，建议使用内存来加速计算
    config.setStoreStrategy(StoreStrategy.valueOf(storeStrategy));
    config.setProtocol(Protocol.valueOf(protocol));
    config.setProcessorFactoryList(Collections.singletonList(powerJobProcessorFactory));
    new PowerJobWorker(config).init();
}

}

@Dependent
public class PowerJobClientConfig {

@ConfigProperty(name = "powerjob.server.address")
String serverAddress;
@ConfigProperty(name = "powerjob.worker.appName")
String appName;

@ConfigProperty(name = "powerjob.client.password")
String password;

@Produces
@DefaultBean
public PowerJobClient initPowerJobClient() {
    return new PowerJobClient(Arrays.stream(serverAddress.split(",")).toList(), appName, password);
}
}
@ApplicationScoped
public class PowerJobProcessorFactory implements ProcessorFactory {
@OverRide
public Set supportTypes() {
return Set.of(ProcessorType.BUILT_IN.name());
}

@Inject
@All
List<BasicProcessor> processors;

@Override
public ProcessorBean build(ProcessorDefinition processorDefinition) {
    String className = processorDefinition.getProcessorInfo() ;
    try {
        BasicProcessor basicProcessor = processors.stream().filter(processor -> processor.getClass().getName().startsWith(className)).findFirst().orElseThrow(() -> new RuntimeException("not found processor"));
        return new ProcessorBean()
                .setProcessor(basicProcessor)
                .setClassLoader(basicProcessor.getClass().getClassLoader());
    } catch (Exception e) {
        Log.warn("[ProcessorFactory] load local Processor(className = {}) failed.", className, e);
    }
    return null;
}
}

**Comment by KricYi** [comment]
目前遇到一个问题，任务执行成功后，状态一直是进行中，已经return new ProcessResult(true, "success");，还是进行中。目前没有找到原因

**Comment by KricYi** [comment]
由于我们的主项目要打native，有大佬成功的没

**Comment by KFCFans** [comment]
> 目前遇到一个问题，任务执行成功后，状态一直是进行中，已经return new ProcessResult(true, "success");，还是进行中。目前没有找到原因

worker 回传执行状态失败了，可以检查下 worker 的日志，理论上应该有请求失败的相关 log。

**Comment by KFCFans** [comment]
native 的话，server 就按 SpringBoot 的方式去打，worker 被集成，原来项目怎么打还是怎么打

**Comment by KricYi** [comment]
> native 的话，server 就按 SpringBoot 的方式去打，worker 被集成，原来项目怎么打还是怎么打

反射有问题，还有fastjson。这个我自己想办法处理。

**Comment by KricYi** [comment]
> > 目前遇到一个问题，任务执行成功后，状态一直是进行中，已经return new ProcessResult(true, "success");，还是进行中。目前没有找到原因
> 
> worker 回传执行状态失败了，可以检查下 worker 的日志，理论上应该有请求失败的相关 log。

instance_info表的status为3，result为worker report timeout, maybe TaskTracker down。
日志开了debug，没有任何异常及警告。

**Comment by KricYi** [comment]
> > 目前遇到一个问题，任务执行成功后，状态一直是进行中，已经return new ProcessResult(true, "success");，还是进行中。目前没有找到原因
> 
> worker 回传执行状态失败了，可以检查下 worker 的日志，理论上应该有请求失败的相关 log。

你好，work端的，TaskTrackerActor.onReceiveProcessorReportTaskStatusReq 结果状态是5。 想问下服务端的状态更新是那个方法实现的？

**Comment by wingwing2005** [comment]
@KricYi，请问集成 worker 是如何支持 native？

**Comment by KricYi** [comment]
> @KricYi，请问集成 worker 是如何支持 native？目前 h2 可以依靠 quarkus 自己的 driver解决，但是 okhttp3 的版本太低 3.x，还有 HikariCP 这两个如何处理。

后面用xxl-job了。  https://github.com/KricYi/xxl-job
