### ISSUE TITLE
求官方一份离线文档，可pdf只可查阅等

### ISSUE THREAD

**Issue by atom0122** [PowerJob/PowerJob#795]
因环境需要，无法连接网络，但是又想使用powerjob，故求一份离线文档，感谢！

**Comment by H-TWINKLE** [comment]
同求

**Comment by KFCFans** [comment]
[PowerJob 产品手册_v4.3.6.pdf](https://github.com/PowerJob/PowerJob/files/14203547/PowerJob._v4.3.6.pdf)

**Comment by KFCFans** [comment]
文件有点大，GitHub 下不下来的话，可以去这里下载：
https://www.yuque.com/powerjob/guidence/others
