### ISSUE TITLE
mongodbji集群怎么配置

### ISSUE THREAD

**Issue by zhangZuCan** [PowerJob/PowerJob#796]
想问问大家怎么配置mongodb集群

**Comment by KFCFans** [comment]
https://www.yuque.com/powerjob/guidence/deploy_server#AI8M1

**Comment by KFCFans** [comment]
<img width="787" alt="image" src="https://github.com/PowerJob/PowerJob/assets/9402086/3b3dc187-3d99-4422-9451-e2958f62f288">
