### ISSUE TITLE
max open files

### ISSUE THREAD

**Issue by java-liu** [PowerJob/PowerJob#799]
## Question

今天使用,
![WechatIMG537](https://github.com/PowerJob/PowerJob/assets/21325318/94107fb0-310d-47d3-a52a-cdb3740e0388)
一直报错,提示达到max open files,想请问下,日志文件的句柄不会自动释放嘛?目前使用的是 mysql 数据库,没用 mongo,每日任务调度在百万上下.

**Comment by yuhan0501** [comment]
#807

**Comment by KFCFans** [comment]
4.3.7 版本已修复
