### ISSUE TITLE
server创建的openapi任务，需要主要触发一次，worker能否在程序重启或者启动时候检测到当前ip存在任务需要执行就立刻执行任务，不用再去server页面再点击一次按钮

### ISSUE THREAD

**Issue by H-TWINKLE** [PowerJob/PowerJob#800]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KFCFans** [comment]
感觉自动触发可能带来的歧义更大，这个特性暂时就先不考虑了。

可以自己考虑用 OpenAPI 实现，worker 启动时调用 runJob 运行任务，应该也能达到一样的效果。
