### ISSUE TITLE
运行任务一直显示	‘等待Worker接收’，这是什么情况呢？

### ISSUE THREAD

**Issue by 1440865373** [PowerJob/PowerJob#806]
## Question
 我机器地址指定的的首页机器地址，SpringBean名称#方法名这样配置的。
一直显示：
任务实例 ID:620973133326713280
状态:等待Worker接收
运行次数:0
TaskTracker 地址:172.17.0.2:27777
预计执行时间:2023-12-29 13:25:32
开始时间:2023-12-29 14:06:07
结束时间:N/A
节点参数:fsd
任务实例参数:
任务结果:
但是我查看work都没有其他任务执行，不知道什么原因，就是接收不到

**Comment by DxForestdeer** [comment]
请问这个问题是如何解决的啊

**Comment by MarvinYu** [comment]
这就很尴尬了~~

**Comment by MarvinYu** [comment]
> 请问这个问题是如何解决的啊

可以排查是否应用服务是否打开了27777端口
