### ISSUE TITLE
email未填写导致告警报异常

### ISSUE THREAD

**Issue by lvhjean** [PowerJob/PowerJob#808]
当录入“报警用户”存在email没有填写的 情况；
且我们任务中使用了此人，会导致后端报错：
 t.p.s.e.d.alarm.impl.MailAlarmService    : [MailAlarmService] send mail failed, reason is Could not parse mail; nested exception is javax.mail.internet.AddressException: Illegal address in string ``''

**Comment by KFCFans** [comment]
感谢发现问题。pr 将于 4.3.7 版本合并。
