### ISSUE TITLE
目前web页面可以设置超级管理员么，比如超级管理员可以查看所有的命名空间下的任务，如果有怎么配置，谢谢

### ISSUE THREAD

**Issue by cuixingzheng** [PowerJob/PowerJob#809]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KFCFans** [comment]
下个大版本（5.x）支持，2月份会发布

**Comment by KFCFans** [comment]
https://github.com/PowerJob/PowerJob/releases/tag/v5.0.0-beta

5.0.0 版本 beta 中，任何问题欢迎及时反馈。
