### ISSUE TITLE
serve和worker的protocol协议是否需要保持一致

### ISSUE THREAD

**Issue by linwei-scholar** [PowerJob/PowerJob#813]
## serve和worker的protocol协议是否需要保持一致

- serve version: 4.3.5
- worker version: 4.3.5

下载了官方源码，Serve端 `oms.transporter.main.protocol=HTTP` ，woker的配置是`powerjob.worker.protocol=http` , 因为没有深入源码，不太了解这种协议是否兼容，即：
- 问题1：`serve`和`worker`的通信协议是否可以不同，比如`serve`使用`HTTP`，`worker`使用`AKKA`，还是必须要保持`serve，worker`协议一致；
- 问题2：因为`AKKA`，`HTTP`使用的端口不同，所以如果使用了`http`协议，那么`AKKA`的端口是否可以关闭？

**Comment by linwei-scholar** [comment]
仔细看了一遍官网上的文档，没找到相关的说明，另外`V4.*`版本相对`V3.*` 变化很大，期待Author能否继续出一些原理解析的文章

**Comment by KFCFans** [comment]
1. 没关系，都是 http，大小写不敏感，内部统一转换的。
2. 可以，废弃协议端口都可以关闭。不过要注意 server 与 server 之间自己也有个通讯协议端口，确认没用到的端口，关闭即可。

3. 有空会出，哈哈。
