### ISSUE TITLE
从Quartz迁移到PowerJob后重复执行

### ISSUE THREAD

**Issue by gmm1126** [PowerJob/PowerJob#815]
环境：worker有两个，版本是4.2.0。

我最近将quartz的任务迁移到powerJob，迁移的方式是从quartz中读取任务，然后通过OpenApi的方式设置进powerJob。

就在迁移完成启动业务的服务后，会出现固定频率的任务偶发性执行多次。可以看到日志receive expired或者receive invalid task status report。

想要了解下，tech.powerjob.worker.core.tracker.task.TaskTracker#updateTaskStatus的作用，这两个是导致重复执行的关键原因吗？其他可能的原因？
<img width="1535" alt="Snipaste_2024-01-11_17-02-30" src="https://github.com/PowerJob/PowerJob/assets/66758513/5068217d-1b4f-49b0-90b9-f355edb07369">

**Comment by KFCFans** [comment]
分布式环境中，网络等问题导致执行结果未及时被回收是可能存在重复执行的情况。
PowerJob 目前的策略是至少执行一次，如果有严格的唯一执行需求，需要在业务层面自行实现。
