### ISSUE TITLE
微服务内worker启动后无法注册到power job server 所有包依赖冲突都已经处理完了

### ISSUE THREAD

**Issue by feifeifeiname** [PowerJob/PowerJob#816]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details. 

![image](https://github.com/PowerJob/PowerJob/assets/37611162/c0428ea7-d5bd-4f1a-96e2-1c402152b030)

**Comment by HeZhanfeng** [comment]
使用http协议的时候我遇到跟你一样的问题，目前用akka正常，问题并没有解决

**Comment by KFCFans** [comment]
大概率和这个问题是一致的，Spring 的 pom 直接控制了 netty 的版本，导致 powerjob-worker 的 netty 冲突，无法正常工作。

https://github.com/PowerJob/PowerJob/issues/667#issuecomment-1996625269

**Comment by KFCFans** [comment]
<img width="932" alt="image" src="https://github.com/PowerJob/PowerJob/assets/9402086/2d375893-d6cb-494f-a8b5-2c76f979f758">
