### ISSUE TITLE
上游节点 任务结果中的msg如何传到下游节点中去？

### ISSUE THREAD

**Issue by yuanhong18** [PowerJob/PowerJob#819]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by KFCFans** [comment]
如果是 mapreduce 工作模式，使用 map API 时构造的子任务即为子节点参数。
如果是 workflow，可使用 `TaskContext#WorkflowContext#appendData2WfContext` 方法追加参数。

tech.powerjob.worker.core.processor.WorkflowContext#appendData2WfContext

<img width="1161" alt="image" src="https://github.com/PowerJob/PowerJob/assets/9402086/adcabcaa-671d-4db4-9278-4f6f40566b62">
