### ISSUE TITLE
客户端的ip是否可以自己手动配置

### ISSUE THREAD

**Issue by TSYMQMYST** [PowerJob/PowerJob#825]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details. 

我们公司的服务器上接入了很多的网线
所以他们有很多的ip

<img width="607" alt="image" src="https://github.com/PowerJob/PowerJob/assets/129494079/71924253-6661-4cc2-93ea-6446a2e27823">

但是在work-server和执行器之间沟通的ip应该是用192.168.5.x的ip才通
但是powerjob自动识别用了192.168.10.x
导致我的任务无法下发
请问可以手动配置客户端ip吗?
或者有什么别的解决方案?

**Comment by TSYMQMYST** [comment]
正常情况我的执行器IP应为:
![Uploading image.png…]()

**Comment by 0xcaffebabe** [comment]
使用 powerjob.network.local.address 或 powerjob.network.interface.preferred

**Comment by KFCFans** [comment]
https://www.yuque.com/powerjob/guidence/problem#ZaRnE

下个版本会采纳网友建议，worker 自动 ping server 选择合适的 IP
