### ISSUE TITLE
swagger无法关闭

### ISSUE THREAD

**Issue by xuzhong555** [PowerJob/PowerJob#826]
源码中关于swagger的注释：是否启用 Swagger-UI，默认关闭，但是通过docker部署后默认是开启的，并且通过启动参数设置oms.swagger.enable=false后，仍然是启动的

**Comment by linwei-scholar** [comment]
springdoc.api-docs.enabled=false

**Comment by KFCFans** [comment]
为了防止后续 API doc 依赖变更后再次出现问题，补充万能方法：
删除 `tech.powerjob.server.config.SwaggerConfig` 类
