### ISSUE TITLE
是否能提供固定分片的任务

### ISSUE THREAD

**Issue by wallacepang** [PowerJob/PowerJob#829]
场景：
处理固定分片数：例如有一个redis 队列，分了200片，有10台机器，需要将这200个分片任务分到10台机器处理。每个线程处理一个分片的数据类似  elastic-job 的分片任务

**Comment by KFCFans** [comment]
PowerJob 提供了比传统分片计算更强大的 Map / MapReduce 计算模型，允许用户使用代码自行分片计算，可参考官方文档：
https://www.yuque.com/powerjob/guidence/hczm7m#b07f5cf2
