### ISSUE TITLE
map方式，子任务调度慢

### ISSUE THREAD

**Issue by yflytom** [PowerJob/PowerJob#830]
版本
```xml
 <dependency>
      <groupId>tech.powerjob</groupId>
      <artifactId>powerjob-worker-spring-boot-starter</artifactId>
      <version>4.3.6</version>
  </dependency>
```

代码
![image](https://github.com/PowerJob/PowerJob/assets/32268317/59099ca1-ed2b-4d9f-b275-a623450426e7)
配置
![image](https://github.com/PowerJob/PowerJob/assets/32268317/ebc6dda5-bddb-47ab-80c0-7d7ecd425e5b)

调度日志
![image](https://github.com/PowerJob/PowerJob/assets/32268317/99da09ab-a39a-4f69-9b37-799569072c99)
大佬，您好，我的场景是根任务可以很快调度，但是根任务将参数放入之后，调度子任务时需要等待好几秒，大概5s左右，是我配置的问题吗？

**Comment by KFCFans** [comment]
Map / MapReduce 任务是针对大规模计算设计的处理器，出于性能考虑基本全部采用的时候异步推送的方式。（大规模任务执行时间都是小时级别起步，分发任务的几秒在这种场景下就可以忽略不计了）。

如果你的任务执行速度很快，可能没必要上 Map / MapReduce 计算模型，直接使用单机计算即可。

**Comment by yflytom** [comment]
> Map / MapReduce 任务是针对大规模计算设计的处理器，出于性能考虑基本全部采用的时候异步推送的方式。（大规模任务执行时间都是小时级别起步，分发任务的几秒在这种场景下就可以忽略不计了）。
> 
> 如果你的任务执行速度很快，可能没必要上 Map / MapReduce 计算模型，直接使用单机计算即可。

好的，感谢回复！
