### ISSUE TITLE
多租户系统如何使用PowerJob

### ISSUE THREAD

**Issue by zerochina2020** [PowerJob/PowerJob#832]
## 使用场景
多租户系统数据需要按照租户隔离，相同的任务在不同的租户需要按照不同的频率执行，任务需要根据入参确定执行逻辑
## 问题
目前PowerJob按照appName接入调度中心，希望同一应用的任务再按照租户隔离，请问有没有使用建议

**Comment by KFCFans** [comment]
worker 的配置里面有个tag 属性，可以根据不同的 tag 区分一个应用下不同的归组。

https://www.yuque.com/powerjob/guidence/ysug77

<img width="820" alt="image" src="https://github.com/PowerJob/PowerJob/assets/9402086/ff9e32d8-aba7-4cb4-9359-dd10a6801f96">
