### ISSUE TITLE
java.lang.OutOfMemoryError: unable to create new native thread 

### ISSUE THREAD

**Issue by kkrgwbj** [PowerJob/PowerJob#838]
**Describe the bug**
![image](https://github.com/PowerJob/PowerJob/assets/6836934/4958a806-857a-4542-a7b6-55329d630a41)

**Environment**
 - PowerJob Version: 4.1.0
 - Java Version:OracleJDK8
 - OS: Centos 7

**Comment by kkrgwbj** [comment]
操作系统都物理内存充足，CPU资源充足。

**Comment by KFCFans** [comment]
4.1.0版本确实有个极端情况oom的问题，后续版本应该已经修复了。
可以追一下 release 记录升级到最新版本（4.3.7）。

kkrgwbj ***@***.***>于2024年2月20日 周二11:24写道：

**Comment by KFCFans** [comment]
顺便如果有条件的话，提供一个线程dump文件，这样问题就一清二楚了。

**Comment by kkrgwbj** [comment]
4.3.7版本没法用，改动太大。初始化的时候要传进去一个spring上下文，但是4.1.0版本不需要。

**Comment by KFCFans** [comment]
你用错了，对你来说需要用 PowerJob SpringWorker，这个行为和之前是完全一致的。

**Comment by kkrgwbj** [comment]
哦，我看下。你意思我用错 sdk 了？

**Comment by KFCFans** [comment]
> 哦，我看下。你意思我用错 sdk 了？
> 
> 

用错类了。你把 PowerJobWorker 全部改成 PowerJobSpringWorker 就行了。推荐还是升级下，新版本稳定性和功能都有很大提升。

**Comment by kkrgwbj** [comment]
大哥，你这样不是改动挺大吗，那如果人家其他项目组的人不乐意改呢？那不是一样报错。。。

**Comment by KFCFans** [comment]
版本升级本来就伴随着潜在的改动，完成后也需要测试回归，这都是最基本的东西。
框架保证用户可升级，给出升级指南就行。

你要是不乐意，就待在老版本吧，随意了。

**Comment by charliecat22** [comment]
> 4.1.0版本确实有个极端情况oom的问题，后续版本应该已经修复了。
> 可以追一下 release 记录升级到最新版本（4.3.7）。
> 
> kkrgwbj ***@***.***>于2024年2月20日 周二11:24写道：
> […](#)

麻烦问一下，oom修复的提交记录是哪个？我需要手动修复
