### ISSUE TITLE
建议：V5.0.0-BETA 中应用列表和namespace列表应该按权限过滤

### ISSUE THREAD

**Issue by buppter** [PowerJob/PowerJob#840]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details. 

试了下V5.0.0-BETA版本，发现非当前用户有权限的应用列表和namespace列表还是会给展示，只不过无法编译和查看，感觉有点怪。
是不是可以在查询的时候直接过滤掉？

**Comment by KFCFans** [comment]
<img width="1782" alt="image" src="https://github.com/PowerJob/PowerJob/assets/9402086/6d738d09-944c-492a-9007-7db6998acc43">

支持只看我的选项，后续可以考虑搞成默认开的模式🤔

**Comment by KFCFans** [comment]
还有其他建议吗哈哈，欢迎踊跃提报

**Comment by buppter** [comment]
> <img alt="image" width="1782" src="https://private-user-images.githubusercontent.com/9402086/306646707-6d738d09-944c-492a-9007-7db6998acc43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NjczOTksIm5iZiI6MTcwODU2NzA5OSwicGF0aCI6Ii85NDAyMDg2LzMwNjY0NjcwNy02ZDczOGQwOS05NDRjLTQ5MmEtOTAwNy03ZGI2OTk4YWNjNDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMDE1ODE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2YzZWE1ZDhjOTQ1ZWFjYjgxM2E0NzNjZWQxOTdjODE0OGNjZTQ0Y2E3MjY4YzNmMDU0MTExMDQ2MjlkNTBjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VdXVEfUuh5uLDktVNLvUWm3_vaOrtEfdoTazSPk8s10">
> 支持只看我的选项，后续可以考虑搞成默认开的模式🤔

【只看我的】勾选后还是得点一下【查询】，是不是可以改成勾选后自动查询一次数据，体验会好一些

**Comment by KFCFans** [comment]
5.1.0 发布后支持
