### ISSUE TITLE
4.3.6版本server从4.0.1版本worker解析消息异常

### ISSUE THREAD

**Issue by AZI-D** [PowerJob/PowerJob#842]
## Question
版本信息：
worker：4.0.1
server：4.0.1
问题描述
4.0.1版本的server想升级到4.3.6版本，出现了序列化失败的错误，统一kryo5和akka版本，统一WorkerHeartbeat对象后，依旧存在这个问题；
错误信息：
 [oms-server-akka.actor.default-dispatcher-5] WARN a.r.a.Deserializer - Failed to deserialize message from [akka://oms@ip:27777] with s
erializer id [6] and manifest []. com.esotericsoftware.kryo.kryo5.KryoException: Unable to read unknown data (unknown type). (tech.powerjob.common.request.WorkerHeartbeat#null)

本地调试了一下，4.0.1版本发送的worker心跳信息没有问题，server端可以接收到心跳，但心跳信息是默认值，导致更新心跳失败。有什么方法能兼容一下呢？

**Comment by AZI-D** [comment]
使用同样的serializers还是存在上述问题
    serializers {
        power-serializer = "tech.powerjob.common.serialize.PowerAkkaSerializer"
    }

**Comment by KFCFans** [comment]
收到，我排查一下。

**Comment by KFCFans** [comment]
<img width="1308" alt="image" src="https://github.com/PowerJob/PowerJob/assets/9402086/4823c7e6-d5fc-4a64-b029-c3f856bd7a39">

前序版本的 bug，kryo 的序列化配置you wen ti有问题，没有用 CompatibleFieldSerializer 导致增减字段后无法序列化。client 已经打出去了无法更改。
方便同时升级 server 和 worker 吗？

或者先把 worker 版本升上去，一般上下几个版本都是兼容的。

**Comment by AZI-D** [comment]
> <img alt="image" width="1308" src="https://private-user-images.githubusercontent.com/9402086/307588967-4823c7e6-d5fc-4a64-b029-c3f856bd7a39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTQ3OTYsIm5iZiI6MTcwODkxNDQ5NiwicGF0aCI6Ii85NDAyMDg2LzMwNzU4ODk2Ny00ODIzYzdlNi1kNWZjLTRhNjQtYjAyOS1jM2Y4NTZiZDdhMzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjZUMDIyODE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmIzYTg1NmE0Mzg2MmZmODcyY2IzNDhhMzBkNWZkMjgyYzdjOTFhNDFjOGFlNzQyYzE3ZDdiOTJiMzNlOWUwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7c8E09-trM1Au_OvfPHBGDNqhVoGK0bO-8PLeBeu-Fw">
> 前序版本的 bug，kryo 的序列化配置you wen ti有问题，没有用 CompatibleFieldSerializer 导致增减字段后无法序列化。client 已经打出去了无法更改。 方便同时升级 server 和 worker 吗？
> 
> 或者先把 worker 版本升上去，一般上下几个版本都是兼容的。

目前接入powerjob的项目均使用的是4.0.1版本的worker，涉及不同的业务，全量升级worker不太现实。我尝试将4.3.6版本中 kryo.setDefaultSerializer(CompatibleFieldSerializer.class) 注释掉，然后统一worker与server端的WorkerHeartbeat对象为4.0.1版本，实现了心跳成功上报更新，但我看在实例状态(TaskTrackerReportInstanceStatusReq)、任务调度(ServerScheduleJobReq)等对象属性上均有差异。这种情况下，如果更改上述对象与4.0.1版本一致，4.3.6版本server代码中还会有一些变动，以此来保证基本功能的正常使用。对于上述改动有什么建议吗？如果按上述方案，是否有必要进行升级呢？
![image](https://github.com/PowerJob/PowerJob/assets/60462826/2c973303-a8a3-4352-8fa3-85e1b53a02b4)

**Comment by KFCFans** [comment]
这样工作量可能太大了。
一般大版本的升级，比较建议多实例部署。即重新起一套高版本的 server 集群，数据库层面可以直接迁移过去（后续官方也可以考虑出迁移脚本，不过DB直接迁移也很简单，clone 个相同的数据库而已），server 的话新开几个容器即可。这样对下游业务来说就存在2套 server，慢慢推动他们迁移到新 worker 和新 server 即可。这种方案对于下游接入方来说迁移成本也很低，只需要：
1. 升级 worker 的 pom 版本
2. 修改 server 地址

推动一段时间下游全部迁入新 server 后，下线老 server 即可。

整体成本应该不高的。

**Comment by KFCFans** [comment]
你们升级的背景是什么，如果现在没有权限的版本符合你们需求，那可以升级到 4.3.9，基本是 4.x 最后的稳定版本了。

如果对用户&权限系统有诉求，可以等一等官方 5.x 版本正式发布，按这个方案做一次大版本升级，一步到位。

后续的版本网络库/序列化的坑踩的差不多了，应该都能server无感升级。

**Comment by KFCFans** [comment]
<img width="845" alt="image" src="https://github.com/PowerJob/PowerJob/assets/9402086/8373d58c-df6d-4bb8-b948-46d542b45acb">

**Comment by KFCFans** [comment]
<img width="774" alt="image" src="https://github.com/PowerJob/PowerJob/assets/9402086/94e621a8-328a-4ca9-b927-de2ee8047f38">

**Comment by AZI-D** [comment]
> 你们升级的背景是什么，如果现在没有权限的版本符合你们需求，那可以升级到 4.3.9，基本是 4.x 最后的稳定版本了。
> 
> 如果对用户&权限系统有诉求，可以等一等官方 5.x 版本正式发布，按这个方案做一次大版本升级，一步到位。
> 
> 后续的版本网络库/序列化的坑踩的差不多了，应该都能server无感升级。

目前权限控制部分不需要，有一套依赖于其他服务的权限控制方案，这个升级方案我们评估下。

**Comment by KFCFans** [comment]
期待你们的最佳实践～其实理论上这个方案是简单的，要是搞定了希望可以分享下～

**Comment by KFCFans** [comment]
对了，有空的话还是可以看下 5.x 的介绍， PowerJob 的设计考虑到了其他账号体系的兼容性，能很轻松接入第三方登录能力。
至于权限部分，本身扩展性需求应该也不高。可以看看5.x能否支持你们的需求。

https://www.yuque.com/powerjob/guidence/user

**Comment by AZI-D** [comment]
> 对了，有空的话还是可以看下 5.x 的介绍， PowerJob 的设计考虑到了其他账号体系的兼容性，能很轻松接入第三方登录能力。 至于权限部分，本身扩展性需求应该也不高。可以看看5.x能否支持你们的需求。
> 
> https://www.yuque.com/powerjob/guidence/user

了解，我详细看看。
