### ISSUE TITLE
4.3.8版本使用minio报错

### ISSUE THREAD

**Issue by cy2008** [PowerJob/PowerJob#844]
4.3.8版本使用minio报错

原因：
minio 8.5.2版本需要使用okhttp4，实际版本是okhttp3

希望作者添加功能后能做好测试

**Comment by KFCFans** [comment]
不好意思，社区pr的功能，看了眼代码比较简单就直接merge了。
后续版本fix。

**Comment by KFCFans** [comment]
4.3.9 已发布并修复上述问题。
