### ISSUE TITLE
MinioOssService使用Files.probeContentType返回为空

### ISSUE THREAD

**Issue by cy2008** [PowerJob/PowerJob#845]
MinioOssService使用Files.probeContentType返回为空

原因：
Files.probeContentType返回值依赖于具体的操作系统，用来判断文件类型时不可靠的

**Comment by KFCFans** [comment]
你直接用 4.3.9 分支吧，同一个问题不用开那么多个 issue...
https://github.com/PowerJob/PowerJob/issues/844
