### ISSUE TITLE
容器的jar更新后实际的任务并没有使用新jar中的类

### ISSUE THREAD

**Issue by cy2008** [PowerJob/PowerJob#850]
容器的jar更新后实际的任务并没有使用新jar中的类
重现方法
1、部署一个容器并部署
2、建个任务运行
3、编辑容器，上传新的jar包并保存并部署容器
4、再次运行任务后观察worker日志

**Comment by KFCFans** [comment]
感谢反馈！看起来很仔细的全部过了一遍功能😂，辛苦了。

4.3.9 分支已修复。

**Comment by KFCFans** [comment]
4.3.9 已发布并修复上述问题。
