### ISSUE TITLE
SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by zhujia112** [PowerJob/PowerJob#852]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details. 

1.根据官方文档部署好了PowerJob-server 和PowerJob-agent。
![image](https://github.com/PowerJob/PowerJob/assets/73097900/7c539ba5-c489-4d2e-be42-5d31761d3e02)

2.参考官方给出的例子，访问baidu成功。
![image](https://github.com/PowerJob/PowerJob/assets/73097900/cbb5b448-2ade-40a9-a3fe-09ea61f61ccc)

3.尝试创建一个自己的任务，是想访问一个写入日志的API，使用官方Http处理器：tech.powerjob.official.processors.impl.HttpProcessor，但是运行完返回以下错误。这是什么原因呢？
![image](https://github.com/PowerJob/PowerJob/assets/73097900/fa9e5eef-4873-4733-903d-82081e4d4158)

**Comment by KFCFans** [comment]
https 鉴权不通过，应该是你的目标域名需要严格校验证书。
这种就需要自己写代码开发相应的处理器了。

**Comment by zhujia112** [comment]
好的，谢谢
