### ISSUE TITLE
5.0.0 BETA 版 Bug 反馈

### ISSUE THREAD

**Issue by dmbjz** [PowerJob/PowerJob#854]
Bug 列表：
浏览器与内核版本： Chrome 122.0.6261.95、Edge 122.0.2365.66 

1、修改当前登陆账号没权限的命名空间，会出现两个弹窗，第二个弹窗没有内容显示
![image](https://github.com/PowerJob/PowerJob/assets/67595782/0e492430-91dd-42db-8f8e-6859b0e52d04)

2、 “命名空间” 的 “标签”、“额外信息” 丢失，触发场景如下：
   一、首次保存“命名空间”时不填写 “标签”、“额外信息”，然后对其编辑，填写这两个参数值后再点击保存
   二、首次保存“命名空间”时填写 “标签”、“额外信息”，然后对其编辑
![image](https://github.com/PowerJob/PowerJob/assets/67595782/5ddae191-9315-4768-a7e0-afa92d37c869)

3、使用默认的 ADMIN 账号创建命名空间，退出登陆后再重新登陆，编辑页上的 “管理员” 会出现两个相同标签
![image](https://github.com/PowerJob/PowerJob/assets/67595782/19246035-417a-41d6-afa4-969322d53574)

4、“任务管理” 中先创建一个”固定频率“的任务，保存后将 ”定时信息“ 修改成 “每日固定间隔”，此时 “每日固定间隔” 弹窗内的所有数据项均无法进行选择
![image](https://github.com/PowerJob/PowerJob/assets/67595782/9da582f6-8cca-49e1-8374-9d64855c7cf2)

5、使用钉钉登陆后再退出登陆，会提示授权码错误弹窗
![image](https://github.com/PowerJob/PowerJob/assets/67595782/fd43a4b8-e5c6-4362-a5be-e812c046a340)

6、powerjob-client 的 OpenAPI 案例中不使用 JSON 方式传参的方法无法正常使用。原因为 OpenAPIController 无法正常接收其参数值。对其修改请求方式后可以正常访问
例如 /assert 方法会返回 ”PowerJobException: can't find appInfo by appName: null“ 错误
例如 /fetchJob 方法会提示 ” can't find job by jobId: null“
![image](https://github.com/PowerJob/PowerJob/assets/67595782/010f2caf-0a4e-42ad-9171-e5141bc89180)
![image](https://github.com/PowerJob/PowerJob/assets/67595782/8793bb81-ca17-4a43-89ab-451f409f5268)

**Comment by KFCFans** [comment]
辛苦了，我们会逐一 check 并处理，感谢您！

**Comment by KFCFans** [comment]
1、2、3、6 已在 5.0.1修复
4和5基本无实际影响，后续版本会逐步修复。
