### ISSUE TITLE
希望 ”应用管理“ 能支持删除的功能

### ISSUE THREAD

**Issue by dmbjz** [PowerJob/PowerJob#855]
如果一开始在 “应用管理” 中为每个项目都配置了一个数据，后期对项目进行了迭代升级，把原有的多个项目重构成一个项目。此时 “应用管理” 中这些被合并掉的项目对应数据都属于无用信息，应该被删除。目前在5.0 版本中没有看到相关功能，希望这个后期可以考虑支持一下

**Comment by KFCFans** [comment]
安排。
趁着 5.x 版本 beta，鼓励大家多提需求，这个阶段合理需求都会大力支持。

**Comment by KFCFans** [comment]
5.0.1已支持
