### ISSUE TITLE
任务未启用点击运行后，任务一直执行

### ISSUE THREAD

**Issue by chenyu9390** [PowerJob/PowerJob#857]
创建任务后状态是未启用的状态，点击运行后，任务一直执行，疑问如下：
1）第一次执行后再次执行的时候是不是需要检查任务的状态，如果未启用任务应该停止
2）这个状态和运行的定义是不是冲突了，运行是不是同时要把状态更新，希望加”运行一次“的功能
![image](https://github.com/PowerJob/PowerJob/assets/8199403/eb3b8ed5-1e08-4db0-94f0-046033811930)
![image](https://github.com/PowerJob/PowerJob/assets/8199403/d3f0519d-d916-4d3d-8a60-4fdc93f24585)
![image](https://github.com/PowerJob/PowerJob/assets/8199403/a00c8d1b-db73-4284-aabc-ffc2901294e4)

**Comment by dmbjz** [comment]
![image](https://github.com/PowerJob/PowerJob/assets/67595782/b790d116-fa7a-45e7-b486-9d3ee09ed71c)
固定延迟和固定频率任务无法停止，只能关闭或者删除、运行一次后又没关闭 & 删除，所以一直运行
