### ISSUE TITLE
5.0.0 BETA “任务管理” 删除异常

### ISSUE THREAD

**Issue by dmbjz** [PowerJob/PowerJob#859]
触发场景：
“任务管理”  中创建 A、B 两个任务，首先删除 B 任务。B任务删除后尝试删除 A 任务，此时 A 任务的删除操作不生效，需要进行重新再点击删除操作才能删除 A 任务
![image](https://github.com/PowerJob/PowerJob/assets/67595782/cee2d371-d09d-4016-b43d-e5debac30695)

**Comment by KFCFans** [comment]
感谢反馈，确认问题后会及时修复。
