### ISSUE TITLE
v4.3.9 docker  server 启动报错

### ISSUE THREAD

**Issue by WallenHan** [PowerJob/PowerJob#865]
**Describe the bug**
v4.3.9 docker  server 启动报错

  at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
powerjob-server            |    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
powerjob-server            |    at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
powerjob-server            |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
powerjob-server            |    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
powerjob-server            |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
powerjob-server            |    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:241)
powerjob-server            |    at com.sun.proxy.$Proxy151.deleteByOwnerIP(Unknown Source)
powerjob-server            |    at tech.powerjob.server.core.lock.DatabaseLockService.lambda$new$0(DatabaseLockService.java:34)
powerjob-server            |    at java.lang.Thread.run(Thread.java:748)
powerjob-server            | Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' available

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
 - PowerJob Version: 4.3.9
- docker
**Screenshots**

**Additional context**

**Comment by KFCFans** [comment]
请提供完整堆栈或错误信息

**Comment by dgs511** [comment]
在5.1.2版本中也遇到了同样的问题，jdk版本：1.8.0_162
