### ISSUE TITLE
反序列化Java8 日期问题

### ISSUE THREAD

**Issue by HeZhanfeng** [PowerJob/PowerJob#869]
版本4.3.9
MapReduce拆分子任务对象中含有LocalDateTime类型的属性，
执行偶发错误：
ERROR tech.powerjob.common.serialize.JsonUtils - [PowerJob] toJSONString failed 
 com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: cn.piesat.sdc.provider.api.domain.dto.relation.calculate.GlobalAreaAccessDistributedTaskDTO["taskStart"])
 
![企业微信截图_17103974382909](https://github.com/PowerJob/PowerJob/assets/16128322/8ee46a00-4e89-4e10-9fb7-cec6f7b513d5)

**Comment by HeZhanfeng** [comment]
表象是任务实例详情中Task查询结果记录中的taskContent一列为空

**Comment by KFCFans** [comment]
哎，感觉 Jackson 也不是什么好东西...问题也一大堆hhh
已收到，后续版本修复

**Comment by KFCFans** [comment]
不过这个错误提示也很明确了，你可以自己在 worker 工程中添加 "com.fasterxml.jackson.datatype:jackson-datatype-jsr310“ 依赖，注意版本和工程的 jackson 版本一致即可。

**Comment by HeZhanfeng** [comment]
哎，类属性涉及日期还是字符串靠谱hhh

**Comment by KFCFans** [comment]
5.0.1已修复
