### ISSUE TITLE
5.0.0 BETA 版 应用管理超管部分获取不到应用密码Bug

### ISSUE THREAD

**Issue by hellsof** [PowerJob/PowerJob#870]
**Describe the bug**
应用管理超管部分获取不到应用密码Bug。
<img width="616" alt="image" src="https://github.com/PowerJob/PowerJob/assets/10841477/c9d1a115-68bd-420f-a623-4605916f1eea">

**修复建议**
tech.powerjob.server.web.controller.AppInfoController

**Comment by hellsof** [comment]
<img width="1067" alt="image" src="https://github.com/PowerJob/PowerJob/assets/10841477/3a4a2775-90cc-4e3c-a0ab-d84a00b54073">
1处的parallelStream使用多线程处理，导致2处方法从ThreadLocal获取不到登录用户，改为stream即可

**Comment by KFCFans** [comment]
非常感谢反馈，会尽快修复！

**Comment by KFCFans** [comment]
5.0.1已修复
