### ISSUE TITLE
5.0.0 BETA OpenAPI 无校验逻辑

### ISSUE THREAD

**Issue by dmbjz** [PowerJob/PowerJob#871]
问题：“工作流”、“任务” 涉及修改 status 状态位的相关方法未进行校验
例子：
1、先调用 “删除工作流”（deleteWorkflow方法），再调用 “启用工作流” （enableWorkflow方法），被删除工作流被恢复为启用状态
2、先调用 ”删除任务“（deleteJob方法），再调用 “启用任务”（enableJob方法），被删除任务将被恢复为启用状态
![image](https://github.com/PowerJob/PowerJob/assets/67595782/d8facc0f-910e-46c2-9f37-38c2de9b11f9)
![image](https://github.com/PowerJob/PowerJob/assets/67595782/e47ff14d-3ac4-4e7a-b5d1-c3ab179cde78)

**Comment by KFCFans** [comment]
这个我觉得可以当 bug 也可以当特性，出于历史兼容性考虑就不动了，哈哈。对有扩展需要的用户来说，保留这个特性可能能玩的更花。
