### ISSUE TITLE
大哥，reflections 无法扫描到CSInitializer接口，以及接口实现，导致接口报错，cannot load CSinitializer

### ISSUE THREAD

**Issue by yinian** [PowerJob/PowerJob#872]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by yinian** [comment]
怎么初始化，能让他被reflections 给扫描到呢

**Comment by KFCFans** [comment]
https://github.com/PowerJob/PowerJob/issues/868

**Comment by KFCFans** [comment]
使用 5.0.1-beta 版本的 worker
