### ISSUE TITLE
5.0.1 BETA  bug 列表

### ISSUE THREAD

**Issue by dmbjz** [PowerJob/PowerJob#875]
bug：

1、"应用管理-只看我的" 看到当前账号无权限的信息

复现步骤：创建一个全部指定为 ADMIN 管理员的命名空间A、应用A，然后创建一个新用户直接登陆进行查询操作。此时 "应用管理-只看我的" 查询条件不生效，能看到全部指定为管理员的信息（应用A）

【命名空间】配置：
![image](https://github.com/PowerJob/PowerJob/assets/67595782/afa634ba-d7e7-4fc6-b5e1-a80099059aff)

【应用管理】配置：
![image](https://github.com/PowerJob/PowerJob/assets/67595782/208076cd-092d-4030-a87d-4e92552f0f98)

2、无权限删除应用抛出异常信息
复现步骤：创建一个新用户，什么权限都不授予，此时删除应用会抛出异常
原因：校验 namespace 穿透权限出现异常
![image](https://github.com/PowerJob/PowerJob/assets/67595782/47cca9ad-e8bc-4d49-9cb7-668d0cf179db)
![image](https://github.com/PowerJob/PowerJob/assets/67595782/8e53cd10-5ceb-41c2-a097-ca5224691227)

**Comment by KFCFans** [comment]
5.1.0 发布后修复
