### ISSUE TITLE
请问调度中心server如何集群部署

### ISSUE THREAD

**Issue by kkrgwbj** [PowerJob/PowerJob#881]
官网文档写的比较含糊，就一句话。

调度服务器（powerjob-server）支持任意的水平扩展，即多实例集群部署仅需要在同一个局域网内启动新的服务器实例，性能强劲无上限！

如果集群部署的话，那我任务配置的时候，需要指定server的ip吗？客户端配置如何连

**Comment by dmbjz** [comment]
worker 连接 server：
![image](https://github.com/PowerJob/PowerJob/assets/67595782/846fd380-716e-4019-adf7-a85829355e45)

任务指定使用集群某节点运行：
![image](https://github.com/PowerJob/PowerJob/assets/67595782/30facdea-1304-4bb8-8974-938ca67434da)
