### ISSUE TITLE
有一个任务报错 no worker available，其他任务正常运行

### ISSUE THREAD

**Issue by ccxyChuzhong** [PowerJob/PowerJob#882]
**Describe the bug**
三个任务，两个正常运行，一个报错 no worker available

![image](https://github.com/PowerJob/PowerJob/assets/55871409/70cd2cfa-e165-476a-8509-2dc6acf3e707)
正常运行的
![image](https://github.com/PowerJob/PowerJob/assets/55871409/3c94dbbe-7f4c-45b5-870d-08cf76e80ef1)
运行异常的
![image](https://github.com/PowerJob/PowerJob/assets/55871409/7ac2b2b2-682b-4d7c-8fdb-e983ed967731)

运行异常任务配置
![image](https://github.com/PowerJob/PowerJob/assets/55871409/bcea18c7-3d7b-479d-93e4-ac9ab43d4e33)

**Environment**
 - PowerJob Version: [4.3.6]
 - Java Version: [e.g. OpenJDK 17]
 - OS: [e.g. CentOS 8.1]

**Comment by ccxyChuzhong** [comment]
看了常见问题有这个，但是我的另外两个就能正常运行，就这一个运行异常。我是在一台服务器部署的服务。两个应用服务，一个powerjob。都是在docker上边运行，就是不太能理解。为什么只有一个不能用，

**Comment by Echo009** [comment]
你这个任务指定了最低的机器配置（内存，CPU），检查下机器配置是否满足要求

**Comment by ccxyChuzhong** [comment]
> 你这个任务指定了最低的机器配置（内存，CPU），检查下机器配置是否满足要求

我确实是指定了，但是我指定的配置远远低于我的服务器。我的cpu是四核，内存是16G，存储更不用说了我配置上边只有10G。但是我把这些删掉之后，能用了！服务器部分配置如下
![image](https://github.com/PowerJob/PowerJob/assets/55871409/c231561b-9a6c-4aaa-b31f-c32ef44d87c9)

**Comment by KFCFans** [comment]
这是你宿主机的配置，powerjob 上报的是 JVM 的配置，如果不特殊指定，JVM默认只会有一半内存，然后我估计就被你的 filter 条件过滤了，可以 check 下。
