### ISSUE TITLE
处理器mapreduce具体的实现示例有没有

### ISSUE THREAD

**Issue by xiaonanstc** [PowerJob/PowerJob#902]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by HeZhanfeng** [comment]
没好好看文档啊兄弟，源码搜搜MapReduceProcessorDemo

**Comment by HeZhanfeng** [comment]
你是不死只启动了一个worker节点？

**Comment by KFCFans** [comment]
相关文档：https://www.yuque.com/powerjob/guidence/processor#bbb35cb5

工程示例：https://github.com/PowerJob/PowerJob/blob/master/powerjob-worker-samples/src/main/java/tech/powerjob/samples/processors/MapReduceProcessorDemo.java
