### ISSUE TITLE
官方HTTP处理器 无法发送请求

### ISSUE THREAD

**Issue by tchtsm** [PowerJob/PowerJob#906]
## Question

使用官方HTTP处理器 无法发送请求:

#### 任务配置
![image](https://github.com/PowerJob/PowerJob/assets/39479897/183ec628-40e3-436d-93cc-60f0dda5e82e)
#### 任务记录
![image](https://github.com/PowerJob/PowerJob/assets/39479897/ad9fa9e0-5954-4ff0-9217-dbcff0b3a6bd)
#### 日志截图
![image](https://github.com/PowerJob/PowerJob/assets/39479897/3356391a-0cc6-481a-a6ff-2a3ad1a2a119)

版本4.3.9
麻烦大佬们帮解答一下！

**Comment by KFCFans** [comment]
PowerJob 至少需要有 server 和 worker 2个节点才可以运行，错误信息 no worker available 的意思就是你需要部署 worker 节点才能运行这个 http 任务。
