### ISSUE TITLE
5.0.1-beta docker部署使用nginx代理无法登录

### ISSUE THREAD

**Issue by cema0110** [PowerJob/PowerJob#910]
## Question
5.0.1-beta 采用docker部署，用nginx代理的proxy_pass方向代理之后，无法登录，输入用户名密码之后点击登录会自动跳回登录页面并提示用户需要登录。powerjob和nginx部署在不同IP的服务器上。
server {
		listen 7700;
		listen [::]:7700;
		server_name _;
		location / {
			proxy_pass http://xxx.xxx.xxx.xxx:7700;
		}
    }

**Comment by commis** [comment]
原因请求头中的Power_jwt被nginx忽略了，需要调整nginx的配置，可参考：
https://blog.csdn.net/m0_37609579/article/details/129118700

**Comment by KFCFans** [comment]
感谢反馈，后续我们兼容一下
