### ISSUE TITLE
Worker 连不上Server

### ISSUE THREAD

**Issue by wangjintaod** [PowerJob/PowerJob#915]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）
![serverError](https://github.com/PowerJob/PowerJob/assets/106147173/86a3dff8-4c00-41c2-a36d-d502141fb162)

Please pay attention on issues you submitted, because we maybe need more details. 

为什么我同一台机器先启动了Server，然后又启动了Worker是可以连上的，但此时断掉Worker，再启动Worker就再也连不上server了。
在worker请求/acquire的时候，server报错如图

**Comment by wangjintaod** [comment]
问题找到了 可能因为我的数据库是OB的，jpa自动创建的数据库表有点问题，所以我手动执行了下表的sql，然后就没问题了，我把oms_lock这个表手动执行了一下表sql就好了。

**Comment by wangjintaod** [comment]
还是不行，只要把表删掉重新建就可以了，但是如果worker在断开 还是连不上，考虑是数据库驱动的问题，数据库是OB的但是我用的是mysql的模式。所以我用的是Mysql的数据库驱动。

**Comment by KFCFans** [comment]
大概率是数据库兼容性导致的 `tech.powerjob.server.persistence.remote.model.OmsLockDO#gmtCreate` 空了
使用的 java 类型是 java.util.Date，可以查下相关资料做下兼容性适配。

<img width="890" alt="image" src="https://github.com/user-attachments/assets/1e4cdc32-73bc-4a59-824e-d29892c5cbe2">
