### ISSUE TITLE
有栈信息 PPP、PPT、ctttp等线程池的线程创建过多，导致JVM崩溃

### ISSUE THREAD

**Issue by passiolin** [PowerJob/PowerJob#917]
**Describe the bug**
定时任务的高峰期，PPP、PPT、ctttp等线程池的线程创建过多，导致JVM崩溃。
![图片](https://github.com/PowerJob/PowerJob/assets/163995028/79ac614d-caf4-4349-9b66-ce49fdfab86a)

**To Reproduce**
我提供堆栈来看吧。

**Expected behavior**

**Environment**
 - PowerJob Version:4.2.0
 - Java Version: openjdk11
 - OS: ubuntu20.04

**Screenshots**
![图片](https://github.com/PowerJob/PowerJob/assets/163995028/b42b32e6-1bc1-4e36-aa50-acc38f213eea)
![图片](https://github.com/PowerJob/PowerJob/assets/163995028/2046784e-f3f8-44b5-a6c4-0c082475ef6a)
![图片](https://github.com/PowerJob/PowerJob/assets/163995028/00a762c0-3193-4f07-9e61-2d817f17e829)

详细的栈信息：[infrastructure.stack.tar.gz](https://github.com/PowerJob/PowerJob/files/15492975/infrastructure.stack.tar.gz)

看了下客户端代码。

PPP、PPT线程，每接收到powjob TaskTracker 的请求，就会创建线程池。这个线程池池化的逻辑是不是有问题，每次都会去new一个啊。
![图片](https://github.com/PowerJob/PowerJob/assets/163995028/a95ab798-0076-4223-a344-ca5db3020780)
![图片](https://github.com/PowerJob/PowerJob/assets/163995028/39e232b9-e7fb-4519-bc34-f98e030ff288)

ctttp线程看着也是一样，每次都回去create一遍，就会再创建线程池
![图片](https://github.com/PowerJob/PowerJob/assets/163995028/054a7ace-6ed8-4f81-8ad8-25019902506c)
![图片](https://github.com/PowerJob/PowerJob/assets/163995028/996b9dc1-6e6e-46fe-8e16-e586c8a70ecd)

**Comment by passiolin** [comment]
这么严重的bug，能挂三天- - 甚至更久

**Comment by Echo009** [comment]
sorry ，最近比较忙，后续如果有比较紧急的问题，可以私发邮件或者用户群里反馈

**Comment by Echo009** [comment]
建议升级到 4.2.1 版本

![image](https://github.com/PowerJob/PowerJob/assets/24402043/3b8cac59-6339-4bca-917c-f30dce4eae11)

**Comment by Echo009** [comment]
> 我看了下最新的master分支，这几个线程池的逻辑没怎么变化，看着问题还在- -

4.2.1 版本之后是有做“流控”的

**Comment by passiolin** [comment]
> sorry ，最近比较忙，后续如果有比较紧急的问题，可以私发邮件或者用户群里反馈

我有发邮件，但是没回复。加Q群的话，人也满了。

**Comment by passiolin** [comment]
![图片](https://github.com/PowerJob/PowerJob/assets/163995028/e7a6c23a-24cb-42a1-ac18-af046f702116)
更新了依赖版本，看着问题是解决了。

说一下我的一些理解：

1、原先的客户端通知分成了两种类型，一种是轻量级、一种是重量级（原先的问题代码）

2、CRON会被归为轻量级任务
![img_v3_02bh_2852cf96-1a41-4e99-856f-029d7fbef54g](https://github.com/PowerJob/PowerJob/assets/163995028/dc5704bf-e3ef-4314-9669-318afe3d7a0d)

3、轻量级任务，线程池是单例的，避免了之前创建线程池过多的问题
![img_v3_02bh_c65b4eba-0da7-43e7-a03c-c26307b5388g](https://github.com/PowerJob/PowerJob/assets/163995028/96bf4fa7-af42-449e-885a-418ff376f927)

4、这个线程池，使用的是有界队列，在任务过多时，会直接丢弃。可能会造成有些能收到通知，有些收不到的情况。
这点可以考虑在业务层面，自己去做异步削峰的处理，问题还不大。

5、重量级，还是之前的问题代码，后续如果有使用的情况下，也还会出问题？
这点我理解是否正确？

**Comment by Echo009** [comment]
> ![图片](https://private-user-images.githubusercontent.com/163995028/336400364-e7a6c23a-24cb-42a1-ac18-af046f702116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDk0MjksIm5iZiI6MTcxNzY0OTEyOSwicGF0aCI6Ii8xNjM5OTUwMjgvMzM2NDAwMzY0LWU3YTZjMjNhLTI0Y2ItNDJhMS1hYzE4LWFmMDQ2ZjcwMjExNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwNDQ1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWFjYmU3MzNkNTMzNmIyZGY2ZTJiYTgxNDZhZmE1YjNmMTI2YWUwMTA0MDMyZTMwNzdiOWJkNjQ5ZWVjODlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YIpWwrOLKNF3H-54GejlYsQYd2fj9-ocnJYO-57I_wA) 更新了依赖版本，看着问题是解决了。
> 
> 说一下我的一些理解：
> 
> 1、原先的客户端通知分成了两种类型，一种是轻量级、一种是重量级（原先的问题代码）
> 
> 2、CRON会被归为轻量级任务 ![img_v3_02bh_2852cf96-1a41-4e99-856f-029d7fbef54g](https://private-user-images.githubusercontent.com/163995028/336400712-dc5704bf-e3ef-4314-9669-318afe3d7a0d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDk0MjksIm5iZiI6MTcxNzY0OTEyOSwicGF0aCI6Ii8xNjM5OTUwMjgvMzM2NDAwNzEyLWRjNTcwNGJmLWUzZWYtNDMxNC05NjY5LTMxOGFmZTNkN2EwZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwNDQ1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTdmOTIxMGJjNzFjOTc5YjFmYThjY2VjNzRjNjk4YjliNDVkNzY5MjdkZDY5OTk2YTIyNWQ4NDY0YjVlM2IzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qKBbEnROntgEIxJMg5-piHe7qMSpfKLrCyASCFXDbgI)
> 
> 3、轻量级任务，线程池是单例的，避免了之前创建线程池过多的问题 ![img_v3_02bh_c65b4eba-0da7-43e7-a03c-c26307b5388g](https://private-user-images.githubusercontent.com/163995028/336400759-96bf4fa7-af42-449e-885a-418ff376f927.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDk0MjksIm5iZiI6MTcxNzY0OTEyOSwicGF0aCI6Ii8xNjM5OTUwMjgvMzM2NDAwNzU5LTk2YmY0ZmE3LWFmNDItNDQ5ZS04ODVhLTQxOGZmMzc2ZjkyNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwNDQ1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjZhNThmOTMxM2JlZWZkN2VjZjJkMDRiOGM1MGY1MzM2MTVmM2Y0ZmJmMzA5MDRjMGZkMTlmNDViOWQ5MzY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n4z_paplgy-WEf0i82ococ71abs_7NzudVWqmb84bXw)
> 
> 4、这个线程池，使用的是有界队列，在任务过多时，会直接丢弃。可能会造成有些能收到通知，有些收不到的情况。 ![img_v3_02bh_4b1249d6-001b-4740-92a1-3475c2a2dd1g](https://private-user-images.githubusercontent.com/163995028/336401473-af6e2489-c885-49b9-869e-46db3461b793.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDk0MjksIm5iZiI6MTcxNzY0OTEyOSwicGF0aCI6Ii8xNjM5OTUwMjgvMzM2NDAxNDczLWFmNmUyNDg5LWM4ODUtNDliOS04NjllLTQ2ZGIzNDYxYjc5My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwNDQ1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzEwNjFkMzcxNTQzNjhiMzM0MmEzMTczM2NkZGQyYWE4NGU5YTFlMDYzNmE0Mzk4NTIxNzUzYWQ4NDc1MWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gnNr3LtBTV2GWhTJUQ6_jJeIQK92U02V3bZNpJ2teTk)
> 
> 这点可以考虑在业务层面，自己去做异步削峰的处理，问题还不大。
> 
> 5、重量级，还是之前的问题代码，后续如果有使用的情况下，也还会出问题？ 这点我理解是否正确？



第一点和第三点 理解没问题。
第二点，划分轻重量级任务并不只是根据任务的定时信息来判断的，还有执行类型，非单击执行的都是重量级任务。
第四点，worker 端直接丢弃任务的情况下，Server 端会通过重试来保证可靠性
第五点，worker 端在接收到重量级任务后，在创建 TaskTracker 之前会检查数量限制，这个值默认是 64

**Comment by passiolin** [comment]
> > ![图片](https://private-user-images.githubusercontent.com/163995028/336400364-e7a6c23a-24cb-42a1-ac18-af046f702116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDk0MjksIm5iZiI6MTcxNzY0OTEyOSwicGF0aCI6Ii8xNjM5OTUwMjgvMzM2NDAwMzY0LWU3YTZjMjNhLTI0Y2ItNDJhMS1hYzE4LWFmMDQ2ZjcwMjExNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwNDQ1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWFjYmU3MzNkNTMzNmIyZGY2ZTJiYTgxNDZhZmE1YjNmMTI2YWUwMTA0MDMyZTMwNzdiOWJkNjQ5ZWVjODlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YIpWwrOLKNF3H-54GejlYsQYd2fj9-ocnJYO-57I_wA) 更新了依赖版本，看着问题是解决了。
> > 说一下我的一些理解：
> > 1、原先的客户端通知分成了两种类型，一种是轻量级、一种是重量级（原先的问题代码）
> > 2、CRON会被归为轻量级任务 ![img_v3_02bh_2852cf96-1a41-4e99-856f-029d7fbef54g](https://private-user-images.githubusercontent.com/163995028/336400712-dc5704bf-e3ef-4314-9669-318afe3d7a0d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDk0MjksIm5iZiI6MTcxNzY0OTEyOSwicGF0aCI6Ii8xNjM5OTUwMjgvMzM2NDAwNzEyLWRjNTcwNGJmLWUzZWYtNDMxNC05NjY5LTMxOGFmZTNkN2EwZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwNDQ1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTdmOTIxMGJjNzFjOTc5YjFmYThjY2VjNzRjNjk4YjliNDVkNzY5MjdkZDY5OTk2YTIyNWQ4NDY0YjVlM2IzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qKBbEnROntgEIxJMg5-piHe7qMSpfKLrCyASCFXDbgI)
> > 3、轻量级任务，线程池是单例的，避免了之前创建线程池过多的问题 ![img_v3_02bh_c65b4eba-0da7-43e7-a03c-c26307b5388g](https://private-user-images.githubusercontent.com/163995028/336400759-96bf4fa7-af42-449e-885a-418ff376f927.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDk0MjksIm5iZiI6MTcxNzY0OTEyOSwicGF0aCI6Ii8xNjM5OTUwMjgvMzM2NDAwNzU5LTk2YmY0ZmE3LWFmNDItNDQ5ZS04ODVhLTQxOGZmMzc2ZjkyNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwNDQ1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjZhNThmOTMxM2JlZWZkN2VjZjJkMDRiOGM1MGY1MzM2MTVmM2Y0ZmJmMzA5MDRjMGZkMTlmNDViOWQ5MzY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n4z_paplgy-WEf0i82ococ71abs_7NzudVWqmb84bXw)
> > 4、这个线程池，使用的是有界队列，在任务过多时，会直接丢弃。可能会造成有些能收到通知，有些收不到的情况。 ![img_v3_02bh_4b1249d6-001b-4740-92a1-3475c2a2dd1g](https://private-user-images.githubusercontent.com/163995028/336401473-af6e2489-c885-49b9-869e-46db3461b793.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDk0MjksIm5iZiI6MTcxNzY0OTEyOSwicGF0aCI6Ii8xNjM5OTUwMjgvMzM2NDAxNDczLWFmNmUyNDg5LWM4ODUtNDliOS04NjllLTQ2ZGIzNDYxYjc5My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwNDQ1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzEwNjFkMzcxNTQzNjhiMzM0MmEzMTczM2NkZGQyYWE4NGU5YTFlMDYzNmE0Mzk4NTIxNzUzYWQ4NDc1MWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gnNr3LtBTV2GWhTJUQ6_jJeIQK92U02V3bZNpJ2teTk)
> > 这点可以考虑在业务层面，自己去做异步削峰的处理，问题还不大。
> > 5、重量级，还是之前的问题代码，后续如果有使用的情况下，也还会出问题？ 这点我理解是否正确？
> 
> 第一点和第三点 理解没问题。 第二点，划分轻重量级任务并不只是根据任务的定时信息来判断的，还有执行类型，非单击执行的都是重量级任务。 第四点，worker 端直接丢弃任务的情况下，Server 端会通过重试来保证可靠性。 第五点，worker 端在接收到重量级任务后，在创建 TaskTracker 之前会检查数量限制，这个值默认是 64，参考代码 tech.powerjob.worker.actors.TaskTrackerActor#onReceiveServerScheduleJobReq

十分感谢！

**Comment by passiolin** [comment]
客户端版本4.2.0更新至4.2.1，问题确认解决
