### ISSUE TITLE
5.0.1版本，openapi接口是否没有受到权限验证的保护？

### ISSUE THREAD

**Issue by andychyiyi** [PowerJob/PowerJob#925]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

5.0.1，这样直接就可以操作所有的openapi了，并不需要进行用户权限的验证，这块什么时候加上呀，
powerJobClient = new PowerJobClient("127.0.0.1:7700", "axax", "axax");

**Comment by KFCFans** [comment]
5.x 正式版发布的时候会加上的，放心～

**Comment by andychyiyi** [comment]
@KFCFans 

还有一个问题，http通信的方式，改用https安全性会更强一些，希望下个版本加一下这个功能。http通信做个二选一可选的配置项

不胜感激。
