### ISSUE TITLE
如何做到强制worker下线

### ISSUE THREAD

**Issue by chenchendashu** [PowerJob/PowerJob#936]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by KFCFans** [comment]
可以细化下需求，比如 需求是在控制台可以指定某些 worker 节点的 offline 吗？
