### ISSUE TITLE
Map/MapReduce 任务，在任务实例中点击详情，看不到子任务执行的信息

### ISSUE THREAD

**Issue by machengjun220** [PowerJob/PowerJob#937]
![image](https://github.com/PowerJob/PowerJob/assets/40233531/b7e696c1-0487-4530-8bd9-da324b5011e0)

但是我看语雀文档上，为啥有子任务执行的信息
![image](https://github.com/PowerJob/PowerJob/assets/40233531/eb548d5d-555c-4dd3-9a4d-3d30ffebc857)

**Comment by KFCFans** [comment]
这个是计算过程中，子节点的运行时数据，一旦任务完成就没有了。
你可以尝试多个子任务，每个子任务需要一段计算时间，就能看到了。
