### ISSUE TITLE
关于 OpenAPI 操作任务，无法查询任务关联的【任务实例 ID】问题。

### ISSUE THREAD

**Issue by wranglerlmx** [PowerJob/PowerJob#938]
当前遇到的问题是，worker 节点可能有问题，任务产生的任务实例一直在等待调度。
项目上有需求，停止某个任务实例的调度，直接通过 OpenAPI 删除某个【任务】，但是【任务】关联的【任务实例】并没有被删除。待 worker 调度恢复之后，依然被执行任务了。

然后关键点是，OpenAPI 没有提供根据 JobId 查询关联的【任务实例】，全部操作都是在提前知道 instanceId（实例 ID）的前提下才能使用 API。所以也无法通过 API 操作删除、关闭【任务实例】，难道没有人提出相关的使用问题？还是有其它我不知道的方式实现？
<img width="1004" alt="tp" src="https://github.com/PowerJob/PowerJob/assets/35132650/f07d7390-06fb-4a43-a338-faddbc3bca87">

**Comment by jjnnzb** [comment]
目前都是 [runJob](https://www.yuque.com/powerjob/guidence/olgyf0#a96f2dac)这个 API 触发，
拿到 instanceId 之后，业务如需要做取消、停止、查询详情等，是需要存储 instanceId 的。
