### ISSUE TITLE
目标服务存在认证绕过漏洞

### ISSUE THREAD

**Issue by hzitao** [PowerJob/PowerJob#940]
**Describe the bug**
通过访问URL:http://ip:port/user/save，获取目标内容如下:{"success":true,"data":null,"message":null},请问官方准备增加鉴权吗？我看源码其他接口也存在类似问题

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
 - PowerJob Version: [e.g. 3.0.0]
 - Java Version: [e.g. OpenJDK 8]
 - OS: [e.g. CentOS 8.1]

**Screenshots**

**Additional context**

**Comment by KFCFans** [comment]
重复issue，保留 #941
