### ISSUE TITLE
接口鉴权漏洞

### ISSUE THREAD

**Issue by hzitao** [PowerJob/PowerJob#941]
**Describe the bug**
通过访问URL:http://ip:port/user/save，获取目标内容如下:{"success":true,"data":null,"message":null}，我看了源码，其他接口也存在类似鉴权的问题，请问官方有打算修复吗

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
 - PowerJob Version: [e.g. 3.0.0]
 - Java Version: [e.g. OpenJDK 8]
 - OS: [e.g. CentOS 8.1]

**Screenshots**

**Additional context**

**Comment by KFCFans** [comment]
你还是4.x版本吧，5.x 版本引入了权限体系，会有严格的用户权限控制。

**Comment by hzitao** [comment]
> 你还是4.x版本吧，5.x 版本引入了权限体系，会有严格的用户权限控制。

是用的4.x，官方是建议用户升级为5.x嘛？还是说以后4.x也会修复？4.x升级到5.x有无什么代价或者坑？

**Comment by KFCFans** [comment]
5.1.0 已正式解决这个问题。
升级可以参考 release 文档。
