### ISSUE TITLE
maxAppendedWfContextLength  这个参数的单位是个数还是KB  

### ISSUE THREAD

**Issue by lipeishen** [PowerJob/PowerJob#942]
https://github.com/PowerJob/PowerJob/blob/d44131128e053e6f9c80788f604fa0fcd25b8f5f/powerjob-worker/src/main/java/tech/powerjob/worker/common/PowerJobWorkerConfig.java#L48

**Comment by jjnnzb** [comment]
`private String suit(String result) {
        if (StringUtils.isEmpty(result)) {
            return "";
        }
        final int maxLength = workerRuntime.getWorkerConfig().getMaxResultLength();
        if (result.length() <= maxLength) {
            return result;
        }
        log.warn("[TaskTracker-{}] task's result is too large({}>{}), a part will be discarded.",
                instanceId, result.length(), maxLength);
        return result.substring(0, maxLength).concat("...");
   }`

看代码逻辑，具体是哪边用到了这个，就知道了呀。做的是 result 长度的截取。

**Comment by jjnnzb** [comment]
`private String suit(String result) {
        if (StringUtils.isEmpty(result)) {
            return "";
        }
        final int maxLength = workerRuntime.getWorkerConfig().getMaxResultLength();
        if (result.length() <= maxLength) {
            return result;
        }
        log.warn("[TaskTracker-{}] task's result is too large({}>{}), a part will be discarded.",
                instanceId, result.length(), maxLength);
        return result.substring(0, maxLength).concat("...");
   }`

看代码逻辑，具体是哪边用到了这个，就知道了呀。做的是 result 长度的截取。

**Comment by jjnnzb** [comment]
请求上下文总长度的上限吧，校验的时候是把整个请求上下文转 json，再判断的长度。
```
public class WorkflowContextUtils {

    private WorkflowContextUtils() {

    }


    public static boolean isExceededLengthLimit(Map<String, String> appendedWfContext, int maxLength) {

        String jsonString = JsonUtils.toJSONString(appendedWfContext);
        if (jsonString == null) {
            // impossible
            return true;
        }

        return maxLength < jsonString.length();

    }

}
```
