### ISSUE TITLE
1：希望非spring部署也可以增加注解来自定义别名， 2：希望可以在控制台根据json任务描述符导入任务。

### ISSUE THREAD

**Issue by wjtien** [PowerJob/PowerJob#943]
如题。

**Comment by jjnnzb** [comment]
可以尝试自己实现呢

**Comment by KFCFans** [comment]
1. 目前 processor 的识别是可以自定义扩展的，这块可以实现 `tech.powerjob.worker.extension.processor.ProcessorFactory` 接口，做你自己想做的逻辑。也欢迎贡献会社区。 
2. JSON导入是天然支持的
<img width="1919" alt="image" src="https://github.com/user-attachments/assets/dfafff26-703f-4d17-9ea2-82e5e1e0df3d">
