### ISSUE TITLE
任务执行完了，但是server端还是显示运行中

### ISSUE THREAD

**Issue by Kingfan1993** [PowerJob/PowerJob#944]
有2个任务，执行长的明明已经执行完成了，但还是显示运行中，没有任何报错，对比了 显示成功的任务的日志，显示运行中的没有输出task complete日志，确认了代码都是有返回执行结果true的，powerjob版本4.3.9
![272c53d6fd08f9604ae95d8b6d80af19](https://github.com/PowerJob/PowerJob/assets/43435329/977b3fe6-9c4f-451e-b11d-cf8b16684f6e)

**Comment by KFCFans** [comment]
稳定复现吗？还是部分任务会有这个问题？

顺便找找 worker 的 WARN、ERROR 日志，有没有状态上报失败的异常信息
