### ISSUE TITLE
API运行任务，如何传入自定义的任务参数？界面的参数运行填写的值并不会改变运行任务的任务参数。

### ISSUE THREAD

**Issue by liangrenjing** [PowerJob/PowerJob#945]
![image](https://github.com/PowerJob/PowerJob/assets/170482555/70b213c8-5434-4a3f-bf0f-21f1e33b713c)

**Comment by jjnnzb** [comment]
页面传入的是`jobParams`字段，从 TaskContext 里取即可。应用场景么，比如定期给业务导出数据汇报。导出的数据逻辑一样，就起止时间都不一样。这种场景，开发在页面上改一下参数，点击运行。

如果是 OpenAPI 里面用的，得用 [runJob](https://www.yuque.com/powerjob/guidence/olgyf0#a96f2dac) 这个 API去调用，从 TaskContext 里取 `instanceParams` 字段，示例见[链接](https://www.yuque.com/powerjob/guidence/attxyvpicg7e93it)。

**Comment by jjnnzb** [comment]
页面传入的是`jobParams`字段，从 TaskContext 里取即可。应用场景么，比如定期给业务导出数据汇报。导出的数据逻辑一样，就起止时间都不一样。这种场景，开发在页面上改一下参数，点击运行。

如果是 OpenAPI 里面用的，得用 [runJob](https://www.yuque.com/powerjob/guidence/olgyf0#a96f2dac) 这个 API去调用，从 TaskContext 里取 `instanceParams` 字段，示例见[链接](https://www.yuque.com/powerjob/guidence/attxyvpicg7e93it)。
