### ISSUE TITLE
初始化 SpringDatasourceSqlProcessor 示例代码

### ISSUE THREAD

**Issue by wusizhong** [PowerJob/PowerJob#946]
@Configuration
@ConditionalOnBean(PowerJobWorker.class)
public class SqlProcessorConfiguration

初始化SpringDatasourceSqlProcessor 示例代码中的ConditionalOnBean(PowerJobWorker.class)需要去掉，
不然SpringDatasourceSqlProcessor注入不了，源码中PowerJobWorker类不属于spring bean

**Comment by KFCFans** [comment]
感谢反馈，确实是之前拆封 PowerJobWorker 和 PowerJobSpringWorker 时引入的 bug，下个版本会 fix。
