### ISSUE TITLE
容器项目能否注入数据源，依赖spring boot

### ISSUE THREAD

**Issue by CZ-Peng** [PowerJob/PowerJob#948]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by MeituanRider** [comment]
换xxl-job

**Comment by KFCFans** [comment]
可以的，方式更新在文档里面了。
https://www.yuque.com/powerjob/guidence/container#LQetv

**Comment by KFCFans** [comment]
<img width="811" alt="image" src="https://github.com/user-attachments/assets/8fbff9cd-f73f-412f-a0e6-e69ff26903ac">
