### ISSUE TITLE
pgsql或mysql  运行部署powerjob   使用api调用超时 no server available

### ISSUE THREAD

**Issue by laoxiansheng-super** [PowerJob/PowerJob#951]
报错： 2024-07-16 18:00:58.756 WARN PowerJobClient.java:578 : [PowerJobClient] request url:http://orain-powerjob:7700/openApi/runJob failed, reason is java.net.SocketTimeoutException: timeout.
2024-07-16 18:00:58.756 ERROR PowerJobClient.java:599 : [PowerJobClient] do post for path: /runJob failed because of no server available in [orain-powerjob:7700].
场景： 执行api调用超时，平时正常使用，莫名其妙服务不可用出现超时，只能多次执行能够复现。网络一台服务器内，多次执行未出现fullgc，等内存满情况

**Comment by KFCFans** [comment]
合并同类项
https://github.com/PowerJob/PowerJob/issues/947
