### ISSUE TITLE
4.3.3 任务过多，work处于阻塞状态，一直处于运行中

### ISSUE THREAD

**Issue by JNIANC** [PowerJob/PowerJob#952]
**Describe the bug**
前提：jvm内容足够大，db存在一定压力
4.3.3版本 当任务过多时候，work处于阻塞状态（运行中），日志里面提示有 worker overload 的提示

尝试将一下参数调大1024倍后，过一段时间还是阻塞掉
tech.powerjob.worker.common.PowerJobWorkerConfig#maxLightweightTaskNum

 /**
     * Max numbers of LightTaskTacker
     */
    private Integer maxLightweightTaskNum = 1024 * 1024;
    /**
     * Max numbers of HeavyTaskTacker
     */
    private Integer maxHeavyweightTaskNum = 64 * 1024;
    
    
![Uploading work.png…]()

**Comment by MeituanRider** [comment]
换xxl-job

**Comment by JNIANC** [comment]
已收到，thanks

**Comment by KFCFans** [comment]
worker 阻塞应该是你自己 worker 代码的问题吧，如果单节点负载过高，可以考虑加 worker，而不是一味调大限流值。
