### ISSUE TITLE
调度中心server节点资源使用问题

### ISSUE THREAD

**Issue by AMysteryMan** [PowerJob/PowerJob#953]
## Question
最近看powerjob源码的时候发现个问题想请教一下老师：如果一个公司只用一套调度端server集群，存在n个work端对应n个应用，work端配置中写的调度端集群的ip地址顺序都是一样的，那是不是所有的应用都注册到同一台调度端实例节点？如果是这样的话，其他的调度端机器岂不是啥也没干，活都被配置文件中的第一个实例干了？求解答！！谢谢

**Comment by KFCFans** [comment]
1. 一般公司内大规模部署的话，比较建议走域名 + 服务发现，DNS 去分配 IP，事实上还是随机的
2. 这块后续我们也可以优化下，选对传入的 iplist做个随机（短期内也可以自己在接入文档写清楚，建议大家挑几个 ip，手动随机）
