### ISSUE TITLE
只修改应用名称，未输入新密码能保存成功。但密码会被置空，导致无法登录

### ISSUE THREAD

**Issue by register2hard** [PowerJob/PowerJob#956]
版本4.3.9
需求：想要修改下应用名称，不想改密码
操作：
1.修改表单中输入了新应用名称和旧密码，新密码没有输入。点击保存，保存成功跳转回登录页面
2.使用新应用名称和原密码登录，出现密码错误提示，检查数据库用户表，发现密码被置空了
3.使用新应用名称和空密码登录，仍然出现密码错误提示

希望能完善校验：新密码必填；或者应用名修改和密码修改分成两个表单。

**Comment by lvhjean** [comment]
我试了一下，免密进入后，重新修改添加上新密码即可；

**Comment by KFCFans** [comment]
哈哈，5.x 也不会再有这个问题了，和用户权限绑定，应用密码只是服务 openAPI 了。
综上，4.x 就不处理了。
后续小心点操作吧哈哈。
