### ISSUE TITLE
是否考虑过  升级第三方 有漏洞的 依赖

### ISSUE THREAD

**Issue by ljp190** [PowerJob/PowerJob#957]
最近我们在做质量检查，发现了不少第三方项目中，有漏洞的包
powerjob中的akka   h2    okio   是否考虑过升级呢
目前2.8着实是太老了，但是无漏洞的，最新的3.4.0跨度又太大，只能来问问看 官方有没有计划来换掉这些
![image](https://github.com/user-attachments/assets/cd88ea56-67e4-4e8c-af88-bca78e7002db)

![image](https://github.com/user-attachments/assets/cc29a7e1-0703-4b97-aca9-5b72d7368aed)

![image](https://github.com/user-attachments/assets/ea6c720a-d1fb-4f8e-ab8a-0cec5d00b215)
![image](https://github.com/user-attachments/assets/b1daf93e-f0f2-4dc3-a149-3c754a0f8243)

**Comment by KFCFans** [comment]
😂不好意思，3.x 版本不再维护了，4.x 和 5.x 的基础性维护是会存在的

**Comment by KFCFans** [comment]
可以考虑参考升级教程升级到高版本～

**Comment by ljp190** [comment]
> 可以考虑参考升级教程升级到高版本～
上面的依赖，是439的     会扫描出cve
