### ISSUE TITLE
请问docker启动的如何修改连接pg数据库

### ISSUE THREAD

**Issue by yongzhengwu** [PowerJob/PowerJob#958]
docker run -d \
 			 --restart=always \
       --name powerjob-server \
       -p 7700:7700 -p 10086:10086 -p 10010:10010 \
       -e TZ="Asia/Shanghai" \
       -e JVMOPTIONS="" \
       -e PARAMS="--spring.profiles.active=product --spring.datasource.core.jdbc-url=jdbc:mysql://192.168.1.1:3306/powerjob-product?useUnicode=true&characterEncoding=UTF-8 --spring.datasource.core.username=root --spring.datasource.core.password=root --spring.data.mongodb.uri=mongodb://192.168.1.1:27017/powerjob-product" \
       -v ~/docker/powerjob-server:/root/powerjob/server -v ~/.m2:/root/.m2 \
       powerjob/powerjob-server:latest

**Comment by KFCFans** [comment]
PG 数据库比较麻烦，可以搜索下相关的资料，比如可以参考下文：

https://github.com/PowerJob/PowerJob/issues/750

https://github.com/PowerJob/PowerJob/issues/538

https://github.com/PowerJob/PowerJob/issues/153
