### ISSUE TITLE
find some instance didn't receive any reply from worker

### ISSUE THREAD

**Issue by HanxuGit** [PowerJob/PowerJob#963]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
 - PowerJob Version: [4.3.9]
 - Java Version: [OpenJDK 8]
 - OS: [mac os 12.7.5]

**Screenshots**
<img width="881" alt="image" src="https://github.com/user-attachments/assets/04f93ab4-1e96-43a8-a7ad-a1e3aa6ad554">
ifconfig命令可以看到两个ip地址，正确的本级网络通信地址应该为192.168.5.51
![Uploading image.png…]()

**Additional context**

**Comment by HanxuGit** [comment]
在同一台机器上启动worker和server服务，server端日志显示发送给worker的任务实例请求没有响应，导致worker端定义的任务没有执行。

**Comment by lvhjean** [comment]
https://www.yuque.com/powerjob/guidence/problem#sJvDR
多个网卡的情况；使用绑定IP的方式处理；

**Comment by KFCFans** [comment]
5.1.0 也优化了网卡获取逻辑，只要有一个网卡可以和 server 双向互通应该就能正常获取到 IP

**Comment by HanxuGit** [comment]
> 5.1.0 也优化了网卡获取逻辑，只要有一个网卡可以和 server 双向互通应该就能正常获取到 IP

能否拿到powerjob的前端源码，想要把powerjob的管理端集成到系统菜单里，请问能实现吗？

**Comment by HanxuGit** [comment]
能否拿到powerjob的前端源码，想要把powerjob的管理端集成到系统菜单里，请问能实现吗？
