### ISSUE TITLE
work与server在不同网段无法执行任务

### ISSUE THREAD

**Issue by Robot1937** [PowerJob/PowerJob#964]
Server段为172.30.8段
work为172.30.25段
在系统首页中为灰色显示但是上次在线时间会更新
执行调度任务报no worker available
![image](https://github.com/user-attachments/assets/e9f44385-6391-4317-a4f2-5911db367deb)

**Comment by Robot1937** [comment]
![image](https://github.com/user-attachments/assets/e5b7b135-5fc5-4c67-9ad5-25ce1ced60ec)

**Comment by KFCFans** [comment]
server 和 worker 需要能相互通讯。
可以在 GitHub 搜一搜类似问题，自己排查下
