### ISSUE TITLE
部署5.1后首页报错[ControllerException] PowerJobException, message is remote process failed: NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "method" is null.

### ISSUE THREAD

**Issue by rongxingsun** [PowerJob/PowerJob#967]
package tech.powerjob.server.remote.server.redirector;
public class DesignateServerAspect {

    @Around("@annotation(designateServer))")
    public Object execute(ProceedingJoinPoint point, DesignateServer designateServer) throws Throwable {
        Object[] args = point.getArgs();
        String methodName = point.getSignature().getName();
        String className = point.getSignature().getDeclaringTypeName();
        Signature signature = point.getSignature();
        MethodSignature methodSignature = (MethodSignature)signature;
        String[] parameterNames = methodSignature.getParameterNames();
        String[] parameterTypes = String[])Arrays.stream(methodSignature.getParameterTypes()).map(Class::getName).toArray((x$0) -> {
            return new String[x$0];
        });
        Long appId = null;

        for(int i = 0; i < parameterNames.length; ++i) {
            if (StringUtils.equals(parameterNames[i], designateServer.appIdParameterName())) {
                appId = Long.parseLong(String.valueOf(args[i]));
                break;
            }
        }

        if (appId == null) {
            throw new PowerJobException("can't find appId in params for:" + signature);
        } else {
            AppInfoDO appInfo = (AppInfoDO)this.appInfoRepository.findById(appId).orElseThrow(() -> {
                return new PowerJobException("can't find app info");
            });
            String targetServer = appInfo.getCurrentServer();
            if (StringUtils.isEmpty(targetServer)) {
                return point.proceed();
            } else if (Objects.equals(targetServer, this.transportService.defaultProtocol().getAddress())) {
                return point.proceed();
            } else {
                log.info("[DesignateServerAspect] the method[{}] should execute in server[{}], so this request will be redirect to remote server!", signature.toShortString(), targetServer);
                RemoteProcessReq remoteProcessReq = (new RemoteProcessReq()).setClassName(className).setMethodName(methodName).setParameterTypes(parameterTypes).setArgs(args);
                URL friendUrl = ServerURLFactory.process2Friend(targetServer);
                CompletionStage<AskResponse> askCS = this.transportService.ask(this.transportService.defaultProtocol().getProtocol(), friendUrl, remoteProcessReq, AskResponse.class);
                AskResponse askResponse = (AskResponse)askCS.toCompletableFuture().get(5000L, TimeUnit.MILLISECONDS);
                if (!askResponse.isSuccess()) {
                    throw new PowerJobException("remote process failed: " + askResponse.getMessage());
                } else {
                    // 这里debug的时候报错： 找不到局部量，jdk17
                    Method method = methodSignature.getMethod();
                    JavaType returnType = getMethodReturnJavaType(method);
                    return OBJECT_MAPPER.readValue(askResponse.getData(), returnType);
                }
            }
        }
    }
}

**Comment by KFCFans** [comment]
JDK17 的兼容性问题是吧，后续我们跟进下。

**Comment by rongxingsun** [comment]
> https://stackoverflow.com/questions/70168301/java-17-cannot-invoke-java-lang-reflect-method-invokeobject-object-becaus
> 
> 大概率是这个问题，你是不是用 JDK17 重新编译了 server？

是的
