### ISSUE TITLE
配置dfs为数据库存储时，initTable如果已经有序列会导致server启动不了

### ISSUE THREAD

**Issue by bluefat** [PowerJob/PowerJob#974]
tech.powerjob.server.persistence.storage.impl.PostgresqlSeriesDfsService#initTable
![1724141353287](https://github.com/user-attachments/assets/a23319ec-c44c-4825-b65b-39a716dd882e)

**Comment by KFCFans** [comment]
临时解决方案：可通过参数关闭自动表创建 `oms.storage.dfs.postgresql_series.auto_create_table=false`

但确实逻辑是不应该让用户多次修改配置，后续我们会兼容
