### ISSUE TITLE
开源组件漏洞修复

### ISSUE THREAD

**Issue by KeekLove** [PowerJob/PowerJob#975]
您好，因为我们这边对开源组件漏洞有要求，然后这是我用dependency-check扫描出来的漏洞报告，后续会有计划修复调整么？
![image](https://github.com/user-attachments/assets/33fd2c62-fe8d-4db6-a706-f7e9fa965bd9)
![image](https://github.com/user-attachments/assets/f17a0225-27b4-44d2-b145-483398b15b41)

**Comment by KFCFans** [comment]
1. akka 是可选组件，选择 http 协议的话，不依赖 akka，可以直接排除
2. 其他依赖理论上可以自己覆盖升级

PowerJob 定期会升级版本，如果有强诉求可以自己处理。
