### ISSUE TITLE
基于tag的任务调度切换

### ISSUE THREAD

**Issue by davionchen** [PowerJob/PowerJob#982]
问题背景：
某个业务被划分为多个机房，对外提供服务。为了保证服务可用性和可靠性，会随机分配流量，包括job流量。
但在容灾演练、灰度发布等场景，需要重新划分job流量。

期待：
目前 powerjob只提供  基于worker的打tag功能 和基于tag的调度功能。但是缺少更精细化的调度。
比如：
1、将某个app的job流量从 a机房（tagA）到b机房（tagB）
2、在a机房的worker宕机的情况下，将流量自动迁移b机房（tagB）

**Comment by KFCFans** [comment]
1. worker 端预留了 tech.powerjob.common.model.SystemMetrics 扩展，可以自定义上报自己的机房信息
2. server 端自己实现 tech.powerjob.server.remote.worker.filter.WorkerFilter 做容灾时候的切流逻辑即可

目前的扩展点已经支持你们自己低成本实现了。
