### ISSUE TITLE
cron和固定延迟不准

### ISSUE THREAD

**Issue by fanyy** [PowerJob/PowerJob#983]
用的最新版本5.1.0
1. cron 想要每10s触发不准，实际是15s左右，而且好像每次按每5s.16s,19s等，都是接近15s频率，行为奇怪.
2. 固定延迟没1s触发也不准，实际5s左右，

能解释下为什么，固定延迟我看了下worker的代码，是有个5s-15s随机轮训造成的？，cron又是为啥，没在官方找到相关说明，我觉得文档里得说明下这个诡异行为，或者解释下不准到底是什么样的误差

**Comment by binglingziyu** [comment]
同样的问题，很困惑😕

**Comment by AMysteryMan** [comment]
因为作者sleep了15s，cron最低就是15s一次

**Comment by binglingziyu** [comment]
还真是 15 秒一次，这种东西为什么不放文档。
https://github.com/PowerJob/PowerJob/issues/201
https://github.com/PowerJob/PowerJob/issues/388
https://github.com/PowerJob/PowerJob/issues/691

**Comment by KFCFans** [comment]
> 还真是 15 秒一次，这种东西为什么不放文档。 #201 #388 #691

一直以为文档写了，去看了下确实没有 =。=
相关限制，已更新到文档中。

**Comment by KFCFans** [comment]
后续也考虑开放配置，允许大家配置最短扫描时间。

**Comment by cosoc** [comment]
真扯淡，劳资找时间用rust写一个，用着真憋屈。
