### ISSUE TITLE
客户端9999

### ISSUE THREAD

**Issue by hrj5032188** [PowerJob/PowerJob#994]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details. 

请问一下状态值9999是什么意思?
用了一段时间, 这两天突然windows的变9999了
不知道发生了什么

<img width="1726" alt="image" src="https://github.com/user-attachments/assets/525cf9c2-a955-4045-9e82-49e8ed006586">

**Comment by KFCFans** [comment]
1 -> 健康，绿色，2 -> 一般，橙色，3 -> 糟糕，红色，9999 -> 非在线机器

节点应该是挂了，或者与 server 之前存在较大时差。

**Comment by hrj5032188** [comment]
这个9999很神奇
就是每隔一段时间他后面的上次在线时间都会更新
然后绿几秒 就灰掉...
现在好了

不知道为什么坏  不知道为什么好
