### ISSUE TITLE
powerjob-server增加上下文context-path的问题

### ISSUE THREAD

**Issue by leonChing** [PowerJob/PowerJob#995]
我们需要把powerjob页面内嵌到我们现有的应用中，必须要在powerjob-server中增加context-path方便代理，但是加了context-path后worker与server的通信就404，请问下这种情况只能改worker的源码了吧？ @KFCFans 
![1726734795482](https://github.com/user-attachments/assets/ae6f0a12-29a0-4208-be53-7e229f90a17d)

**Comment by leonChing** [comment]
我在server-address中都加了context-path，现在通信没问题，但不确认会不会有什么问题？ 麻烦作者看到了帮忙回复下，谢谢
![1726735451225](https://github.com/user-attachments/assets/b6da15a3-4764-4282-857f-89f5104bba8f)

**Comment by KFCFans** [comment]
这种做好测试就可以了，理论上没啥问题，能连上就行。
