### ISSUE TITLE
无法离线运行

### ISSUE THREAD

**Issue by reformc** [PowerJob/PowerJob#996]
使用docker compose启动，服务器处于离线环境，运行时报错dingtalk无法获取到access_token，dingtalk url无法解析。然后程序就退出了。这个中间件必须要依赖钉钉才能运行吗？现在要在离线环境部署一个powejob，如何实现？

**Comment by KFCFans** [comment]
可以离线运行的，完全删除 oms.alarm.ding 相关配置项即可。
<img width="1315" alt="image" src="https://github.com/user-attachments/assets/0368f91a-0429-4fa0-bc99-e095fe0a7172">
