### ISSUE TITLE
希望【PowerJobClient】支持批量任务创建、启用、禁用和删除任务

### ISSUE THREAD

**Issue by xtito** [PowerJob/PowerJob#997]
需求场景：在业务系统中需要建立某个数据的统计分析或者数据收集工作，该工作会需要定期执行多个任务执行收集和处理。

处理过程：
1、现有情况：先创建一个数据收集工作，与此同时使用PowerJobClient，循环创建多个PowerJob任务（如果在创建某个任务过程中失败呢？）；
2、现有情况：数据收集工作需要停止或删除，完成该操作后需要使用PowerJobClient进行删除，依然需要循环禁用或删除任务。

希望能通过任务ID或任务自定义KEY进行批量操作。

感谢您的辛苦付出。

**Comment by KFCFans** [comment]
其实给批量接口也只是在服务端循环，任务模型整体还是比较重的，且这个操作没有太高的性能要求，在调用端循环执行即可。
