### ISSUE TITLE
MapReduce子任务之间有延迟， 使用官方案例有2秒延迟，自己的业务代码有5秒延迟

### ISSUE THREAD

**Issue by aokinba** [PowerJob/PowerJob#998]
单机每执行2次子任务就会有延迟，使用官方案例有2秒延迟，自己的业务代码有5秒延迟

官方案例
![a973b8416702891a0ed9e1dbcd3e30a1](https://github.com/user-attachments/assets/dc05fb11-d6d5-4ce9-af12-769e3e07b5c2)

业务代码案例
![7f6214d73f0975807f7e45e91434615f](https://github.com/user-attachments/assets/aa4fc638-b7c2-40bd-8695-dc323bc4dec7)

**Comment by aokinba** [comment]
增加debug级别日志，这是延迟之间的日志
![5c43c4f2bdf63fce3480f547702b133f_720](https://github.com/user-attachments/assets/8e214e51-f84f-4093-8164-68ffa66b8497)

**Comment by charles-chao0910** [comment]
我也碰到了同样的问题 请问解决了吗？

**Comment by aokinba** [comment]
> 我也碰到了同样的问题 请问解决了吗？

解决了，全局搜索源代码的关键字"5000"， 降低这个数字就Ok
